### ISSUE TITLE
Error when trying to access new level at the end of the quiz

### ISSUE THREAD

**Issue by OnnoEbbens** [hedyorg/hedy#1008]
When you click on the button "Ga naar level 6" (in Dutch) at the end of the quiz

![image](https://user-images.githubusercontent.com/10562903/137156807-b9ec1c63-380a-42b5-b08d-e9e44954528e.png)

You get an error.

![image](https://user-images.githubusercontent.com/10562903/137156942-13f09f72-44fa-4416-94a1-5e2cb5b84745.png)

This happens at the end of all the quizzes. It has something to do with embedding the quiz in a view I think.

**Comment by fpereiro** [comment]
Hi @Felienne & @bjorn3 !

Indeed, an iframe cannot reload the entire page, just its little corner. We need to find a way for the iframe to signal to the js in the outer page that we want to go to another page altogether.

I was going to propose a horrible solution involving a hidden link and a function being executed at intervals, but apparently it can be done in a nicer way (source: https://stackoverflow.com/a/25273917):

`<a href="..." target="_parent"></a>`. Maybe we could give this a try!

**Comment by Felienne** [comment]
> I think we can solve this with some jQuery magic! Hiding the button when we call the quiz-page and showing it again when we reach the final quiz-page. I can take a look! However, I think that in the long-term it would be best to not use an iframe structure for the quiz but just implement it in the page itself.

Cool, if you can pick this up it would be awesome!
