### ISSUE TITLE
Replace parts of 'for teachers' page with this presentation

### ISSUE THREAD

**Issue by MarleenGilsing** [hedyorg/hedy#1017]
I've made a presentation to make the teacher page look better. This page can be embedded into the English for teachers page. 

This presentation can replace : For teachers — Hedy, Introduction Hedy, Preparations and Teaching with Hedy.
**MIND**: The frequently made mistakes should stay on the page as is, because have not found a proper way to make it look better and still be as handy. 
MIND: The 'My classes' feature should - of course- also stay on this page. 

Here is the link to the presentation: https://view.genial.ly/61680ae0e003960dea8a5e8b/interactive-content-teacher-manual-hedy

And here is the code for embedding it: 
iframe: 
<div style="width: 100%;"><div style="position: relative; padding-bottom: 56.25%; padding-top: 0; height: 0;"><iframe frameborder="0" width="1200" height="675" style="position: absolute; top: 0; left: 0; width: 100%; height: 100%;" src="https://view.genial.ly/61680ae0e003960dea8a5e8b" type="text/html" allowscriptaccess="always" allowfullscreen="true" scrolling="yes" allownetworking="all"></iframe> </div> </div>

script: 
<div class="container-wrapper-genially" style="position: relative; min-height: 400px; max-width: 100%;"><video class="loader-genially" autoplay="autoplay" loop="loop" playsinline="playsInline" muted="muted" style="position: absolute;top: 45%;left: 50%;transform: translate(-50%, -50%);width: 80px;height: 80px;margin-bottom: 10%"><source src="https://static.genial.ly/resources/panel-loader-low.mp4" type="video/mp4" />Your browser does not support the video tag.</video><div id="61680ae0e003960dea8a5e8b" class="genially-embed" style="margin: 0px auto; position: relative; height: auto; width: 100%;"></div></div><script>(function (d) { var js, id = "genially-embed-js", ref = d.getElementsByTagName("script")[0]; if (d.getElementById(id)) { return; } js = d.createElement("script"); js.id = id; js.async = true; js.src = "https://view.genial.ly/static/embed/embed.js"; ref.parentNode.insertBefore(js, ref); }(document));</script>

**Comment by TiBiBa** [comment]
I did some tweaking with the style of the for-teachers page, implementing the button-structure suggested by @MarleenGilsing. Let me know what you think!

**Old view**
![Schermafbeelding 2021-10-21 om 13 02 59](https://user-images.githubusercontent.com/38155424/138265065-097ed900-6951-4310-99e8-f5739160b809.png)

**New view**
![Schermafbeelding 2021-10-21 om 13 02 46](https://user-images.githubusercontent.com/38155424/138265075-07715880-068c-43af-b897-65bbedf1f6c6.png)
