### ISSUE TITLE
Duplicate answer in Hedy Quiz level 7

### ISSUE THREAD

**Issue by redelaar** [hedyorg/hedy#1052]
In Hedy level 7, quiz adventure question 6, the following question is being asked: 
![Hedy level 7, quiz question 6](https://user-images.githubusercontent.com/33595265/138071817-be80bccc-bcb4-460f-a933-9c3297063b87.png)

Answer C and D are duplicates. There should probably be a new answer for answer C or D.

**Comment by MarleenGilsing** [comment]
Hi Felicia, good catch! There was a difference in indention, but it doesn't show in the answer options right now. I've changed the \n lay-out to |- . Hopefully the difference will show now, otherwise @LterHaar could maybe take a look at it .

**Comment by Felienne** [comment]
Closed by #1067
