### ISSUE TITLE
Radio button size changes in Q6 quiz level 7

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#1075]
Superstrange but the radio button are smaller? Only in this Q as far as I could see:

![image](https://user-images.githubusercontent.com/1003685/138294097-c4837f1d-a701-4ed3-aec4-3a57455505f1.png)

**Comment by LterHaar** [comment]
![image](https://user-images.githubusercontent.com/86956321/141787034-7413e32f-a1b6-40c0-b3ee-1cc866b7698a.png)
 
Ik heb de radio button geheel verplaatst naar onder het optiesymbool. Zodat er meer plek overblijft voor de optietext en dit specifieke probleem niet meer optreedt.
