### ISSUE TITLE
Check for "almost quote"

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#1100]
Since #1085 we give better error messages for backticks (#721):

![image](https://user-images.githubusercontent.com/1003685/138866124-e74e74d5-a752-4123-9af1-c6910d927f98.png)

But, now we do not give a more specialised warning, something like: You enclosed the string in ` instead of '.

Rust has a notion of "similar characters" with lovely error messages (see: https://github.com/rust-lang/rust/issues/25957) like this:

`note: Unicode character U+37E (Greek Question Mark) looks like a semicolon, but is not.`

Would be really cool if we implemented something like that too!

**Comment by Felienne** [comment]
Ah good to get a reminder of old issues! What do you think @jpelay, one for you too (but not with all too high priority I think?)

**Comment by jpelay** [comment]
> Ah good to get a reminder of old issues! What do you think @jpelay, one for you too (but not with all too high priority I think?)

Ok!! No problem, I like working on the grammar :D

**Comment by Felienne** [comment]
Now discussed in https://github.com/hedyorg/hedy/discussions/3759
