### ISSUE TITLE
[UI idea] The confetti could be only shown on certain conditions

### ISSUE THREAD

**Issue by fRedelaar** [hedyorg/hedy#1257]
**Idea incl level**
The confetti at the moment is being shown whenever a user successfully runs their Hedy code. It might be even a better idea, to only make the confetti available if the user meets certain requirements such as that the user used the learning concepts of that level. By inspecting the parse tree for the user's input and the learning concepts of the level, the confetti emoji could be either shown or not.

***Additional idea**
With confetti-JS, the library that is being used for confetti, there are a lot of different settings available. For adventures with a spook house theme, we could launch confetti with a ghost emoji for example. 👻 See a visual example with emoji confetti in the video below.

https://user-images.githubusercontent.com/33595265/141490126-34cc6f8b-8747-452a-8268-8c57c461a510.mov

**Comment by johannadekker** [comment]
The additional idea has become a separate issue: #1294
