### ISSUE TITLE
[UI idea] Do not show confetti when running demo code

### ISSUE THREAD

**Issue by TiBiBa** [hedyorg/hedy#1275]
**Idea incl level**
Currently, the user is given a positive message when successfully running a program, combined with the option to show confetti with the click on an icon. I think it would be nice to only show this to the user when the created program is unique program and not when simply running a start or demo program. This should be easy because we already keep track if a program is either a start or demo program

**Additional context**
Add any other context about the idea here.

**Comment by Felienne** [comment]
Good idea!! At one point the confetti will be more limited anyway with a few victory conditions but this is a good idea to start with!

**Comment by Felienne** [comment]
Maybe a fun little issue for you @jpelay?

**Comment by jpelay** [comment]
Yes! 

> Maybe a fun little issue for you @jpelay?

**Comment by jpelay** [comment]
@TiBiBa I'm working on this one, but I can't see what you by "we already keep track if a program is either a start or demo program" I can't see that in the /parse endpoint, or anywhere, can you help me with that? Do you mean that we can know if a program is a `start_code` or `demo_code` by checking if it's in the `load_adventures_per_level` list?

**Comment by Felienne** [comment]
> @TiBiBa I'm working on this one, but I can't see what you by "we already keep track if a program is either a start or demo program" I can't see that in the /parse endpoint, or anywhere, can you help me with that? Do you mean that we can know if a program is a `start_code` or `demo_code` by checking if it's in the `load_adventures_per_level` list?

Yes I am pretty sure that it what @TiBiBa meant!

What we could alternatively do (and will be helpful going forward anyway...) is to track if a button is clicked from an example or form a cheatsheet. If we start tracking that we can gather more finegrained data about how kids use the site (atm we do not know how often examples and the cheatsheets are used apart from our own observations)
