### ISSUE TITLE
[CONTENT] Change is to = in adventures levels 6 and up 

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#1527]
Since #1504, levels 6 and up support the use of `=` in assignments in addition to `is`. 

That PR updates the programs in all level defaults, but only does the programs of adventures for en and nl. 

But it misses two things:
* The explanation in other langs, because I don't know the other langs, but that could be fixed with Google translate
* The adventures programs for all other langs should be fixed. That is not a big issue because `is` also still works but it would be nicer to also change it in the other langs (but it is tedious manual work)

**Comment by Carlosbogo** [comment]
Hi, I'm a native Spanish speaker and I would like to work on solving this issue for that language. Is there anyone doing it already?

**Comment by Felienne** [comment]
@Carlosbogo Thanks for the kind offer!! Not as far as I know, so do go ahead!

If you want to do more useful translation work, we are also almost ready to release localized keywords! So if you want Hedy keywords in Spanish, you can simply copy the en.yaml file in [this dir](https://github.com/Felienne/hedy/tree/main/coursedata/keywords) and make it into es.yaml

https://github.com/Felienne/hedy/tree/main/coursedata/keywords

**Comment by Carlosbogo** [comment]
Hi, I was working on the translation of the keywords and I run into some problems:

Some of the keywords (like elif) cannot be precisely translated to spanish using only one word. Should I mix the words (like happens with elif in English) or would it be better to just use an underscore to mark the spaces?

I would like to keep consistency over the repository and while it's a small change, I think it could get a bit confusing later on if done wrong.

**Comment by Felienne** [comment]
> Hi, I was working on the translation of the keywords and I run into some problems:
> 
> Some of the keywords (like elif) cannot be precisely translated to spanish using only one word. Should I mix the words (like happens with elif in English) or would it be better to just use an underscore to mark the spaces?
> 
> I would like to keep consistency over the repository and while it's a small change, I think it could get a bit confusing later on if done wrong.

Yeah that is a great question, and not easy to answer... I think it is best to make up a word that represents `elif` as best as possible. We can always change the keywords if we change our mind.

**Comment by sarangia-dev** [comment]
what's the update with this issue now?

**Comment by sarangia-dev** [comment]
I can try to add keywords in French if that works? I study French at my university and believe I would be able to translate!

**Comment by Felienne** [comment]
Hi @MarleenGilsing!

I am cleaning up old issues and I am assigning a few to you :) Feel free to close if they are no longer relevant.
