### ISSUE TITLE
[CONTENT] Change is to == in defaults and adventures levels 14 and up

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#1597]
Similar to https://github.com/Felienne/hedy/issues/1527

Since https://github.com/Felienne/hedy/pull/1580 levels 14 and up support the use of == in comparison in addition to `is` and `=`.

The above PR updates the programs in level defaults and adventures, but only for en and nl.

But it misses:

- The explanations in other langs, because I don't know the other langs, but that could be fixed with Google translate
- The level defaults and adventures programs for all other langs should be fixed. It is not a big issue because is also still works but it would be nicer to also change it in the other langs (but it is tedious manual work)

**Comment by Felienne** [comment]
Hi @MarleenGilsing!

Same here: I am cleaning up old issues and I am assigning a few to you :) Feel free to close if they are no longer relevant.

**Comment by MarleenGilsing** [comment]
Closing it because it is the same as #4287
