### ISSUE TITLE
[LANGUAGE] Extend type system to take into account variable reassignments of different types

### ISSUE THREAD

**Issue by boryanagoncharenko** [hedyorg/hedy#1631]
**Describe the bug**
The type validation of Hedy fails when a variable is reassigned with a value of a different type. All variables are stored as entries in a lookup table and are accessed during type checking and transpilation. When a variable is reassigned, two entries are created in the lookup table. However, when validating the type of the variable, the type checker only gets [the first entry match from the table](https://github.com/Felienne/hedy/blob/main/hedy.py#L673). This means that during type validation the variable reassignment will be ignored, which could lead to incorrect errors provided by Hedy.

**Paste the Hedy code & level**
For example, consider the following level 12 snippet:
```
a = 'test'
a = 25
print a * a
```

**Add a screenshot (optional)**
![Screenshot 2022-01-06 at 1 18 53](https://user-images.githubusercontent.com/3010723/148303518-7159f9cb-f8b2-4968-a1df-8ce73839f5bc.png)

**Expected behavior**
Hedy incorrectly returns an error that multiplication cannot be performed with strings. Instead, the code should run successfully.

**What machine and browser you were using (optional)**
If the issue concerns things in the website, let us know:
- What computer you are using (Windows, Mac, Linux?)
- What browser you were using (Chrome, Edge, Safari)

**Comment by racertop** [comment]
Hi! Is anyone planning to take this one? Can I assing it to myself?

**Comment by boryanagoncharenko** [comment]
Hey, please go ahead! The only thing to keep in mind is that this bug requires program slicing (i.e. knowing what part of the code belongs to what line/program block). @Felienne wanted to work on slicing, so you should sync on that.

@Felienne do you have any plans for slicing in the near future? If not, is it possible to work on this bug/missing feature?

**Comment by Felienne** [comment]
Feel free to take it up @racertop! I indeed want to work on slicing bu I have not found the time yet, so feel free to go for it and see where you can get. Maybe I can then steal some work for the slicing plans.

**Comment by racertop** [comment]
Thank you @boryanagoncharenko and @Felienne! I'll work on this and let you know where I get :)

**Comment by arjank** [comment]
According to PR #1694 this issue has been addressed but not fixed. It seems to me that the issue described in the ticket has been fixed (code runs as expected) and other calculations are also performed correctly. If there's still work that needs to be done, we should describe that, and maybe even offload it to a new ticket.

**Comment by jpelay** [comment]
> According to PR #1694 this issue has been addressed but not fixed. It seems to me that the issue described in the ticket has been fixed (code runs as expected) and other calculations are also performed correctly. If there's still work that needs to be done, we should describe that, and maybe even offload it to a new ticket.

The problem is not completely fixed in my opinion because there are still cases where we would fail to correctly typecheck, for example:

```
name is 'Hedy'
if name is Hedy
   name is 3
print name + 3
```

Here it would still mark an error, even though we are reassigning a number to the variable and this path will always be taken.

**Comment by Felienne** [comment]
Maybe you want this one back @boryanagoncharenko :P

**Comment by boryanagoncharenko** [comment]
The type system of Hedy is meant for simple programs and definitely cannot handle complex cases such as the example described by @jpelay. However, we recently added descriptive, translated error messages in the transpiled code (kind of "type checking at runtime"), which addresses the mentioned example. We have such "runtime type checks" for multiple commands including turn, forward, play, color, repeat, calculations etc. Maybe we could identify more examples where such checks should be added?

Please note that the code snippet provided above seems to be incorrect and it should yield a type error.
```
name is 'Hedy'
if name is Hedy
   name is 3
print name + 3
```
The code above does generate an error because the condition of the if-statement is not true. The correct program seems to be:
Levels 1-11
```
name is Hedy
if name is 'Hedy'
   name is 3
print name + 3
```
Levels 12-18
```
name is 'Hedy'
if name is 'Hedy'
   name is 3
print name + 3
```

@jpelay do you agree?

**Comment by boryanagoncharenko** [comment]
Since all code snippets now returns nice error messages, I will close this issue. We could open a new issue when a new piece of code needs to be addressed.
