### ISSUE TITLE
[CHORE] Clean-up TODOs in hedy.py

### ISSUE THREAD

**Issue by boryanagoncharenko** [hedyorg/hedy#1632]

**Comment by Felienne** [comment]
Thanks for opening this @boryanagoncharenko! I see this as an on going issue, something that we continuously need to check upon, because knowing myself I will make more in the future haha!

**Comment by boryanagoncharenko** [comment]
I was planning to resolve it now, but then I see there are more TODOs in hedy.py, so probably we should keep it open?

**Comment by Felienne** [comment]
Yeah and some more in the grammar files that are all mine, so let's keep this open for now! Thanks for your help on your todos!

**Comment by boryanagoncharenko** [comment]
Moved 2 TODOS from hedy.py to #1875 and #1876.
Removed 1 TODO which I don't remember what means :(

@Felienne shall I assign the ticket to you? Or do you want me to clear all of them from hedy.py?

**Comment by Felienne** [comment]
> Moved 2 TODOS from hedy.py to #1875 and #1876. 

Thanks!

> Removed 1 TODO which I don't remember what means :(

Haha I have had a few of those :D 

> @Felienne shall I assign the ticket to you? Or do you want me to clear all of them from hedy.py?

It would be lovely if you can go through what is there and make issues for what you can understand!! I will then try to pick up the remainder. Ow and they are not just in hedy.py but also in the grammars :/

**Comment by boryanagoncharenko** [comment]
Another small batch

**Comment by Felienne** [comment]
What to do about this one @boryanagoncharenko? We can also close it?
