### ISSUE TITLE
[IMPROVEMENT] Ensure the user cannot create an _END_BLOCK token

### ISSUE THREAD

**Issue by boryanagoncharenko** [hedyorg/hedy#1914]
The _END_BLOCK token is an Internal symbol used to denote end of blocks. It is used by the grammars but it is not supposed to come from user input; it is added by the preprocess_blocks function. Currently the value of the _END_BLOCK token is 'end-token'. 

With this issue, change the value of this token to ensure that the user can't write it.

**Comment by Felienne** [comment]
This seems rare enough that we can leave it for now.
