### ISSUE TITLE
[CONTENT] verification of the use of double quotation marks

### ISSUE THREAD

**Issue by thjazi39** [hedyorg/hedy#2269]
In case the PR #2249  would be accepted, the quizzes would have to be checked to ensure that the answers are correct. And this in all languages.

There is this question that will have to be corrected, but there are surely others.
![image](https://user-images.githubusercontent.com/48509466/159459451-f957227b-8a28-4ed1-9a37-7a37abd13af7.png)

**Comment by Rezwin** [comment]
Just to let you know I am looking at the fix for this issue.

**Comment by Rezwin** [comment]
I can see the options of this question has been changed on `main` branch. 

   ```
 2:
            question_text: "Which code uses the proper quotation marks?"
            mp_choice_options:
            -   option: |
                    ```
                    {print} `hello`
                    ```
                feedback: "This quotation mark is skewed, you need a straight one."
            -   option: |
                    ```
                    {print} 'hello'
                    ```
                feedback: "Correct"
            -   option: |
                    ```
                    {print} hello
                    ```
                feedback: "There are no quotation marks here!."
            -   option: |
                    ```
                    {print} ,hello,
                    ```
                feedback: "This is a comma, you need quotation marks."
            correct_answer: "B"
            hint: "Pick the right quotation marks."
            question_score: '10'

```

However the changes are not yet visible on the website. 

<img width="1027" alt="Screenshot 2022-07-11 at 16 31 15" src="https://user-images.githubusercontent.com/98986856/178734981-38193f7b-9d4b-42da-9ffa-257f013238fe.png">

Does anyone know if the changes has been already deployed to the main server ?

If the changes are already deployed, I guess the problem could be with rendering of backtick.

**Comment by Felienne** [comment]
Ha @Rezwin! I missed your comment sorry, I was on vacation.

Firstly, you can always see on https://hedycode.com/version what commits have been deployed!

I can also confirm the change is indeed live:

<img width="1369" alt="image" src="https://user-images.githubusercontent.com/1003685/180617595-471f437d-4846-4c14-9cfe-25f84cca458e.png">

But indeed ``` does not seem to be a good choice as it does not render properly, so either @TiBiBa should maybe make a change to the code block rendering here or you should change the option. Would it be hard to change the rendering?

**Comment by Rezwin** [comment]
> Ha @Rezwin! I missed your comment sorry, I was on vacation.
> 
> Firstly, you can always see on https://hedycode.com/version what commits have been deployed!
> 
> I can also confirm the change is indeed live:
> 
> <img alt="image" width="1369" src="https://user-images.githubusercontent.com/1003685/180617595-471f437d-4846-4c14-9cfe-25f84cca458e.png">
> 
> But indeed ``` does not seem to be a good choice as it does not render properly, so either @TiBiBa should maybe make a change to the code block rendering here or you should change the option. Would it be hard to change the rendering?

Thanks @Felienne 

I opened https://github.com/Felienne/hedy/pull/3102 to fix the issue.

**Comment by Felienne** [comment]
This issue was a bit derailed I think by the backtick issue and now I am not sure if the quizzes are all updated (removing the " as option) Could you check @jpelay
