### ISSUE TITLE
[Content] make sure all blanks use the same symbol (and explain it!)

### ISSUE THREAD

**Issue by thjazi39** [hedyorg/hedy#2380]
Blanks are not recognized on valid lines at levels 1-3:
![image](https://user-images.githubusercontent.com/48509466/160877692-c55c0405-3c0e-4c9a-b637-ed3120d6662d.png)

This is the opposite of bug #2359, because here the syntax highlighting is not applied, but the interpreter considers that YES, it should be colored (while in the case of bug #2359, it considers that the # should not be colored)
![image](https://user-images.githubusercontent.com/48509466/160877897-2e03f835-8834-495a-9827-7401ab445694.png)

As a result, the previous code, which is not excutable, cannot give the following result
![image](https://user-images.githubusercontent.com/48509466/160877987-aa2b40ac-2b7b-4ebf-91b7-1cb52e43b8b4.png)

**Comment by jpelay** [comment]
The current implementation doesn't allow to print blanks, not even on further levels. We preprocess blanks before they're fed to the transpiler (the program that makes Hedy code Python code). Maybe a solution to this is to not detect blanks that are inside a print? But this still leaves the issue that at levels 1-3 we can't distinguish string and vars, so maybe in this case this is actually what we want: you can't print blanks because blanks mean that you need to fill in some code there.

**Comment by Felienne** [comment]
Hi both!

I would say the highlighter is ok as it is, I consider this a content issue, we are content creators can make sure we don't use blank in that way, kids will never type blanks anyway (of they do, they don't mean them as blanks!)

**Comment by Felienne** [comment]
> Ok, so in that case, I have to correct the syntax highlighting so that the blanks are highlighted? (so that the kids understand where the error comes from)

No, leave this one for now. As I said I consider it a content issue.

The other changes to the highlighter (less overcoloring) are a lot more important, focus on those first

**Comment by Felienne** [comment]
Just a note to self, currently, both _ and _?_ are highlighted as blanks:

<img width="67" alt="image" src="https://user-images.githubusercontent.com/1003685/188414869-d62b1de9-182a-4670-a7f3-d53bc09dab01.png">

So the issue that remains here is to make sure: 
1. All locations use the same blank and
2. Explain what it means to users

**Comment by jpelay** [comment]
I feel the same way, this is not a bug it's a feauture!

**Comment by thjazi39** [comment]
> Just a note to self, currently, both _ and _?_ are highlighted as blanks:

it's not exactly that, currently only : `(^| )(_)(?= |$)` and `_?_` are recognized

- we need to escape the question mark because it is a symbol used in regex :
https://github.com/Felienne/hedy/blob/ff751661c8457d4ba020e45534b6d720f3b56e61/highlighting/rules_list.py#L34

- the underscore will be recognized only if there is a space on each side (with cases for the beginning and end of lines) :
https://github.com/Felienne/hedy/blob/ff751661c8457d4ba020e45534b6d720f3b56e61/highlighting/rules_list.py#L35

Thus the following strings will not be recognized:
```
e_e
e_
_e
?_
_?
?
 _  # with insecable space
```
