### ISSUE TITLE
[BUG] Finishing empty lines are not allowed on the translator

### ISSUE THREAD

**Issue by jpelay** [hedyorg/hedy#2383]
**Describe the bug**
Now that we solved issue #1140, the same thing is happening on levels 4 onward in the translator. For example on level 3 we have the following program as an example:

```
print 'Hola mundo'
        
```

Notice the spaces after the print (I didn't add them, they're there by default btw) So if I try to use the button to translate this to Spanish I get the following error: 

![image](https://user-images.githubusercontent.com/45865185/160955350-624f2942-0a05-4bbc-95e9-a1896b229cb1.png)

It is caused by the spaces, If I remove them, it works fine.

**Expected behavior**

Since it works on the transpiler, it should work on the translator as well.

**Comment by arjank** [comment]
I can't seem to reproduce this issue. Does it still exist?

**Comment by Felienne** [comment]
This seems to not be a problem anymore, I also can't reproduce it (and we only show this for the admin user, anyway)
