### ISSUE TITLE
[LANGUAGE] Add warning for unused variables

### ISSUE THREAD

**Issue by OnnoEbbens** [hedyorg/hedy#2394]
My students often create a variable that they don't use. For example:
```
name is Fatih
print 'my name is Fatih'
```
It would be nice to raise a Warning for each variable that was created but not used.

This could also help a lot in level 5 with if/else. I see a lot of students doing this:
```
name is print 'what is your name?'
if naam is gvr print 'ok' else print 'ai'
```
This code always prints 'ai' because the check (`naam is gvr`) is always false. It can be hard for a student to discover why. Raising a warning would inform the student that they've not used the variable `name` in the if-statement.

**Comment by MarleenGilsing** [comment]
Good idea!

**Comment by TiBiBa** [comment]
Love this idea! I'm not really familiar with the compiler (yet), but this seems like a great issue to dive into that code. Will try to implement this!

**Comment by Felienne** [comment]
I can imagine that @fRedelaar also wants to take this into account for the debugger (f.e. show a var in red in the list if ti is not used?)

**Comment by Felienne** [comment]
And this one I think could also be fun for you @jpelay, and not too hard? I do not think @fRedelaar will still do this as she has left the team a while ago

**Comment by nycdotnet** [comment]
For what it's worth, several editors I use will slightly gray out variables that aren't used rather than marking them in red; I like this as it is a subtle hint.  There are some languages such as Go where unused variables are actually a compilation error, but I don't recommend Hedy implement this as I think it's quite user hostile.

**Comment by jpelay** [comment]
> And this one I think could also be fun for you @jpelay, and not too hard? I do not think @fRedelaar will still do this as she has left the team a while ago

Yes, no problem :D
