### ISSUE TITLE
Range in for loop not recognised when misspelled

### ISSUE THREAD

**Issue by LauraTSD** [hedyorg/hedy#268]
![image](https://user-images.githubusercontent.com/23657961/113315293-69928500-930d-11eb-9e34-2fd4b301796a.png)

Range is not recognized when typed like rang.

**Comment by Felienne** [comment]
Issue still exists, f.e. current level 11:

```
for counter in rang 1 to 5
    print counter
```

What I guess is needed here is a more generic `invalid` rule. In early levels, we have invalid that is basically misspelled keyword followed by anything. Here we would want to gather all words in the line and see if they are like keywords.

**Comment by Felienne** [comment]
Now discussion in https://github.com/hedyorg/hedy/discussions/3759
