### ISSUE TITLE
[BUG] Type 'text' and type 'input from ask' cannot be merged together with the +-symbol

### ISSUE THREAD

**Issue by remva** [hedyorg/hedy#2689]
Right now, the input from ask cannot be merged with plain text, when the plus symbol is used. This immediately creates the following error (level 12 and higher levels):

![image](https://user-images.githubusercontent.com/77205246/166697542-e877f6ed-e9d2-4467-abe4-a4474ae6a706.png)

Solution: It should be made possible to merge the input from ask with plain text, if the input from ask turns out to be of type string/text.

On the other hand, there is no error if the input of ask is of type integer and is added to plain numbers. So this does not create an error:
![image](https://user-images.githubusercontent.com/77205246/166694282-f26c14a9-45df-4079-8f08-3c0432fd215c.png)

**Comment by boryanagoncharenko** [comment]
Nice catch! You can easily make the behavior of addition and concatenation consistent by adding `input_to_string` to the rules defined in [to_sum_typed_tree](https://github.com/Felienne/hedy/blob/main/hedy.py#L599) method. This will ensure that concatenating an input and string will not yield a static type check error.

**Comment by Felienne** [comment]
> Nice catch! You can easily make the behavior of addition and concatenation consistent by adding `input_to_string` to the rules defined in [to_sum_typed_tree](https://github.com/Felienne/hedy/blob/main/hedy.py#L599) method. This will ensure that concatenating an input and string will not yield a static type check error.

Hi @boryanagoncharenko! This could be an issue for you to pick up? It even has a bit of info from yourself to get started 😅
