### ISSUE TITLE
[Language idea] Translation of punctuation in code

### ISSUE THREAD

**Issue by Mark-Giesen** [hedyorg/hedy#2724]
The code (keyword) translation needs to be extended to translate other punctuation than western. 

In Chinese for instance the colon is not ':' but the '：' (unicode #ff1a). Same thing for the ';', this would be '；' (#ff1b). Comma's and periods might be the same. Apparently it's not hard for Chinese to use western punctuation, but it would be a lot friendlier if we supported both.

**Comment by Felienne** [comment]
Just because I was fixing this in Weblate the other day, a few more characters in Chinese that are very much like English ones:

```
！
（）
！
?
，
？
：
```

**Comment by Felienne** [comment]
This should be fixed by #4077, I have not explicitly added ? and ! in Chinese, since they do not really occur in the grammar anymore (a thing I realized when trying to fix this)
