### ISSUE TITLE
[BUG] What is the difference here?

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#2738]
```
            8:
                start_code: |
                    {repeat} ٥ {times}
                        {print} "مرحباً يا أصدقاء!"
                        {print} "سيتم تكرار كل هذا ٥ مرات"
                story_text: "## الإزاحة\n`{ask}` و `{print}` لا يزالان يعملان بنفس الطريقة التي تعرفونها. لكنهناك تغيير على الأوامر `{if}` و `{repeat}`.\nيمكننا الان عند استخدام هذه الأوامر تنفيذ مجموعة من الأسطر البرمجية مع بعضهم (وليس سطر واحد فقط)، ولكن علينا *إزاحة* الكود. \nهذا يعني وضع اربع فراغات (باستخدام مفتاح المسافة على لوحة المفاتيح اربع مرات). يجب علينا أن نقوم بالإزاحة حتى لو كان الكود يتكون من سطر واحد فقط.\n"
                example_code: "## مثال توضيحي\n```\n{repeat} ٥ {times}\n\t{print} \"مرحباً يا أصدقاء!\"\n\t{print} \"سيتم تكرار كل هذا ٥ مرات\"\n```\n"
```

start_code works, example_code does not parse nor highlight (from the adventure yaml). I do not have time to dive in now but one day I want to figure this one out.

**Comment by arjank** [comment]
@Felienne could you verify whether or not this issue still exists? I think either it has been fixed, or I should improve my skills in reproducing issues ;)

**Comment by Felienne** [comment]
This is not an issue more a note to self!

I will have to dive in myself here

**Comment by jpelay** [comment]
> @Felienne could you verify whether or not this issue still exists? I think either it has been fixed, or I should improve my skills in reproducing issues ;)

I think if you substitute the code with the arabic keywords it doesn't work

```
## مثال توضيحي
 كرر ٥ مرة
    قول "مرحباً يا أصدقاء!"
    قول "سيتم تكرار كل هذا ٥ مرات"
```

**Comment by Felienne** [comment]
This is an editor issue, nothing to be fixed here apart from paying a lot of attention when editing Arabic
