### ISSUE TITLE
[PERFORMANCE] Create a cron job to retrieve all public programs each x minutes

### ISSUE THREAD

**Issue by TiBiBa** [hedyorg/hedy#2930]
**Description**
With the merging of #2929 we improve the server load by caching all public programs once. However, this is not ideal as we only perform this on server start and don't change this cache list later on. We should implement some type of cron job to update the list each x minutes.

**Comment by Felienne** [comment]
I am not sure this is still true and/or still an issue? Do you happen to know @TiBiBa? I am cleaning up issues for tomorrow :)

**Comment by Felienne** [comment]
We don't cache the programs anymore but we use pagination, so this is no longer relvant
