### ISSUE TITLE
[UI idea] Make sure the browser is notified on password change

### ISSUE THREAD

**Issue by TiBiBa** [hedyorg/hedy#3081]
**Idea incl level**
Currently the browser does not handle a password change well as it is not notified. This is cumbersome to work with when using something like a password manager (which I assume most users do). You have to manually edit the password when changing because it won't update. It would be nice if we dived into how this process works and trigger this on a password change (or logging in with an unknown password).

**Comment by Felienne** [comment]
In our new view, our users (teachers, students) are unlikely to use password managers.
