### ISSUE TITLE
[BUG] Mailing list is blocked on Firefox

### ISSUE THREAD

**Issue by alexnederlof** [hedyorg/hedy#3157]
**Describe the bug**
When subscribing to the mailing list using Firefox nothing happens.

When using Firefox, all mailchimp code is considered "Tracking code" and therefore blocked. Unfortunately Mailchimp does not handle this error so as a user it looks like nothing happens when you press the button.

**Add a screenshot (optional)**
![Screenshot 2022-08-15 at 20 32 05](https://user-images.githubusercontent.com/992615/184708711-07102785-9954-4092-9bf9-03dde3ec7129.png)

**Expected behavior**
Email form should work.

**What machine and browser you were using (optional)**
Mac, Firefox 103.

Verified it works on Chrome and Safari. 

**Workaround**
Use other browser. 

Since this is a generated form by Mailchimp, you may want to consider telling the user upfront it won't work in Firefox unless they disable blocking, or by using another browser.

**Comment by TiBiBa** [comment]
Thanks for finding this bug! I will look into this if we can make a work-around and otherwise notify the user as suggested.

**Comment by TiBiBa** [comment]
It seems this is a common issue: 
https://discourse.webflow.com/t/webflow-mailchimp-form-not-working-in-firefox/54679/6

But also a possible solution is provided:
```
After stressing out by trying multiple different things, I found out that by removing the “s” from the “https://” part of the Form Action url, that it FINALLY worked!
```

**Comment by alexnederlof** [comment]
I would *strongly* advise you not to try that workaround. It would send user email and name unencrypted over the wire. Besides, I think that it won't even work as Firefox should block unencrypted traffic.

**Comment by TiBiBa** [comment]
> I would _strongly_ advise you not to try that workaround. It would send user email and name unencrypted over the wire. Besides, I think that it won't even work as Firefox should block unencrypted traffic.

Agree. For now I will look into a simple message until I have time to dive into this issue.

**Comment by alexnederlof** [comment]
If you have a lot of FireFox users you could consider proxying it over your backend, but then you lose the anti-spam detection from Mailchimp which I think is part of the current code
