### ISSUE TITLE
[UI idea] Improve responsiveness of public profile page

### ISSUE THREAD

**Issue by TiBiBa** [hedyorg/hedy#3158]
**Description**
The screenshot below should be self-explanatory.
![Schermafbeelding 2022-08-16 om 10 35 23](https://user-images.githubusercontent.com/38155424/184835591-19ff6f08-69e5-44ed-af5d-103561a32f03.png)

**Comment by TiBiBa** [comment]
Will work on this once #3159 is merged as we also work on the same template in that PR.

**Comment by reedspool** [comment]
I plan to look into this before the collaborator meeting. Should I assign myself?

Also, is what it should look like at my discretion? That is, there's no existing visual design decisions made about this page/component at a skinny screen size? I'll include screenshots with a PR so we can discuss any choices I make.
