### ISSUE TITLE
[UI idea] Allow multiple teachers for a class?

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#3197]
This year @OnnoEbbens and me will co-teach a course and we were thinking other teachers might also be in this situation, would it be doable to allow 2 teachers to view the progress of a class and maybe also to make modifications? I am not sure how involved that would be?

**Comment by TiBiBa** [comment]
I think this is possible! It would require quite some re-structuring as we verify in a lot of places if the user is the teacher of the class.

This should all be changed to some list structure, supporting multiple teachers. Wouldn't be to hard if we didn't have any classes yet but as we have 100+ already this makes it a bit more complex. Fastest way might be to write all the code and manually change all already existing classes from "teacher" to "teachers".

We do have to think about some edge cases:

- can both teachers remove the class?
- are there possible dead lock situations?

**Comment by Felienne** [comment]
Yeah I think @sanyaade-teachings's idea of a primary and a secondary teacher would make a lot of sense! But we don't have any bandwidth to work on this now I fear

**Comment by Felienne** [comment]
We already have this now!
