### ISSUE TITLE
💻 Remove/change a few initial achievements

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#3267]
**Describe the issue**
If you just created a new account, you get a lot of achievements, which can be 1) distracting and 2) not really what we are going for. I think we should change a few, f.e. running 1 program might not be so useful, in addition to the tutorial one?

**Comment by AnneliesVlaar** [comment]
I have looked at the achievements for students. Here is a list of the achievements with suggestions to keep (K) and maybe adjust a bit, remove (X) and ideas to add (A) new achievements. Name suggestions for new achievements are put between double quotes. 

**General**
- X -  Finish the Hedy tutorial: which tutorial?
- X - Store a program from an adventure: saving is not a thing anymore, this one can be removed.
- K - Run a successful program after an error: nice one, does not work after every kind of error,  for example is not achieved when you forget to use print in front of text. But when print is misspelled it is achieved. Can this one be expanded to running a successful program after 3 errors in a row?
- X - Create a program with the 'ask' command: is achieved when example code is used. 
- A - Create a program with 3 ask commands. "Burning questions".
- A - Create a program with 5 echo's. "Echoput".
- K - Create a program that has no output: Nice one. 
- K - Use all Hedy commands at least once: nice (but I haven't achieved it yet, although I though I used them all...)
- K - Create a program with the turtle: is achieved with example code. Maybe change it to 'Let a turtle turn around' (as in 360 degrees). "Giddy" or "Seasick".
- X - Share a saved program: I think sharing stuff should be a decision from the student itself and not be pushed by achievements.
- X - Delete a saved program: is this action important? The button to delete a program is very hidden.
- X - Join a class: If a teacher creates the accounts for the students, they are already in a class and don't achieve this. 
- K - Turn on the programmers mode: nice one.
- K - Let your program be read aloud: nice.
- X - Finish a Hedy quiz: The achievement is not visible.
- X - Get the maximum score on a quiz: The achievement is not visible when achieved.
- X - Get a duplicate program name warning: I am not able to achieve this. 
- A - Rename a program. "Organiser"
- X - Create a public profile: I think sharing stuff should be a decision from the student itself and not be pushed by achievements.
- K - Change your profile picture: nice. Can this only be done when making your profile public?
- K - Search within the explore page: although I already achieve it when clicking explore. Maybe changing 'search' into 'sniff'.
- K - Programs created: Maybe change the title to "Programs executed".
- X - Programs saved: not a thing anymore.
- K - Programs submitted: The achievements are not visible when submitting a program. If you submit all programs of level 1 you have all achievements. I would suggest to change it into submitting 3, 10, 30, 100 programs. 

**Hidden**
- X - Run a program that prints the text 'Hedy': is achieved with example code.
- A - Run a program that uses Hedy as a variabele name.
- ? - Hedy-ious
- ? - Talk-talk-talk
- ? - Hedy Hacking
- ? - Programming Panic
- ? - Watch out!

**Suggestions**
- A - Use the debugger. "pest controller" "Wat mot je?"
- A - Use the yellow copy button. "Copy cat"
- A - Switch language of commands. "bilingual"
