### ISSUE TITLE
[CONTENT] wrong quiz question

### ISSUE THREAD

**Issue by OnnoEbbens** [hedyorg/hedy#3273]
Question 3 in the quiz from level 3 is incorrect. The question is "What's wrong in line 2 of this code?" and should be "How do you fix the mistake in line 2 of this code?"

This is also wrong in the Dutch translation. I don't mind fixing this but I am afraid if I create a pull request there will be problems with Weblate. That is way I've created this issue first.

**Comment by Felienne** [comment]
Ah thanks @OnnoEbbens and yes, fixing issues here can cause problems with Weblate (although we can fix them so don't worry too much about it)

 If you want to, you can fix the error in weblate directly! But of course I can also do it!

**Comment by Felienne** [comment]
Also for @MarleenGilsing?

**Comment by OnnoEbbens** [comment]
I think I fixed this in Weblate

**Comment by Felienne** [comment]
I see you did indeed fix it, but that does not mean it it fixed in all (copied) langs, which is not a problem for you but it is nice to keep up to date for the project, so I made a new PR!
