### ISSUE TITLE
[Language idea] move `color` for the turtle drawing to a higher level

### ISSUE THREAD

**Issue by OnnoEbbens** [hedyorg/hedy#3275]
A few months ago the color command was added to the drawing with turtle. I really like that students can now use colors! However I think we should introduce this command in a higher level (3 or 4) because the first level contains a lot of information already. Also it would be nice to use the color in more higher level adventures since it is now only shown in level 1 and not mentioned in any higher level (although it does work in higher levels).

**Comment by Felienne** [comment]
One for @MarleenGilsing I think?

**Comment by MarleenGilsing** [comment]
Whoops think I missed this issue, but I'm on it!

**Comment by MarleenGilsing** [comment]
Moved it to level 4, because 4 did not have new exciting features for the turtle. But now it does :) 
#3612
