### ISSUE TITLE
[CONTENT] Quiz question 1 level 4 (Dutch) multiple correct answers, only one is allowed

### ISSUE THREAD

**Issue by OnnoEbbens** [hedyorg/hedy#3277]
Question 1 level 4 (Dutcht) answer 2 "In level 4 werkt ask anders dan in level 2" is marked as wrong and answer 1 "In level 4 werkt print anders" is marked correct. If 1 is correct 2 should be correct as well.

![image](https://user-images.githubusercontent.com/10562903/190096793-74a06e05-5f33-44ac-9326-2f4e4048c477.png)

**Comment by OnnoEbbens** [comment]
Question 2 of the same quiz also has multiple correct answers while only one is marked as correct. In Hedy you can use both single ' and double " quotation marks. We only explain the single ' quotation mark but the double " works as well.

![image](https://user-images.githubusercontent.com/10562903/190098131-acc80e0f-d064-46ff-810f-e7bc39edcfb1.png)

**Comment by jpelay** [comment]
Hi! @MarleenGilsing I was working with this one, and sure enough, there are 2 possible answers in the Dutch quiz, but @Felienne and I agree that it's better if we leave a single answer possible for each question. What do you think? In both cases mentioned in this issue, both questions have a single answer in English.
