### ISSUE TITLE
[BUG] Reported line number out of sync after each indented statement-block

### ISSUE THREAD

**Issue by eremmel** [hedyorg/hedy#3291]
**Describe the bug**
When program contains a bug at line N, the line number N is reported in the error block below the program-enter-window. But the line number gets out of sync after each indented code block (nested indenting adds as well). My impression is that the size (number of lines) in the indented block do not contribute to the line number deviation.

**Paste the Hedy code & level**
The issue is observed at the levels: 8, 10, 13, 17, 18 (not all levels tested).

**Add a screenshot (optional)**
Here is a program without indenting and an error on line 7. Reported correctly:
![image](https://user-images.githubusercontent.com/1874108/190660572-57f636b9-ab03-425f-b128-66fea6f09711.png)

Now lines 4 to 6 are replaced with indented block note the reported line number:
![image](https://user-images.githubusercontent.com/1874108/190661011-6095d077-598e-49ac-bd3f-d8f490231535.png)

This happens with two indented blocks of code:
![image](https://user-images.githubusercontent.com/1874108/190661381-024c1c26-9dd8-4720-9b4f-227a7c6b7ed6.png)

So some larger and complicated programs get hard to debug...

**Expected behavior**
Correct line number should be show regardless program contains indented code block or not.

**What machine and browser you were using (optional)**
N/A. Server issue.

**Comment by sfayyad** [comment]
Hi! I'm new to open source and would love to get my hands on this as one of my first contributions!

**Comment by Felienne** [comment]
Hi @sfayyad! I am already working in this (see the linked PRs) so no need to pick this one up at the moment
