### ISSUE TITLE
[BUG] remember entered accounts

### ISSUE THREAD

**Issue by Mark-Giesen** [hedyorg/hedy#3292]
**Describe the bug**
When adding accounts, you can enter 26 names, which I did, and when "creating accounts" fails (duplicate or wrong character), all textboxes are filled with my loginname again. That is very annoying :-)

**Expected behavior**
Leave all textboxes filled

**Comment by TiBiBa** [comment]
I think the auto-filling with your own username is a browser specific issue (however, we should still prevent this). Emptying the form should only happen on success, I will look into this!

**Comment by TiBiBa** [comment]
I'm unable to re-produce this issue on Safari and Chrome, what browser are you using?

**Comment by MarkGiesen** [comment]
Brave, a chromium browser.
