### ISSUE TITLE
[BUG] Handling of indexed data not always  consistent.

### ISSUE THREAD

**Issue by eremmel** [hedyorg/hedy#3293]
**Describe the bug**
One can use index data from a list. In a number of situations you can use that index-expression (e.g. mylist[i]) directly as expression in a more complex situation. But not at all logical places.

The most minimal implementation is to use an index-expression as the only r-value in a assignment expression. This approach will always work (line 6).
Some more complex and working examples are seen below in the screen shot.
line 7: can be in boolean expression.
line 8: can be in print statement

Accepted with questionable results:
line 9: treated as unquoted literal string (any way wrong at level 18)
line 10: treated as unquoted literal string (?) at least value is not removed.
An not excepted expression is 'if mylist[i] in mylist3:'
 
**Paste the Hedy code & level**
Run this only on lvl 18:
![image](https://user-images.githubusercontent.com/1874108/190668103-64136f3d-53c0-4aba-ac53-47b574aefbc5.png)

**Add a screenshot (optional)**

**Expected behavior**
Allow index expression on all places where a  'input'  type is allowed or force only the most simple approach: indexed data needs to be  copied to variable first and that variable can be used in expressions.

**What machine and browser you were using (optional)**
N/A Server issue.

**Comment by Felienne** [comment]
Hi @boryanagoncharenko!

Here is another language related issue. If might be fixed by #3685, but I am not sure (I did not check) if it does, feel free to close it!

**Comment by boryanagoncharenko** [comment]
PR #3685 addresses having list access of the left-hand-side of adding and removing from/to lists, so I am closing the issue.
