### ISSUE TITLE
[CONTENT] Explain that list assignments are using reference copy

### ISSUE THREAD

**Issue by eremmel** [hedyorg/hedy#3294]
**Describe the bug**
I noticed that assignment of a list to a new variable is (just as in python) a reference copy. But with a language like hedy I expect that assignments are always deep copies for mutable data types like lists.

**Paste the Hedy code & level**
Observed at lvl 18
![image](https://user-images.githubusercontent.com/1874108/190674969-8d0ee4cc-9555-412b-bed2-158c8f423b28.png)

**Expected behavior**
assignment of a list to new variable should be a deep copy.

**What machine and browser you were using (optional)**
If the issue concerns things in the website, let us know:
- What computer you are using (Windows, Mac, Linux?)
- What browser you were using (Chrome, Edge, Safari)

**Comment by Felienne** [comment]
Interesting point! I guess since we are building up to Python, I find the behaviour ok as it is, but I agree we could explain it in a bit more depth. Feel free to open a PR or to add some extra text in Weblate, I will not be picking this up soon because we have so many other things going on atm.
