### ISSUE TITLE
[BUG] list manipulation with literal-values are interpreted as strings.

### ISSUE THREAD

**Issue by eremmel** [hedyorg/hedy#3295]
**Describe the bug**
One can change the content of a list with 'remove X from list' or 'add X to list' When X is a variable (input) its value is taken according the input's type and all is well. But when X is a number of an unquoted string (should not be acceptable at lvl 18) it is treated as a string.

**Paste the Hedy code & level**
Lvl: 18, other not checked.
![image](https://user-images.githubusercontent.com/1874108/190677022-742232d4-080a-40e2-8429-9060888a3a4c.png)

**Expected behavior**
the commands remove X from.... and add X to ... should:
- When X is a word without quotes it should be a valid variable (input) otherwise an error should be given: string literals should be placed between quotes.
- When X is a literal number it should be handled as a literal number (and not implicit converted to string)  

**What machine and browser you were using (optional)**
N/A server response.

**Comment by arjank** [comment]
I've checked what happens when you add a variable to a list. It will correctly add the value that's assigned to the variable, and it will not change numbers to strings. So it looks like the main issue is that numbers are added as strings instead of numbers.

**Comment by agusikhin** [comment]
Hi! Could @maryannho123 and I be assigned to this?

**Comment by agusikhin** [comment]
> Hi! Could @maryannho123 and I be assigned to this?

Just wanted to follow up on this! We are students at the University of Michigan and we would like to contribute to Hedy as part of a project we are working on. Thanks!

**Comment by boryanagoncharenko** [comment]
This issue has been resolved by #5548. Quotes are now required when adding and removing elements to/from a list. Numbers are not converted to strings when added to a list.
