### ISSUE TITLE
[CONTENT] Copy teacher's docs to teacher facing spots

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#3305]
Our technical docs on Github have quite some info on how teacher features work (in https://github.com/Felienne/hedy/blob/main/TEACHERS.md). While it is good to have it here, where Hedy devs can read it, a lot of this should also be merged in a place where teachers can find it.

There are two places where that information should also be placed:

1. In the teacher welcome email (f.e. https://github.com/Felienne/hedy/blob/59e60e449b180471fc9bcac3485cd5284abab876/translations/en/LC_MESSAGES/messages.po#L1281) 

2. In the Teacher's Guide (https://github.com/Felienne/hedy/blob/main/content/pages/en.yaml)

**Comment by shay2442** [comment]
Do you just want the link put in those two places? Or do you want all of the content displayed? I could do either

**Comment by Felienne** [comment]
> Do you just want the link put in those two places? Or do you want all of the content displayed? I could do either

Great question! I could have thought about it a bit more! It came in a discussion on Discord and I wanted to not lose the idea. I propose the following:

We put the info from the md file into the teachers docs (point 2) Some of it is already there, so it will require a bit of "massaging" to get it in the right form.

There will also be some things in the docs that do not need to go to the teacher's page, f.e. the stuff about the invite codes is not needed there. If you want to take a stab at it with the vague constraints, that'd be lovely @shay2442 (and welcome to Hedy, are you in our Discord yet?)
