### ISSUE TITLE
[CONTENT] at random is moved to level 4

### ISSUE THREAD

**Issue by Mark-Giesen** [hedyorg/hedy#3307]
**Describe the issue**
In the "next" tab of level one it is said that "at random" wil be learned in the next level, but this seams to be moved to level 3?

**Comment by Felienne** [comment]
Great catch! Indeed that changed! Can you update that in Weblate?

**Comment by Felienne** [comment]
Maybe a small task for @jpelay (together with the few open quiz issues we have remaining?)

**Comment by jpelay** [comment]
> Maybe a small task for @jpelay (together with the few open quiz issues we have remaining?)

Miss Felienne, with "the few open quiz issues we have remanining" you mean those like #3277 #3347 ? Can you tell me which ones do you refer here? Thank you!

**Comment by Felienne** [comment]
> > Maybe a small task for @jpelay (together with the few open quiz issues we have remaining?)
> 
> Miss Felienne, with "the few open quiz issues we have remanining" you mean those like #3277 #3347 ? Can you tell me which ones do you refer here? Thank you!

Yes, those two! I thought we might be able to do it in 1 content PR (maybe even via Weblate to not create merge issues?)

**Comment by jpelay** [comment]
Closed by #3271
