### ISSUE TITLE
[BUG] error message unclear in level 5 when forgetting the last quote

### ISSUE THREAD

**Issue by OnnoEbbens** [hedyorg/hedy#3329]
When you forget the last quote in a `print` or `ask` statement the error is unclear (although most of the times not completely off). When you run the same code in level 4 the error is very clear.

```
print 'Hoi ik ben Hedy de Waarzegger
print 'Ik kan voorspellen wie morgen de loterij wint!'
naam is ask 'Wie ben jij?'
```

Error in level 5:
![image](https://user-images.githubusercontent.com/10562903/192335434-952b3654-9f65-49b2-814c-c4b419b97687.png)

Error in level 4:
![image](https://user-images.githubusercontent.com/10562903/192335591-9a28859f-36e6-46f8-a8b6-bad29912e99e.png)

In this example the error in level 5 is still quite clear. The error type is correct only pointing to the wrong line of code. In some cases, that I cannot reproduce right now, the error was completely wrong when the last quote was missing.

**Comment by OnnoEbbens** [comment]
I forgot to say that the error messages in level 1 to 4 has improved so much that my students have no questions anymore. Teaching has become so easy. Thanks a lot!

**Comment by Felienne** [comment]
> I forgot to say that the error messages in level 1 to 4 has improved so much that my students have no questions anymore. Teaching has become so easy. Thanks a lot!

Let's aim to get to that level too for higher levels, I will see what I can do about this specific one (and I'll examine the logs for even worse ones you might have seen today)
