### ISSUE TITLE
[BUG] Scrollbar on Edge in Windows blocks code

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#3341]
**Describe the bug**
If you have a long program, the scroll bar overlays the final letters of lines:

![image](https://user-images.githubusercontent.com/1003685/192771897-8be35a92-7ef2-43c4-8154-d24032aa49ef.png)

This is annoying if that is exactly the location of a missing `'` (this is not a hypothetical story haha, spent 10 mins looking with a kid today)

We fixed a previous similar issue #3249 by moving the blur button, but I think we should put the scroll bar outside the code at all (and then we can roll back this small blur change)

**Comment by TiBiBa** [comment]
Looks like this needs some 'not-really-supported-but-still-possible CSS tweaking', will look into this!

**Comment by Felienne** [comment]
Hi @jpelay!

I am cleaning up issues :) Could you check whether this will still be an issue with CodeMirror in the open branch? If not, you may close this!

**Comment by Felienne** [comment]
Cool! Let's close this cause it will be fixed when we move to CodeMirror (hopefully soon!)
