### ISSUE TITLE
[BUG] In mandatory developer mode, switcher remains visible (and usable)

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#3363]
**Describe the bug**
If I enable developers mode as a teacher, the switcher is still visible:

![image](https://user-images.githubusercontent.com/1003685/193267900-d8f6c251-8349-4c2e-99c5-46cc954104a6.png)

And I can also use it (once back and forth) and then the adventures come back.

And I was thinking, maybe we should also remove the tabs in (mandatory) developers mode?

**Comment by TiBiBa** [comment]
This should be an easy fix, will look into this! Originally we had the tabs hidden when on developer's mode, but if I recall correctly we decided a few months ago to allow users to switch tabs as their corresponding saved programs are automatically loaded and they can, for example, switch to the teacher exercise and save/submit that one.

**Comment by Felienne** [comment]
Thanks!! I was wondering why we kept the tabs, I think in retrospect we want to tabs to also be gone?

**Comment by TiBiBa** [comment]
The only issue with removing the tabs is that a user is unable to directly continue working on a program they saved within a specific adventure. For example, when someone saves a program in "level 7 - turtle" it is automatically loaded when selecting this tab in level 7. We remove this feature when also removing the tabs. Is that something we prefer?

I'm not sure how much this function is used by teachers. But I can imagine that it is used in combination with some sort of "final assessment" that is stored in a custom adventure and will be useful when able to continue working on it (and automatically loading).

**Comment by Felienne** [comment]
> The only issue with removing the tabs is that a user is unable to directly continue working on a program they saved within a specific adventure. For example, when someone saves a program in "level 7 - turtle" it is automatically loaded when selecting this tab in level 7. We remove this feature when also removing the tabs. Is that something we prefer?

Yeah the whole saving and loading should be rethought anyway, but if a kids has saved a program, opens it and then goes to dev mode, that would still work right?

> I'm not sure how much this function is used by teachers. But I can imagine that it is used in combination with some sort of "final assessment" that is stored in a custom adventure and will be useful when able to continue working on it (and automatically loading).

Ah yes that is a way in which people use it sometimes, but I think mostly it is kids that want more space for a bigger program or bigger output.
