### ISSUE TITLE
[BUG] Issue in DST generation does not (always) lead to front-end error shown

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#3367]
**Describe the bug**
Sometimes (but not always) a problem in dst generation does not show a 500 but just silently fails, for example in level 1:

```
color black
forward -20
turn right
forward 20
```

(this fails because of the color but that is not the issue here, I will solve that separately)

Here is Chrome shown with the error in the console but not in the screen:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/1003685/193527183-00c07573-7db1-4ca8-93eb-381ad490721f.png">

**Comment by TiBiBa** [comment]
Weird! Might have something to-do with the cumbersome way we generate and download the .dst-files. Currently we generate the file on the server, store with a hash name (like 032493dfsf.dst) and then retrieve it, send it to the user and delete again. If I recall correctly we use some dependencies to make sure the flow integrity is always there, but we might have missed some.
