### ISSUE TITLE
[UI] "preview as student" option for teachers

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#3374]
**Idea incl level**

It will be a lot of work but it would be great if we could have a "view as student" button in the Teacher's UI where a teacher can see exactly what the interface will look like for students (I do this my opening a second browser but that is kind of cumbersome).

This is quite a common features in such teacher tools.

**Comment by Felienne** [comment]
> * Do we want to add a button to the customizations page (or the class overview page?)

I think it only makes sense for customized classes (otherwise teachers can just go to /hedy themselves)

> * How do we enable the teacher to return to their own profile view
>   
>   * Maybe implement an apart routing to view the levels
>   * Instead of `/hedy/<level>` something like `/hedy/preview/<class_id>/<level>`

That would be lovely! And then add a button or link to go there on the customization page.

> Maybe the easiest solution: When the teacher selects 'preview as student' we simply add the teacher as a student to their own class. This way everything is automatically rendered as expected. When using the return option 'overview button, close page old' remove the teacher from the class again.

Ah yeah that would be an easy way to make it work with not too much effort! 

But I guess we can also grab the customizations from the database (we already have them to populate all the checkboxes) and use those to render the `/hedy/preview/<class_id>/<level>` page? That might be a bit less "depending on voodoo"?

**Comment by sfayyad** [comment]
Hi! If this is still open, I would love to be assigned to the issue and work on it!

**Comment by Felienne** [comment]
@sfayyad yes it is still open! It would be great if we could get this to work but it will be very complex (for front and back-end work), so it might be hard to get started? Maybe you want to pick up an issue with the `good first issue` label first?

**Comment by sfayyad** [comment]
It is complex; however, I have experience working on tasks similar to this, so I believe I can do it!

**Comment by Felienne** [comment]
Hi @jtwaleson!

If you are looking for a front-end issue that would add a lot of value, this would be awesome!

**Comment by jtwaleson** [comment]
@Felienne I'm going to take a stab at this this week, but it's quite complex and I'll probably have some questions while implementing.

First questions: I'm assuming we only want to view the class, and not impersonate any specific students to "see what they see"? So if we write it as a user story it'd be something like:

"__As a__ teacher __I want to__ see what a customized class looks like as a student __so that__ I can preview it before I open it up to my students."

Is my understanding correct?

Do we want to make this fully read-only, or are you able to also run some programs while in "preview mode"?

**Comment by yilmazdurmaz** [comment]
Consider these:
- I am not sure if you implemented it knowing, or if it is a side effect, but a teacher can join in their own classes as students. I have used this (and still using) to test score setting on quizzes, level locks, etc.
- I haven't actually tested what happens if teachers have their own adventure layout, but I fear it won't work as expected because my account is a teacher's.

Then I would suggest two things to have:
- make teachers a student of their own classes (invisible to students) by default
- modify pages to have an extra check (and switch button) for teachers to go "non-teacher" view mode, which will become student's view when combined with above. (if is_teacher and as_teacher show view_teacher?!)

**Comment by jtwaleson** [comment]
Thanks, that's helpful context! I haven't looked at the teacher UI much so far so I'll start by exploring that.

**Comment by yilmazdurmaz** [comment]
to find the current way fast, in the class view (create one if none), use "add student" -> "invite by username", write your own username. then you will get notification of the invite and join in upon accepting it.

**Comment by Felienne** [comment]
As discussed in the meeting today, we would already be happy with just viewing, editing might not even add value, but certainly is not necessary to move this forward for now.
