### ISSUE TITLE
[CONTENT] New adventures to explain new pygame keywords

### ISSUE THREAD

**Issue by daandj** [hedyorg/hedy#3414]
❗ https://github.com/Felienne/hedy/issues/3337 , #3406 and #3546 have to be completed first, otherwise the new adventure won't work.

Issue #3337 adds a new keyword 'pressed' to the hedy language of level 5. In order for the students to learn about this keyword and how to use it, a new adventure should be added to level 5 with an example and explanation.

**Comment by maximilionis** [comment]
Still returns an error message saying pygame_end not defined when running unit tests on level 8
