### ISSUE TITLE
[CONTENT] Wrong translation in dutch "spiekbriefje"

### ISSUE THREAD

**Issue by Mark-Giesen** [hedyorg/hedy#3417]
**Describe the issue**
In the Dutch spiekbriefje (menu item with possible commands) in level 3; to is translated as tot, this should be toe. Maybe this is in code (so wrong in every language) or maybe just in some translations, like Dutch.

**Add a screenshot (optional)**
![image](https://user-images.githubusercontent.com/28646458/195832902-19b718b2-7bad-4cf3-a123-e691f0e56f45.png)

**Comment by TiBiBa** [comment]
This list is dynamically created from the keyword translations used throughout the whole app. Maybe we have two different variants of 'to'? Can't think of another reason this would be incorrect.

**Comment by Mark-Giesen** [comment]
Yes, we have two versions of to: to_list and to.

**Comment by TiBiBa** [comment]
Whoops, good catch! This is a bit complex to fix as the 'spiekbriefje' has a bit of a straightforward implementation. As all translations are stored as a dict of keyword combinations (English - other language) we do a simple look-up where we iterate over the dictionary, getting the translation for the requested language by using the English keyword as key and storing it here. Never keeping in mind that some keywords are stored different in the parser than how they are displayed.

We have two feasible solutions:
- Make a bucketfix, simply hard-code if "to": do some extra check to find out which one
- Improve the look up by finding out dynamically which one it is (probably with some parsing)
