### ISSUE TITLE
[UI idea] Add informational overlay message on disabled level button

### ISSUE THREAD

**Issue by TiBiBa** [hedyorg/hedy#3431]
**Idea incl level**
Currently we "grey out" the next / previous level button when it is disabled by class customizations for any reason. This can be because it is locked by the teacher or the quiz threshold has not been reached yet. It would be nice if we return some informational message to the user as **why** the button is disabled.

When using direct routing we already have an explanatory error message on the "not allowed" page, something similar should be implemented on the button. Note: It would be nice to generalize this and create some funky jQuery class we can call on any HTML element to add an overlay string. This can be useful for multiple purposes and keeps or implementation a bit uniform.

**Comment by reiades** [comment]
hello, I am interested in working on this task!
