### ISSUE TITLE
[BUG] Variable names in the "Variables" pop-up sometimes have confusing suffixes

### ISSUE THREAD

**Issue by jeremydavis519** [hedyorg/hedy#3432]
**Describe the bug**
When I click the button to see the variables after or while running a program, some of them have suffixes that would confuse most students. In particular, `name` (a very common variable name in early examples) is shown as `name_$rw$`. I don't know if this happens with any other variable names.

**Paste the Hedy code & level**
This happened in Level 2. I haven't checked any higher levels, but I wouldn't be surprised if it happened in all of them.
```
name is Hedy
age is 15
print name is age years old
```

**Add a screenshot (optional)**
![image](https://user-images.githubusercontent.com/14192265/196489871-c2f436e8-6b2d-4c02-91fd-6298323d1051.png)

**Expected behavior**
The variable `name_$rw$` on the right should just be called `name`.

**What machine and browser you were using (optional)**
If the issue concerns things in the website, let us know:
- What computer you are using (Windows, Mac, Linux?)
  - Windows 10
- What browser you were using (Chrome, Edge, Safari)
  - Brave

**Comment by Felienne** [comment]
Weird, I am not sure why this happens! I though it was maybe because of a clash with Python reserved words, but name is not one:

https://github.com/Felienne/hedy/blob/175b4abaa6cb0c04bbd39910a5af5bcc98951ac5/hedy.py#L37

Maybe @jpelay wants to dive in?

**Comment by jpelay** [comment]
Hello! Yes, I tried in every level and it does happen in all of them!
