### ISSUE TITLE
[BUG] Switching languages fails to update the keyword translation

### ISSUE THREAD

**Issue by jeremydavis519** [hedyorg/hedy#3433]
**Describe the bug**
If I have keyword translation enabled and I switch to a different language without first disabling it, the keywords in the example code remain in the first language. Toggling keyword translation off and on again resolves the issue, but it's still inconvenient, especially in English and languages without translated keywords (as the toggle doesn't exist in those languages' UIs).

**Paste the Hedy code & level**
I tested this on Level 2 using the Turtle adventure, but it should reproduce everywhere.

**Add a screenshot (optional)**
After a transition from Dutch to English:
![image](https://user-images.githubusercontent.com/14192265/196496183-0ea11c2f-a985-434f-b608-729db0101343.png)

After a transition from German to Dutch:
![image](https://user-images.githubusercontent.com/14192265/196496400-a11c6e03-6d7a-4f25-ab4c-27b109bf74f2.png)

**Expected behavior**
As soon as a different language is selected, the keywords should also be updated to match the new language. Or, if the new language is English or otherwise doesn't have translated keywords, keyword translation should be turned off at that point.

**What machine and browser you were using (optional)**
If the issue concerns things in the website, let us know:
- What computer you are using (Windows, Mac, Linux?)
  - Windows
- What browser you were using (Chrome, Edge, Safari)
  - Brave

**Comment by babaMar** [comment]
I'm looking into this, how do I enable the "keyword translation" ? In top-right I do only see my username there, not the drop-down menu with the language

**Comment by jeremydavis519** [comment]
I haven't actually made an account, so I'm not entirely sure how the UI changes when you're logged in, but I think I heard that the teacher can set the language and prevent the students from changing it. Maybe that's why you don't see the menu?

In any case, you should be able to reproduce the bug if you log out, since anonymous users can change the language freely.

**Comment by Felienne** [comment]
> I'm looking into this, how do I enable the "keyword translation"? In top-right corner I do only see my username there, not the drop-down menu with the language

If you are logged in, you can change the language in your profile (which will then update the language everywhere) The switcher is only shown when you are not logged in.
