### ISSUE TITLE
[CONTENT] Typo in a list of suggestions

### ISSUE THREAD

**Issue by jeremydavis519** [hedyorg/hedy#3436]
**Describe the issue**
In Level 3, in English, the dropdown list of suggestions contains a typo.

**Add a screenshot (optional)**
![image](https://user-images.githubusercontent.com/14192265/196505884-b2ce45e5-355f-4634-80f5-f3cafa8fa3fb.png)

**Expected text**
The third option should look more like this:

> `remove` an `item` from a list.

**Comment by Felienne** [comment]
Could you check if this is still the case @MarleenGilsing?
