### ISSUE TITLE
📜  Division is used without being introduced

### ISSUE THREAD

**Issue by jeremydavis519** [hedyorg/hedy#3443]
**Describe the issue**
The English introduction to level 6 describes how to write addition, subtraction, and multiplication but doesn't mention division at all. I thought this was fine at first, since integer division is somewhat more complicated than the other operations and might be introduced later, along with the modulo operator. But the _Fortune teller_ adventure's first example on this level uses division:
```
kids = length / age
```

If the students are expected to use division at this level, the introduction should mention it, especially since it has the same issue as multiplication: students (or American students at least) often learn that `÷` means division and `/` means a fraction, without realizing that the two concepts are nearly identical. So they may need to be shown that we use `/` for division, just like we use `*` for multiplication.

**Expected text**
The introduction should have a short description of why we use `/`, just like why we use `*`. If it can be kept simple, this text should mention that Hedy ignores the remainder when dividing. Also, the example code on the right should be expanded to something like this:
```
print '5 plus 5 is ' 5 + 5
print '5 minus 5 is ' 5 - 5
print '5 times 5 is ' 5 * 5
print '5 divided by 5 is ' 5 / 5
```

**Comment by reiades** [comment]
hello I would like to work on this issue!

**Comment by Felienne** [comment]
Fantastic!
