### ISSUE TITLE
[BUG] Incorrect error message when an unquoted backslash is found in a print statement

### ISSUE THREAD

**Issue by jeremydavis519** [hedyorg/hedy#3444]
**Describe the bug**
Trying to use a backslash as an operator is, of course, a syntax error, but Hedy seems to get confused about where exactly the error is. This situation can arise if a student, having recently been given access to division, forgets which way the slash should be slanted.

In the example code below, Hedy gives an error starting like this:
```
Be careful. If you ask or print something, the text should start and finish with a quotation mark.
```

That's fine so far, but the error becomes confusing in the next sentence:
```
You forgot that for the text divided.
```

The problem is that `divided` _was_ part of the quoted text.

**Paste the Hedy code & level**
I tried this on level 6.
```
print '5 divided by 5 is ' 5 \ 5
```

**Add a screenshot (optional)**
![image](https://user-images.githubusercontent.com/14192265/196531145-cfb89a81-5360-4f59-8415-d66aafaa1361.png)

**Expected behavior**
I expected the error to say that the backslash needed to be quoted, or perhaps all of `5 \ 5`.

Ideally, though, Hedy would suggest using a forward slash instead, since that's probably what the student meant. I've seen some references to the Confusables package in other issues, and that might help in this case. Not sure, as I haven't looked into what that package does specifically.

**What machine and browser you were using (optional)**
If the issue concerns things in the website, let us know:
- What computer you are using (Windows, Mac, Linux?)
  - Windows 10
- What browser you were using (Chrome, Edge, Safari)
  - Brave

**Comment by Felienne** [comment]
Thanks for a good catch! There are a few approaches here, we could add `\` to the parser or maybe just output slightly different Python? I am not even sure myself why the error is as it is, because both quotes should still be around the text? Maybe @jpelay can dive in?

**Comment by jpelay** [comment]
> I am not even sure myself why the error is as it is, because both quotes should still be around the text?
The cause of this is that the error returns as unquoted text the first child of the `error_print_nq` node:

https://github.com/hedyorg/hedy/blob/211948b660d9cada93317bc0fe89f39e9639293d/hedy.py#L997-L999

In the  case of this code snippet it returns the second word of the first text 'divided', if we change that line, the error message changes accordingly. 



![Image](https://user-images.githubusercontent.com/45865185/199120113-c8f82de3-87c9-41a9-b2f0-373a2e842989.png)

**Comment by boryanagoncharenko** [comment]
Nowadays the error indicates that there are missing quotes:
<img width="508" alt="Screenshot 2024-08-06 at 14 43 00" src="https://github.com/user-attachments/assets/a6344eba-26b3-4f84-b8d0-b051d50bfcf1">

However, it seems a bit off that the error points the whole text including the already quoted parts. It would be nicer to only mention the unquoted parts, e.g. 5 \ 5. Also, the double backslash should be addressed.
