### ISSUE TITLE
📜 Level 11 only has complex adventures, add a few simpler ones

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#3455]
**Describe the issue**
While level 12 has a few different adventures to get started, level 11 lacks some simpler assignments to get started, the fish song already is quite complex. Maybe a simpler story, like a countdown to New Year to get started would be nice?

**Comment by GraceWei1314** [comment]
Hi, I was wondering if me and a friend could be assigned to this? It seems really interesting! 
Thanks!!

**Comment by Felienne** [comment]
Sure, I am curious to see what fun adventures you can come up with!

**Comment by Felienne** [comment]
Should you need help, let us know here or in Discord!

**Comment by GraceWei1314** [comment]
Hi Felienne! I was able to add a new year's story for the Level 11 Quiz; I was hoping to confirm that the way I implemented it is ok before adding some more?
