### ISSUE TITLE
[CONTENT] Cleaning up the quizzes in Hedy

### ISSUE THREAD

**Issue by sjensen19** [hedyorg/hedy#3458]
As mentioned before, a lot of questions contain minor mistakes. @Felienne suggested to go through all the questions and look for minor mistakes

**Comment by sjensen19** [comment]
@MarleenGilsing I haven't started yet, so I'll leave it to you if you are already working on it! Thanks alot!

**Comment by Felienne** [comment]
Some things I noticed (in general, specifically I think in levels 10 and 11) in addition to layout issues, is that the difficulty of the questions seems to be a bit all over the place, it would be nice if it would be easier questions first and then harder ones later on. In level 11 specifically, something you might not see right away is that in Q3 both answers 3 and 4 are correct:

<img width="1258" alt="image" src="https://user-images.githubusercontent.com/1003685/199505992-74e0b67c-ee35-417e-b119-c9a87310766c.png">

**Comment by MarleenGilsing** [comment]
All the English quizzes should be cleaned up by now.
