### ISSUE TITLE
[BUG] Unclear message "list index out of range"

### ISSUE THREAD

**Issue by qnojansen** [hedyorg/hedy#3463]
**Describe the bug**
When choosing an item from an empty list, you get the error message "list index out of range".

**Paste the Hedy code & level**
Level 16
fruit = []
f = fruit at random
print f

**Add a screenshot (optional)**
See attached file

**Expected behavior**
The message should be more descriptive (and in Dutch) so students will understand it.

![image](https://user-images.githubusercontent.com/116218471/196795059-22a57347-b353-421b-8eaa-780db089341a.png)

**Comment by LeslieMurphy** [comment]
Also a student can get error message **list index out of range** in level 3.  

I propose to enhance Hedy to generate error message something like this "List animals contains 3 entries. Index 4 is out of range".  What does everyone think?

Weirdly `print animals at 0` does the same thing as `print animals at 3`. Both print _kangaroo_.  Is that another bug?

```
animals is dog, cat, kangaroo
print animals at 4
# The above code generates error: list index out of range

```

**Comment by Felienne** [comment]
Ah great catch, thanks!! It is indeed a Python error message leaking out. We aim to not have that happen but it sometimes does. Here also it is quite hard to fix cause this happens at runtime. 

Best we can do I think is to generate a try-catch and have that output an error (we have done that in other places)

@jpelay do you think you can pick this one up? If not I will do it!

**Comment by LeslieMurphy** [comment]
I can try to look into this to see if I can figure it out. Is there a closed issue with similar python runtime message leak I might review?

**Comment by Felienne** [comment]
Great question! Not one that know of by heart (and I am traveling at the
moment so I can't easily check until Monday) but if you check the generated
Python code for higher levels, you can see that we generate a try catch,
you could take a similar approach here?

**Comment by LeslieMurphy** [comment]
While I delve into this, I pose another related question if you do not mind. 

Are lists in hedy supposed to be mutable by index? It does not seem to work (level 16 and above).  Was trying to simplify the tic tac toe example into using a single dimension list and could not accomplish it.  Current logic has 9 variables (spot_1, spot_2, spot_3 etc.). 

```
friends = ['Ahmed', 'Ben', 'Cayden']
print friends[1]  # this prints Ahmed
friends = ['Fred', 'George', 'Fritz'] #reassignment
print friends[1]  # this prints Fred
friends[1]='Les'  # not valid Hedy code. There is a mistake on line 5, at position 8. You typed [, but that is not allowed.
lucky_numbers = [15, 18, 6]
for i in range 1 to 3
    print 'the lucky number of ' friends[i]
    print 'is ' lucky_numbers[i]


```

**Comment by LeslieMurphy** [comment]
For the original level 16 bug - random selection from an empty list, this kludge in the code would work.  It is not very user friendly, but it is better than the default python message.  Ideally, the error would include the variable name of the list that is being accessed incorrectly.

in **hedy.py**

```
class ConvertToPython_5(ConvertToPython_4):
    def list_access_var(self, meta, args):
        var = escape_var(args[0])
        if isinstance(args[2], Tree):
            # protect in case of empty list
            return f"try:\n  {var} = random.choice({args[1]})\nexcept IndexError:\n  raise Exception('The list is empty, there is no random value!')"
            #return var + ' = random.choice(' + args[1] + ')'
        else:
            return var + ' = ' + args[1] + '[' + args[2] + '-1]'
```

<img width="363" alt="image" src="https://user-images.githubusercontent.com/4464416/198718169-113dfef9-c9e9-42fc-868e-9b47362165ce.png">

Also, in level 16 an error can occur on an out of bounds list access.  This is a fix for that:

```
def print(self, meta, args):
        argument_string = self.print_ask_args(meta, args)
        return f"try:\n  print(f'{argument_string}')\nexcept IndexError:\n  raise Exception('Sorry I cannot find that item in the list!')"

```

<img width="355" alt="image" src="https://user-images.githubusercontent.com/4464416/198718819-de58e8b1-396a-4609-9e8a-6d803516157b.png">


Finally for my level 3 bug, here is a fix for that.  I am sure there are other cases lurking around as well.  Probably need to review all unsafe access areas and wrap the code with try/catch more systematically.


```
def print(self, meta, args):
        args_new = []
        for a in args:
            # list access has been already rewritten since it occurs lower in the tree
            # so when we encounter it as a child of print it will not be a subtree, but
            # transpiled code (for example: random.choice(dieren))
            # therefore we should not process it anymore and thread it as a variable:
            # we set the line number to 100 so there is never an issue with variable access before
            # assignment (regular code will not work since random.choice(dieren) is never defined as var as such)
            if "random.choice" in a or "[" in a:
                args_new.append(self.process_variable_for_fstring(a, meta.line))
                argument_string = ' '.join(args_new)
                return f"try:\n  print(f'{argument_string}')\nexcept IndexError:\n  raise Exception('Sorry I cannot find that item in the list!')"
            else:
                ...
```
<img width="355" alt="image" src="https://user-images.githubusercontent.com/4464416/198719289-c4e7f7c6-bed0-44f5-a7ed-a96f81251a93.png">

**Comment by LeslieMurphy** [comment]
I found another Python message leak.  

**cannot concatenate 'str' and 'int' objects**

Shouldn't it be possible to concatenate a string and text in Hedy?  I was looking at simplifying my multiplication table formatting logic, and this approach currently won't work:

<img width="359" alt="image" src="https://user-images.githubusercontent.com/4464416/198753552-c561c991-a782-4904-af59-1cca084418ff.png">
