### ISSUE TITLE
[BUG] Unclear message "unsupported operand type(s) for //: 'int' and 'str'"

### ISSUE THREAD

**Issue by qnojansen** [hedyorg/hedy#3465]
**Describe the bug**
When you use ask to ask the user to type a number but the user enters a text, you get the error message "unsupported operand type(s) for //: 'int' and 'str'". This is not clear to the students.

**Paste the Hedy code & level**
Level 15
hoeken = ask 'Hoeveel hoeken krijgt dit figuur?'
hoek = 360 / hoeken
repeat hoeken times
  repeat hoeken times
    forward hoek
    turn hoek
  turn hoek
  forward hoek

**Expected behavior**
The error message should be more clear (and in Dutch) so students know what went wrong here.

**Comment by jpelay** [comment]
> Thanks for noticing @qnojansen!!
> 
> This one is quite similar to #3463 in the sense that it is also a Python message leaking out. @jpelay maybe this one could also be for you?

Yes of course! When I create the error message I'll send it to you so you can provide me with the correct Dutch translation!

**Comment by Felienne** [comment]
> When I create the error message I'll send it to you so you can provide me with the correct Dutch translation!

For sure! I can just push them on the PR whenever you are ready!

**Comment by Felienne** [comment]
One more for @boryanagoncharenko?
