### ISSUE TITLE
[BUG] Parsons are given in right order

### ISSUE THREAD

**Issue by Mark-Giesen** [hedyorg/hedy#3475]
**Describe the bug**
Parsons codelines are in correct order. The lines of code given to drag/drop in the right order, are given in the right order. Not every now and then, but allways. Restarting in new browser results in the same order. I seems the fisherYatesShuffle in Parsons.ts doesn't shuffle very well.

**Expected behavior**
I expect the lines to be presented at random order, this is to easy.

**Comment by TiBiBa** [comment]
Did anything change in our front-end code? It did seem to work before.

**Comment by TiBiBa** [comment]
The last changes seem to be made in #3317, but this is already 27 days ago. So either no one noticed that the order is always correct or something else isn't working as expected. I didn't (re-)write this part, so I think it would be best if @rix0rrr took a quick peak at the code.
