### ISSUE TITLE
[BUG] Erroneous syntax highlighting in Hebrew. CHARACTER regex without Hebrew characters

### ISSUE THREAD

**Issue by o11k** [hedyorg/hedy#3476]
**Describe the bug**
In Hebrew, there are two separate keywords: "ב" (at) and "בתוך" (in). When typing the keyword "בתוך", the editor recognizes "ב" as a complete word, and doesn't highlight the rest of the word.
I believe this is down to the fact that the constant `CHARACTER` in the file [highlighting/definition.py](https://github.com/Felienne/hedy/blob/main/highlighting/definition.py), doesn't include Hebrew characters. It should include the range א-ת (Aleph א through Tav ת).

**Add a screenshot (optional)**
Observed in level 10
![image](https://user-images.githubusercontent.com/61731312/197292752-5f77df9b-81a4-4f8c-8444-7f79ea3867b0.png)

**Expected behavior**
The entire word "בתוך" should be highlighted as a keyword, not just the first letter "ב".

**Comment by Felienne** [comment]
And thanks for letting us know @orilevenglick! Hebrew is not as developed as other languages, sorry!
