### ISSUE TITLE
[idea] Make usernames unique in class, instead of in the whole db?

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#3480]
Follow up of https://github.com/Felienne/hedy/issues/3473

I think for the longer run it would be great if we could make usernames in the database with the class: student1-class5 or student1@class5 or the like, and then only show the first part in the UI, so we do not have too many clashes. As we are growing it might not be reasonable to expect all usernames in classes to also be unique?

However, @TiBiBa has some valid questions regarding of this idea:

_The longer run solution would be very hard to implement. What if the class is deleted? The name of the class is changed? Or what if we have two identical class names with the same user? Because in our whole project we dependent on unique username for specific actions and verifications._

_I agree that the current implementation has some limitations as multiple teachers simply want their students to have their surname as login. And I also don't have a clear idea on how we would best be able to tackle this issue._

**Comment by huangjac1** [comment]
Hi, new to open source and looking to contribute! I've been able to build and run Hedy. I'm working with a partner from my class to do an assignment that pertains to contributing to open-source. Any chance this issue is still unassigned and we can work on it?

**Comment by Felienne** [comment]
Hi @huangjac1!

This issue is unassigned but we are not all in agreement what is the best path forward here so I would not propose to pick this up now, it is very involved.
