### ISSUE TITLE
[BUG] Language switcher does not work in single adventure

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#3485]
If we use a single adventure (f.e. https://hedy.org/adventure/parrot/1) the language switcher does not seem to show well:

![image](https://user-images.githubusercontent.com/1003685/197784335-a9b8bcb5-e958-4946-b336-ef4aa9de3d2a.png)

Also, using the link directly does not seem to work to start with the language in the link:

https://hedy.org/adventure/parrot/1?keyword_language=nl

(Maybe these are two separate issues, feel free to split out)

**Comment by TiBiBa** [comment]
To explain a bit on this issue: we use separate routing for the "normal" rendering and the specific adventure rendering. Both routes have a dedicated function in `hedyweb.py` to handle the rendering and parse the correct values to the (same) front-end template.

**Comment by Felienne** [comment]
Reopening so we don't forget!

**Comment by TiBiBa** [comment]
Whoops, I was supposed to pick this up! Will take a look today (and now for real)!

**Comment by TiBiBa** [comment]
Just created a fix!
