### ISSUE TITLE
📜 Improve Level 9 calculator

### ISSUE THREAD

**Issue by LeslieMurphy** [hedyorg/hedy#3489]
In Level 9 the calculator sample can be improved

**Add a screenshot (optional)**

CURRENT

![image](https://user-images.githubusercontent.com/4464416/197894155-3da52441-337c-4754-a1e5-bf6e1965537a.png)

PROPOSED

![image](https://user-images.githubusercontent.com/4464416/197895058-2433bc76-e295-4e41-8094-3b18701a2856.png)

**Expected text**

I propose this for content/adventures/en.yaml  (and similar for other languages) example_code_2:

```
score = 0
question_count = 10
repeat question_count times
    numbers = 1, 2, 3, 4, 5, 6, 7, 8, 9, 10
    number1 = numbers at random
    number2 = numbers at random
    correct_answer = number1 * number2
    print 'What is ' number1 ' times ' number2 '?'
    answer = ask 'Type your answer here...'
    if answer is correct_answer
        score = score + 1
        print 'Your answer ' answer ' is correct!'
    else
        print 'Your answer ' answer ' is wrong, sorry!'
print 'Great job! Your score is... ' score ' out of ' question_count '!'
```

**Comment by jakeklaris** [comment]
If this is still available and in need of updating, I'd be happy to take it on!

**Comment by Felienne** [comment]
Hi @MarleenGilsing! I actually like the code as it is now, because it is a bit messy (not sure that was intentional haha) My preferred solution would be to add a sentence in the exercise to clean it up and make it look nicer, to encourage engagement with the code.
