### ISSUE TITLE
[BUG] Empty modal on sharing

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#3493]
**Describe the bug**
Sometimes, but I am not sure exactly when, an empty modal is shown when a program si shared:

![image](https://user-images.githubusercontent.com/1003685/197950089-dd9a7675-d43d-427d-a27d-a78ee798cbf0.png)

I have not been able to reliably reproduce it, but I have seen it many times with kids in class.

**Comment by TiBiBa** [comment]
I'm unable to re-produce this error by saving and sharing a program:
![Schermafbeelding 2022-10-26 om 09 03 21](https://user-images.githubusercontent.com/38155424/197957341-926d8efd-263c-40b9-a8a5-f6cfd92c33c3.png)

**Comment by Felienne** [comment]
> I'm unable to re-produce this error by saving and sharing a program: ![Schermafbeelding 2022-10-26 om 09 03 21](https://user-images.githubusercontent.com/38155424/197957341-926d8efd-263c-40b9-a8a5-f6cfd92c33c3.png)

Yeah same for me, it only occasionally happens and I do not know when exactly. Maybe @jpelay remembers how he saw it?

**Comment by TiBiBa** [comment]
Weird! I just looked into the code and this snippet should be responsible:
```
if (shared) {
      $('#modal-copy-button').attr('onclick', "hedyApp.copy_to_clipboard('" + viewProgramLink(response.id) + "')");
      modal.copy_alert (response.message, 5000);
    } else {
      modal.alert(response.message, 3000, false);
    }
```

Can't find any reason why it wouldn't work as expected...

**Comment by Felienne** [comment]
To reproduce, click Save and Share and then click the link button:

http://localhost:8080/hedy/fb43dfa3aaf240439193dd650ca6bc5c/view

**Comment by TiBiBa** [comment]
Whoops never picked this up, will look at this today!
