### ISSUE TITLE
[CONTENT] Level 8, English, Quiz

### ISSUE THREAD

**Issue by LeslieMurphy** [hedyorg/hedy#3506]
**Describe the issue**
Level 8, English, Quiz

question 4 says Were going on holiday.
question 5 says the last two lines should start on new lines en start with 4 spaces
question 7 - the correct answer is 4 - wrong indentation, but the code is still wrong (variable name issue)

**Add a screenshot (optional)**
Make a picture or screenshot to show the issue. Tip! You can make a screenshot and simply paste the image into GitHub with ctrl-v.

**Expected text**
What should we write instead?  

Q4
We are going on holiday.  Or you could also change the code to say `print "We're going on holiday!" `
NOTE in the United States we say: We are going on vacation instead of holiday.  

Q5
the last two lines should start on new lines **and** start with 4 spaces (I learned just now en is dutch for and!)

Q7
the first line of sample code needs to be 
`food = ask 'What would you like to eat?' ` (instead of setting variable `eten`)

**Comment by reiades** [comment]
hello! I am new to Hedy and would love to tackle this issue if no one has been assigned yet!

**Comment by sjensen19** [comment]
Hi @reiades! First of all, welcome to Hedy! I don't think the issue has been assigned yet, so if you want to work on this issue, feel free to do so!

If you have any questions regarding where to start, feel free to ask!

**Comment by reiades** [comment]
here is my PR for this issue! https://github.com/hedyorg/hedy/pull/3631
