### ISSUE TITLE
📜  level 17 blackjack code bug

### ISSUE THREAD

**Issue by LeslieMurphy** [hedyorg/hedy#3507]
**Describe the issue**
Level 17 English Blackjack

**Add a screenshot (optional)**

<img width="327" alt="image" src="https://user-images.githubusercontent.com/4464416/198408183-b7b36511-086c-4f4f-8c1c-67f05998011f.png">

**Expected text**
The code for blackjack is wrong for the hit logic:

This:

```
if hit == 'yes':
    if card_3 == 'Jack' or card_3 == 'Queen' or card_3 == 'King':
        points = points + 10
    elif card_3 == 'Ace':
        if points > 11:
            points = points + 11
        else:
            points = points + 1
```

Should be this:

```
if hit == 'yes':
    if card_3 == 'Jack' or card_3 == 'Queen' or card_3 == 'King':
        points = points + 10
    elif card_3 == 'Ace':
        if points > 11:
            points = points + 1
        else:
            points = points + 11

```

**Comment by reiades** [comment]
hello I am interested in working on this issue!

**Comment by Felienne** [comment]
Great! Feel free to pick this up and let us know if you need any help.

**Comment by Felienne** [comment]
I think this issue is still a good one, but the real issue is that the example is waaaaay too long!

Can we shorten it with functions?
