### ISSUE TITLE
[BUG] Explore program box it out-of-bound due to number of lines

### ISSUE THREAD

**Issue by TiBiBa** [hedyorg/hedy#3512]
**Describe the bug**
We should give the explore program box a little bit of love to avoid the out-of-bound design.

**Add a screenshot (optional)**
![Schermafbeelding 2022-10-28 om 13 05 18](https://user-images.githubusercontent.com/38155424/198572951-a2007c72-5ba7-489b-b742-76f2ab390f06.png)

**Comment by jpelay** [comment]
Hi, Timon! I was testing this bug on my end and it seems to be working correctly, tested both in Firefox and Brave. How can I reproduce it?

![image](https://user-images.githubusercontent.com/45865185/199744412-efce2e59-93d1-4597-a6cc-ab1547e7df95.png)

**Comment by TiBiBa** [comment]
> Hi, Timon! I was testing this bug on my end and it seems to be working correctly, tested both in Firefox and Brave. How can I reproduce it?
> 
> ![image](https://user-images.githubusercontent.com/45865185/199744412-efce2e59-93d1-4597-a6cc-ab1547e7df95.png)

I get this bug on Safari. Alternatively (and maybe a better solution than the one I implemented) we can simply hide the overflow on the box and remove the scrollbar completely.

**Comment by jpelay** [comment]
> > Hi, Timon! I was testing this bug on my end and it seems to be working correctly, tested both in Firefox and Brave. How can I reproduce it?
> > ![image](https://user-images.githubusercontent.com/45865185/199744412-efce2e59-93d1-4597-a6cc-ab1547e7df95.png)
> 
> I get this bug on Safari. Alternatively (and maybe a better solution than the one I implemented) we can simply hide the overflow on the box and remove the scrollbar completely.

I think that the scrollbar it's useful, although it works differently in every browser it seems! Sadly, I can't test it on Safari because I don't own a Mac, maybe someone who has one can review your PR, sorry!
