### ISSUE TITLE
[CONTENT] Level 8 turtle code is wrong

### ISSUE THREAD

**Issue by LeslieMurphy** [hedyorg/hedy#3520]
**Describe the issue**
Level 8 turtle code is wrong - English.  It loops way too many times!

Current code

```
angles = ask 'How many angles should I draw?'
angle = 360 / angles
repeat angle times
    turn _
    forward _

```
Correct code

```
angles = ask 'How many angles should I draw?'
angle = 360 / angles
repeat angles times
    turn angle
    forward 40
```

Suggested enhancement to make the turtle colorful

```
angles = ask 'How many angles should I draw?'
colors =  black, blue, brown, gray, green, orange, pink, purple, red, yellow
angle = 360 / angles
repeat angles times
    turn angle
    color colors at random
    forward 40
```

**Comment by Felienne** [comment]
Ah great catch! The angle to angles change should indeed happen, do you know how to do that in Weblate? That is the easiest way to prevent conflicts. If not you can do it in a PR here too.

The second suggestion could be added as a third code example but there already are some color examples before and I worry it would become a bit long. Of course you could add it as your own adventure in your class!

**Comment by LeslieMurphy** [comment]
I will try to figure out the weblate platform, when I get a chance.  Thanks!

**Comment by Felienne** [comment]
I am not sure this has been with through Weblate in the meantime. Could you check @MarleenGilsing?

**Comment by MarleenGilsing** [comment]
Changed all the old English to the new (correct) content in #4622

**Comment by Felienne** [comment]
A fix is still needed for a few other languages, see https://github.com/hedyorg/hedy/pull/4622#issuecomment-1759680183 @yilmazdurmaz has kindly volunteered to pick this up

**Comment by yilmazdurmaz** [comment]
Weblate commits in PR #4625 now has the all-language correction. So, I am closing the issue. feel free to reopen, or add comments, if something is not right.
