### ISSUE TITLE
[BUG] Highlighting in Chinese is incorrect

### ISSUE THREAD

**Issue by Mark-Giesen** [hedyorg/hedy#3521]
**Describe the bug**
Highlighting of commands is incorrect in Chinese.

**Add a screenshot (optional)**
![image](https://user-images.githubusercontent.com/28646458/198734488-62dd5c76-ddb3-48c1-81c0-8e24e7a76ad2.png)

**Expected behavior**
The keyword {in} is translated into 在里面, but only the first character of this translated keyword is highligted!

**Comment by Felienne** [comment]
Yes, this is a known issue that was discussed in the (still open) #3500

**Comment by Mark-Giesen** [comment]
Ah, OK. If that is the same issue, this can be closed.

**Comment by Felienne** [comment]
Well not 100% since I asked for the change to be also made for Chinese. We can leave this open until #3500 is indeed improved, just to be sure, bur at least you now know a fix is being discussed!

**Comment by Felienne** [comment]
Can confirm this is fixed by #3700 

<img width="1332" alt="image" src="https://user-images.githubusercontent.com/1003685/206750061-00fa29e1-d9af-4b90-b5c4-4d80ff4994f0.png">
