### ISSUE TITLE
[BUG] Language selecter doesn't work when pasting code

### ISSUE THREAD

**Issue by Mark-Giesen** [hedyorg/hedy#3523]
**Describe the bug**
Change the site from (i.e.) English to Chinese, then paste some Chinese code in the editor. Now try to change the command language from Chinese to English. This will result in a complete refresh of the page, included the "site leaving" message.

**Paste the Hedy code & level**
Tried this with this code from Level 12:
一组动作 = '拍拍手', '跺跺脚', '喊万岁!'
取 动作 在里面 一组动作
    取 i 在里面 范围 1 到 2
        打印 '如果你很高兴，你意识到它。'
        打印 动作
    打印 '如果你很高兴，你意识到它，你真的想表现出来'
    打印 '如果你快乐并意识到它'
    打印 动作
    

**Add a screenshot (optional)**
![image](https://user-images.githubusercontent.com/28646458/198818646-74c63a49-4097-4675-afcc-1993a99a9f46.png)

**Expected behavior**
I expect the pasted code to remain in the editor and have English commands.

**What machine and browser you were using (optional)**
This is on a windows machine with the Brave browser.

**Comment by Mark-Giesen** [comment]
tested it on Chrome, same behaviour.

**Comment by Felienne** [comment]
Yes that is the way the switcher is implemented. Could you just first switch (thus refresh the page) and then paste?

**Comment by Mark-Giesen** [comment]
I can, but after pasting I can no longer swap command language, that is not what I expect.

**Comment by Mark-Giesen** [comment]
If impossible or by choice, I'm fine with it and this can be closed. Remains as a "would have" for me ;-)

**Comment by Felienne** [comment]
> I can, but after pasting I can no longer swap command language, that is not what I expect.

Note that switching keywords in a code snippet is no longer shown in the interface *unless* you are admin, so you can only do that locally (I assume you were using it do test snippets?) This is to keep the UI simple enough for kids.
