### ISSUE TITLE
[TESTING] Create front-end tests for log-in features

### ISSUE THREAD

**Issue by JimmyOei** [hedyorg/hedy#3531]
**Description**
Create front-end tests in Cypress for all the features in the `login` page.
- ‘Log in’ button
- ‘Create account’ button
- ‘Forgot your password?’ button

**Comment by Felienne** [comment]
Thanks for the issue but maybe we can split it up into a few more issues (Testing all teacher features, all logging features etc.) That will be useful to track progress and to see what we still have to do when you all leave.
