### ISSUE TITLE
[UI idea] Additional ideas for creating your own adventure

### ISSUE THREAD

**Issue by OnnoEbbens** [hedyorg/hedy#3533]
At first I did not use it much but now I love the feature to make your own adventures as a teacher. It makes it a lot easier to have students work at their own pace.

While creating the adventures I came up with some suggestions to further improve this feature:
1. It is already possible to show code blocks using the `<pre></pre>` tags. I would like to show desired output of a program as well. This will be similar to a code block but without the syntax highlighting and the possibility to copy into the editor. This way I can make an adventure in which I tell students to write the code for a certain output.
2. When I create multiple adventures in a Hedy level the order in which they appear seems a bit random. Probably the last saved adventure appears last. I would like to be able to set the order without having to save all the adventures in a certain order each time I change an adventure.
3. This one is probably at bit more far fetched but it would be great for teachers to see and use adventures that others have created per level (and probably per language). Maybe even with some like button if there are a lot of them.

I am curious what you think of these ideas. Also feel free to move this to the discussion section if it belongs there.

**Comment by NOTE-HBL** [comment]
I agree with list-item number 2 on the random order. It doesn't seem to be the last saved adventure that determines the order. It would be nice to make the order predictable with dates or alphabetical ordering.

**Comment by Felienne** [comment]
all of this has been fixed in the meantime!
