### ISSUE TITLE
[LOCALIZATION] Localize Ace search box 

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#3536]
The way we place "search..." in the Ace search editor now means that it cannot be localized. Would be nice if that is also possible.

_Originally posted by @Felienne in https://github.com/hedyorg/hedy/pull/3504#discussion_r1010375528_

**Comment by TiBiBa** [comment]
This is a bit complex as the "search..." value is set within the ace extension .js file. But with some creative knutselen it should be possible to get this from a template variable. Will take a look!

**Comment by Felienne** [comment]
Yeah if it was easy I would have done it myself 😅 thanks for looking into it!

**Comment by TiBiBa** [comment]
Found a way!
![Schermafbeelding 2022-11-04 om 13 28 20](https://user-images.githubusercontent.com/38155424/199972737-2e9ebc6a-b5a2-4ccd-81b5-85e006f6216b.png)
