### ISSUE TITLE
[CONTENT] Add 🤫 to tutorial text for cheatsheets

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#3538]
This is a good point, shall we change the text to add "You can find the cheatsheet at the 🤫 in the top left/right corner "?

> Hi. I'm new to Hedy.  In the teacher tutorial it mentions cheatsheets, but it is not clear (to me at least!) where to locate / view them in the user interface.  I looked into both "Learn more" and "Explore" and could not find the cheatsheets.

<img width="1155" alt="image" src="https://user-images.githubusercontent.com/4464416/198386257-44b15292-94df-45eb-80b3-495652b58cee.png">

_Originally posted by @LeslieMurphy in https://github.com/hedyorg/hedy/issues/2245#issuecomment-1294003910_

**Comment by LeslieMurphy** [comment]
YES PLEASE!  

 

From: Felienne Hermans ***@***.***> 
Sent: Tuesday, November 1, 2022 6:48 AM
To: hedyorg/hedy ***@***.***>
Cc: LeslieMurphy ***@***.***>; Mention ***@***.***>
Subject: [hedyorg/hedy] [CONTENT] Add 🤫 to tutorial text for cheatsheets (Issue #3538)

 

This is a good point, shall we change the text to add "You can find the cheatsheet at the 🤫 in the top left/right corner "?

Hi. I'm new to Hedy. In the teacher tutorial it mentions cheatsheets, but it is not clear (to me at least!) where to locate / view them in the user interface. I looked into both "Learn more" and "Explore" and could not find the cheatsheets.

 <https://user-images.githubusercontent.com/4464416/198386257-44b15292-94df-45eb-80b3-495652b58cee.png> 

Originally posted by @LeslieMurphy <https://github.com/LeslieMurphy>  in #2245 (comment) <https://github.com/hedyorg/hedy/issues/2245#issuecomment-1294003910>

**Comment by MarleenGilsing** [comment]
Fixed with #4374
