### ISSUE TITLE
[UI idea] Allow teachers to customize adventures ordering

### ISSUE THREAD

**Issue by jpelay** [hedyorg/hedy#3541]
**Idea incl level**
In #3540 we start allowing to customize the ordering of adventures in each on the levels, but this is hard coded and we should allow teachers to reorder this, and also reorder their own adventures, and choose which one appears in which level.

I was thinking about something like this (in the customize class menu):
![adventures](https://user-images.githubusercontent.com/45865185/199351726-c368765b-ad80-4e62-a82f-68c5e2f511d6.png)

You could drag and drop the adventure around and that would reorder it, a button to delete it, a menu to add new adventures, etc.

**Comment by Felienne** [comment]
Wow this looks AMAZING!! It is more or less point 2 of #3533, but even better!

What do you envision when a user clicks "add adventure" will we show them the adventure editor also in this view? Maybe we can even allow them editing in a view that looks like Hedy (with the code editor shown also so snippets can be tested?) But we can do this in a separate PR too of course!

**Comment by jpelay** [comment]
> Wow this looks AMAZING!! It is more or less point 2 of #3533, but even better!
> 
> What do you envision when a user clicks "add adventure" will we show them the adventure editor also in this view? Maybe we can even allow them editing in a view that looks like Hedy (with the code editor shown also so snippets can be tested?) But we can do this in a separate PR too of course!

Thank you! I envision a drop down list with the adventures available for a certain level! I didn't think this screen to be an editor, just like a way to pick and order the adventures for each level. I think that can be a separate PR, but I like the idea!
