### ISSUE TITLE
[LANGUAGE idea] New command for 'not in list'

### ISSUE THREAD

**Issue by MarleenGilsing** [hedyorg/hedy#3550]
**Language idea incl level**
We have the command 'in' to check if an item is in a list, but we do not have the possibility to check the opposite. For example:

item = ask 'What would you like to buy?'
stock = 'bread', 'milk', 'eggs'
if item **not in** stock
    print 'Sorry, we do not sell that'

In level 14 we add != but that doesn't seem to work with lists. We introduce the in command in level 5.

I thought we also used to have a True/False level, but I can't seem to find it @Felienne. 
Because then you could do something like: 

if item in stock = False
    print 'Sorry'

**Comment by maryannho123** [comment]
Hi! I'm a new contributor and would like to solve this. Can you assign me to this?

**Comment by maryannho123** [comment]
Hi @arjank! I am working on the bug with my partner and we have a couple of clarifying questions. 

1) For Hedy's purpose should we implement a 'not in' command or a 'not' command 

2) I have chosen the 'not in' command for now and edited several files (hedy.py, level5-Additions.lark, definition.py, highlighting.json, list_keywords.py) to include the new functionality. However, the parser does not recognize the command. Are there any suggestions on what other files to edit?  

3) Is there any specific documentation for us to read to understand more on how to add the 'not in' functionality?

**Comment by maryannho123** [comment]
Hi @arjank ! We are close to finishing the 'not in' command. How do we change the color of 'not' to be the same color as the other commands? Do we only need to change the files in the highlighting folder?

**Comment by Felienne** [comment]
> Hi @arjank ! We are close to finishing the 'not in' command. How do we change the color of 'not' to be the same color as the other commands? Do we only need to change the files in the highlighting folder?

Yes, the files in the highlighting folder control the highlighter. Is there a PR for us to look at, that is aways helpful i communicating.

And are all your other issues solved, I saw a message with some other questions?

**Comment by agusikhin** [comment]
> Yes, the files in the highlighting folder control the highlighter. Is there a PR for us to look at, that is aways helpful i communicating.
> 
> And are all your other issues solved, I saw a message with some other questions?

Hi @Felienne ! We will make sure to submit a PR within a few hours! Thanks for your response. The other issues have been solved, thank you!

**Comment by agusikhin** [comment]
I'm unable to create a new branch since I am not a collaborator and it does not seem that there is a branch for this issue. What should I compare to? Thanks!

**Comment by Felienne** [comment]
See: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork

**Comment by agusikhin** [comment]
Thanks so much for your help! Just submitted the PR with the command working, but the highlighting part is still in progress.
