### ISSUE TITLE
[UI idea] Tiny UI change in placement of button in quiz

### ISSUE THREAD

**Issue by MarleenGilsing** [hedyorg/hedy#3553]
**Idea incl level**
Right now in the quizzes the button to go to the first question and to go to the next level is on the left side, while usually buttons like this are on the right side of the screen. If it's not too much trouble, maybe someone can move it?

![image](https://user-images.githubusercontent.com/80678586/199713542-8888ca0b-f066-4012-8607-0cae50d51780.png)

**Comment by TiBiBa** [comment]
Will do!
