### ISSUE TITLE
[BUG] No points are deducted after mistakes in the quiz

### ISSUE THREAD

**Issue by MarleenGilsing** [hedyorg/hedy#3556]
**Describe the bug**
if you make a mistake in the quiz, points should be deducted, but they aren't. I keep scoring 100, because i corrected the mistakes. 
Edit: If you don;t correct the mistakes, some points are deducted, but I think we should deduct points if you don;t get it right the first time. And we should also deduct points if you're using a hint.

**Comment by ana3999** [comment]
Hello!
I was wondering whether it was possible to claim this issue? 
Thank you!
