### ISSUE TITLE
[TESTING] Create front-end tests for the home page

### ISSUE THREAD

**Issue by JimmyOei** [hedyorg/hedy#3557]
**Description**
Create front-end tests in Cypress for all the features in the hedy `home` page.
- Selecting languages
- Clicking headers
- `Try it' button
- Youtube video

**Comment by KavyaManocha** [comment]
Hi, I would love to help work on this feature!

**Comment by JimmyOei** [comment]
Hey! This issue is unfortunately not meant to be done by other developers. The issue belongs to a project I and other Leiden University students are doing for the course Software Engineering, where we develop front-end tests for Hedy. I'm sorry for the inconvenience and will assign all the issues of the project, such that there is no confusion. But I'm sure there are lots of other issues you can help with.
