### ISSUE TITLE
[TESTING] Create front-end tests for the hedy page

### ISSUE THREAD

**Issue by JimmyOei** [hedyorg/hedy#3558]
**Description**
Create front-end tests in Cypress for all the features in the `hedy` page.
- Switching Programmer’s mode on/off
- Read aloud: selecting a language
- Typing in code box
- ‘Run code’ button
- ‘Go to level x’, ‘go back to level x’
- Clicking headers within a level to redirect to different parts of that level
- ‘Save code’ button
- ‘Save & share code’ button
- Button that shows a list of things to try out and the try buttons within that list

**Comment by hanna1231** [comment]
I will split this issue in smaller issues
