### ISSUE TITLE
[BUG] Hedy's choice programs always have 101 lines

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#3572]
**Describe the bug**
This is tiny but weird! If I make a program Hedy'd choice, it shows 101 lines:
<img width="1261" alt="image" src="https://user-images.githubusercontent.com/1003685/199941755-b9353f3e-2649-42a9-8d88-4dfdc91d2801.png">

Before I make it Hedy's Choice, it shows correctly:

<img width="273" alt="image" src="https://user-images.githubusercontent.com/1003685/199942074-9efca27c-ec03-4d6e-bae2-e4d0110582f9.png">

After:

<img width="277" alt="image" src="https://user-images.githubusercontent.com/1003685/199942141-f77f9aaa-bd9d-47b0-8c60-5829570d8f30.png">

**Comment by sarangia-dev** [comment]
hi! I was wondering if I could claim this issue?

**Comment by kadeng14** [comment]
Hi! I am a new comer here and I am wondering whether I could claim this issue. Also, I am wondering which portion of the code is related to this bug. Thank you!

**Comment by Felienne** [comment]
> Hi! I am a new comer here and I am wondering whether I could claim this issue. Also, I am wondering which portion of the code is related to this bug. Thank you!

I also don't know where the error is exactly, but start looking in app.py. There is a line there:

`    number_of_lines = code.count('\n')`

Maybe that is the cause? You will have to run the code, and explore a but to see why it is always showing 101. If the process of debugging is unclear (rather than our codebase) I think you should maybe ask your professor or a TA?

**Comment by Felienne** [comment]
Somehow the issue seem to have changed! Now they all show 2 lines?!

<img width="1260" alt="image" src="https://user-images.githubusercontent.com/1003685/205847745-5f1d050d-7fed-404a-853e-d9b11820b6d3.png">

**Comment by sarangia-dev** [comment]
so does it only show 2 lines after you make it hedy's choice? before, is the number of lines correct?

**Comment by sarangia-dev** [comment]
also, how do I recreate this error when I run the code and am on the website?

**Comment by jpelay** [comment]
Already fixed
