### ISSUE TITLE
[UI idea] Adding an adventure to more levels at once

### ISSUE THREAD

**Issue by NOTE-HBL** [hedyorg/hedy#3573]
Hi,

I used the Discord to ask this but also promised to make an issue in github, so here it is: 

I want my students to make a project in class that I am going to grade. I would like to make this adventure available across all levels so that students can make the project on their own level. Could you make another option that an adventure could be added to every level? Otherwise I have to copy it 18 times, once for every level. Or is there something that prohibits this? Would be a small but nice addition for me! Turning the adventure off and on again in the class personalisation is a great feature, so I would leave that intact. Just when creating the adventure it would be nice to not have to copy it 18 times. 

For the code snippets problem: No code snippets when making a multi-level adventure could be an option. Another (more complicated) option might be to show the students the code that they created for this adventure in the last level (if they did so) in order to build upon that.

Thanks in advance for looking into this!
Kind regards, 
Tamara

Extra info in Dutch: 

Leerlingen werken bij mij op hun eigen tempo. Sommigen zijn dus (veel) verder dan anderen. Ik wil ze graag hun eigen project laten inleveren in Hedy, waarbij ze hun eigen programma bedenken. De opdracht is heel open, en leerlingen werken dus op het level wat ze bereikt hebben. Ik wil ze dus ook in dat level waar ze gebleven zijn het PO laten maken, maar wel allemaal dezelfde opdracht geven.
In principe is dat vergelijkbaar met de avonturen die in de levels steeds terugkomen, alleen geven jullie in de omschrijving een hint die terugslaat op het leerdoel in dat level, maar het thema is hetzelfde. In principe zou je dus ook steeds met dezelfde context uit de voeten moeten kunnen. Bij het PO is het idee dat alle leerlingen dus dezelfde context krijgen, maar op hun eigen niveau laten zien wat ze kunnen.

Buiten het idee van het PO zou ik dat in de lessen ook mooi vinden, om een context aan meerdere levels toe te voegen waar leerlingen kunnen oefenen zonder die level-specifiek te maken, zodat ik die in klassikale besprekingen ook kan gebruiken en we kunnen zien hoe de code evolueert waar we iets nieuws erbij leren.

**Comment by TiBiBa** [comment]
> Another (more complicated) option might be to show the students the code that they created for this adventure in the last level (if they did so) in order to build upon that.

I really like this idea! It's a bit complex but with our current custom adventure structure I think we can add this. Can will dive into this issue at the beginning of next week. Will keep you up-to-date!
