### ISSUE TITLE
[UI idea] Adding a date and timestamp when handing in adventures

### ISSUE THREAD

**Issue by NOTE-HBL** [hedyorg/hedy#3574]
Hi, 

I am using the hand-in feature so that I can grade students on their work. It is great that they can't edit their work after handing it in, that's a really nice feature. I just find myself wondering when exactly they handed in the code, because there are deadlines. It would be nice if a date and timestamp could be added to handed in code at the moment of submission. 

Kind regards, 
Tamara

**Comment by Felienne** [comment]
Hi Tamara!

Thanks for this suggestion! If you go to the link of a submitted program, it shows the last edited timestamp. While in theory of course they can submit a lot after the last change, in practice this will often be the same time. Will this help enough?

<img width="1353" alt="image" src="https://user-images.githubusercontent.com/1003685/200146625-9e59c508-4d63-4c17-b378-d0154fe8090a.png">

If not, we can also change the last edited time into the submitted time, that will be an easy change!
