### ISSUE TITLE
[BUG] If fix needs to be applied in Dutch

### ISSUE THREAD

**Issue by Mark-Giesen** [hedyorg/hedy#3575]
**Describe the bug**
The Sleep command disturbs a program.

**Paste the Hedy code & level**
The code is in the screenshot, running this result in the warning that nothing is printed. It results in a badge, but is not what we expected. If you remove the sleep command, the program acts like I expect.

**Add a screenshot (optional)**
![image](https://user-images.githubusercontent.com/28646458/199962343-3efe0d4c-1ce8-436b-a973-efa7f2993487.png)

**What machine and browser you were using (optional)**
On chromebooks and on my machine (windows with brave browser)

**Comment by Felienne** [comment]
It is not the sleep, but I know what the cause it, wil work on a fix!

**Comment by Felienne** [comment]
(note that this issue does not exist in English at the moment, so that is a work around)

**Comment by Mark-Giesen** [comment]
If I comment out the sleep line, it works! That's why I thought it must be sleep. Maybe this helps, but then again, you allready know the fix :-). My student wrote this in Level 6.
