### ISSUE TITLE
[CONTENT] Replace (very old!) video with more recent one

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#3577]
I just realised the video we have on the site is from March 2020! Also @ifsheldon pointed out that the subtitles are weird because they insist the video is Dutch (must be my accent haha) 

Let's replace it with the new Strangeloop talk:
https://www.youtube.com/watch?v=fmF7HpU_-9k

Ideally, but this will be harder/more work, we also extract the subtitles file and add it to Weblate so people can translate the subtitles.

**Comment by raintarango** [comment]
Hi! I'm a new contributor and would like to solve this. Can you assign me to this?

**Comment by raintarango** [comment]
Do you mean to replace the video on the homepage? The why is Hedy gradual video? Or were you referencing somewhere else?

**Comment by Felienne** [comment]
Do we have two videos? I meant the one on the home page, that indeed comes below: 

"In this video Felienne, the creator of Hedy, explains why Hedy is gradual."

I think we can also update the text because the new video explains a lot more!

**Comment by Felienne** [comment]
And if we are updating things, it would be great to add this (Dutch) podcast somewhere!

https://pom.show/2022/08/12/een-oplossing-voor-het-it-tekort/

**Comment by raintarango** [comment]
Of course! Do you have any text you would like to introduce the video with? I tried translating it and it seems like it would fit well on the landing page (when you first open Hedy) but did you have another vision? Additionally, since it's dutch would putting it solely in the page rendered for dutch be ok or would you like me to include it in all the languages pages?

**Comment by Felienne** [comment]
> Of course! Do you have any text you would like to introduce the video with? I tried translating it and it seems like it would fit well on the landing page (when you first open Hedy) but did you have another vision? 

For the video we can just swap out the link only (the video is En)

> Additionally, since it's dutch would putting it solely in the page rendered for dutch be ok or would you like me to include it in all the languages pages?

That could go under press!
