### ISSUE TITLE
[BUG] Incorrect label for 'Stop program' button in Spanish

### ISSUE THREAD

**Issue by jpelay** [hedyorg/hedy#3580]
**Describe the bug**
The 'Stop program' in Spanish has been mistranslated, saying 'Save code' instead:

![image](https://user-images.githubusercontent.com/45865185/200070404-5be06881-1ec6-4f9e-b44b-f89ca70283d2.png)

**Comment by KavyaManocha** [comment]
Hi, would I please be able to be assigned to this bug ?

**Comment by jpelay** [comment]
> Hi, would I please be able to be assigned to this bug ?

Sorry, I forgot to add that I already solved it in Weblate!

![image](https://user-images.githubusercontent.com/45865185/200412871-b7036951-7915-4562-94b7-f39e91ddd31b.png)
