### ISSUE TITLE
Wrong value after calculation in level 12 [BUG]

### ISSUE THREAD

**Issue by OnnoEbbens** [hedyorg/hedy#3591]
When I calculate (7.5 + 8.4)/2 I get 7 as the answer using the code below.

```
lijst is 5.0, 7.5, 9.5
cijfer = lijst at random
eerder_cijfer = 8.4
som = cijfer + eerder_cijfer
gemiddelde = som / 2
print 'je gemiddelde is nu een ' gemiddelde
```

**Comment by KavyaManocha** [comment]
Hi, could I please be assigned to this bug?

**Comment by Felienne** [comment]
Hi @OnnoEbbens! I think is already addressed by #3567, which is now live on the main site, see:

![image](https://user-images.githubusercontent.com/1003685/200500979-60abe24e-75e1-454b-8f57-68e757c87bd1.png)

**Comment by Felienne** [comment]
> Hi, could I please be assigned to this bug?

Sorry this was already closed! If you want to pick up something else, let us kno!

**Comment by KavyaManocha** [comment]
Hi thank you for your quick reply! So, I am working on a project for my college class and I wanted to contribute to your project. It seems like the bugs or features I have picked so far are closed or not meant for devs - are there any bugs you would recommend that I could do/start with?
