### ISSUE TITLE
[CHORE, TESTING] Run tests with label and with changes to hedy.py

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#3607]
In #3461 we optimize the test running, which is nice so you do not have to wait for all grammar tests in a front-end PR, but changes to hedy.py do not trigger a run (causing issues in #3587 cause I thought it was complete but it was not).

I propose 2 things:
* Also run the tests if hedy.py changes
* Make a label like `force-tests` that we can put on a PR so all tests are ran. We can do that with mergify I think.

**Comment by jpelay** [comment]
Also, maybe we should execute the test you if one of the files inside tests/ change! I also like the label idea!
