### ISSUE TITLE
[UI idea]Make editor "foldable"

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#3608]
**Idea incl level**
Kids really want to have a larger output field, esp. when using the turtle. Could we add a button to fold the code "in", like the files panel in repl.it:

Folded out:

<img width="879" alt="image" src="https://user-images.githubusercontent.com/1003685/200861435-f71d93f6-50b1-4774-a122-f74280713b9b.png">

Folded in:

<img width="745" alt="image" src="https://user-images.githubusercontent.com/1003685/200861607-dcfffb72-f9a8-4052-afd3-87910f91fc51.png">

Since this is just a small change is ts, it could be a good first issue!

This could also replace the blur button that is also used to "hide" code.

**Comment by TiBiBa** [comment]
This is a bit complex as we currently use a grid structure for our code page. Dividing the code relevant elements into two columns. One with the editor and corresponding buttons and one with the output and prev/next level buttons. When we shrink the editor we have to complete overhaul the structure to make sure the output feels "free" to grow to the space available. Currently looking into this, but a bit more of a nightmare to fix than expected.

**Comment by TiBiBa** [comment]
Propose to first clean-up the whole editor template in a separate issue to be more responsive as well as ready for this implementation. I'm afraid if we continue building on the already existing one the template itself would even be more difficult to understand (and we already added a gruesome load of small elements debug, blur, keyword switcher etc. etc.).

**Comment by Felienne** [comment]
> Propose to first clean-up the whole editor template in a separate issue to be more responsive as well as ready for this implementation. I'm afraid if we continue building on the already existing one the template itself would even be more difficult to understand (and we already added a gruesome load of small elements debug, blur, keyword switcher etc. etc.).

Totally agree a refactoring would be in order, it is a bit feature on top of feature on top of feature!
