### ISSUE TITLE
Problem with presenting the Arabic code

### ISSUE THREAD

**Issue by marrryam** [hedyorg/hedy#3637]
### Arabic hedy: the boundaries of the code editor hides part of the code
In level 1 -->  haunted house adventure: When pressing the green button to apply/paste the example code to the hedy editor, then the beginning of each line of the pasted code is partially hidden by the line numbers (see screenshot). 
The problem persists even when the student/user clears the code and starts writing from scratch, the code will remain being partially hidden at the start of each line. 

The problem is not limited to level 1, it can be seen in the following levels for the same adventure (Arabic language).

**Screenshot of the problem**
![2022-11-11_14-31-57](https://user-images.githubusercontent.com/90961143/201341290-8089c9b6-93f8-44f0-9e51-cb7cf87510ee.png)

**Comment by TiBiBa** [comment]
Hi @marrryam! Thanks for creating this issue. I might have an idea what is causing this, will look into this!

**Comment by Felienne** [comment]
Fixed with the switch to CodeMirror
