### ISSUE TITLE
[UI idea] Allow disabling of multiple lines at once

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#3644]
Disabling a line of code with the "sleeping guy" is very helpful when debugging but in a long program it is a lot of clicking. Could we change the Ui to make it easier to select more lines at once? Not sure how is easiest to build, maybe by

1. Allowing dragging by keeping the mouse button pressed and/or...
2. Selecting multiple lines by clicking two lines when pressing something like shift and then disabling all lines in between?

**Comment by TiBiBa** [comment]
I think the shift option would be easiest. At the point of clicking we can check "is the shift button pressed" if so, disabled all lines between the current one and the first one above we find when iterating the lines high-low. Will look into this today!
