### ISSUE TITLE
[LANGUAGE idea] Add "clear screen" feature

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#3645]
**Language idea incl level**
As suggested by kids in my class, could we add a language element like clear screen for textual output? It is not all too hard for kids and seems doable to build, I think (although I am not sure how whether Skulpt supports it)

**Additional context**
I am not sure what a good level would be. Maybe 4 because it does not have many "cool" features?

**Comment by TiBiBa** [comment]
Whoops read this wrong. Thought about a UI implementation not a language one. Will un-assign myself!
