### ISSUE TITLE
[CONTENT/BUG] quote in French error message breaks Javascript

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#3661]
**Describe the issue**
French elif example in level 17 gives a front-end error:

<img width="1414" alt="image" src="https://user-images.githubusercontent.com/1003685/202110719-bdbc199d-a307-4ebf-a2b3-7721a12f7935.png">

Because the text of the error message is: `msgstr "Il y a déjà un programme en cours, finissez d'abord celui-ci."` and that quote in "d'abord" upsets Javascript when the message is loaded on the front-end!

I can fix it for this error (just reqrite the sentence without the quote), but I want to explicitly make an issue because this is a fascinating problem needs a bit of work to be fixed  in general. 

More details to be added later (no help needed at this point)

**Comment by Felienne** [comment]
Further investigation shows it is not always a problem in the front-end, f.e. this message with a quote just renders without issues:

<img width="747" alt="image" src="https://user-images.githubusercontent.com/1003685/202112999-9a0928c9-c3a0-4c5a-8a86-0d6d00aafafe.png">

So maybe it is just error messages?

**Comment by TiBiBa** [comment]
> Further investigation shows it is not always a problem in the front-end, f.e. this message with a quote just renders without issues:
> 
> <img alt="image" width="747" src="https://user-images.githubusercontent.com/1003685/202112999-9a0928c9-c3a0-4c5a-8a86-0d6d00aafafe.png">
> 
> So maybe it is just error messages?

I can look into this and I already have a feeling what causes this bug. At some places we safely parse translations to the front-end using parseJSON, but not everywhere! This might be a spot where we don't have this implemented (yet) and the function call crashes. Can look into this!
