### ISSUE TITLE
[CONTENT] Allow non-Latin letters for pressed commands

### ISSUE THREAD

**Issue by ToniSkulj** [hedyorg/hedy#3663]
currently, only Latin letters and numerals can be used for mapping pressed commands:
```python
if a is pressed
    print "Ouch!"
```
This should also be made possible for non-Latin letters and numerals such as in Arabic, Russian and Hebrew:
```python
if ش is pressed
    print "Ouch!"

if ф is pressed
    print "Ouch!"

if ש is pressed
    print "Ouch!"
```

**Comment by RikvanSchaick** [comment]
This issue was a follow up of issue #3549.
