### ISSUE TITLE
[CONTENT] level 1 turtle change code/text

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#3667]
**Describe the issue**
As pointed out by @marrryam, 5 steps is a weird directive in level 1 Turtle with the current code.

<img width="1355" alt="image" src="https://user-images.githubusercontent.com/1003685/202367284-8bcdef12-dfc0-4ee3-96ce-05a6d124b0b7.png">

We have to change the code a bit so a 5 steps stair would fit!

**Comment by MarleenGilsing** [comment]
Fixed in #4373
