### ISSUE TITLE
Delete batchhedy and archive folders

### ISSUE THREAD

**Issue by jpelay** [hedyorg/hedy#3670]
**Describe the bug**

@Felienne pointed out in the Hedy meeting that this folders are relics from older times and should be deleted because they serve no purpose in the current state of the project.

**Comment by Felienne** [comment]
Ah thanks for making an issue @jpelay!! I shall pick it up right away!

**Comment by Felienne** [comment]
Closed by https://github.com/hedyorg/hedy/pull/3671
