### ISSUE TITLE
[BUG] error when using floats in a list in level 16

### ISSUE THREAD

**Issue by OnnoEbbens** [hedyorg/hedy#3673]
When I create a list with floats in Hedy level 16 I get an error.

`lijst = [5, 2.5, 2.5]`

![image](https://user-images.githubusercontent.com/10562903/202654222-339b435a-8242-4ff7-8e46-83cb27530b1a.png)

**Comment by KavyaManocha** [comment]
Hi, could I be assigned to this bug?

**Comment by Felienne** [comment]
> Hi, could I be assigned to this bug?

For sure, but be aware this is probably going to be a very complex bug to fix, I deem it very unlikely a new comer will be able to easily fix it, as it requires a lot of knowledge of the transpiler mechanics. If you have not done so, please hop onto the Discord to chat about it there!

**Comment by KavyaManocha** [comment]
Hi, I understand I didn’t think it would be that complicated. No worries, you can leave it open for someone more experienced.
