### ISSUE TITLE
[BUG] Variable i should be escaped

### ISSUE THREAD

**Issue by Mark-Giesen** [hedyorg/hedy#3676]
**Describe the bug**
The label in the right top corner of the output window shows variable in the program that ran. But if you use ```repeat``` an extra variable i is introduced. This variable should be escaped. 

**Add a screenshot (optional)**
![image](https://user-images.githubusercontent.com/28646458/202692958-dcd6cafb-e612-4487-ae91-656966307502.png)

**Comment by KavyaManocha** [comment]
Hi, would I be able to be assigned to this bug?

**Comment by Felienne** [comment]
> Hi, would I be able to be assigned to this bug?

For sure! Do be aware that we can't escape `i` in all cases, because sometimes of course the `i` is a variable that a kids has made. We might want to rewrite repeat so that is generates a different variable name that is less likely to occur? Let us know if you need further help!

**Comment by Mark-Giesen** [comment]
In the turtle examples there's another variable to escape: trtl. There might be more!
It might be a good idea to use some sort of mask for introduced variables so all can be escaped easily. * and _ are already heavily used in python, maybe $ or # ?

**Comment by KavyaManocha** [comment]
which page / level did this bug occur on originally ?

**Comment by Mark-Giesen** [comment]
> which page / level did this bug occur on originally ?

trtl is visible from the level 2, i from level 7 (repeat is introduced)

**Comment by KavyaManocha** [comment]
Hi sorry I have been asking so many questions but I'm still a little unfamiliar with the code base. What file(s) should I be looking to fix this bug? I was looking at hedy.py which seemed like it would be a good start but I wasn't sure.
