### ISSUE TITLE
[CONTENT] Rethink Parsons yaml structure

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#3677]
I am seeing a lot of translation mistakes in the Parsons problems, which is annoying cause I usually end up fixing them. Often the issues are in between lines (different variable names in different lines) and that make me take a look at Weblate and the yamls, and it seems each line is saved and shown separately, f.e.:

https://hosted.weblate.org/translate/hedy/parsons/es/?checksum=f07cac93dbaca3e4&q=comida+es+pizza%2C+helado%2C+ensalada%2C+sandwich&sort_by=-priority%2Cposition

<img width="1070" alt="image" src="https://user-images.githubusercontent.com/1003685/202892664-744b4129-51de-4df4-b167-4c2d3c216515.png">

Of course this makes sense because the yaml structure is:

<img width="601" alt="image" src="https://user-images.githubusercontent.com/1003685/202892695-809527ec-272f-406a-84a4-b87ddd385d92.png">

Can we make the code block into 1 block so it will be shown as one in Weblate? Or somehow make these lines show as one with some weblate magic?

**Comment by TiBiBa** [comment]
This is a difficult one! I do agree that the alphabet structure doesn't make any sense: we don't use this anywhere in the front-end and could replace the checking by simply checking the line ordering. I think this is still some relic-code decision from where it was a student project. I would propose to change this from a dict structure to a list. Not sure if Weblate will handles this better. It is, in this case, crucial that the order stays the same; not sure how well Weblate handles this.

**Comment by Felienne** [comment]
Yes indeed this is legacy but it it now at the point that it is hampering my work. A dict might work, but maybe we can also consider a code block:

```
{print} welcome to bakery Hedy
{ask} ...
{echo} ...
{print ...
```

And then scramble in either Python or in ts? That wat the translators will see the whole snippet at once.

This simplifies the test code too since we can just test the whole snippet.

**Comment by TiBiBa** [comment]
> Yes indeed this is legacy and I am ok with code that is not optimal, but it it now at the point that it is hampering my work because I have to fix bugs all the time.
> 
> A dict might work, but maybe we can also consider a code block:
> 
> ```
> {print} welcome to bakery Hedy
> {ask} ...
> {echo} ...
> {print ...
> ```
> 
> And then scramble in either Python or in ts? That wat the translators will see the whole snippet at once.
> 
> This simplifies the test code too since we can just test the whole snippet.

Sounds good! We can do some Python magic to split on the newlines. We do have to keep track of the order of the lines as well, but this should be fix-able. I can write a script to automatically convert the YAML and fix the back-end code as well.
