### ISSUE TITLE
[CONTENT] Make pressed possible with lowercase special keys

### ISSUE THREAD

**Issue by ToniSkulj** [hedyorg/hedy#3701]
#3664 Makes it possible to bind 'special' commands such as _Shift_ and _Tab_. It would be very nice if we can make it possible to use lowercase letters only such as _shift_ and _tab_.

Current implementation:
![image](https://user-images.githubusercontent.com/48225550/203826989-a76bb0bf-0d68-4687-b9cb-edd218646c4e.png)

**Comment by eremmel** [comment]
The Shift, Ctrl, Alt, etc are so called key modifiers (Tab is not), and most of time not (only at very low level) used on their own (or do I have too less game experience?). My experience is that you combine them with a certain key like: Alt-a or Alt-A == Alt-Shift-A etc.

Another interesting set of keys would be the arrow keys, or should I expect that h,j,k,l is the way to go (I like to support VIm, but ...)

I think it is also good to make a difference between a letter that is expected and a variable with the same name (at least for the higher levels, that will it also make more simple to support for instance tokens like @, !, #, $ in future. Having a single character string might do the trick.
