### ISSUE TITLE
[BUG] Badge incorrectly earned

### ISSUE THREAD

**Issue by Mark-Giesen** [hedyorg/hedy#3713]
**Describe the bug**
One of my students earned the badge for using all commands at least once, but we're only at level 8, so that shouldn't be possible I believe? This student earned it by using all possible commands in one level, I think. But this shouldn't be the case, or is it?

**Comment by TiBiBa** [comment]
This should indeed not be possible. The following check is performed to verify someone has used all commands:
```
if set(session['commands']).union(set(session['new_commands'])) == self.all_commands:
    session['new_achieved'].append("trying_is_key")
```

Whereas the variable `self.all_commands` contains all available Hedy commands. Which in turn is calculated like this:
```
commands = []
        for i in range(1, hedy.HEDY_MAX_LEVEL+1):
            for command in hedy.commands_per_level.get(i):
                commands.append(command)
        commands = set(commands)
```
Printing this variable gives the following set:
```
{'turn', 'echo', 'input', 'print', 'color', 'pressed', 'sleep', 'else', 'ask', 'add', 'while', 'elif', 'remove', 'repeat', 'if', 'and', 'random', 'in', 'forward', 'or', 'is', 'for'}
```

**Comment by Mark-Giesen** [comment]
Is this stored per session or even per program, or per user over sessions? I'm sure this student didn't use pressed, input or elif, he wouldn't know those. Is there a way to see the values for a specific user?

**Comment by TiBiBa** [comment]
> Is this stored per session or even per program, or per user over sessions? I'm sure this student didn't use pressed, input or elif, he wouldn't know those. Is there a way to see the values for a specific user?

It is stored in the database after each program, if there are new command detected.

**Comment by Mark-Giesen** [comment]
Nice, that gives me the hope to achieve it someday. I was afraid this had all to be in one program. How my student received it is still unknown. He does talk about hacking al day ;-)

**Comment by mennoliefstingh** [comment]
Might become time we start a bug bounty program then ;)

**Comment by Mark-Giesen** [comment]
I don't believe he did it correctly, but if we can't find it....
Did you check to see if all commands are in his database record? For instance "pressed" is one of the commands, but it can't even be used at the moment, only by a few pilot users.

**Comment by TiBiBa** [comment]
> I don't believe he did it correctly, but if we can't find it....
> Did you check to see if all commands are in his database record? For instance "pressed" is one of the commands, but it can't even be used at the moment, only by a few pilot users.

I should have clarified that the list produced was from main. Not sure if the current Hedy version in production also already has this keyword implemented. Will close this for now and keep it is mind to maybe add some tests for the achievements in the future.
