### ISSUE TITLE
[UI idea] disable achievements in level 1

### ISSUE THREAD

**Issue by OnnoEbbens** [hedyorg/hedy#3734]
When students start with Hedy they see a lot of new stuff. The first few programs they run return a pop-up with an achievement. For some students the achievements are more confusing than rewarding. Some think the pop-up is the result of a program rather than the text in the output window. I propose to start with the achievements in level 2 when the students are more used to the interface.

**Comment by TiBiBa** [comment]
I like this idea! We have to think it a bit through as we have to alter some stuff:

- How do we handle the x amount of created programs?
- Should we hide the menu option as well when in level 1?
- The command `echo` only exists in level 1 -> should be removed from the "all commands" achievement

Maybe it would be better to hide the achievements for the first x (e.g. 10) programs as a "warm-up" period?

**Comment by OnnoEbbens** [comment]
Thanks for the fast reply! Good idea to hide achievements for the first x programs. I think it should be something between 5 and 10 programs. 

Than you can leave the menu option and keep the `echo` command in the "all commands" achievements.

**Comment by Felienne** [comment]
Totally agree @OnnoEbbens! I opened a sort of similar issue a while ago: https://github.com/hedyorg/hedy/issues/3267
