### ISSUE TITLE
[HIGHLIGHTING] Do not highlight strings that do not end in a quote

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#3768]
From level 4 on, strings need to be enclosed in quotes, but the highlighter is not as strict:

<img width="352" alt="image" src="https://user-images.githubusercontent.com/1003685/205448701-0af9a758-60f0-4937-aa9b-48f948e7eecf.png">

I know that in most systems it is common practice to also highlight unclosed strings:

<img width="313" alt="image" src="https://user-images.githubusercontent.com/1003685/205448804-ab60cd20-20aa-480d-be5a-7fd501e201f5.png">

But I think in our case it would make sense to make `'Bonjour le monde` white and not purple in this code:

```
print 'Bonjour le monde
```

We could consider making the `'` purple? I think I need to see that in action to decide.

**Comment by sfayyad** [comment]
Hi! I already communicated in Discord that I will be working on this issue, but I also wanted to say it here too!

**Comment by arjank** [comment]
> Hi! I already communicated in Discord that I will be working on this issue, but I also wanted to say it here too!

I just assigned the issue to you so others can easily see that this is being worked on.

**Comment by antoineveldhoven** [comment]
> But I think in our case it would make sense to make `'Bonjour le monde` white and not purple in this code:
> We could consider making the `'` purple? I think I need to see that in action to decide.

Does marking the unterminated quoted string as invalid make any sense, or does it defy the essence for Level 4?

![afbeelding](https://user-images.githubusercontent.com/14979232/226918997-ca263038-1f6b-45d2-a4fd-0e1baf4c9268.png)

**Comment by antoineveldhoven** [comment]
@sfayyad Are you still working on this issue, if so: I would like to have your opinion on PR #4165

**Comment by Felienne** [comment]
> [FIX] Highlight unterminated quoted strings differently than correctly terminated quoted strings. #4165

No I think that is an excellent idea!!

**Comment by Felienne** [comment]
> Does marking the unterminated quoted string as invalid make any sense, or does it defy the essence for Level 4?

No I think that is an excellent idea!
