### ISSUE TITLE
[UI IDEA] Change signup forms a bit

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#3769]
Two small changes I would like to see in the sign-up page:

1) Remove the field "sign up to newsletter" for student users. When we send email it is always adult facing (the fact that it is there is legacy from when we had just 1 signup)
2) Add a 'How have you heard about Hedy?' option for teacher users, with the options:
* From another teacher
* Social media
* From a video
* From a magazine or website
* Other

And store these results in the database so we get a better understanding of what leads teachers to Hedy.

**Comment by sfayyad** [comment]
Hi! I already communicated in Discord that I will be working on this issue, but I also wanted to say it here too!
