### ISSUE TITLE
Add a Touch Typing Tutorial

### ISSUE THREAD

**Issue by OrionRandD** [hedyorg/hedy#3770]
This is a PR:
I think that part of the solution to overcome the Syntax of any programming language is teaching children, teens, adults and everyone who uses a computer, how to touch type. So that, they can type quickly and get to know their keyboard better and concentrate in the language concepts themselves instead of looking to their keyboard keys to do something useful...

I think that every IDE should have a touch typing tutorial as part of the program...
I use Emacs, and I have a package for training touch typing...

See this article:
https://blog.codinghorror.com/we-are-typists-first-programmers-second/

**Comment by Felienne** [comment]
Hi @OrionRandD!

I support your sentiment, I see a lot of kids in classes struggle with touch typing. However, it is a bit out of scope you Hedy, especially since it is explicitly meant for class room settings. Teachers can integrate Hedy in digital literacy classes where they do typing before Hedy.

**Comment by OrionRandD** [comment]
On Sun, Dec 04, 2022 at 03:08:43AM -0800, Felienne Hermans wrote:

-------------------------

Another suggestion is:
Instead of adding a typing course to Hedy, you can, at least, add this
suggestion to your public Talks and, say, enhance this necessity...
You can, e.g., suggest a program like klavaro and gtypist for
training...
In GNU/Linux debian and debian-like OSes, you install it with:
sudo apt install klavaro gtypist

-------------------------

    Hi ***@***.***!
 
    I support your sentiment, I see a lot of kids in classes struggle with
    touch typing. However, it is a bit out of scope you Hedy, especially
    since it is explicitly meant for class room settings. Teachers can
    integrate Hedy in digital literacy classes where they do typing before
    Hedy.
 
    —
    Reply to this email directly, [2]view it on GitHub, or [3]unsubscribe.
    You are receiving this because you were mentioned. Message ID:
    ***@***.***>
 
 References
 
    1. https://github.com/OrionRandD
    2. https://github.com/hedyorg/hedy/issues/3770#issuecomment-1336381845
