### ISSUE TITLE
[UI] Improve account creation page

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#3774]
There are a few things we can do to make account creation easier, if we think of the perspective of a teacher that is adding ca. 30 accounts.

1. Add more than 1 (5? 10?) rows if we press +, now I have to push it 25 times. Or maybe make the default 20?

2. Make Generate Passwords a toggle and if turned on, remove the Password column altogether

3. Can we make a button for `Append classname` and/or `Append this string` to make it easier to generate unique names?

4. Ow and can we disable autocomplete by password tools:

<img width="1590" alt="image" src="https://user-images.githubusercontent.com/1003685/205615715-02e79070-a6bd-4dd9-83fb-8ceb35e68943.png">

I now have to manually empty 28x2 fields 😭

**Comment by Felienne** [comment]
> I agree with almost all changes, however I would like to propose to leave the passwords column. It makes the UI restless when we shift all columns and it has no disadvantage of being there. Might also be nice for the teacher to get visual feedback that indeed random password have been generated.

Fair enough! Maybe grey it out when the "generate" toggle is on? Because as it is now it is not clear we should not fill it in.

**Comment by TiBiBa** [comment]
> > I agree with almost all changes, however I would like to propose to leave the passwords column. It makes the UI restless when we shift all columns and it has no disadvantage of being there. Might also be nice for the teacher to get visual feedback that indeed random password have been generated.
> 
> Fair enough! Maybe grey it out when the "generate" toggle is on? Because as it is now it is not clear we should not fill it in.

Sounds good to me! Will disable the inputs when toggled. The PR is almost done, with set it ready for review after this last change.
