### ISSUE TITLE
[UI] Make name of class link (instead of the eye symbol)

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#3776]
We now have an extra column to visit a class with the eye at 'Bekijk' (sorry for the Dutch img)

<img width="1254" alt="image" src="https://user-images.githubusercontent.com/1003685/205624960-701d7aa6-0096-41e1-af04-1e0b27e98ce0.png">

Could we remove that column, and make the name a link? I think that is more conventional.

And we might have the eye in more places, let's do this everywhere.

**Comment by TiBiBa** [comment]
I think we have this eye in quite some spots, will 'knutsel' a bit to remove it a bit and still make clear that the row is clickable.

**Comment by Felienne** [comment]
> I think we have this eye in quite some spots, will 'knutsel' a bit to remove it and still make clear that the row is clickable.

ok! I updated the text of #3782 a bit os we don't close it before we have "knutseled" away all eyes :)

**Comment by Felienne** [comment]
> I think we have this eye in quite some spots, will 'knutsel' a bit to remove it and still make clear that the row is clickable.

ok! I updated the text of #3782 a bit os we don't close it before we have "knutseled" away all eyes :)

**Comment by Felienne** [comment]
> I think we have this eye in quite some spots, will 'knutsel' a bit to remove it and still make clear that the row is clickable.

Thanks for the quick fix! 

In the linked PR, it seems only updated in one place. Did we just have it in one place after all or does more need to be done to close the issue?

**Comment by TiBiBa** [comment]
> > I think we have this eye in quite some spots, will 'knutsel' a bit to remove it and still make clear that the row is clickable.
> 
> Thanks for the quick fix!
> 
> In the linked PR, it seems only updated in one place. Did we just have it in one place after all or does more need to be done to close the issue?

I looked around and was convinced that we had this styling in more places, but couldn't find any! So I think this issue can be closed.
