### ISSUE TITLE
[BUG] ask/in command does not work with non-quoted input for list of strings

### ISSUE THREAD

**Issue by agusikhin** [hedyorg/hedy#3789]
**Describe the bug**
For level 5, if a list contains elements with quotes and the user asks for an element without quotes, the "in" command does not work.

**Paste the Hedy code & level**
Level 5:

item is ask 'What would you like to buy?'
stock is 'bread', 'milk', 'eggs'
if item in stock
print 'We have that'
else print 'we do not have ' item

eggs is not found but 'eggs' is found.

**Add a screenshot (optional)**
<img width="1430" alt="Screen Shot 2022-12-05 at 10 50 47 PM" src="https://user-images.githubusercontent.com/117694418/205808985-c2dd4ba3-5775-47b7-a08e-4eb8c91d9848.png">

<img width="1439" alt="Screen Shot 2022-12-05 at 10 50 56 PM" src="https://user-images.githubusercontent.com/117694418/205809019-2104c2a1-04d0-40d3-ac93-9a03c7d7d331.png">

<img width="1434" alt="Screen Shot 2022-12-05 at 10 51 07 PM" src="https://user-images.githubusercontent.com/117694418/205809036-b22ef7f0-50ff-41f7-96b3-9ce9ff988ee2.png">

<img width="1430" alt="Screen Shot 2022-12-05 at 10 51 20 PM" src="https://user-images.githubusercontent.com/117694418/205809042-20dd88e4-b90b-4607-95c5-51ba45549f25.png">

**What machine and browser you were using (optional)**
Chrome

**Comment by gtongxin** [comment]
claim

**Comment by huangjac1** [comment]
I'd like to be assigned to this
