### ISSUE TITLE
[UI idea] Add numbers for the lines of code in the puzzle assignment

### ISSUE THREAD

**Issue by sjensen19** [hedyorg/hedy#3796]
**Idea incl level**
In today's lesson, we were going to do the puzzle assignment in class. However, when doing this assignment in class, students were confused about what to write down on the erasing boards. Adding numbers in front of the code lines will help students understand where to place them in order. (This applies to all levels that have a puzzle assignment)

**Comment by TiBiBa** [comment]
I don't think I completely understand the issue. Do you propose to add line numbers to the placeholders or to the lines themselves? As the exercise is to put the in the right order it wouldn't make sense to add the line numbers (and so making it very easy to solve). Please let me know!

Do you mean like this?
![Schermafbeelding 2022-12-07 om 13 48 46](https://user-images.githubusercontent.com/38155424/206183688-e93f444a-df65-4426-ba74-2eae37c97fc2.png)

**Comment by sjensen19** [comment]
Hi @TiBiBa, thanks for the follow-up! In class we tried to do the puzzle assignment with the whole group. The idea was that the students would put the code in the right order on whiteboards. Numbers in front of the options would make it easier to show the order on the whiteboards, instead of them having to imagine the numbers. See the screenshot below.

![image](https://user-images.githubusercontent.com/55716630/206243583-fe6de61b-82a5-49f8-99b9-095c3036325d.png)
