### ISSUE TITLE
[UI idea] Re-style the homepage

### ISSUE THREAD

**Issue by TiBiBa** [hedyorg/hedy#3806]
**Idea incl level**
As discussed with @Felienne on Discord it would be nice to give the homepage a fresh look. Based on this schematic drawing we should just start knutselen until it looks nice.
![IMG_DF1545DCA592-1](https://user-images.githubusercontent.com/38155424/206458394-c704ec87-fb72-4191-9039-db0ee3d0872c.JPEG)

**Comment by TiBiBa** [comment]
Well the sketch is also replicated...
![Schermafbeelding 2022-12-08 om 15 12 58](https://user-images.githubusercontent.com/38155424/206468224-7ce8d02f-68f5-4c2b-89fc-3da472b182af.png)

**Comment by Felienne** [comment]
Closed by #3844
