### ISSUE TITLE
[DOCUMENTATION] Pygame markdown

### ISSUE THREAD

**Issue by jonathanvdheuvel** [hedyorg/hedy#3851]
**For team Pygame:**

1. Create `pygame.md` for documentation.
This should make it possible for other contributors to understand what we've implemented during our project.

2. It's important to note what we've **done** and what we've **NOT done** so far. 
3. Mention the technical implementation.

**Comment by Felienne** [comment]
Pretty sure this will not happen anymore :) Maybe @ToniSkulj can add a few docs when we pick up https://github.com/hedyorg/hedy/issues/3966?
