### ISSUE TITLE
[BUG] Change "Waiting for a button press..." into "Waiting for a key press..." when appropriate

### ISSUE THREAD

**Issue by daandj** [hedyorg/hedy#3856]
**Describe the bug**
While waiting for a key press or a button press, the message below the output screen will always say "Waiting for a button press.." Even when waiting for a key press.

**Paste the Hedy code & level**
For example in level 5:
```python
if x is pressed print "hello world"
```

**Add a screenshot**
![image](https://user-images.githubusercontent.com/17110151/207167423-d84c957a-e8b0-4e46-af48-1010ad1da82f.png)

**Comment by boryanagoncharenko** [comment]
Now that we do not have support for buttons, it is weird that the message says 'Waiting for a button press' while the content refers to this as a `key press`. I am reopening the issue and assigning it to myself.
