### ISSUE TITLE
[CLEANUP] Delete stale branches

### ISSUE THREAD

**Issue by mennoliefstingh** [hedyorg/hedy#3868]
Currently we have a lot of branches that remain from old fixes, edits, closed PR's etc. Think it would be a good idea to clean those up. To avoid deleting stuff that's actually being used it might be nice to take some inspiration from the municipality of Amsterdam and tag these branches for a week or two first before we take them to the eternal depot at Sloterdijk.

**Comment by Felienne** [comment]
Good idea for another cleanup @mennoliefstingh!

> take some inspiration from the municipality of Amsterdam and tag these branches for a week or two first before we take them to the eternal depot at Sloterdijk.

🤣 

We can probably do this with a bot? We already have one running to comment on issues that have not received attention for a year.
