### ISSUE TITLE
[CHORE] Implement isort in pre-commit hook 

### ISSUE THREAD

**Issue by mennoliefstingh** [hedyorg/hedy#3869]
isort is a library that automatically sorts your imports according to pep8 conventions, i.e. in alphabetical order, 'from' imports separated, all at the top of the file. It's even less invasive than e.g. autopep8 since the worst it can do is move imports to the top of a file, which can't really break anything.

**Comment by mohitsaxenaknoldus** [comment]
Do you want to replace it with `autopep8`?
