### ISSUE TITLE
[BUG, PERFORMANCE] Dive into why pushAchievement() is called so often

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#3877]
In #3876 we bucket fix an issue where `pushAchievement()` is called very often in quick succession, but we don't really understand why. Let's try to figure that out.

**Comment by arjank** [comment]
@Felienne `pushAchievement()` is called with different arguments. Do we have information which ones were called very often in quick succession?

**Comment by Felienne** [comment]
This could be a bit of a wild goose chase but could someone dive in? (@TiBiBa? @jpelay?)

**Comment by Felienne** [comment]
Not needed anymore
