### ISSUE TITLE
[CONTENT, SLIDES] Make slides downloadable as slides.com zip

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#3924]
In https://github.com/hedyorg/hedy/pull/3860 we add slides to show in the browser. If teachers what to edit them, it'd be nice if they can download a reveal.js file so they can be uploaded in slides.com and can be edited. 

It should *theoretically* be doable since these are reveal.js slides, but because we have fiddled with the css a bit it might be tricky.

**Comment by Felienne** [comment]
ok, to make it possible for someone who is not me to persui this, let me explain my thinking. The way slides now work (see hedy.org/slides) is that they are shown in the browser, easy and translatable! But teachers will want to make changes because they have their won content (like deadlines) and they will most likely not fork the repo and type more yaml code. It is probably hard to generate a pptx file, so I thought we can most easily go through slides.com which is a version of reveal.js.

In slides.com, you can upload a zip file:

<img width="853" alt="image" src="https://user-images.githubusercontent.com/1003685/212960839-bae653b5-d26d-4cde-9fba-f194f67a41ea.png">

This is more info on the format: https://help.slides.com/knowledgebase/articles/546541-export-to-zip-lite-pro

So if we add a download button in /slides that generates a slides.com compatible zip file., teachers can upload them and adapt relatively easily (and once the slides are in slides.com, they can even download a powerpoint)

**Comment by Felienne** [comment]
I suspect this plan is easiest:

* Create an empty slide deck template HTML file along the lines of html in the zip file in the message above
* Add our css to the template zip
* Copy in any content we generate into the index.html file
* Zip it and serve it (we have done that for embroidery files too)

**Comment by jpelay** [comment]
> ok, to make it possible for someone who is not me to persui this, let me explain my thinking. The way slides now work (see hedy.org/slides) is that they are shown in the browser, easy and translatable! But teachers will want to make changes because they have their won content (like deadlines) and they will most likely not fork the repo and type more yaml code. It is probably hard to generate a pptx file, so I thought we can most easily go through slides.com which is a version of reveal.js.
> 
> In slides.com, you can upload a zip file:
> 
> <img alt="image" width="853" src="https://user-images.githubusercontent.com/1003685/212960839-bae653b5-d26d-4cde-9fba-f194f67a41ea.png">
> 
> This is more info on the format: https://help.slides.com/knowledgebase/articles/546541-export-to-zip-lite-pro
> 
> So if we add a download button in /slides that generates a slides.com compatible zip file., teachers can upload them and adapt relatively easily (and once the slides are in slides.com, they can even download a powerpoint)
> 
> Here is an example of a one slide slide deck: https://slides.com/felienne/deck-103cea and the corresponding downloaded: https://www.dropbox.com/s/0utw91wp92si6iq/slides_deck-103cea.zip?dl=0

Miss Felienne I can't access the dropbox file you sent!

**Comment by Felienne** [comment]
> Felienne I can't access the dropbox file you sent!

Ah sorry! I moved the file. The link should work again! I also added it here: [slides_deck-103cea.zip](https://github.com/hedyorg/hedy/files/10453854/slides_deck-103cea.zip)
