### ISSUE TITLE
[CONTENT] Reset password email has no link to actually reset the password

### ISSUE THREAD

**Issue by gustavnovotny** [hedyorg/hedy#3928]
**Describe the bug**
On request for link for forgotten password, the email is recieved, but contains no link (to reset the password).
The email service is gmail.com. Even you open the source of the email, you just see the formatting, image and textation, but no link. The language of the account tested was Czech.

**Paste the Hedy code & level**
N/A

**Add a screenshot (optional)**
<img width="665" alt="image" src="https://user-images.githubusercontent.com/1414313/211848017-689e9bec-6092-4300-b990-121dadd7c437.png">
**What machine and browser you were using (optional)**
Mac / Chrome

**Comment by Felienne** [comment]
Ah thanks for letting us know @gustavnovotny! This is a content issue, the translator in Czech accidentally removed the link from the text.

You can find the text here: https://hosted.weblate.org/translate/hedy/web-texts/cs/?checksum=c74f2bd8797496c3&q=obnoven&sort_by=-priority%2Cposition

Could you translate the rest of then sentence and put {link} back in? I can of course add the link but I don't know Czech for the rest :)

**Comment by Felienne** [comment]
Closed by #4628
