### ISSUE TITLE
[UI idea] Give teachers access to the manual immediately

### ISSUE THREAD

**Issue by MarleenGilsing** [hedyorg/hedy#3974]
**Idea incl level**
Now, if a teachers makes a teachers account, they have to wait until it's approved. This means a teacher can't access the manual. I think it would be beneficial if the teacher could access it immediately, so they can start prepping immediately and don't have to get back to it the next day. 

Suggested solutions:
- Remove the approval and give everyone that requests it a teacher account. (I don't see much harm in students accidentally making a teacher account, it's not like they can cheat that way or something). 

or...
- Give accounts that have requested a teachers account, but aren't approved yet, access to the manual. 
- Give the teacher a warning that eventhough they cannot access the manual yet, the manual will be there for them in x time.

**Comment by Felienne** [comment]
Manual link can be found at the bottom of the page, and we will also add this to the new /start page.
