### ISSUE TITLE
[INTERFACE] Customize class page still needs some love

### ISSUE THREAD

**Issue by MarleenGilsing** [hedyorg/hedy#3976]
**Describe the bug**

Hi Jesus, 
I love the new way of selecting adventures for teachers! 

I was just trying it out and I think this page can still use some improvements. 

![image](https://user-images.githubusercontent.com/80678586/214845492-448e7ad4-3041-4d92-9a2d-33f2997ffb05.png)

I started this issue thinking I had selected level 1 and 3, but I couldn't customize them. Now I'm thinking about it, I probably deselected them instead of selecting them, changing the issue into a - much easier to solve- graphics problem. It's not clear to the user whether an adventure is selected or deselected (blue and green don't intuitively mean anything), so maybe we can change the deselected levels to a lock picture? 

I also still think this page is very busy and overwhelming for teachers. Here are some clean-up suggestions.

![image](https://user-images.githubusercontent.com/80678586/214847338-c219d9d4-65fe-4195-87d1-d9d0a317b539.png)
This explanation can be deleted, since we have a much better way of selecting adventures now. 

![image](https://user-images.githubusercontent.com/80678586/214848615-03396207-3425-4505-9f65-a60c1718a9c9.png)
Maybe we can change the texts in the dropdown menus to make them fit more beautifully. I would suggest 'Level' in the first menu and 'add adventure' in the second. 

![image](https://user-images.githubusercontent.com/80678586/214847782-11e35248-9077-4095-9ea0-5342b25bcd63.png)
Can we maybe make these features foldable? Especially the openingdates are distracting to me (and not that important for teachers to see on the first glance). 

Lastly 'Unlock level tesholds' might need a little line of text as explanation.

**Comment by Felienne** [comment]
Hi @hasan-sh!

There was an old issue asking for a bit of love for the customization page, a lot has been done since this issue was first opened (as you can see from the screenshot) but maybe we can keep this open for you and add the things that we discussed today?
