### ISSUE TITLE
[UI idea] Open hyperlinks in new tab instead of this tab

### ISSUE THREAD

**Issue by MarleenGilsing** [hedyorg/hedy#3979]
When I click on a link in Hedy, for example a link to a youtube video in the teachers manual, this link opens in my current tab. I would love it if it could open a new tab to watch the video, so I don't lose the teacher manual.

**Comment by Felienne** [comment]
I think you can fix this yourself! If you type a link in HTML, you can add ` target="_blank"` in the URL and it will work!

Example:

`<p>Check out <a href="www.hedy.org" target="_blank">Hedy</a>.</p>`

**Comment by MarleenGilsing** [comment]
And if I type a link in a yaml file? Like this section from the teachers manual?

            [Hier](https://www.youtube.com/watch?v=Lyz_Lnd-_aI) vind je een (Engelstalige) video over hoe je je kunt aansluiten bij onze community.
