### ISSUE TITLE
[UI idea] Go to class page after making a new class.

### ISSUE THREAD

**Issue by MarleenGilsing** [hedyorg/hedy#3980]
**Idea incl level**
(Minor Issue) Right now, if you create a class, you are directed to the class customize page. To me it would make more sense if you would be send to the class page, because the most logical step is to add students first.

**Comment by AnneliesVlaar** [comment]
I had the same confusion when I created a new class.

**Comment by Felienne** [comment]
Yes, this is annoying, and the whole teacher workflow should be redesigned.
