### ISSUE TITLE
[LANGUAGE idea] Add clear to turtle

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#3991]
**Language idea incl level**
In https://github.com/hedyorg/hedy/pull/3989 we have added clear for clear the screen, which works for text but not for the turtle screen, can we make that work too?

**Comment by Felienne** [comment]
I am not sure turtle supports it but I would think so? Maybe you can take a look @ToniSkulj?

**Comment by Felienne** [comment]
Update: yes it does:

<img width="952" alt="image" src="https://user-images.githubusercontent.com/1003685/215455235-908f4490-4465-4d9c-a6b6-50f5fe2e75fb.png">

**Comment by ToniSkulj** [comment]
> I am not sure turtle supports it but I would think so? Maybe you can take a look @ToniSkulj?

Will do! Very doable as well.
