### ISSUE TITLE
[UI] Numbered lists render to the left

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#4000]
This is tiny but numbered lists are rendered more "to the left" than looks nice (f.e. level 11 Haunted House (on alpha, not yet released!)

![image](https://user-images.githubusercontent.com/1003685/216273625-50ad5409-3055-4c74-bb32-481c3a972f58.png)

**Comment by TiBiBa** [comment]
This can be solved very easily, with the `list-inside` tailwind class.
