### ISSUE TITLE
[BUG] No comma's allowed after at random: better error message?

### ISSUE THREAD

**Issue by MarleenGilsing** [hedyorg/hedy#4010]
**Describe the bug**
![image](https://user-images.githubusercontent.com/80678586/216423352-bdce6f1e-7f50-442f-862a-7f909b643062.png)
I made this code in level 3. I was not allowed to use this comma and got this error message. After removing the comma, there was no longer a problem. Can we maybe fix this or make a better error message? 

**Paste the Hedy code & level**
level 3 
dishes is spaghetti, brussels sprouts, hamburgers
print You will have dishes at random tonight!
prices is 1 euro, 10 euros, 100 euros
print That will be prices at random, please.

**Comment by Felienne** [comment]
I saw in your PR that you ran into this! There is already an issue open to fix this, will try look at it soon!
