### ISSUE TITLE
[LANGUAGE idea] Localization: Chinese quote marks and other characters

### ISSUE THREAD

**Issue by ifsheldon** [hedyorg/hedy#4012]
**Language idea incl level**
I would like to propose to use Chinese quote marks in the Chinese version of Hedy language. Quote marks are introduced in Level 4. They are "" and '' in English while they are “” and ‘’ in Chinese. 

**Additional context**
The usage and semantics of Chinese and English quote marks are virtually the same, so we safely replace them in the Hedy language. 

The table of unicode for quotation marks is the below

| Quotation mark    | Unicode |
| ---- | ---- |
| “ (Chinese Left Quotation Mark, A.K.A Left Double Quotation Mark in Unicode) | U+201C |
| ” (Chinese Right Quotation Mark, A.K.A Right Double Quotation Mark in Unicode) | U+201D |
| ‘ (Chinese Left Single Quotation Mark, A.K.A Left Single Quotation Mark in Unicode) | U+2018 |
| ’ (Chinese Right Single Quotation Mark, A.K.A Right Single  Quotation Mark in Unicode) | U+2019 |
| “ (English Quotation Mark) | U+0022 |
| ‘ (Apostrophe) | U+0027 |

Fun fact BTW, this header file has become kind of meme in Chinese C programmer community, which replaces frequently used characters in Chinese version with English ones:
```c
#define ； ;
#define ， ,
#define “ "
#define ” "
```
So I also suggest replace `,` and `;` with their Chinese counterparts `，` and `；` so to complete the localization.

**Comment by Felienne** [comment]
Totally agree! (we even have a related issue open for semicolons and brackets: #2724)

Will you be picking this up yourself?
