### ISSUE TITLE
[UI] Weird white bar on save button

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#4019]
Not sure when this happened, but there is a weird line (Chrome, macOS).

<img width="540" alt="image" src="https://user-images.githubusercontent.com/1003685/217197331-cf0f33b2-898d-4796-bae3-bd85256a1762.png">

**Comment by TiBiBa** [comment]
It seems like a z-index issue on the language dropdown. Did the styling change at this part?

**Comment by Felienne** [comment]
We are not sure how it happened but #4021 fixes it!
