### ISSUE TITLE
[TESTING] Refactor cypress tests

### ISSUE THREAD

**Issue by jpelay** [hedyorg/hedy#4027]
As stated by @rix0rrr in #3972 there are two ways in which our tests can be improved:

1. Test organization: Instead of having `define`s with a single `it` we can group different tests under a single `define`. Saving code and making our test suite more organized.
2.  Selecting HTML elements by ID: Cypress actually prevents against using `id` or other HTML attributes used in functionality for the tests.

Update: I will change tests bit by bit
- [x] admin page
- [x] explore program page
- [x] feedback
-> #5393 
- [x] for-teacher page
    - [x] class page -> https://github.com/hedyorg/hedy/pull/5530
    - [x] customize class 
    - [x] customize adventure -> https://github.com/hedyorg/hedy/pull/5683
    - [x] general -> #5592 
- [x] hedy page -> https://github.com/hedyorg/hedy/pull/5648
- [x] home page
- [x] login page
- [x] recover page 
- [x] signup page
- [x] subscribe page
-> #5647
- [x] lezer test
- [x] public adventures
- [x] public programs
- [x] teacher page
- [x] tools
-> https://github.com/hedyorg/hedy/pull/5683

**Comment by Felienne** [comment]
One more task for @Annelein?

**Comment by Felienne** [comment]
All done!
