### ISSUE TITLE
[TESTING] Create accounts Cypress test is flaky 

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#4041]
**Describe the bug**
This test keeps passing and failing and passing and failing. Sometimes it works in a PR and then fails on main, or the other way around, I can't really find a pattern. Can you take a look @noelgolding or maybe @jpelay? I can also disable the test for now (because it interferes with merging if it fails on a PR) but it is of course better to fix it.

<img width="733" alt="image" src="https://user-images.githubusercontent.com/1003685/219321901-77a38aea-c67e-4266-84ba-f0f1fe024cf6.png">

**Comment by noelgolding** [comment]
@jpelay the only way I can reproduce this locally is to comment https://github.com/hedyorg/hedy/blob/main/tests/cypress/e2e/for-teacher_page/class_page/create_accounts_page/create_accounts.cy.js#L21

Do you think a `cy.wait(500)` is required before looking for `.username-cell`?

```
    cy.get('#back_to_class_button').click();
    cy.wait(500);
    cy.get('.username_cell').should(($div) => {
```

**Comment by noelgolding** [comment]
actually, I think this is a cleaner approach, the original test was taking advantage of a side effect.
```
    navigateToClass(classname);
    cy.get('.username_cell').should(($div) => {
```
