### ISSUE TITLE
[BUG] Consequitive if pressed with print in between

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#4042]
**Describe the bug**
Ok, @ToniSkulj we are getting these, but this remains (level 8)

```
als s is ingedrukt
    print 'leuk'
anders
    print 'wat ben jij stom doei'
print 'maak jij de kinderen wakker'
als a is ingedrukt
    print 'ja ik maak ze wakker'
anders
    print 'wat vervelend ben jij dan doe ik het wel.'
```

The second if creates an if without the while true around it:

```
while not pygame_end:
  pygame.display.update()
  event = pygame.event.wait()
  if event.type == pygame.QUIT:
    pygame_end = True
    pygame.quit()
    break
  if event.type == pygame.KEYDOWN:
    if event.unicode == 's':
      print(f'leuk')
      break    
    else:
      print(f'wat ben jij stom doei')
      break
    
print(f'maak jij de kinderen wakker')
  if event.type == pygame.KEYDOWN:
    if event.unicode == 'a':
      print(f'ja ik maak ze wakker')
      break    
    else:
      print(f'wat vervelend ben jij dan doe ik het wel.')
      break
```

<img width="781" alt="image" src="https://user-images.githubusercontent.com/1003685/219349266-9b7e4016-2111-4c6c-b1d5-99227ed5d29e.png">

I think the fix is to change the semantics so that each `if pressed` get its own `while`, not very hard to fix I think! Let me know if you have the bandwidth to look at it!

**Comment by ToniSkulj** [comment]
Hi @Felienne, thanks for the fix on https://github.com/hedyorg/hedy/pull/4039 !!

_I think the fix is to change the semantics so that each if pressed get its own while, not very hard to fix I think! Let me know if you have the bandwidth to look at it!_
Yeah should be very doable! I have some time tonight, hopefully I will have PR ready.

**Comment by ToniSkulj** [comment]
I quickly realized why I had implemented it this way. Take for example the following code:
```python
if a is pressed
    print "Hello from A!"
    
if b is pressed
    print "Hello from B!"
```

If we would wrap every single _ifpressed_ command with its own while loop then it would not be possible to press **b** the first time and expect something to happen, because the code is blocking in the first while loop, or the event loop so to speak. Thats why the code adds the _ifpressed_ to the existing event loop.

This breaks when there is a command in between, such as print.

We obviously want both 😅, so if the above example code is run **b** can be pressed, but if a command is in between _ifpressed_ or _ifpressed_else_ commands we want to make another while loop (or start another event loop) for the second bit. I'm not 100% sure on how to implement this. Anyway, I'm going to think about a solution for this. When I have something I will post it here!

**Comment by Felienne** [comment]
> I quickly realized why I had implemented it this way. Take for example the following code:
> 
> ```python
> if a is pressed
>     print "Hello from A!"
>     
> if b is pressed
>     print "Hello from B!"
> ```

Yes I realized that, which is why I proposed to change the meaning of the command (but I guess I should have expressed myself better)

What I would like is that if we have

```
if a is pressed
    print "Hello from A!" 
````

means that if you press a, it prints, and if you press something else nothing happens and the command ends (like an implicit `else Pass`

This is, arguably, a bit weird, but Scratch had a similar thing, this:

<img width="360" alt="image" src="https://user-images.githubusercontent.com/1003685/219629270-465edfff-3bf7-4588-8f37-887170d16efa.png">

only checks once.

**Comment by jpelay** [comment]
I think that maybe we can add a new keyword for this type of behaviour such as:

```
select
  a: print "You pressed a"
  b: print "You pressed b"
  c: print "You pressed c"
```

Because I think the problem arises when we use the same command, if, for 2 things: normal conditionals that execute sequentially and the `ifpressed` commands that run together. What do you think?

**Comment by jpelay** [comment]
> That is a nice idea we did not yet consider! I do worry it will add maybe too much complexity...? In the current form, it is ncie that we teach on thing (if) and then show multiple ways in which it can be used. If we go along your lines @jpelay, I think we should make it into a separate level where we teach the idea of a wait?

That's what I'm afraid of, that it would add too much complexity, adding yet another thing that kids need to learn. But maybe the complexity of the usage of if pressed is already there? In the sense that I don't know how easy will be for kids that if pressed works a certain way sometimes and another ways other times. So the mental model they built around if shifts.

**Comment by Felienne** [comment]
Yeah that is true, it is complex! We can of course still also decide to make it simpler, or drop the idea cause it is not feasible (even though we love it, kill your darlings and all...)

**Comment by jpelay** [comment]
> Yeah that is true, it is complex! We can of course still also decide to make it simpler, or drop the idea cause it is not feasible (even though we love it, kill your darlings and all...)

In this sense would you still feel ok to ship https://github.com/hedyorg/hedy/pull/4049/ and see how kids behave with them?

**Comment by ToniSkulj** [comment]
> I think that maybe we can add a new keyword for this type of behaviour such as:
> 
> ```
> select
>   a: print "You pressed a"
>   b: print "You pressed b"
>   c: print "You pressed c"
> ```
> 
>  What do you think?

That's a great idea! I thought of making the kids define their own while/event loop but like you both stated that could make it more complex. 

>  So the mental model they built around if shifts.

Yeah, that is big a problem. The obvious solution (like Felienne mentioned) is to remove that functionality and only make it possible to press one key. 

> In this sense would you still feel ok to ship https://github.com/hedyorg/hedy/pull/4049 and see how kids behave with this if?

Maybe we could test run this in just a handful of classes, and see how the kids react?

**Comment by Felienne** [comment]
> > Yeah that is true, it is complex! We can of course still also decide to make it simpler, or drop the idea cause it is not feasible (even though we love it, kill your darlings and all...)
> 
> In this sense would you still feel ok to ship #4049 and see how kids behave with this if?

Yeah I would prefer to test it as is (I can test in in my upcoming run) and then decide. If you feel #4049 does not create new errors, let's merge it!
