### ISSUE TITLE
[CONTENT] Add slides to teacher manual

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#4043]
Since #4023 the slides are visible for teachers (for level "0" (general explanation) and 1), this should still be added to the manual.

We explain they exist and also how to download and upload them to slides.com to get them into Powerpoint (let me know if you need help there Marleen!)

**Comment by Felienne** [comment]
Just dumping this here because I have no time to check but are the paper sheets in the teacher's manual? https://github.com/hedyorg/hedy/pull/2207

**Comment by schneems** [comment]
I would love some pre-made or shared content. I'm working with 4th and 5th graders. We were previously using code.org and they have slides and videos to talk about concepts. I don't think it needs to be quite that high-fidelity though. 

Having even some shared outlines or a community space where teachers can share common challenges students face could help build a feedback cycle to better prepare other students for future classes.

**Comment by Felienne** [comment]
Hi @schneems!

We are working on slides and what we have can already be found here: https://hedy.org/slides/1 (and similarly for level 2) I saw in the other thread that you have figured out how to then download and adapt them but as you say, you an also just use them for inspiration.

As for the community space to talk about challenges, that is what we currently use Discord for, see #teachers-general.
