### ISSUE TITLE
[BUG] Clear feature does not work

### ISSUE THREAD

**Issue by ToniSkulj** [hedyorg/hedy#4053]
The **clear** feature does not work anymore that was added in  #3989 & #3992.
The error _name 'extensions' is not defined_ is given

![image](https://user-images.githubusercontent.com/48225550/220057927-515ab8c5-a86f-4819-949d-b15b7680aa6a.png)

**Comment by Felienne** [comment]
Ah good catch!! Was this caused by the cleanup of the includes?

Maybe these types of errors warrant a more extensive testing on the front-end (will make a not to chat about it next meeting)

**Comment by ToniSkulj** [comment]
> Ah good catch!! Was this caused by the cleanup of the includes?

Thanks!! Yeah that was the cause.

> Maybe these types of errors warrant a more extensive testing on the front-end (will make a not to chat about it next meeting)

Great idea!
