### ISSUE TITLE
[UI Idea] Collapse content menu in teachers manual when used in a phone

### ISSUE THREAD

**Issue by jpelay** [hedyorg/hedy#4079]
I think it would be a nice idea to collapse the content menu in the teachers manual when used in phones. Something along the lines in this page https://craftinginterpreters.com/scanning.html:

Big screen:
![image](https://user-images.githubusercontent.com/45865185/222198101-b38533c6-9ecb-4eb0-98b7-7ad800b335b9.png)

Phone screen:
![image](https://user-images.githubusercontent.com/45865185/222198183-b4d61a53-c20a-4ce5-ac4d-c2e74cf0303b.png)

**Comment by Felienne** [comment]
This fits in a larger plan of making Hedy more responsive
