### ISSUE TITLE
[UI idea] Add adventures from customization page

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#4084]
Adding your own adventures is a bit cumbersome now, if you want to add a new one to your class you have to go all the way back to the teachers page (2x back) add it there and go back to your class (2 clicks forward)*.

Couldn't we do this in the customization page, with an extra button?

<img width="1217" alt="image" src="https://user-images.githubusercontent.com/1003685/222434332-11b3b7d4-008e-47f1-bde1-8e5bd6949845.png">

That could just bring up the author page and, upon saving, add the fresh adventure to the class right away? Is this doable?

* We used to have (I think?) the option to add the adventure to a class right away but that seems to be gone.

**Comment by Felienne** [comment]
I suspect this is no longer useful because the design has changed so much in the mean time?

**Comment by Annelein** [comment]
> I suspect this is no longer useful because the design has changed so much in the mean time?

I guess this is solved in https://github.com/hedyorg/hedy/pull/5154 ? 
But if you think it would still be nice to be able to add an adventure through there, I think it would be possible @hasan-sh ?

**Comment by Felienne** [comment]
I think it would still be nice to have if possible! We can discuss tomorrow in the meeting how to do it (and who will pick it up)
