### ISSUE TITLE
[UI idea] Make the UI work uncluttered on FullHD Screens

### ISSUE THREAD

**Issue by Ausbildungsleiter** [hedyorg/hedy#4104]
On a FullHD screen, you can't see the whole page, so it's cluttered. Only on a 4k screen did I find the Hedy website clear for learners. But 4k resolution screens are rare in education, where FullHD is now the norm. So please check your pages on FullHD screens and redesign them accordingly.

**Comment by Felienne** [comment]
Thanks for the feedback @Ausbildungsleiter but it is not actionable enough to warrant an issue this way. Maybe you can share a screenshot and help us understand what is not visible?

**Comment by Ausbildungsleiter** [comment]
4k : ![2023-03-10-113353_3436x1388_scrot](https://user-images.githubusercontent.com/43267773/224294314-35ce509a-2dd4-4fb1-8abe-23a7b932f15a.png)

about FullHD: 
![hedy](https://user-images.githubusercontent.com/43267773/224294485-e68c213e-9f9f-4cb3-a8ac-33adb8e522a8.png)

It seems someone already worked on it. It looks better today, but still scrolling is possible and sometimes needed. On my laptop I had to move up and down a lot, seeing the examples and seeing my code. In my opiniion an educational tool shall distract as less as possible, and to achieve that here, everything should fit on a single FullHD laptop screen, and there should be no need to scroll around. But that is my opinion, and you may have good reasons for your design.

**Comment by Felienne** [comment]
Hi @Ausbildungsleiter!!

Have you seen the "Programmers view" button below the coding field? If hides the explanation:

<img width="1670" alt="image" src="https://user-images.githubusercontent.com/1003685/224295943-909b5e2f-e67c-428d-be09-96d7e86cdb54.png">

<img width="1575" alt="image" src="https://user-images.githubusercontent.com/1003685/224295986-f908c0a8-d893-4fab-b519-999084f6f522.png">

And yes, there is a trade off here. Having the explanation in view is helpful (if kids have to find this in another tab or on paper, that is *also* distracting) and that comes at the cost of sometimes scrolling.

One more free tip: as a teachers, you can hide certain adventure tabs and even make your own ones! So if this is too distracting for your group (any group is different, ages, size of group, size of screens etc) you can author shorter adventures so there is less scrolling! This type of teacher customization is what makes Hedy great in our opinion!

**Comment by Felienne** [comment]
And with that I think we can close this issue, but you are also very welcome to hop onto our Discord and discuss more there, or attend a meeting where we brainstorm features and prioritize them!

**Comment by Ausbildungsleiter** [comment]
Well, we can close it. I made my point, and can add to the programmers mode: Well, then I don't see the examples. Of course I can copy them in the editor first ... I'm not sure, how well that will work with pupils. I did not do any experimenting so far with pupils with hedy. So everything is based on my transferred experiences from other course offerings.
