### ISSUE TITLE
Sabina_takenlijst

### ISSUE THREAD

**Issue by SabinaChita** [hedyorg/hedy#4105]
Logo vervangen

**Comment by SabinaChita** [comment]
We gebruiken nu op veel plaatsen het witte ronde logo maar de laptop is mooier. 

Zie GitHub issue: [https://github.com/hedyorg/hedy/issues/4073](https://github.com/hedyorg/hedy/issues/4073#issuecomment-1449954965)

**Comment by Felienne** [comment]
Hi Sabina! This one already has an issue (#4073 as you also linked) so we do not need a new one. We use one issue per task.
