### ISSUE TITLE
Explain Weblate Zen modus

### ISSUE THREAD

**Issue by SabinaChita** [hedyorg/hedy#4112]
Translating in weblate is quite hard, the UI is super complex and there are a lot of features. It would be better if we explain somewhere to translators about the Zen modus and how it works.

**Comment by Felienne** [comment]
Yes, great point! Maybe we can even make Zen mode the default mode, potentially @Mark-Giesen can look into that?

**Comment by Mark-Giesen** [comment]
Zen is explained in translating.md. Not enough?

**Comment by Felienne** [comment]
Sadly I don't think so. I keep hearing from translators that they don't know about it. 

translating.md as it is now in itself is also quite overwhelming with all the screenshots (Weblate's fault mostly, not yours!) Also people might not be coming in through GitHub but through our website!

**Comment by Mark-Giesen** [comment]
We can't set Zen default for the project

**Comment by Mark-Giesen** [comment]
> Translating in weblate is quite hard, the UI is super complex and there are a lot of features. It would be better if we explain somewhere to translators about the Zen modus and how it works. 

Any good ideas about better UI? I believe it's one of the focuspoints for weblate this year, we could even help out

**Comment by SabinaChita** [comment]
I totally agree with Felienne! I started translating in Romanian myself and tried both UI and with and without zen. I have to say that I can imagine that who is translating and has no programming experience will get scared about the amount of info and (other/ error) messages and run away. Also the zen button is not really easy to find/to see. Not sure how many translators that never used weblate before starting translating read first the manual and find out that zen mode exits. I understand that is not possible to make the zen button more prominent and move it in place where you can just see it right away, but then for starters I can try to make some video/file-info for translators that explain how zen works/they can use it? And maybe also the rest of the things that they should not translate to save some time Mark from fixing bugs.
