### ISSUE TITLE
Order new logo stickers

### ISSUE THREAD

**Issue by SabinaChita** [hedyorg/hedy#4113]
We need to order new stickers with the new logo:

https://hedy.org/images/hero-graphic/hero-graphic-en.png

Not only in English but also e.g. Chinese and Arabic.

**Comment by Felienne** [comment]
I made an Arabic version already @SabinaChita!


![Image](https://user-images.githubusercontent.com/1003685/224331332-58b0b439-abf2-4ec6-9bba-6058eb42f881.png)

It has a little white line so it does need a little bit of love.

Also, the currect stickers are a bit too big, I think we want smaller ones.

**Comment by Felienne** [comment]
Ah cool @SabinaChita!! When will the stickers be ready?

**Comment by SabinaChita** [comment]
Just emailed a couple of times yesterday and today with Steven van den Elzen from stikerkoning, they were closed during easter now they will start mass production (just 50 pieces first to see if we are happy with the layout form), I did a small smoothening in illustrator for the white border cause of their 2,5 mm cutting marge, I asked for print on vinyl, other options also available if we don't like this one, they will be around 7 by 5 cm; he said in his last email (half an hour ago) that I will get them by 18th op April.

**Comment by Felienne** [comment]
> Just emailed a couple of times yesterday and today with Steven van den Elzen from stikerkoning, they were closed during easter now they will start mass production (just 50 pieces first to see if we are happy with the layout form), I did a small smoothening in illustrator for the white border cause of their 2,5 mm cutting marge, I asked for print on vinyl, other options also available if we don't like this one, they will be around 7 by 5 cm; he said in his last email (half an hour ago) that I will get them by 18th op April.
> 
> ![Image](https://user-images.githubusercontent.com/127490004/231400951-19944ada-8555-4ef0-9177-5706f908b6f3.jpg)

Looks fantastic!! And well in time to hand out on May 10th!

**Comment by Felienne** [comment]
Reopening so we don't forget to keep an eye on the status

**Comment by Felienne** [comment]
Hi @SabinaChita!!

The first batch of stickers was awesome! Let's order a bigger batch (1000?), but the version with "Hedy.org" in the bar, have you fixed the one I sent you?

And let's also make the Arabic, Chinese version with the url and a Dutch version? Extra cool! I will drop the images here.

**Comment by SabinaChita** [comment]
Great to hear, I'm also happy with stikker company work and choice of materials. Yes, I am fixing the logo this week, is on my to do list :-)

I will then order 50-100 per NL, Arabic and Chinese version when I get your images and 1000 for english version all with url on, same dimensions and same material as we did with the first batch. 

I'll update this issue once the images are "de deur uit".

**Comment by Felienne** [comment]
All versions here @SabinaChita:

[Stickers.zip](https://github.com/hedyorg/hedy/files/11330357/Stickers.zip)


The ones with url are for the stickers!

**Comment by SabinaChita** [comment]
@Felienne: I made all versions for stickers, put them also into folder op g: https://drive.google.com/drive/folders/1Tx4RZv_9syYxCdrjDZdUrIYXr9osUkhN?usp=share_link

ter info: in case you need to add more languages or change layout just let me know, I'm reasonably handy with photoshop and illustrator. 

i'm sending them this week to the printer with the following order of magnitude: english (1000); arabic (50); chinese (50); dutch (50). Are we ok with these amounts?
