### ISSUE TITLE
[CONTENT?] Kurdish shows placeholders!

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#4119]
This is an interesting WTF:

<img width="1414" alt="image" src="https://user-images.githubusercontent.com/1003685/224406944-323920d8-ce07-438b-a7a0-6289c70697ae.png">

This is broken on the site and locally too. Of course I ran

` hedyorg % pybabel compile -f -d translations`

<img width="1115" alt="image" src="https://user-images.githubusercontent.com/1003685/224407031-da58ec90-2126-4a9c-8211-c1800748ba0a.png">

It even tells me it has compiled kmr but places holders are still shown.

Not sure who can dive into this, maybe @jpelay or maybe @TiBiBa?

We could temporarily remove kmr as a language so that this ugly view is not shown?

And also, we must add a test to detect place holders on the site, even though we do `pybabel` on the server so "this should never happen"... apparently is does happen!

**Comment by jpelay** [comment]
It seems to be added correctly to Weblate and no apparent issues there?

**Comment by rix0rrr** [comment]
I went into `.env/lib/python3.8/site-packages/flask_babel/__init__.py` and added a couple of `print` statements:

<img width="820" alt="image" src="https://user-images.githubusercontent.com/524162/224475499-c2ecc4bc-d249-4e36-ac33-385ce2cef858.png">

And the output is:

```
GET_TRANSLATIONS
ku_TR
```

So, it looks like there might be some confusion around the language code for this language. Certainly, some [GitHub thread I found via Google](https://github.com/directus/directus/discussions/9786) seems to indicate that this confusion happens more often.

I don't know what to do with that information, but this is what I've been able to figure out so far.

**Comment by TiBiBa** [comment]
We already have some Babel magic in place as a work-around for non-matching language codes between Weblate and Babel. 

This should be fixable by simply adding the corresponding language keys to the dictionairy we define for this.
