### ISSUE TITLE
[LANGUAGE idea] Translate the clear command

### ISSUE THREAD

**Issue by MarleenGilsing** [hedyorg/hedy#4132]
We need a Dutch version of the clear command (and probably some other languages too). 
I was thinking of 'wis' or 'leeg'.

**Comment by Felienne** [comment]
You can actually translate that yourself in Weblate: https://hosted.weblate.org/translate/hedy/keywords/nl/?checksum=3de866884cb541f0&q=clear&sort_by=-priority%2Cposition

`wis` lijkt me goed, of `maak leeg`, zodat het gebiedende wijs is zoals de andere keywords?
