### ISSUE TITLE
[CONTENT] common mistakes and hints in teacher manual

### ISSUE THREAD

**Issue by noeleont** [hedyorg/hedy#4185]
**Describe the issue**
Level 12, Adventure calculator.

In the adventure the following extra exercise is mentioned: 

> (extra) Increase the difficulty by adding lives: A player loses a life for a wrong answer and after three wrong answers the game ends.

I think this is not possible in this level since `while` is introduced in level 15 or am I missing something? 

Meta: should such a discussion happen over on the translation website?

**Comment by Felienne** [comment]
> Meta: should such a discussion happen over on the translation website?

Discord would be better, could you hop over there? I will ask @MarleenGilsing to look at the exercise in any case!

**Comment by MarleenGilsing** [comment]
@noeleont Nice to be challenged by my own exercises haha, but I've solved the puzzle:  

![image](https://user-images.githubusercontent.com/80678586/228762839-f114bcb5-a388-4233-a6a9-0a2500fa8033.png)

```
numbers = 1, 2, 3, 4, 5, 6, 7, 8, 9, 10
lives = 3
repeat 10 times
    if lives = 0
        print 'You lost'
    else
        number_1 = numbers at random
        number_2 = numbers at random
        answer = ask number_1 ' times ' number_2
        correct_answer = number_1 * number_2
        if answer = correct_answer
            print 'Great job!'
        else
            lives = lives - 1
            print 'Wrong! You lose a live!'
```

Only problem is that it might say 'You lose' a couple of times if you fail before the 10 times are up.

**Comment by MarleenGilsing** [comment]
@Felienne This got me thinking that we might need some kind of answersheet in the teacher manual for the extra challenging exercises.

**Comment by MarleenGilsing** [comment]
Yes I was thinking of hints too! I'll add these to my to do list.
