### ISSUE TITLE
[CONTENT] Twister

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#4206]
In the pressit adventures (removed in #4146) there was a lovely idea for a Twister game:

```
            16:
                story_text: |
                    Lets move a little with a game of Twister!
                    When everyone is ready, press the x key for the next move!
                example_code: |
                    ```
                    limbs = ['Right Hand', 'Left Hand', 'Right Foot', 'Left Foot']
                    colours = ['Blue', 'Green', 'Red', 'Yellow']
                    {repeat} 20 {times}
                        l = limbs[{random}]
                        c = colours[{random}]
                        {if} x {is} {pressed}
                            {print} l + ' on ' + c + '!'
                    ```
                start_code: "# place your code here"
```

I want to bring that back in a different from, making an issue so I don't forget!

**Comment by Felienne** [comment]
Hi @MarleenGilsing!

I love this twister idea, can we make it with a simple ask or wait, instead of an `is_pressed` (we don't really trust the is_pressed for now)

**Comment by Felienne** [comment]
It also do not have to be level 16, it could be 11 as well?

**Comment by MarleenGilsing** [comment]
Hi Felienne, 
I've seen it before and loved it, so I've put it in the functions adventures I'm working on now. I'll see if I'll put in in some earlier levels as well!
