### ISSUE TITLE
[UI idea] Mini issue: remove header 'example hedy code'

### ISSUE THREAD

**Issue by MarleenGilsing** [hedyorg/hedy#4217]
Since I'm on the topic of removing clutter from the interface: Can we remove the header that says 'Example Hedy code". 
It's unnessecary info. We could keep the first header, but if there's multiple examples, we don't need the second or third header.  

![image](https://user-images.githubusercontent.com/80678586/230419541-e7792e0e-62f5-4257-bbaf-e2dd074c1e27.png)

**Comment by Felienne** [comment]
Hi @MarleenGilsing!

I was thinking the same! But maybe we can *also* remove the first header? What do you think about that? Since it is always the same thing in each page, and what else would this be than example code?

**Comment by MarleenGilsing** [comment]
Sounds good! I only said 'maybe just the second and third' in case someone was attached to this header haha!

**Comment by Felienne** [comment]
Ok I am playing with the code, this is without the second (etc.) one:

<img width="1579" alt="image" src="https://user-images.githubusercontent.com/1003685/230597653-4586f486-c864-4624-add6-547385b9e6c8.png">

<img width="1630" alt="image" src="https://user-images.githubusercontent.com/1003685/230597689-4797a6c7-368d-408a-822f-2441e2f7a98b.png">

**Comment by Felienne** [comment]
A lot better esp. for level 12: 

<img width="1635" alt="image" src="https://user-images.githubusercontent.com/1003685/230597766-9252a4aa-9baa-4335-8e6d-603566848671.png">

(although with the splitting of command adventures that might be less important)

**Comment by Felienne** [comment]
And this is without the first header too:

<img width="1606" alt="image" src="https://user-images.githubusercontent.com/1003685/230597910-07f348f0-5b4e-49cb-b38e-1d10f364cfb7.png">


Now that I am looking at it, it feels a bit "naked"? I guess because the left still has the title?

**Comment by Felienne** [comment]
But going further along this path... Do we need the left header? There is already a lot of context (we are in the Introduction tab).

In an adventure, the left header is the 3rd mention of Parrot:

<img width="1595" alt="image" src="https://user-images.githubusercontent.com/1003685/230598066-db48c59b-9a67-40bd-b4e7-f46ce45cac5a.png">

Maybe we can get rid of that header too and everything is a lot more "clean"?

**Comment by Felienne** [comment]
Here is the version without all headers, it feels very naked, but after looking at it for a bit longer, it also feels "rustig"

<img width="1598" alt="image" src="https://user-images.githubusercontent.com/1003685/230598394-4d792deb-1f6d-4e27-8693-3214dd885fd7.png">

<img width="1640" alt="image" src="https://user-images.githubusercontent.com/1003685/230598409-dc1809b1-473e-4cfe-8faf-c9b05800fa5b.png">

What do you think @MarleenGilsing

**Comment by Felienne** [comment]
The benefit in addition to "rustig" is that is also makes the field smaller increasing the chances that kids have the run button in view without scrolling
