### ISSUE TITLE
[CONTENT] "This is what other teachers say about Hedy" page

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#4218]
We get a lot of nice emails, let's gather them all in one place (if we are allowed to share of course) so everyone can see how much teachers love Hedy!

@SabinaChita: 

Can you make a nice (Word) document with everything in one place, we can then add it is Github!

**Comment by SabinaChita** [comment]
yes of course! i'll gather everything i can including the previous feedback.
