### ISSUE TITLE
[UI] Start at highest level achieved

### ISSUE THREAD

**Issue by SabinaChita** [hedyorg/hedy#4219]
From a teacher survey:

"Alternatively, when students are in a class that has Levels locked behind completing quizzes, it would be great if they would start back on their highest unlocked level when they log in. Students sit there clicking the "Go to Level 2", "Go to Level 3", etc. buttons for a long time at the start of class."

**Comment by Felienne** [comment]
I usually telly my students to "hack the url" but I guess that is not a thing all teachers know!
