### ISSUE TITLE
[UI idea] Grid: Show overview of tick marks

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#4241]
This issue relates to #4008, we are splitting it into separate issues for @ akadahsalim.

Step 1 is to add tickmarks in an interface (partly completed in #4238 already). For now, we want this overview to show all adventures and students for one level. Note that:

* We want the filtering to happen in Python
* If we have interaction, use HTMX where possible (see https://github.com/hedyorg/hedy/wiki/Hedy-Developer-Guide#front-end-html-tailwind-htmx-hyperscript-typescript-skulpt)
* Classes can have custom adventures made by teachers, in addition to the adventures leaded from the yaml files.

**Comment by akadahsalim** [comment]
Should we now close this and proceed into the next step? I believe this is handeled with the last push into #4238.

**Comment by Felienne** [comment]
we can close this when we actually merge #4238

**Comment by Felienne** [comment]
Can now be closed (by #4238)
