### ISSUE TITLE
[TESTING] Improve coverage of `app.ts` 

### ISSUE THREAD

**Issue by jpelay** [hedyorg/hedy#4251]
`app.ts` is the file where most of our logic concerning the web page is located. This file sits at 46.61% test coverage as of today. Some core functionalities are missing testing including:

- [ ] * `saveMachineFiles`
- [ ] * `closeAchievement`
- [x] * `delete_program`
- [x] * `set_favourite`
- [ ] * `submit_program`
- [ ] * `inputFromInlineModal`

Among others (you can check which by running the code coverage as described in the documentation).

**Comment by Felienne** [comment]
Hi @Annelein!

Increasing test coverage of the front-end too is a task for you?

**Comment by Felienne** [comment]
See new issue #5992
