### ISSUE TITLE
[BUG] newlines are gone from quiz answers

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#4258]
This is due to the quiz rewrite in #4224, I think:

<img width="1131" alt="image" src="https://user-images.githubusercontent.com/1003685/233117378-94355137-b70b-45b1-932e-70044a0dc264.png">

**Comment by axvr** [comment]
Hi, I think the change made in #4259 to fix this issue has caused another one.  Some of the quiz answers contain `</br>`s.  (E.g. level 1 quiz question 3 and some questions on the level 3 quiz.)

<img width="1126" alt="image" src="https://user-images.githubusercontent.com/26504626/234373833-25ac23e6-a874-450f-915e-6da1aba9ad2d.png">

**Comment by Felienne** [comment]
> Hi, I think the change made in #4259 to fix this issue has caused another one. Some of the quiz answers contain `<br />`s. (E.g. level 1 quiz question 3 and some questions on the level 3 quiz.) I saw it on Firefox, I haven't tested other browsers.
> 
> <img alt="image" width="1126" src="https://user-images.githubusercontent.com/26504626/234373833-25ac23e6-a874-450f-915e-6da1aba9ad2d.png">

Ah thanks for noticing! I reverting the fix and will look into a beter solution!

**Comment by Felienne** [comment]
Fixed by #4270
