### ISSUE TITLE
[BUG] Printing a list in level 3 is possible by adding a list to a list

### ISSUE THREAD

**Issue by jhoobergs** [hedyorg/hedy#4272]
**Describe the bug**
In level 3, printing a list is not supported. It is currently, however, possible to add a list to a list and then print that list item by using `at random`. It might be that it is actually not supposed to be possible to add a list to a list...

**Paste the Hedy code & level**
Level 3

When trying to print a list, Hedy gives an error about not being able to print a list.
```
list is appel, peer
print list
```

The following code allows printing a list
```
list is appel, peer
sublist is chocolade, frieten
add sublist to list
remove appel from list
remove peer from list
print list at random
```

**Comment by Felienne** [comment]
As discussed, not really something that matters for us at this point
