### ISSUE TITLE
👪 Write a small article for Wiki kids about Hedy

### ISSUE THREAD

**Issue by SabinaChita** [hedyorg/hedy#4273]
@SabinaChita will make a first draft for a short article for wiki kids (https://wikikids.nl)

**Comment by MarleenGilsing** [comment]
There already seems to be a Wikikids about Hedy https://wikikids.nl/Hedy_(programmeertaal) 
The English version of wikikids (vikidia) seems super sketchy (has a random Hitler image on the front page), so I don't think we need an article there.
