### ISSUE TITLE
[COMS] Create translators newsletter 

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#4274]
Let's make a newsletter for translators to keep them up to date!

**Comment by Felienne** [comment]
Hi @SabinaChita!

We just made a new page (/subscribe) that will be live soon, so we can get started on this! Translators that will subscribe will now have a Translator tag.

Steps:
* Cross check the list that I send with Weblate translators manually, and give everyone on that list and in Mailchimp the tag
* Make a first newsletter to tell people 1) the newsletter now exists, 2) there is a Discord for them 3) We have a brand new wiki!

**Comment by SabinaChita** [comment]
[like]  Chiță, S.M. (Sabina) reacted to your message:
________________________________

**Comment by Felienne** [comment]
Done!
