### ISSUE TITLE
[BUG] Support Bulgarian quotes

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#4313]
A new form of quotes that we don't support yet!

`принтирай „Здравейте!“`

<img width="736" alt="image" src="https://github.com/hedyorg/hedy/assets/1003685/821e0bd0-f752-464e-a8e3-8cf245fb07e0">

**Comment by Felienne** [comment]
A good first step for this issue is to add a test, like this one:

https://github.com/hedyorg/hedy/blob/9af04472d785a81cafd742a6cad1bba26ae489a6/tests/test_level/test_level_04.py#L29

but containing this code:

```
print „Здравейте!“
```

After that, fixing this will involve changing this regex to include the new quotes: https://github.com/hedyorg/hedy/blob/9af04472d785a81cafd742a6cad1bba26ae489a6/grammars/level4-Additions.lark#L30

and add the quotes here too:
https://github.com/hedyorg/hedy/blob/9af04472d785a81cafd742a6cad1bba26ae489a6/hedy.py#L1457C15-L1457C15

**Comment by quinnah** [comment]
Hello! I'd like to give a try at this

**Comment by Felienne** [comment]
> Hello! I'd like to give a try at this

That would be lovely! Let us know if the outline above is not enough to help you get started!

**Comment by quinnah** [comment]
@Felienne I created a PR, would love feedback!
