### ISSUE TITLE
[BUG] Code in quiz level 14, question 8 is incorrect

### ISSUE THREAD

**Issue by r0the** [hedyorg/hedy#4324]
**Describe the bug**
The code in question 8 of the level 14 quiz is incorrect. Since 1 proves to be correct answer, the `print` statements in the if and else clause should be switched:

```python
length = ask 'Please fill in your length in cm'
if length > 120
    print 'Enjoy the ride'
else
    print 'Sorry, you cannot go on this roller coaster.'
```
![Bildschirmfoto 2023-05-31 um 14 57 47](https://github.com/hedyorg/hedy/assets/1057839/27f9d036-7743-4252-b2d7-0e19f2990673)

**Comment by Muhammadummerr** [comment]
Do I need to change it in all language files or only for English, and that it will automatically update in all the other language files?
