### ISSUE TITLE
[BUG] Filtering students programs returns My Programs Page

### ISSUE THREAD

**Issue by jpelay** [hedyorg/hedy#4346]
Reported by Zenior on the Discord page:

> If I choose one of my students from the classlist to see their programms, this seems to work, but as soon as I select a level (15 in my case), this screen changes into MY programms.

This happens when you try to filter by adventure too.

**Comment by jpelay** [comment]
> ne of my students from the classlist to see their programms, this seems to work, but as soon as I select a level (15 in my case), this screen changes into MY programms.

Yes!

**Comment by Felienne** [comment]
Same here, maybe @hasan-sh oe @Annelein could also pick this one?
