### ISSUE TITLE
[UI idea] Don't show every adventure in the Explore Programs filter

### ISSUE THREAD

**Issue by jpelay** [hedyorg/hedy#4347]
When you are in a students page, looking at their programs, every adventure is shown, I think we should only show the adventures for that level:

![image](https://github.com/hedyorg/hedy/assets/45865185/5b90615a-5e23-4fe3-9159-0e40ba37e6ef)

**Comment by TiBiBa** [comment]
This is a legacy issue as originally we had the same adventure in each level. But agree that this should be improved.

**Comment by Felienne** [comment]
> This is a legacy issue as originally we had the same adventure in each level. But agree that this should be improved.

Did we ever have that? That must be a long time ago :) Do you want to pick this up @jpelay?

**Comment by Felienne** [comment]
I think maybe @hasan-sh or @Annelein could also pick this one (since @jpelay has a lot to do already)

**Comment by Annelein** [comment]
@jpelay this is currently already solved right?

**Comment by jpelay** [comment]
> @jpelay this is currently already solved right?

It is! But now the programs page is failing, see #5559
