### ISSUE TITLE
[BUG] variable names interpreted in string literals before they are defined with `is`

### ISSUE THREAD

**Issue by jurgenvinju** [hedyorg/hedy#4376]
Hello there; thanks for making Hedy! ♥️

**Describe the bug**

This is from memory, so excuse a few slipups. It's a simple scenario. 

We were in level 2 where we printed something that contained a variable name that is introduced later.

It was something like this:
```hedy-2
print some thing is funny
thing is ask something funny
```

* The error message will highlight the first line and a missing variable `thing`. 
* If you remove the second line, the first line will work again.

I'm not sure what design solution fits level 2 best. Also we haven't tried on other levels; we're not there yet 😎

**Comment by Felienne** [comment]
Thanks for the suggestion @jurgenvinju!

This indeed causes an error, this one:

<img width="630" alt="image" src="https://github.com/hedyorg/hedy/assets/1003685/c6a87ba4-c7cd-4a26-83d4-adb0b0b35fbc">

We could, with a bit of work, silently allow the use of `thing` in lines before the assignment, but the reason we currently don't is that we also want to stress that the program is executed top to bottom. Allowing your program would also allow this program:

```
print name
name is Harry
```

Which likely is not a convenient mistake like your example, but a fundamental misunderstanding of the working of textual programming (it represents the "Excel mental model", where I would be able to do A1=A5, A5="Felienne" even though A5 is below A1.). To overcome that confusion, we choose the error as we have it now.

Would love to hear what you think is the best solution!

**Comment by jurgenvinju** [comment]
Thanks for explaining the point about the Excel mental model. Good point! We did not have that since David does not use Excel yet, and I'm also more of a textual programmer.

* Maybe it would help to **highlight** (or underline) all the interpolated variable names; since we did not realize we were **using** the same word twice for different things. Now all the words just look the same. 
* "You tried to use the variable ..." is not true, so we were put off a bit. Perhaps in this instance the error message could be more specific to the situation. `"We interpreted a word ("this") as a variable on line 1, but you only set it on line 2"`, or something in that vain?

Just thinking out loud here ;-) I'm not the expert on learnable languages.

**Comment by Felienne** [comment]
> * Maybe it would help to **highlight** (or underline) all the interpolated variable names; since we did not realize we were **using** the same word twice for different things. Now all the words just look the same.

We have an almost finished PR open that just that: https://github.com/hedyorg/hedy/pull/3988 But we still need to expand that a bit more :) 

> "You tried to use the variable ..." is not true, so we were put off a bit. Perhaps in this instance the error message could be more specific to the situation. "We interpreted a word ("this") as a variable on line 1, but you only set it on line 2", or something in that vain?

I like that idea! Maybe even:  "We interpreted a word ("this") as a variable on line 1, *because* you set it on line 2"

> Just thinking out loud here ;-) I'm not the expert on learnable languages.

Np, we love feedback of real users (rather than hypothesised issues!)

**Comment by jurgenvinju** [comment]
> I like that idea! Maybe even: "We interpreted a word ("this") as a variable on line 1, because you set it on line 2"

That would be true, and helpful message indeed. Nice.
