### ISSUE TITLE
[UI idea] profile page should say "their programs"

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#4377]
If you navigate to a profile, the header says: "My programs"

but they are not mine, they are the programs of the user I am looking at! 

This is probably a simple po-file issue!

<img width="1469" alt="image" src="https://github.com/hedyorg/hedy/assets/1003685/c3dee9ae-fd7b-4ac7-8195-8346d2088331">

**Comment by YanRui-Lv** [comment]
Would you please assign this task to me? I'm a beginner and i want to have a try.

**Comment by Felienne** [comment]
> Would you please assign this task to me? I'm a beginner and i want to have a try.

Absolutely feel free to pick this up!

My suspicion that that this is the offending line:

https://github.com/hedyorg/hedy/blob/644318414d59866eaac6e691fd930fff11607af1/templates/public-page.html#L86C27-L86C41

And the solution would be to use the key `programs` instead.

Hope that helps!

**Comment by Felienne** [comment]
"Programs" is fine, especially since we already have a key for it!

**Comment by Felienne** [comment]
Closed by #4387
