### ISSUE TITLE
[BUG] Reset adventures button not working

### ISSUE THREAD

**Issue by jpelay** [hedyorg/hedy#4385]
After #4303, when we changed the names of several templates, the Reset adventures button in the customizations isn't working.

**Comment by Felienne** [comment]
Hi @jpelay!

I want to reproduce this issue but I am not really sure how it is currently broken, so it is hard to know if #4386 fixes it. Can you detail the brokenness? Thanks!

**Comment by Felienne** [comment]
Ah yeah I see:

<img width="985" alt="image" src="https://github.com/hedyorg/hedy/assets/1003685/de55d57b-4bf5-47f0-9cb6-fff12665054b">

Will check if this PR fixes it for me!
