### ISSUE TITLE
[BUG] Skipping mistakes does not work anymore

### ISSUE THREAD

**Issue by ToniSkulj** [hedyorg/hedy#4393]
For some reason, skipping mistakes, merged in #4320 does not work anymore in main.
Currently, when a mistake is made it only results in the following error:
![image](https://github.com/hedyorg/hedy/assets/48225550/e2995c26-8978-4da2-97b7-da9bd858f50e)

The function did work after #4368 in alpha (from what i can remember)

**Comment by ToniSkulj** [comment]
Reverting #4341 does seem to fix the problem. It think it may just be a difference in front-end that breaks the previous implementation. 

![image](https://github.com/hedyorg/hedy/assets/48225550/05d60e80-35de-45d4-83ba-1e0c93b89264)

**Comment by jpelay** [comment]
This is also pretty important since we can't deploy until this is fixed
