### ISSUE TITLE
[UI idea] Should we skip a line if there is only one?

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#4404]
f.e. this program:

<img width="737" alt="image" src="https://github.com/hedyorg/hedy/assets/1003685/ad1036f7-6ede-4a9e-a821-83c841639e70">

Does it make sense to skip the line here? I would propose to just give the error in case we have one line with an error, that saves a click and is more clear. What do you think @jpelay and @ToniSkulj?

**Comment by ToniSkulj** [comment]
Hi @Felienne!

Sorry for the late response, I think this is a great idea and not too difficult to implement!
I will cook up a PR this weekend for this.
