### ISSUE TITLE
[BUG] A weird issue in skip line!

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#4412]
It seems skip line is causing issues on main (I am hearing from teachers) so I will be rolling it back shortly.

The issue is hard to reproduce, but it seems sometimes you get an error message from another program, like this:

<img width="694" alt="image" src="https://github.com/hedyorg/hedy/assets/1003685/cec1600e-bab6-45e7-b22a-08c3ea0d4a17">
 
or:

<img width="700" alt="image" src="https://github.com/hedyorg/hedy/assets/1003685/68c3a417-c83c-418f-a7f0-934f3734b744">

**Comment by Felienne** [comment]
I am quite puzzled that this is happening. My best hunch is that this has to do with the fact that we are running a few processes of Hedy concurrently and somehow they get access to each other's programs? 

I can't easily reproduce it on alpha or locally at all, making it harder to figure out what is going on (but strengthening my belief that it has to do with traffic and processes on main.

**Comment by Felienne** [comment]
Hopefully @ToniSkulj or @jpelay can dive in? 🙏

**Comment by ToniSkulj** [comment]
> Hopefully @ToniSkulj or @jpelay can dive in? 🙏

Will do! I will start to investigate if/how I can reproduce the issue.

**Comment by Felienne** [comment]
> > Hopefully @ToniSkulj or @jpelay can dive in? 🙏
> 
> Hi @Felienne, Will do! I will start to investigate if/how I can reproduce the issue.

Thanks! The best way to reproduce I have now is to click around with erroneous programs a bit until inevitably you'll get an error belonging to another program. But not on main cause that has been rolled back now.

**Comment by ToniSkulj** [comment]
> I'm currently looking into this issue, I managed to reproduce it quite easily on Alpha. I'm looking at the logs to see what's happening.

That's amazing @jpelay!! I have been trying for hours but I can't seem to reproduce it on Alpha. Let me know if you find anything and if I can help.

**Comment by Felienne** [comment]
> I'm currently looking into this issue, I managed to reproduce it quite easily on Alpha. I'm looking at the logs to see what's happening.

Great! I certainly would love to keep the feature in in the long run!

**Comment by jpelay** [comment]
Apparently I spoke too soon :crying_cat_face: haven't been able to reproduce it ever since.

**Comment by jpelay** [comment]
> It seems skip line is causing issues on main (I am hearing from teachers) so I will be rolling it back shortly.
> 
> The issue is hard to reproduce, but it seems sometimes you get an error message from another program, like this:
> 
> <img alt="image" width="694" src="https://user-images.githubusercontent.com/1003685/259502086-cec1600e-bab6-45e7-b22a-08c3ea0d4a17.png">
> or:
> 
> <img alt="image" width="700" src="https://user-images.githubusercontent.com/1003685/259501854-68c3a417-c83c-418f-a7f0-934f3734b744.png">

Felienne, I noticed something here: the error marker in the second line of the first image. The Skip Line feature prevents that, because there was some code involved in the display of errors. Is there a possibility that this error was present before this feature?

**Comment by jpelay** [comment]
I did it again folks!!!! 

Some info on the enviroment: Vivaldi last version (Chromium browser), same user in Hedy Alpha, different levels: top editor is level 10, bottom is level 5. Same session on both windows.

![image](https://github.com/hedyorg/hedy/assets/45865185/097f2d82-8e70-468f-851c-148c381dbea6)

**Comment by jpelay** [comment]
Some further developments, and good news. I managed to reproduce the error locally.

![image](https://github.com/hedyorg/hedy/assets/45865185/7c9615db-4051-43bc-b186-c5dd60416829)

Just add a small delay to the server, say 2 seconds, and run two programs at the same time. With this in mind I think we can approve  #4413 and start working on this issue.

**Comment by Felienne** [comment]
Ah thanks for the great detective work @jpelay!! Must have been quite a puzzle! Maybe with the new info @ToniSkulj will have an idea of the root cause?

**Comment by ToniSkulj** [comment]
Amazing work @jpelay!! Thank you so much for this! I will dive into the code this evening and try to fix it, I have a hunch that it may have a correlation to the reposting of the code when a mistake has been caught.

**Comment by jpelay** [comment]
> Amazing work @jpelay!! Thank you so much for this! I will dive into the code this evening and try to fix it, I have a hunch that it may have a correlation to the reposting of the code when a mistake has been caught.

Thanks! Yes, that's also my hunch. It only happens after it retries the compiling phase so maybe that's the cause!
