### ISSUE TITLE
[FEATURE] Show translation switcher for some users

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#4420]
In https://github.com/hedyorg/hedy/pull/3327 we made it so that only the admin sees the translation option in the editor:

<img width="721" alt="image" src="https://github.com/hedyorg/hedy/assets/1003685/f6d38d25-604e-4245-ba52-58ddaf3817fe">

But @Mark-Giesen would like to use it as a teacher also. I am open to the idea but the reason we removed it was that it is a bit much to show for student users. I would prefer an option in your profile to enable this (maybe only visible for teacher users) 

What do you all think?

**Comment by Felienne** [comment]
Ow and I see now that the switcher gives an error (I don't use it so often).

<img width="888" alt="image" src="https://github.com/hedyorg/hedy/assets/1003685/1e9955be-b2e4-4d41-9c26-26153fc43cad">

Might be due to the new interface for the editor (#4339)? Of course that will also need to be fixed before we release it.

**Comment by Mark-Giesen** [comment]
There is another option, which is still available to all: the language selector in the cheatsheet. Was this meant as a replacement for this switcher in the editor, or are the use cases different?
We discussed a similar feature once: change the created code into generic code, so replacing all commands with the {} placeholders. This way translators could easily try code and once ready, transform it without typos into YAML text. These options might be combined by having three options available for certain people/settings: EN/selected/generic languages.

**Comment by Mark-Giesen** [comment]
See #2573 for the feature mentioned above.

**Comment by Felienne** [comment]
After more discussion with @Mark-Giesen, we have a plan forward!!

The keyword switcher, that we already support:

<img width="1275" alt="image" src="https://github.com/hedyorg/hedy/assets/1003685/9b7aa5a1-9704-4737-90ca-e449eda08d8b">

should just *also* translate the code in the code box. In essence I think this is a simple fix, which could be done more or less like this:

* Remove the switcher for the admin (see #3327 that removes it for all other users)
* Make sure the UI does not switch to the first tab (I do not know what causes this, we can also do that separately) 
* Call translate_keywords() on the program in the editor

Maybe @Mark-Giesen would like to pick this up (I think it is easier maybe than the yaml generator)

**Comment by Mark-Giesen** [comment]
> Maybe @Mark-Giesen would like to pick this up (I think it is easier maybe than the yaml generator)

I'm happy to take on both, but it will take some weeks before I have some spare time. End of first quarter coming up, some work deadlines to consider.

**Comment by Felienne** [comment]
No rush!! Happy to see your contribution when you have time.

**Comment by Felienne** [comment]
We discussed this in the meeting today and we have a path forward:

This is what I mean with the top switcher:

![Image](https://github.com/hedyorg/hedy/assets/1003685/ec661a56-7935-47da-b852-0c5889b303ac)


* Make the top switcher translate the program too (Felienne can pcik that up, she thinks haha)
* Remove the switcher in the editor
* Show the top switcher, also when people are logged in, so they can use the button to switch it
* Rename the top switcher, so that it does not show the translation emoji, but the current keyword language (so: `en` or `nl`)

**Comment by Felienne** [comment]
I wil do a few first steps and check back in if I need help
