### ISSUE TITLE
[BUG] Change color of some text so it's readable

### ISSUE THREAD

**Issue by MarleenGilsing** [hedyorg/hedy#4423]
![image](https://github.com/hedyorg/hedy/assets/80678586/c8e91976-ce5c-493b-a2b9-065d7b282ea9)
In the 'create your own adventure' section of the for teachers page the text that explains what to type is white and so is the background. This makes it unreadable.

**Comment by Felienne** [comment]
Ah good catch @MarleenGilsing! I fixed it
