### ISSUE TITLE
[CONTENT] Error in source string (Translation in Weblate)

### ISSUE THREAD

**Issue by Kamborio15** [hedyorg/hedy#4440]
**Describe the issue**
I am translating Hedy to Spanish and I have found one error in a source string.
In Quizzes component, in English language, the source string in `levels->9->7->mp_choice_options->[3]->feedback` is in Dutch instead of English. 
https://github.com/hedyorg/hedy/blob/1ba3e8750a55f2be4a7160caa30b21930a267095/content/quizzes/en.yaml#L2000C1-L2000C1
It says `Bijna goed maar kijk eens naar die laatste regel.`.
(from DeepL it would be translated as `Almost right but look at that last line`).

Reviewing from other translated languages I don't know how to translate it correctly to Spanish, e. g. from German is translated as `Du bist sehr gut, aber du musst dich an die letzte Regel halten.` but this string doesn't make sense in Spanish.

I have translated all components (do not tell my boss) but Webpages which I will do the next. In Quizzes this is the only string I am missing to complete it to 100%

**Add a screenshot (optional)**
![image](https://github.com/hedyorg/hedy/assets/28843833/6027f1d1-0a3d-4c5b-b672-b3495d4f59d5)

**Expected text**
What should we write instead?
I don't know a proper translation from other languages, I need it to be in English to do it

**Comment by Felienne** [comment]
Hi @Kamborio15!!

> **Describe the issue** I am translating Hedy to Spanish and I have found one error in a source string. In Quizzes component, in English language, the source string in `levels->9->7->mp_choice_options->[3]->feedback` is in Dutch instead of English. https://github.com/hedyorg/hedy/blob/1ba3e8750a55f2be4a7160caa30b21930a267095/content/quizzes/en.yaml#L2000C1-L2000C1 It says `Bijna goed maar kijk eens naar die laatste regel.`. (from DeepL it would be translated as `Almost right but look at that last line`).

Great find! I am tagging @MarleenGilsing our main content editor, she can fix that!

> Reviewing from other translated languages I don't know how to translate it correctly to Spanish, e. g. from German is translated as `Du bist sehr gut, aber du musst dich an die letzte Regel halten.` but this string doesn't make sense in Spanish.

The sentence means:

"Almost correct, but check out the last line" I hope that helps! 

> I have translated all components (do not tell my boss) but Webpages which I will do the next. In Quizzes this is the only string I am missing to complete it to 100%

THANKS YOU!! Are you in the Discord yet? We'd love to chat with active translators!!

**Comment by MarleenGilsing** [comment]
Fixed it with #4483
