### ISSUE TITLE
[UI idea] Change the puzzle interface to make dragging easier

### ISSUE THREAD

**Issue by MarleenGilsing** [hedyorg/hedy#4442]
As I'm working on making more puzzles I notice how it's quite a hassle to drag the lines of code to the input screen. Especially if the codes are getting longer. 

Is it maybe possible to put the lines where you have to fill in your answers next to the place where they start? (Like in the mock-up I made below)
![image](https://github.com/hedyorg/hedy/assets/80678586/d240ae49-7d75-4979-bcb2-d65ac4398623)

This would make it much easier to drag the answers, but it might mean we need an extra button (or two) to get the code from the "answer place" to the input screen. I do think it might be a nice touch if the kids could see the lines from the puzzelcode into real code (so without the seperation between the lines.

**Comment by jpelay** [comment]
I like this!

So to be clear with the requirement, you mean like a preview of the resulting code into a real read-only editor that the kids can execute it and see it a little bit better?
Something like this?

![PXL_20230903_220916912~2](https://github.com/hedyorg/hedy/assets/45865185/708e96e5-fb12-4c67-aeea-7e7bd81925e8)

I was also thinking that maybe we could make the UI a little bit more puzzle-like, with the pieces having a little bit more depth and the places where you put them look like little holes where you put the pieces.

**Comment by MarleenGilsing** [comment]
Yes! That looks perfect!
