### ISSUE TITLE
[BUG] Flaky Cypress Tests

### ISSUE THREAD

**Issue by jpelay** [hedyorg/hedy#4455]
**Describe the bug**
In [this job ](https://github.com/hedyorg/hedy/actions/runs/6076542251/job/16484723178?pr=4435)there were 2 failing Cypress unrelated to what's being done in that PR. When I rerun the tests again on GH and local they worked again, so I'm making this issue as a note to self to investigate this.

The two failing tests are the following:
[BUG] Flaky Cypress Tests
 
```
1 failing

  1) Is able to download login credentials
       "before each" hook for "Passes":
     CypressError: Timed out retrying after 4000ms: `cy.type()` failed because this element is not visible:

`<strong id="username" class="inline-block w-1/2 px-2">teacher1</strong>`

This element `<strong#username.inline-block.w-1/2.px-2>` is not visible because its parent `<div#profile-change-body.profile-section-body>` has CSS property: `display: none`

 Running:  for-teacher_page/class_page/logs_page/search_button.cy.js                     (82 of 84)


  Is able to press the search button
    1) Passes
Cannot find coverage file /home/runner/work/hedy/hedy/tests/.nyc_output/out.json
Skipping coverage report


  0 passing (10s)
  1 failing

  1) Is able to press the search button
       Passes:
     AssertionError: Timed out retrying after 4000ms: Expected to find element: `.view_class`, but never found it.
      at Context.eval (webpack:///./cypress/e2e/for-teacher_page/class_page/logs_page/search_button.cy.js:10:7)


```

**Paste the Hedy code & level**
It is super helpful if we can copy-paste the Hedy code to test, so please paste the code here, and don't forget to tell us what level you were in.

**Add a screenshot (optional)**
Make a picture or screenshot to show the issue. Tip! You can make a screenshot and simply paste the image into GitHub with ctrl-v.

**What machine and browser you were using (optional)**
If the issue concerns things in the website, let us know:
- What computer you are using (Windows, Mac, Linux?)
- What browser you were using (Chrome, Edge, Safari)

**Comment by jpelay** [comment]
The test in the file `editor_box.cy` inside the `describe` Test editor box functionality` are constantly failing. We need to remove them for now, and then keep working on them.

**Comment by Felienne** [comment]
#4529 might have fixed some issues, but there still is a weird flaky test in the test for creating a class (if I see it occur, I will add more details here) So we need to keep this open for now.

**Comment by Felienne** [comment]
Here it is again in #4581 

<img width="872" alt="image" src="https://github.com/hedyorg/hedy/assets/1003685/c9baa752-1fac-4962-8c4f-53b0eddb5304">

https://github.com/hedyorg/hedy/actions/runs/6392606011/job/17350202761?pr=4581

@jtwaleson if you feel like diving in, this is an annoying issue (unrelated to your work in #4581, it happens occasionally and we don't know why)

**Comment by jtwaleson** [comment]
I'll pick it up next. Spent a bit too much time on the project in the last week :upside_down_face:
