### ISSUE TITLE
[CHORE] Remove old stats page and logs

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#4475]
In #4474 we remove calls to a lot of backend code that we used to create stats and query logs. This should be removed because it has been replaced by the new dashboard (and the logs were actually only used ever by me, and I can also query the real DB).

How to get started with this issue:

* Python: The calls we have removed call the routes `/stats/class/` and `/logs/class/`, so you could search the Python code and find references to these. They are in statistics.py, but note that that file also contains routes related to the grid, which *is* still in use
* Typescript: I know there is also code in the front-end to render graphs, but I am not 100% sure where. Figuring that out is step 2 :)

**Comment by Felienne** [comment]
Hi @jtwaleson!

This too could be a nice issue to pick up, which is also going to remove a lot of front-end code, so will help you get a better grasp on things in the js/ts world

**Comment by Felienne** [comment]
> > * Typescript: I know there is also code in the front-end to render graphs, but I am not 100% sure where. Figuring that out is step 2 :)
> 
> This code lives in `statistics.ts`, which also contains code for the new grid that is in use.

Ah thanks! So we need to take a bit of care in removing the relevant stuff.

**Comment by jtwaleson** [comment]
Great, I'll take a look in the next couple of days :) Thanks for the context @jpelay .

**Comment by jtwaleson** [comment]
@Felienne @jpelay That was a bit of a struggle, but I think it's nearly done. Could one of you take a look and see if this is the right direction? See my branch here: https://github.com/jtwaleson/hedy/tree/4475-remove-admin-stats-preview 

I didn't include the compiled typescript and css yet, but it does compile fine and seems to run fine locally. BUT: I don't have the production statistics and locally there is not a lot of data, so I can't see with the `teacher1` account whether all the stats work.

**Comment by Felienne** [comment]
> @Felienne @jpelay That was a bit of a struggle, but I think it's nearly done. Could one of you take a look and see if this is the right direction? See my branch here: https://github.com/jtwaleson/hedy/tree/4475-remove-admin-stats-preview
> 
> I didn't include the compiled typescript and css yet, but it does compile fine and seems to run fine locally. BUT: I don't have the production statistics and locally there is not a lot of data, so I can't see with the `teacher1` account whether all the stats work.

Ah cool @jtwaleson! Have you tried the local test db, it is small but it has a few runs. Can you make a draft PR out of your branch, that makes it easier to look at your code and run it locally.

**Comment by jtwaleson** [comment]
> Ah cool @jtwaleson! Have you tried the local test db, it is small but it has a few runs. Can you make a draft PR out of your branch, that makes it easier to look at your code and run it locally.

Yes, I did the local run but I'm not 100% sure that what I'm looking at makes sense yet :)

Here's the draft of the PR : https://github.com/hedyorg/hedy/pull/4505 .

BTW I created some notes about local accounts that I'd like to add to the wiki too near the docker section.
