### ISSUE TITLE
[CONTENT] Can I alphabetize the adventures?

### ISSUE THREAD

**Issue by MarleenGilsing** [hedyorg/hedy#4488]
The adventures are in a random order now, but can i alphabetize them (to help me find adventures slightly quicker and just because it would look prettier) or does this cause more harm than good?

I could obviously do this myself, but i dont know if it will cause chaos and might interfere with other PRs.

**Comment by jtwaleson** [comment]
@MarleenGilsing I'm not 100% sure if this is what you meant, but I believe this now solved with the YAML autoformatter. If so, we can close this issue.
