### ISSUE TITLE
[BUG] Weird error when separating if and else by multiple new lines in level 5

### ISSUE THREAD

**Issue by jpelay** [hedyorg/hedy#4495]
I'm not sure whether we should allow this or not, but I think this error is not very helpful and is also not what's happening here!

![image](https://github.com/hedyorg/hedy/assets/45865185/f3841c31-7507-4c22-a6f4-f2ea8e7427e4)

**Comment by Felienne** [comment]
Haha, nice find! Surely not how we want it. This is an artefact of the level 5 transpiler, I will fix it.
