### ISSUE TITLE
[CONTENT] Incorrect content in adventures in level 17

### ISSUE THREAD

**Issue by jpelay** [hedyorg/hedy#4497]
**Describe the issue**
In level 17, in English, the Introduction adventure says: 
> You have almost reached the last level of Hedy, well done! In this level you will learn a real Python way to use `print`.

But in level 17 there are no changes being made to that command. Also a `print` adventure is included, but rather than explaining something related to `print` it introduces the colon:

![image](https://github.com/hedyorg/hedy/assets/45865185/2ed8d61a-2324-44a7-bd21-eb217db1f13a)

I think this is an issue for @MarleenGilsing?

**Comment by MarleenGilsing** [comment]
Good catch! Fixed it in #4519
