### ISSUE TITLE
[BUG] Going to the level after failing the quiz, blocks the level

### ISSUE THREAD

**Issue by jpelay** [hedyorg/hedy#4507]
**Describe the bug**
Reported by user VeronW on the Discord server:

> I have found another bug  Kids are great bug-hunters haha
>
> I asked the children to do the level 1 quiz before going to level 2. And one kid got a too low score to continue. Instead of clicking on try the quiz again he clicked back to home to get to the level again. He then got a message that his quiz score was too low. There is no way to avoid this error message apart from lowering the score treshold to the score that he got. 
>
> To reproduce:
> * Make a new account
> * Play the quiz, make a lot of errors
> * Do not click on try the quiz again but go back to the level

I was able to reproduce this error locally using the steps indicated above.

**Comment by Annelein** [comment]
@jpelay I am not able to reproduce this issue anymore, can you still? Otherwise it might be fixed already?

**Comment by Felienne** [comment]
Is already fixed!
