### ISSUE TITLE
[CONTENT] How fast is your release/build cycle of the website?

### ISSUE THREAD

**Issue by yilmazdurmaz** [hedyorg/hedy#4510]
**Describe the issue**
I am translating Hedy into Turkish. I finished the most important parts: Keywords, Adventures, Parsons.

I would like to see/check them live on the site. The last update has "2023 Sep 12(40ea28)", just a day before I started. It is already a week now.

Can you please tell me how long I should wait to see my translations in effect?

**Comment by Felienne** [comment]
Hi @yilmazdurmaz!

Thanks for the amazing work on Turkish, we have been seeing in roll in over the weekend and we were in awe of your speed!

However, to keep things manageable, may I please ask you to place such questions in Discord (https://discord.gg/8yY7dEme9r), this is not an issue to be solved but a question to be answered. Submitting issues for these is somewhat disruptive of our workflow.

Our translation workflow is documented in our Wiki: https://github.com/hedyorg/hedy/wiki/Hedy-Translation-Tutorial#general-workflow

So you want to see your changes in action, you can immediately do so on the alpha environment. 

We typically release about once a week to hedy.org, but sometimes other changes are made in between the translations and there are reasons that we don't yet deploy. I will now check the open changes that we have, and deploy when I can do so safely.

I hope this helps!

**Comment by yilmazdurmaz** [comment]
@Felienne ,

I am happy to ask this question here, because Discord does not mean anything for some of us as much as you think. GitHub issues is, for example, the place I look for answers first. This one will help others like me.

This link: https://github.com/hedyorg/hedy/wiki/Hedy-Translation-Tutorial#general-workflow
and this alpha page: https://hedy-alpha.herokuapp.com/

For us translating contributors, these two you just give now are very important links. And, at least the wiki link needs to be included in other more visible "how to contribute translations" pages.

**Comment by Felienne** [comment]
> I am happy to ask this question here, because Discord does not mean anything for some of us as much as you think. GitHub issues is, for example, the place I look for answers first. This one will help others like me.

Fair enough, Discord is quite complex! Instead, email can be used: hello@hedy.org. I understand that you placed this issue here, that is no problem at all, since I understand that it was the first place you looked. But going forward, to keep things organized here, please use email.

> This link: https://github.com/hedyorg/hedy/wiki/Hedy-Translation-Tutorial#general-workflow and this alpha page: https://hedy-alpha.herokuapp.com/
> 
> For us translating contributors, these two you just give now are very important links. And, at least the wiki link needs to be included in other more visible "how to contribute translations" pages.

Absolutely! We just added that wiki link to hedy.org/join! Once we have deployed later this week it will be visible there. Are there any other places that you found that missed the link? Let me know and I will add it there too.

**Comment by yilmazdurmaz** [comment]
Thanks for taking your time

> Are there any other places that you found that missed the link? Let me know and I will add it there too.

There is one more place that will benefit greatly for these two links:
[Hedy info page on Weblate](https://hosted.weblate.org/projects/hedy/#information)

I don't know how frequent translators use this info page on Weblate, but I am sure having the links there will help newcomers, as they are (I was) trying to shoot first, ask later (we look into details after making some translations). We have very different backgrounds and each project we contribute to also has different workflows, so we try our best to adapt to them.

I am about to complete my first run (texts and quizzes are left) then I will try to understand your workflow, and also make edits (or give info) about typos or small errors like forgotten curly braces for keywords.
