### ISSUE TITLE
[CONTENT] wrong variable name

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#4515]
Mailtje van een docent:

```
Hallo,    

Totaal_prijs moet wel totaal-prijs blijven (i.p.v. totaal_price)  
Fastfood wordt wel erg goedkoop zo!     
```

![image](https://github.com/hedyorg/hedy/assets/1003685/a9055dc6-f6a9-4a3e-bb5b-db910423e86b)

**Comment by Felienne** [comment]
And there is a similar one in the quiz of level 13:

<img width="1150" alt="image" src="https://github.com/hedyorg/hedy/assets/1003685/5c1666b6-73c8-40d3-ba55-e60cfdcf1afa">

And in Q7 (cat -> kat):

<img width="203" alt="image" src="https://github.com/hedyorg/hedy/assets/1003685/86ab10e4-cc75-4e8e-9f59-1e0169d879cd">

Finally (not translation related) should 38 be in quotes here?

<img width="783" alt="image" src="https://github.com/hedyorg/hedy/assets/1003685/7d534941-6611-4d9f-92da-434a0ec1069a">

**Comment by MarleenGilsing** [comment]
Ook opgelost
