### ISSUE TITLE
[TRANSLATING] Add new wiki link to Weblate info

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#4517]
> Are there any other places that you found that missed the link? Let me know and I will add it there too.

There is one more place that will benefit greatly for these two links:
[Hedy info page on Weblate](https://hosted.weblate.org/projects/hedy/#information)

I don't know how frequent translators use this info page on Weblate, but I am sure having the links there will help newcomers, as they are (I was) trying to shoot first, ask later (we look into details after making some translations). We have very different backgrounds and each project we contribute to also has different workflows, so we try our best to adapt to them.

I am about to complete my first run (texts and quizzes are left) then I will try to understand your workflow, and also make edits (or give info) about typos or small errors like forgotten curly braces for keywords.

_Originally posted by @yilmazdurmaz in https://github.com/hedyorg/hedy/issues/4510#issuecomment-1727816142_

**Comment by yilmazdurmaz** [comment]
Hi @Felienne ,

Just to be sure, "two links" mentioned here are these two:

Link to translation tutorial wiki: https://github.com/hedyorg/hedy/wiki/Hedy-Translation-Tutorial

And the Hedy Alpha page: https://hedy-alpha.herokuapp.com/

**Comment by Felienne** [comment]
> Hi @Felienne ,
> 
> Just to be sure, "two links" mentioned here are these two:
> 
> Link to translation tutorial wiki: https://github.com/hedyorg/hedy/wiki/Hedy-Translation-Tutorial
> 
> And the Hedy Alpha page: https://hedy-alpha.herokuapp.com/

I added the tutorial to the Weblate page! Since the Wiki has the info about the alpha version, I left that out for now. Always a tight rope between too little and too much into. I am also working on a newsletter!
