### ISSUE TITLE
[CONTENT] What's the use of 'key' in the teacher manual?

### ISSUE THREAD

**Issue by MarleenGilsing** [hedyorg/hedy#4523]
In the teacher manual is the header 'key'used quite often I don;t know what it does. But if it's just a bookmark for us, we should tell the translators not to translate it, so we could easily navigate in documents that are in a foreign language. 

![image](https://github.com/hedyorg/hedy/assets/80678586/96def3b4-0e8d-4976-a8a6-b8b30e93a155)

**Comment by Felienne** [comment]
HI @jpelay!

Do you know this from the top of your head? If not, don't sweat it, I can look into it too!

**Comment by jpelay** [comment]
> HI @jpelay!
> 
> Do you know this from the top of your head? If not, don't sweat it, I can look into it too!

Nope, sorry! I don't know where that key might be used :c

**Comment by Felienne** [comment]
np! I will dive in!

**Comment by Felienne** [comment]
Ok, new update! The keys matter and it is nicer to translate them so the url will also be translated for other languages. So a bit more work for us sadly.
