### ISSUE TITLE
[BUG] foo.txt file appears in the repo - waiting for flask-commonmark to implement a fix

### ISSUE THREAD

**Issue by jtwaleson** [hedyorg/hedy#4540]
**Describe the bug**
A wild foo.txt file appeared in the root directory of the project. I removed it but it was re-added automatically due to a github workflow. After some investigation I found the source of the problem in the flask-commonmark package, and am waiting on getting an upstream fix in flask-commonmark merged. See https://gitlab.com/doug.shawhan/flask-commonmark/-/merge_requests/4

Note that this issue is NOT urgent at all. It just serves as documentation that this quirk exists for future contributors, and a reminder to update the package when a fix ever gets released.

**Comment by jtwaleson** [comment]
As the upstream library does not look to be actively maintained we can prevent this from happening by including it in the .gitignore file. This will ensure that the github actions that commit back to the repository do not include the file.

**Comment by jpelay** [comment]
Ohhhh, thanks for figuring out where that file came from! It made me crazy and I had no idea! 



> As the upstream library does not look to be actively maintained we can prevent this from happening by including it in the .gitignore file. This will ensure that the github actions that commit back to the repository do not include the file.

Yes, last commit is from 2 years ago, I don't think they're merging your fix anytime soon.

May I ask how did you manage to find where the file came from?

**Comment by jtwaleson** [comment]
I use the [silver searcher](https://github.com/ggreer/the_silver_searcher) for finding stuff. I ran `ag -ul foo.txt` (the -u flag searches EVERYWHERE, also in the dependencies, -l shows the filenames).
