### ISSUE TITLE
[CONTENT] Sort all yamls 

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#4541]
Text from #4484

Another thing that complicates adding new content or changes to (partly) translated files is that each file uses a different order of headings. For example: In English all the quizzes go from question 1 to 10, but some other files can go 1,5,3,2,8,9,10,7,6,4. In quizzes, this is not really a problem because you can still see the number so you know which heading this is. But in the teacher manual, all the headers are translated so you can't easily see which header is which. That makes it hard to make changes to the content. 

This same issue causes an issue in /slides (see #4480) now where the order is messed up and accidentally meaningful. So we should sort all yamls, not just the toplevel, but sublevels too. 

Maybe this can be done as a setting in Weblate? Or maybe we can run a script to do it once, because I think Weblate do keeps the same order. If we do it with a script in the repo (f.e. at build) we should test whether that does not mess up weblate.

**Comment by jtwaleson** [comment]
I looked into this a bit yesterday. Weblate has a sort_keys option but it seems to be only for JSON storage. We could move everything to JSON as it is quite a bit simpler than yaml, but I don't know enough about the translators to know if that would work for them. I believe some edit the files directly?

If we keep with YAML I believe this is something that can be automated (like flake8 / autopep8 but for the translation files). E.g. if you parse and re-write the yaml files you can save with `sort_keys=True` which will (hopefully) do what is needed. We can then auto-commit the fixes back just like the current autoformatters do.

As a bonus we could also check whether the `{keywords}` that are present in English are also present in all the other languages, either as warnings or as blockers.

Would that be an acceptable solution? Of course we would still need to check how Weblate deals with this and check where we have accidentally meaningful ordering.

Maybe these issues are not relevant here, but in a previous project I've also extended the translations linter to check:
1. Whether all the languages have the exact same set of messageids
2. Whether translation keys are actually found in the code (python, typescript and/or templates), to prevent translators spending their time on texts that are no longer used in the project.

Maybe those are not relevant to Hedy, but if so, we can consider implementing something like that.

**Comment by Felienne** [comment]
> I looked into this a bit yesterday. Weblate has a sort_keys option but it seems to be only for JSON storage. We could move everything to JSON as it is quite a bit simpler than yaml, but I don't know enough about the translators to know if that would work for them. I believe some edit the files directly?

They do indeed, and also an overhaul to JSON will be a lot of work and error-prone, so I am not enthusiastic unless it is really needed.
 
> If we keep with YAML I believe this is something that can be automated with a small script that we write ourselves (like flake8 / autopep8 but for the translation files). E.g. if you parse and re-write the yaml files you can save with `sort_keys=True` which will (hopefully) do what is needed. We can then auto-commit the fixes back just like the current autoformatters do.

This sounds perfect!

> As a bonus we could also check whether the `{keywords}` that are present in English are also present in all the other languages, either as warnings or as blockers.

Yes, that would be a great addition to the checks we have now.

> Would that be an acceptable solution? Of course we would still need to check how Weblate deals with this and check where we have accidentally meaningful ordering.

Let's see how Weblate deals with it when we sort.

> Maybe these issues are not relevant here, but in a previous project I've also extended the translations linter to check:
> 
> 1. Whether all the languages have the exact same set of messageids
> 2. Whether translation keys are actually found in the code (python, typescript and/or templates), to prevent translators spending their time on texts that are no longer used in the project.
> 
> Maybe those are not relevant to Hedy, but if so, we can consider implementing something like that.

1. We already do in the yaml-structure check. 2. Could be nice. I suspect that the extraction does that already, but we could check.

**Comment by Felienne** [comment]
So the first next step as I see it is to explore the script for yaml-sorting and leave the other points (1 and 2) for now.

**Comment by jtwaleson** [comment]
Ok please take a look. A couple of points to pay attention to:
- the script currently rewrites all translation yaml files (not .pot yet) in a deterministic way
- it uses some rules, which we can tweak as we want

Currently it does:
- strips leading and trailing whitespace (I'm not sure if "\n" at the end of some strings is intentional or not)
- re-orders dict keys using the default `sorted` method, hower if the `title` and `text` keys are present it will use those first
- it standardizes on 4 spaces indentation
- it standardizes on `|` syntax for multiline strings and "normal" unquoted syntax for single line strings

I believe this style is closest to what we had for English and Dutch, but like I said, we can tweak this however we want.

I'm not sure how to check how weblate will respond to this!

We can do the github workflow integration and pre-commit integration in this PR or in a follow-up.
