### ISSUE TITLE
[CONTENT] Improve gender balance in adventures

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#4548]
From Discord:

Teacher: I was playing around in Hedy to get to know it. When I did the 'story adventure' in level 1, I run the example code and filled in my own name (of course). The result is that "He's a bit scared, Annelies", which feels a bit... dissappointing(?). 

me: Thanks for your message! In a sense, this is intentional!! If you don't like the program, you can just change it! Kids should be encouraged to go into the program to change gender or other things. 

Teacher: Maybe a mix of pronounces would be an option. For now in the English version the first 7 stories are 6 male characters and 1 neutral and the last 4 stories are 3 female and 1 bear 😉 . The distribution is mainly like this because the first story is coming back in level 1 to 4. If it is not necessary to keep it exactly the same there is room to swap.

I think mixing gender a bit more is a great idea, we do not need the exact same program across levels in the story adventure. We can even encourage fixing the issue in the exercise description.

**Comment by yilmazdurmaz** [comment]
Some languages, like Turkish, are lucky in this gender topic as they do not use such pronouns.

Instead of trying to balance gender, it might be better to rework the content to be genderless as much possible by removing pronouns. It is for school teens first after all.

**Comment by Felienne** [comment]
> Some languages, like Turkish, are lucky in this gender topic as they do not use such pronouns.
> 
> Instead of trying to balance gender, it might be better to rework the content to be genderless as much possible by removing pronouns. It is for school teens first after all.


Yes some languages have it easier, but let's try to find a balance for languages that do have genders.

**Comment by MarleenGilsing** [comment]
Aanvullende opmerking van Leo van Learnbeat: 

Verder vind ik persoonlijk dat veel van de voorbeelden over onderwerpen gaan die vaak net wat meer bij jongens aansluiten. Het is natuurlijk een beetje een stereotypering, en er zijn genoeg meiden die bijvoorbeeld voetbal en/of superhelden ook leuk vinden, maar misschien is het een idee om de “stereotypes” wat meer samen te voegen. Het zijn hele kleine punten, maar ze kunnen wel helpen met wat meer representatie voor meisjes denk ik!
https://hedycode.com/hedy/5#parsons bij het rijtje met favoriete_films zou je bijvoorbeeld Barbie en Captain Marvel kunnen toevoegen
in de quiz van level 4 (vraag 9) staat een rijtje van beste voetbalclubs, in de quiz van level 5 (vraag 6) zullen vaak dezelfde clubs weer genoemd worden bij de voorspelling, misschien zou je in de quiz van level vier het kunnen aanpassen naar iets als:
voetballers is Beerensteyn, Spitse, Miedema, Martens  
 print ‘De beste voetballer is…’ voetballers at random
