### ISSUE TITLE
[BUG] Skip faulty shows that there was an error, even if the program is correct.

### ISSUE THREAD

**Issue by jpelay** [hedyorg/hedy#4562]
**Describe the bug**

When the user executes code, not always, but sometimes, the skip faulty feature shows an alert that there was an error with the program, even if there wasn't any:

https://github.com/hedyorg/hedy/assets/45865185/45b7a33f-2c11-4dec-84c2-b4906f72c0a4

**Comment by Felienne** [comment]
Fixed by #4564
