### ISSUE TITLE
[CONTENT] Confusing label for password reset

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#4568]
When you reset a password, the label says "password". Just got an email from a kid that thought they needed their old password to reset it! So this must be "new password" and maybe "repeat new password". I suspect these labels are shared with the signup page, do we will need new labels.

<img width="736" alt="image" src="https://github.com/hedyorg/hedy/assets/1003685/57e5ece1-0bbd-4b34-a595-7361cb5a6b49">

Steps to fix this would be:
* Add two new labels here: https://github.com/hedyorg/hedy/blob/77a2b4c40c065ec45e29fa084fd037cdd857660e/templates/reset.html#L9 and https://github.com/hedyorg/hedy/blob/77a2b4c40c065ec45e29fa084fd037cdd857660e/templates/reset.html#L13
* Extract the new labels with the extract script (see wiki)
* Translate the new labels to English

**Comment by devansh83** [comment]
Hello, so this is my first time contributing in a project and I had a small doubt. Sorry if it is really stupid but what do you mean by "Extract the new labels with the extract script". After changing the labels, what exactly do I need to do? I looked over the wiki but was unable to find a mention of any extract script. Again sorry if it is something trivial.

**Comment by yilmazdurmaz** [comment]
this "new_password" key is used on the profile page like this, with correct translation.

https://github.com/hedyorg/hedy/blob/77a2b4c40c065ec45e29fa084fd037cdd857660e/templates/profile.html#L164-L165

We may simply change the line 9 like this:
```
<label class="inline-block w-80">{{_('new_password')}}</label> 
```
But this is true only if we re-use keywords. On Weblate, I see only [1 string with "password" key](https://hosted.weblate.org/translate/hedy/web-texts/en/?checksum=1a2ba1eb3fee50c1), yet it is used on both "login" and "signup" pages. Then I will assume they are re-used.

@Felienne before moving further on the issue, can you please check if my statement holds? will this simple change be enough?

**Comment by Felienne** [comment]
Welcome to the project @devansh83!

The extraction script and some more details about translation keys are here: 
https://github.com/hedyorg/hedy/wiki/Hedy-Development-Process#adding-new-translation-keys

This explains how to preview the website locally if you have made a change:
https://github.com/hedyorg/hedy/wiki/Hedy-Development-Process#working-with-translations

Indeed you will not simply be changing the text, we need a new label, something like:

 `<label class="inline-block w-80">{{_('new_password')}}</label> `

We have a string for password, but that is already used in other places, so we can't just change the contents, we need to add a new name and then add content. And we can't just add a label "new" in front of if since some languages might have a different change (the order "password new", for example). Hope that helps!

**Comment by Felienne** [comment]
If you need more info, feel free to ask here, or join us on Discord!
