### ISSUE TITLE
[CONTENT] on "My programs" page, localization does not work for Adventure names

### ISSUE THREAD

**Issue by yilmazdurmaz** [hedyorg/hedy#4570]
When is "my programs" page, adventure names show their literal values without translations such as `{if} & {else}`
This happens at least for Turkish

adventure name shown on saved program
![Screenshot (4)](https://github.com/hedyorg/hedy/assets/1812105/8ea73652-4ce8-4a70-8acc-bfcde71127a3)

and adventure names in the dropdown list
![Screenshot (5)](https://github.com/hedyorg/hedy/assets/1812105/5567518b-956b-438b-8b2a-f2fb87ca87bb)

**Expected text**
Localization process should include these parts of the page and translate them. `{if} & {else}` would then be `eğer & değilse`

**Comment by Felienne** [comment]
Great find @yilmazdurmaz! We will look into this.

**Comment by yilmazdurmaz** [comment]
@Felienne I think this is the right time and place to mention and old issue, #4134. I guess it has been forgotten since it has a "UI-idea" label, but I think this also need attention at the same level as this one.

**Comment by Felienne** [comment]
> @Felienne I think this is the right time and place to mention and old issue, #4134. I guess it has been forgotten since it has a "UI-idea" label, but I think this also need attention at the same level as this one.

Yes, it could be fixed by the same code potentially. 

However, I want to ask you to communicate in the way as we ask in our Wiki. Saying that something is "forgotten" is not appropriate; almost all of us are volunteers and we work as hard as we can. Please understand that we are doing our best, and we do not have enough bandwidth to fix all issues as quick as we would all like. 

If you absolutely feel something needs attention, you are very welcome to create a PR for it yourself, and we are also happy to help you get started, if the wiki does not suffice in information.

**Comment by yilmazdurmaz** [comment]
> Saying that something is "forgotten" is not appropriate

Forgive my words of choices. I wasn't thinking of any offending meaning here. I had this in mind: the "common mistakes" part is another important bridge between teachers and students.

**Comment by Felienne** [comment]
Thank you! 

The connection between the issues indeed is meaningful and helpful! Likely we can tackle both with one PR. I will look at it when I have the chance (which will be after the weekend)

**Comment by yilmazdurmaz** [comment]
By the way, the common mistakes content would also be very useful to all students, especially to self-learners. Moving that section to its own page with visibility to all students may not only help all learners, but also help this keyword translation process.
Worth to consider later, but maybe before working on that page all together.
PS: I will make a duplicate of this sentence in the other issue as a reminder, for it mainly belongs there.
