### ISSUE TITLE
[CONTENT] Level 15 quiz question 8 uses while-else, but this is not introduced in Hedy

### ISSUE THREAD

**Issue by yilmazdurmaz** [hedyorg/hedy#4571]
**Describe the issue**
The question is this one
```
while toilet == 'occupied'
    lights = 'on'
    air_freshener_sprays = 'yes'
    sleep 60
else
    lights = 'off'
```

I thought this would be while to if correction, but the options has the meaning this one is actually a while-else code. (though misses line to leave the toilet). While-else is not introduced in any level.

This will require changes in the code and maybe in the options, so should be handled carefuly.

**Comment by Felienne** [comment]
Hi @yilmazdurmaz!

This is simply an issue in the quiz questions, we do not support while-else (and I don't plan to support it in the future).

**Comment by yilmazdurmaz** [comment]
Some simple editing suggestions to change only the code. I haven't cross checked with answers though.

Without lines asking to leave, this might do the job.
```
while toilet == 'occupied'
    lights = 'on'
    air_freshener_sprays = 'yes'
    sleep 60
lights = 'off'
```

Adding code asking to leave and set toilet status and lights.
```
while toilet == 'occupied'
    lights = 'on'
    air_freshener_sprays = 'yes'
    sleep 60
    answer = ask 'Leave?'
    if answer == 'yes'
        toilet = 'unoccupied'
        lights = 'off'
```
