### ISSUE TITLE
"student_details" holds no string to be used in "messages.po"

### ISSUE THREAD

**Issue by yilmazdurmaz** [hedyorg/hedy#4577]
Added with https://github.com/hedyorg/hedy/pull/4166 to be used in [templates/class-live-student.html](https://github.com/hedyorg/hedy/commit/7e2519792cd2f8001e095b0967fd80b8fb47aa3a#diff-645c5bd0c47460bd729a2d56e9c39bddc0f1ab5b09a2a0cd88a420bd27135a4e)

https://github.com/hedyorg/hedy/blame/82fd39a9e215246a37f652aef416bb1600d849db/translations/en/LC_MESSAGES/messages.po#L1546

"student_details" holds no string to be used

**Comment by Felienne** [comment]
Closed with #5022
