### ISSUE TITLE
[PERFORMANCE] cache grammar generation in production

### ISSUE THREAD

**Issue by jtwaleson** [hedyorg/hedy#4588]
This is a follow-up to #4581 . During the review it was noted that there can be some performance improvements to the caching of the grammar generation. We disabled the memory cache holding the parsers in production, making the `create_grammar` function the critical path of about 50ms (not 100% sure about the timing, please check this out!). As `create_grammar` create a simple string but takes some computational power, we can return that same string as long as there were no changes to the grammar files on disk.

Right now the implementation caches all the generated grammars to memory which results in about 10MB-30MB of per-process extra memory once all the permutations of levels and languages are hit. With more languages added in the future, this will increase. As we want to run with many worker processes on the production environment the per-process memory usage should be reduced to a minimum. We can use the disk as a cache instead, which will be cached to memory by the OS but this cache is shared across processes at the cost of a couple of syscalls.

It would be great if someone could create a simple solution for this, but I leave it up to others to determine the urgency.

**Comment by Felienne** [comment]
For now I think we are fine, there are a lot more pressing problems which can't be solved by money (contrary to this one)
