### ISSUE TITLE
[CONTENT] Update quizzes level 12 to 14 (or even 18) to contain functions

### ISSUE THREAD

**Issue by MarleenGilsing** [hedyorg/hedy#4596]
To do list for myself to do now that we have functions. I should:

- ~~Translate content to Dutch~~
- ~~Add functions to the slides.~~
- Add functions to the quizzes
- ~~Add functions in the other adventures in level 12 + (in all languages)~~
- ~~Add functions exercises to answer account.~~ (Not done but made a seperate issue)
- ~~Double check if all the new adventures are on the site.~~

**Comment by MarleenGilsing** [comment]
@Felienne Should this issue be closed? I haven't changed the quizzes. Or have you closed it because it's low priority?

**Comment by Felienne** [comment]
I have closed it because I don't want more energy to go to quizzes at the moment. I am trying to keep only issues open I want people to really pick up :)
