### ISSUE TITLE
[UI] Syntax highlighting variables

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#4599]
### Discussed in https://github.com/hedyorg/hedy/discussions/3929

<div type='discussions-op-text'>

<sup>Originally posted by **stevecopley** January 12, 2023</sup>
Can't find any prior mention of this in the discussions, so...

To aid understanding the concept of  user-created variables, it would be helpful to subtly highlight variables within print statements, so that they are visually different to the surrounding text. Students could then see that their variables are placed within the text.

</div>

**Comment by Felienne** [comment]
We had a PR open for this (#3988) which could be useful if we try this in the new CodeMirror system

**Comment by jpelay** [comment]
Yes, CodeMirror can parse the input using the [Lezer parser generator](https://lezer.codemirror.net). Hedy's syntax has some ambiguities: variables and text being one of them. However, Lezer also let's you build  an [external tokenizer](https://lezer.codemirror.net/docs/guide/#external-tokens) if the Lezer built in one won't suffice. I think this feature can be used to built a data structure where we store the variables, but I'm not 100% sure of this.

**Comment by Felienne** [comment]
It is not a high priority (since the don't have it now either) but it would be cool!! We could even highlight (with an error underline) undefined variables too!

**Comment by Felienne** [comment]
We have this now! <3
