### ISSUE TITLE
[UI] Remove pyGame variable from variable list

### ISSUE THREAD

**Issue by jpelay** [hedyorg/hedy#4601]
When you execute a program that has pyGame in it, the variable list view contains variables related to the pyGame: `pygame_end`, and `button_list`. I think we should probably remove them from there?

**Comment by Felienne** [comment]
Good catch @jpelay! 

This would be a pretty easy fix for a newcomer, just add the variables here: https://github.com/hedyorg/hedy/blob/a05c6c676f7786538a6206bf1ca27310121e3004/static/js/debugging.ts#L83. And test it our, of course!

**Comment by jpelay** [comment]
Also, a bit more information: when I say that a program has pyGame, it means that it uses the `is pressed` command! You can see examples of those programs under the Press it adventures!

**Comment by Yaups** [comment]
I'll be happy to take this one on if no one else has!

**Comment by youssefkaddachi** [comment]
hello @jpelay I'm trying to run the code with is_pressed command but the variables list doesnt show up in the terminal . can I get help with that ?

**Comment by Felienne** [comment]
Fixed already (I suspect because of the recent PyGame changes?)
