### ISSUE TITLE
[CONTENT] Small issue in yaml cleanup

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#4608]
The yaml sorter/cleanup is great, but there is something it does not yet cover well, I don't really know why. Let's look at the last Weblate PR, there is this commit, changing the indents to 2:

https://github.com/hedyorg/hedy/pull/4602/commits/9f55fafaae0896770eb22e9ae6e7531a33401ea3#diff-967ecf156bdb622fd3475e5dec8febe0d03c31c7f2958e447782df87be683345 (I also don't know why this indent is changed, what steps in Weblate lead to this change, why would a translator do this? But let's park that for now)

Then the cleanup commit comes in and adds 2 more spaces:
https://github.com/hedyorg/hedy/pull/4602/commits/d1c3ebdf9df0303dec34fcaed7dcfc50d39d137e#diff-967ecf156bdb622fd3475e5dec8febe0d03c31c7f2958e447782df87be683345

But now there are 8 spaces!

<img width="512" alt="image" src="https://github.com/hedyorg/hedy/assets/1003685/834e9267-3a9b-4620-b7a4-e9dce6d8e27d"> And then the tester thinks this is a code snippet and fails.

**Comment by yilmazdurmaz** [comment]
Observation: I don't know what the original purpose for having these `|2` and `|4` was, but they seemingly exist only in adventure files and there is none in the most recently(!) active adventure languages files: 
```
content/adventures/ca.yaml
content/adventures/en.yaml
content/adventures/es.yaml
content/adventures/nl.yaml
content/adventures/tr.yaml
```
