### ISSUE TITLE
[BUG] "bad input" error in French workspace for lists or "at random"

### ISSUE THREAD

**Issue by yilmazdurmaz** [hedyorg/hedy#4610]
**Describe the bug**

The code below is the fortune teller program from level 5 (stripped off braces from English keywords). This code works without any problem if I set preferred language to German, Dutch, Turkish. But it gives "bad input" error for French as @etienneCharignon  commented on Weblate.

I dig a bit more and played with this code on Hedy. It seems to be either on parsing lists, or the use of "at random", but surely for French at least, as this simple code does not work either:
````
amis is Jonathan, Lucile, David
print amis at random
````
> Quelque chose s’est mal passé en exécutant ce programme.

**Paste the Hedy code & level**

Level 5 - fortune teller

```
amis is Jonathan, Lucile, David
print "Je peux prédire si tu vas gagner à la loterie demain !"
personne is ask "Qui es-tu ?"
bonnes_réponses is Hourra ! Tu as gagné !, Tu vas certainement gagner !, Nous avons un gagnant !
mauvaises_réponses is Pas de chance ! Essaye encore !, C`est une autre personne qui gagnera, Tu as perdu !
if personne in amis print bonnes_réponses at random
else print mauvaises_réponses at random
```

**Add a screenshot (optional)**
![screenshot-hedy-alpha herokuapp com-2023 10 07-18_18_00](https://github.com/hedyorg/hedy/assets/1812105/a89b3918-cbf0-4a66-adda-5bf3ed7021f2)

**What machine and browser you were using (optional)**
- Windows
- Edge

**Comment by Felienne** [comment]
Intriguing! I will take a look when I can.

**Comment by yilmazdurmaz** [comment]
I dug a bit more back to levels 4 and then 3. it is now clear that either lists or "at random" got broken for French. This simple program does not work from level 3 onwards.
````
amis is Jonathan, Lucile, David
print amis at random
````

I moved all the way up to level 16, and tried to use indexes instead of "at random". Errors are more on the variable definitions. I am now thinking towards "parsing the lists is broken".

**Comment by Felienne** [comment]
It is the error message, it contains a quote!

<img width="936" alt="image" src="https://github.com/hedyorg/hedy/assets/1003685/05ab41ec-39ef-4923-8e06-c1a31b62cecc">

So the parsing is not broken, but the running. It can, for now, be fixed rewriting the error message. For later we can escape the quote in the code.

**Comment by Felienne** [comment]
> I moved all the way up to level 16, and tried to use indexes instead of "at random". Errors are more on the variable definitions. I am now thinking towards "parsing the lists is broken".

I understand you are trying to help, I really do, but please, you don't know enough to make good guesses at this point.

Parsing is not broken. Stop a minute and think about the possible impact of your words, you might get other people to dive deeper into parsing while that is not the issue! The same thing happened to me the other day with your misdiagnosis of the Weblate issue. Also people might get quite stressed if they read parsing is broken.

It seems to me from the interactions we have had so far, that you do not, before you type things to us, think about the possible impact on the people on the other side of the line. I ask you to do so in the future.

**Comment by yilmazdurmaz** [comment]
> escape the quote in the code

Ok, got it.
