### ISSUE TITLE
[UI idea] Ask teacher for class info

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#4612]
If teachers make a class and add students, they don't need to provide any student personal info (which is good, allowing for GDPR safe usage of Hedy!) but... we don't have any info about the students (like age, gender) to do analysis with, which is sad for us, because we want to understand what school types and ages use Hedy.

My first proposal is to ask teachers, when they sign up, a few simple questions:

* What is the age range in your group?
* What is the estimated gender balance in your group?
* Are you a school or a code club?
* Is participation mandatory or voluntarily?
* What is the dominant natural language in explanations?
* What is the dominant natural language in keywords?(pertaining to the examples they use, not necessarily what kids use in the class)

And simply drop this extra info in the database. Over time this will help us understand the user base better!

**Comment by Felienne** [comment]
Hi @hasan-sh!

This is a relative simple issue I think that maybe you are interested to pick up in between other tasks?

**Comment by hasan-sh** [comment]
I like this. It will help us exponentially later!! For instance, suggest adventures that target similar groups (assuming we have the tags idea of adventures implemented) or even grouping public classes if we even make the choice to make a marketplace of classes where students can join and benefit from; just like public adventures for teachers to reuse!

**Comment by Felienne** [comment]
> I like this. It will help us exponentially later!! 

Yes, I think so too! Also in terms of data analysis

> For instance, suggest adventures that target similar groups (assuming we have the tags idea of adventures implemented) or 

> even grouping public classes if we even make the choice to make a marketplace of classes where students can join and benefit from; just like public adventures for teachers to reuse!

I love both of these ideas a lot! Like: here is a preset class for 8 graders with all the nice adventures!

**Comment by Annelein** [comment]
Hey! I am also looking into this issue now. 

I agree, when a teacher account is being created, there are already a lot of questions. But also, a teacher might teach different classes, so I was thinking maybe we could split these questions to creating a teacher account and when creating a new class: 

> * What is the age range in your group?
> * What is the estimated gender balance in your group?

When creating a new class

> * Are you a school or a code club?

When creating a teacher account

> * Is participation mandatory or voluntarily?
> * What is the dominant natural language in explanations?
> * What is the dominant natural language in keywords?(pertaining to the examples they use, not necessarily what kids use in the class)

When creating a new class

Curious what you think of this! 
@hasan-sh are you working on it already? In case you are not, I also find it an interesting start of working on Hedy :)

**Comment by Felienne** [comment]
This could be a great first issue for you @AnneAnne! @hasan-sh has some other things to work on I think.

And I like the idea of splitting the questions, smart! 

We have to think a bit about edge cases though, some shool, teachers also run code clubs. Maybe when they have filled out details and then create a new class, we ask them if his class follows their previous answer?

But that could come later!

**Comment by Annelein** [comment]
I have created a [draft pull request](#4711), I thought before adding test it would be nice to know if this is how we want it! 

- The survey view can take x questions.
- Only unanswered questions are shown and if the survey is skipped, it won't be shown again.
- It pops up when a class contains students. (If someone can tell me how I can make it a fade in pop up that would be great!)
- Questions are saved under the Classes table

Two questions:
- Do we want it more generic? (Creating a Survey table so any survey's in the future will be easily implemented)
- It's my first contribution so any tips on better practices or better/cleaner code etc are very very welcome :)
