### ISSUE TITLE
[UI idea] Make cheatsheet and command toggle mutually exclusive

### ISSUE THREAD

**Issue by TiBiBa** [hedyorg/hedy#4619]
**Idea incl level**
This is a bit crowded, one should close when the other is openend:

![Scherm­afbeelding 2023-10-11 om 13 29 13](https://github.com/hedyorg/hedy/assets/38155424/df4ffe3f-e8a4-4233-974f-34be3ebe8502)

**Comment by hasan-sh** [comment]
Good catch. This is a general behavior, i.e., it actually happens with other menu types as well. For instance, the profile one:
![image](https://github.com/hedyorg/hedy/assets/20051470/1ecb8d4a-d4f7-4975-9e04-723afc3b1c23)

**Comment by TiBiBa** [comment]
This should be easy to solve as all dropdown menu's should inherit the same class `dropdown`. When clicking a menu we should simply close all that are not the one we click before toggling the one we target.

**Comment by TiBiBa** [comment]
Weird, the code is already here in `app.ts`:

```
// Close the dropdown menu if the user clicks outside of it
  $(document).on("click", function(event){
      if(!$(event.target).closest(".dropdown").length){
          $(".dropdown-menu").slideUp("medium");
          $(".cheatsheet-menu").slideUp("medium");
      }
  });
```
