### ISSUE TITLE
[UI idea]  Create adventure from class page

### ISSUE THREAD

**Issue by hasan-sh** [hedyorg/hedy#4633]
**Idea incl level**
Allow adding an adventure from within `/for-teachers/class/[id]` page. 

**Additional context**
Perhaps with a `create adventure` button.

**Comment by Annelein** [comment]
@hasan-sh is this what you mean?

https://github.com/hedyorg/hedy/assets/48122190/3ba60333-6c29-49ae-ad5e-584c10d6ebc2

**Comment by hasan-sh** [comment]
> @hasan-sh is this what you mean?
> 
>  Screen.Recording.2024-02-13.at.13.16.55.mov

I think this is what I meant initially, indeed. However, I don't really see the value of it anymore and it may confuse the teachers since having that button here kind of suggests that the created adventure would be added this the current class, which is not the case. 

So, I think it'd be much nicer to add such button in the available adventure dropdown in the class customization page. Shall we discuss this tonight?

**Comment by Annelein** [comment]
> I think this is what I meant initially, indeed. However, I don't really see the value of it anymore and it may confuse the teachers since having that button here kind of suggests that the created adventure would be added this the current class, which is not the case.

I agree! Let's discuss it tonight

**Comment by Annelein** [comment]
As discussed in the meeting: this will be added for now and this page will be designed better soon
