### ISSUE TITLE
💻 Realtime updates

### ISSUE THREAD

**Issue by hasan-sh** [hedyorg/hedy#4646]
**Idea incl level**
Currently, whenever the user makes an action, we mostly "reload" the page or redirect them. However, this isn't the best UX. For instance, removing a class, student and an adventure isn't reflected in the UI of all parties.  

**Additional context**
This is problematic when different parties make changes simultaniously; e.g., after allowing second teachers to make changes (#4644). Use socketio or something similar.

**Comment by TiBiBa** [comment]
I have quite some experiencing with implementing Soketi websockets in a project. Please let me know if you need any help!

https://docs.soketi.app

**Comment by Felienne** [comment]
Hi @hasan-sh!

I know we have now done this in some places (creating adventures) but I am not sure where else. It is totally ok if you leave this one, but can you make a list here of places where it needs to be done still, to ease handover?

**Comment by Felienne** [comment]
Hi @Annelein!

Can you pick this up for the /admin page?

**Comment by Felienne** [comment]
> #5631

Awesome, thanks!!

> I can however look into creating a list of pages for which it would be nice to implement autosave?

Love your proactive spirit, thanks! Sounds like a great idea to make this list, we can then prioritize in a next meeting.
