### ISSUE TITLE
[FEAT] (Re)invite/add existing students when duplicating a class!

### ISSUE THREAD

**Issue by hasan-sh** [hedyorg/hedy#4653]
The following function needs to be updated https://github.com/hedyorg/hedy/blob/ccc2f1f1d67d600d3ff8bed8b7e57305d573d5c1/website/classes.py#L185-L228 

Currently, duplicating a class only duplicates its customization. However, the class is empty and the teacher needs to invite (the same) students all over again. This also applies for second teachers; see #4644

**Comment by Felienne** [comment]
Hi @hasan-sh, this is actually working as we want it (but your issue means we should document it better!)

This feature is useful when you are teaching multiple similar classes (1a, 1b, 1c...) and you want to customize them in the same way! So you do not want to copy the students!

**Comment by Felienne** [comment]
So I guess we want to change this issue into:

* updating the teacher docs and UI
* and, updating the code

**Comment by hasan-sh** [comment]
Makes sense. How about second teachers?

**Comment by Felienne** [comment]
> Makes sense. How about second teachers? 

I don't think I understand the question. Is the question whether, if we have a class with 2 teachers, and that class is duplicated, the new copy has both teachers? 

I think I would lean to no, if I have an intern, I don't have them for all similar classes per se (and inviting them to all is not a lot of work, there will hardly ever be dozens of those classes)

**Comment by hasan-sh** [comment]
UPDATE: after discussing with @Felienne, we may give the option to teachers whether they also want to duplicate the customization(default), students, second teachers.

**Comment by Annelein** [comment]
I could pick this up. I was thinking of adding the three options here?

<img width="742" alt="Screenshot 2023-11-28 at 17 00 59" src="https://github.com/hedyorg/hedy/assets/48122190/daf50b3b-479d-45cb-acdc-a91a4bae0624">

But now that I think of it, maybe you want to add the students from a different class but with the customizations of another class.
Then maybe it would make sense to also add a button at 'Add student options' to add (all or a selection of) students from a different class? Let me know what you think! @hasan-sh @Felienne

**Comment by hasan-sh** [comment]
> > UPDATE: after discussing with @Felienne, we may give the option to teachers whether they also want to duplicate the customization(default), students, second teachers.
> 
> Yesterday I discussed this in the meeting and the conclusion was that it wouldn't make sense to duplicate students at all because their progress belongs to their profile, not the class. But you missed that discussion @hasan-sh . Why did you think it would make sense to duplicate students?

Now only the last class they're enrolled in (i.e., accepted the invitation from) is applied to students indeed, I'm not sure what "theor progress belongs to their profile, not the class" means. Either way, this isn't needed in Hedy, currently! 

I'm not sure what the future will bring, but perhaps we may have a marketplace of different classes that teach specific programming principles and students can join what they want/like/need. Therefore, I logically thought this is an essential feature and that the relation between classes and students isn't one-to-many but rather many-to-many.

**Comment by Felienne** [comment]
> I'm not sure what the future will bring, but perhaps we may have a marketplace of different classes that teach specific programming principles 

I love this as an idea! Then teacher will not only be able to share adventures but also classes with each other! Let's keep that in mind for later on.


As for this issue (noting this mainly for @Annelein) what is needed is I think:

* only the option to ask teachers if they also want to copy the second teachers to the copy. The customizations are copied by default.
* We also need to update the docs/teacher to explain to teachers what will happen when copying a class (maybe that can be a separate issue for @MarleenGilsing?)

**Comment by MarleenGilsing** [comment]
Yes, I'll make a seperate issue.
