### ISSUE TITLE
[UI idea] Replace "try it" button on the front-page

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#4655]
The front-page now has a "try out" button, but that leads right to the programming interface. It is a bit of very old legacy, when we thought we were designing a tool for kids. Since we are now clearly designing a tool for teachers, this button is not productive anymore. I'd like the front page to have two buttons, a bit like the sign-up page has also (not this layout, but this choice):

<img width="574" alt="image" src="https://github.com/hedyorg/hedy/assets/1003685/644b03d2-6c7c-4747-853c-22e312cd17ec">

So maybe a "start programming" and "start teaching" button? Start programming than works as it does now, and start teaching will lead to hedy.org/start (which is now still a bit messy but Sabina is working on that)

**Comment by musakurel** [comment]
I'd like to work on this!

**Comment by hasan-sh** [comment]
> I'd like to work on this!

Great @musakurel, if anything is unclear, don't hesitate to ask here or preferably on discord ;)

**Comment by Annelein** [comment]
@gisellandrade did you have time yet to look into this?

**Comment by gisellandrade** [comment]
yes, I can make a quick check on this one and have a proposal for today's meeting, is that fine? @Annelein

**Comment by Annelein** [comment]
yes perfect! @gisellandrade

**Comment by gisellandrade** [comment]
This are some proposal for the login page. I've donde two. One that has small changes for changes in the login (texts and some different buttons and layouts) and the other one that is a little bit different. Let me know your comments about this. 

![Pantallas de login](https://github.com/hedyorg/hedy/assets/154460618/9fcb66e4-c649-4461-b647-2737155d4913)
![Pantallas de login II](https://github.com/hedyorg/hedy/assets/154460618/5bd1f15f-2238-4696-a668-a39125f70f12)



![Pantallas de login III](https://github.com/hedyorg/hedy/assets/154460618/d0dbd3a7-ff2e-4394-9f4b-8fd97acc59e8)

**Comment by Annelein** [comment]
@gisellandrade I think you were mistaken by the screenshot that Felienne added in the description. But this issue is about the 'Try it' button on the Front Page, if you read the issue description, Felienne explains it there. 

Your 3rd design is a bit more what we're looking for, with the Hedy logo. But it would be nice if it looks a bit more like the Front Page looks now, just add the new buttons that replace the 'Try it' button.

Could you change the design accordingly?
Pin me on Discord if you need further explanation

**Comment by gisellandrade** [comment]
This are new proposals for the try it button on the front-page. The texts are optional, you can change it if you want to 

![image](https://github.com/hedyorg/hedy/assets/154460618/b95e8a58-6ba1-4a70-8c91-f293a4f4300a)
![image](https://github.com/hedyorg/hedy/assets/154460618/64455463-cbc5-4fb2-a123-c1a510aa1d57)

**Comment by Felienne** [comment]
> I would prefer the first one, what about you? @Felienne @jpelay @hasan-sh ?

Me too, I think it looks really nice!

**Comment by jpelay** [comment]
> This are new proposals for the try it button on the front-page. The texts are optional, you can change it if you want to
> 
> ![image](https://private-user-images.githubusercontent.com/154460618/308643100-b95e8a58-6ba1-4a70-8c91-f293a4f4300a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyMTY3NjUsIm5iZiI6MTcwOTIxNjQ2NSwicGF0aCI6Ii8xNTQ0NjA2MTgvMzA4NjQzMTAwLWI5NWU4YTU4LTZiYTEtNGE3MC04YzkxLWYyOTNhNGY0MzAwYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyOVQxNDIxMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MWU0OWI3MzczMWQ2MDJhZDE4MDg5ZmUxOGM0MzUzYzFkZjQyMWYyNWVkNzZjZjNiMWVhYTY5NGMzMmY4NjkzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xTZEmikQhWEeepAPclcja_Nn7vldocVmANeRUTfzbKg) ![image](https://private-user-images.githubusercontent.com/154460618/308643146-64455463-cbc5-4fb2-a123-c1a510aa1d57.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkyMTY3NjUsIm5iZiI6MTcwOTIxNjQ2NSwicGF0aCI6Ii8xNTQ0NjA2MTgvMzA4NjQzMTQ2LTY0NDU1NDYzLWNiYzUtNGZiMi1hMTIzLWMxYTUxMGFhMWQ1Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIyOVQxNDIxMDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MThhNmVjYjNkYTJjMGE2ZWEyZDk5YmY5Mzg1ODAwYTkxY2E4NWQ3OWFkYWMzMDk4OGYzMGY3YjdlYzc4Y2ZkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nFosbPKygWAbxwkmyzc8EAj2U4vNVkun7oOKRTYKttg)

I prefer the first one as well!!!

**Comment by Annelein** [comment]
Sweet! I can start implementing it along with #5183. Anyone that wants to help me out with creating a "teacher mode" account?

**Comment by Felienne** [comment]
> Sweet! I can start implementing it along with #5183. 

Great! 

> Anyone that wants to help me out with creating a "teacher mode" account?

What help do you need? This is the link the teacher button should go to: https://hedy.org/signup?teacher=true Does that help?

**Comment by Annelein** [comment]
@Felienne as I said, I can implement it along with #5183, so also implement having a "teacher mode" where teachers can try out teaching before having to sign up. Or did I get that issue wrong?

**Comment by Felienne** [comment]
> @Felienne as I said, I can implement it along with #5183, so also implement having a "teacher mode" where teachers can try out teaching before having to sign up. Or did I get that issue wrong?

Ah I see!

What I think we want, roughly is:

* A red bar like the one we have in preview mode indicating people are in a test environment
* A fake database with a few students, adventures, and a few runs for the dashboard, and a teacher account let's call that TestTeacher

When the teacher clicks the try button, they are referred to this page and "logged in" as TestTeacher.

How to exactly fake the database and delete the info on closing the browser, that is a question for @hasan-sh or @jpelay!

**Comment by Annelein** [comment]
Yes all of that @hasan-sh wrote in #5183 , so @hasan-sh @jpelay if one of you wants to (help) work on it, let me know!

**Comment by Felienne** [comment]
> Yes all of that @hasan-sh wrote in #5183 , so @hasan-sh @jpelay if one of you wants to (help) work on it, let me know!

Ok, I will let the three of you figure this out together!

**Comment by hasan-sh** [comment]
> Yes all of that @hasan-sh wrote in #5183 , so @hasan-sh @jpelay if one of you wants to (help) work on it, let me know!

I think the best way forward is divide-and-conquer. If you put the front-end together, I I'd be happy to make the test account possible.
