### ISSUE TITLE
[DOCS] contributing guidelines link takes me to a test page

### ISSUE THREAD

**Issue by michaelficarra** [hedyorg/hedy#4669]
When I go to open an issue, I am prompted to read the contributing guidelines:

<img width="498" alt="image" src="https://github.com/hedyorg/hedy/assets/218840/644f6dff-969d-4927-914b-b230c9a57cd9">

But the link takes me to https://github.com/hedyorg/hedy/blob/main/docs/CONTRIBUTING.md, which currently just says

> Testing to see if this create a tile in the /contribute page.

This should be filled out with real contribution guidelines or be removed so new contributors don't get prompted.

**Comment by Felienne** [comment]
Ah good catch @michaelficarra! We recently added that and I forget to follow through! Added a link to the wiki now, where all our docs live.
