### ISSUE TITLE
[LANGUAGE] Hedy doesn't fully support non-positional numeral systems

### ISSUE THREAD

**Issue by michaelficarra** [hedyorg/hedy#4670]
The [Hedy grammar](https://github.com/hedyorg/hedy/blob/main/grammars/terminals.lark#L4-L7) permits code points that participate in many kinds of numeral systems, but Hedy appears to only really support base-10 positional numeral systems (composed of sequences of code points in General Category `Decimal_Number`). When a user tries to use another numeral system that is permitted by the Hedy grammar, such as Ethiopic, Brahmi, or Roman numerals, they get error messages like the following:

<p><img width="551" alt="image" src="https://github.com/hedyorg/hedy/assets/218840/86e23982-9b58-41a1-b043-b0c1c784af7b"></p>

<p><img width="715" alt="image" src="https://github.com/hedyorg/hedy/assets/218840/f4b83191-cc75-4a70-9b4b-29c28721f611"></p>

There's a couple things that could be done here, in order from easiest to hardest.

1. Limit the grammar to only accept sequences of `Numeric_Type=Decimal` (or `General_Category=Decimal_Number`, same thing) code points.
2. Simply improve the error messages for programs that contain these unsupported numeral systems.
3. Limit the grammar to accept either sequences of `Numeric_Type=Decimal` or **just one** code point with an integral `Numeric_Value` property.
4. Add support for computing the numeric value of all of these currently unsupported numeral systems. This is a *lot* of work.

**Comment by Felienne** [comment]
Ah good find @michaelficarra!!

I suspect 2 would be the best way to go, 4 sounds like a lot of fun (maybe a fun project for a student one day?) but also a lot of work!

Maybe @akseron, who is currently working on improved error messages would love to pick this up?

I think adding an extra error production to catch these would not be very hard. If we limit the grammer (as you suggest in 1) kids would still get an ugly syntax error, so parsing + showing an error seems the way to go.

So, in steps:

* Change the grammar for numbers to only accept sequences of Numeric_Type=Decimal
* Add these non-supported characters (hopefully they also have a nice unicode category, maybe @michaelficarra nows this?) as an error production
* Make a new error message for unsupported numeral systems

(optional) make an issue for option 4 in `Discussion/Large project plans` so someone who would like to do this can pick it up!

**Comment by michaelficarra** [comment]
You should be able to use the current `INT` definition (`[\p{Nl}\p{Nd}\p{No}]+`) for the error production and then change the `INT` definition to a sequence of decimal numerals (`\p{Nd}+`). And the numeric literals with decimal separators (`NEGATIVE_NUMBER`/`POSITIVE_NUMBER`) must also only support decimal numerals, for obvious reasons. I don't think a special error production will be needed for those, as using non-positional numerals with a decimal separator wouldn't make any sense.

**Comment by akseron** [comment]
Working on this in error-productions-2 branch!
