### ISSUE TITLE
[LOCAL] Run-time messages are always English!

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#4676]
Working on #4675 made me realize our run-time error are not localized:

<img width="1457" alt="image" src="https://github.com/hedyorg/hedy/assets/1003685/b3499031-e9e7-40fb-b5c7-f66c4269a247">

Now that we have added a language parameter in some places (esp. in the color) this is not so hard to fix!

**Comment by jpelay** [comment]
Have you advanced on this? I can work on this, since I've done it before for the IndexError exception.

**Comment by Felienne** [comment]
ow by all means, if you want to pick it up, go for it! (but don't you need a bit of chill after CodeMirror?!)
