### ISSUE TITLE
[CODE] Document API endpoints

### ISSUE THREAD

**Issue by hasan-sh** [hedyorg/hedy#4679]
**Description**
Currently, we have some endpoint description in the wiki page, but not all. Also, endpoints are regularly updated/added.

**Idea**
One of the following:
- swagger ui
- postman

**Comment by Felienne** [comment]
Haha, I just put that on the agenda for Tuesday: https://github.com/orgs/hedyorg/projects/1?pane=issue&itemId=42664296

**Comment by Pooja1672** [comment]
HI @hasan-sh , I would like  to work on this issue can you please assign this issue to me ?

**Comment by Felienne** [comment]
Done! Let us know if you need any help, I can imagine that this is quite a lot or work, even though it does not necessarily require a lot of knowledge of the code base (and hence is a good first issue).

The workflow is to look at all routes in app.py labeled with @route (f.e. this is the first one: https://github.com/hedyorg/hedy/blob/4c4d24ee0322f37205f0bed2c1a5e44e7f4a1d39/app.py#L463)

And document those in the Wiki: https://github.com/hedyorg/hedy/wiki/Hedy-Development-Process#documentation-of-routes

Thanks!!

**Comment by Pooja1672** [comment]
Thank you @Felienne

**Comment by Felienne** [comment]
Also @Pooja1672 may I ask if this is part of a university project? I saw a bunch of new people pop up in the repo, and my experience is this is often the case :)

**Comment by Pooja1672** [comment]
No @Felienne , just doing it to learn contributing a bit with open source projects..just out of interest .

**Comment by Felienne** [comment]
Perfect! Welcome to the repo in any case, are you also already in the Discord? That is our main place of communication

**Comment by Pooja1672** [comment]
Yeah , I'm on discord

**Comment by Pooja1672** [comment]
Can you share the discord channel link or profile please ?
