### ISSUE TITLE
[CONTENT] Level 7 story should not refer back to level 6

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#4683]
In level 7, we refer to a level 6 story:

<img width="735" alt="image" src="https://github.com/hedyorg/hedy/assets/1003685/8e4e9918-832d-4905-befd-7019e89392bc">

But level 6 is calculations and does not have a story. We should change this. We can either do "level 5" or just say: "a previous level" which allows for more freedom, what do you think @MarleenGilsing?

If we do level 5, we could even include a direct link: https://hedy.org/hedy/5#story which is nice?

**Comment by MarleenGilsing** [comment]
I changed it to 'a previous level' as we often do.
