### ISSUE TITLE
Add Skulpt fork to our repos

### ISSUE THREAD

**Issue by jpelay** [hedyorg/hedy#4685]
In #4465 we are adding a debugger using Skulpts. For I modified Skulpt in my own fork, here: https://github.com/jpelay/skulpt. We need to add this repo to our organization, or fork it again and reproduce the changes there.

**Comment by Felienne** [comment]
Do you have the right permissions to add this fork to our org?

**Comment by jpelay** [comment]
> Do you have the right permissions to add this fork to our org?

I'm not entirely sure, I'll try and if I can't I'll reach out to you!

**Comment by Felienne** [comment]
Hi @jpelay!

This is done with https://github.com/hedyorg/skulpt right? Or should we still change our internal dependencies?
