### ISSUE TITLE
[CONTENT] mistake level 9 if else example

### ISSUE THREAD

**Issue by MarleenGilsing** [hedyorg/hedy#4698]
**Describe the issue**
What level, language and adventure does this concern?

**Add a screenshot (optional)**
Make a picture or screenshot to show the issue. Tip! You can make a screenshot and simply paste the image into GitHub with ctrl-v.

**Expected text**
What should we write instead?

**Comment by Felienne** [comment]
Can this be closed @MarleenGilsing (because you moved it to done?) Since it misses a description it is hard to know what it means for me haha
