### ISSUE TITLE
[BUG] Rename the teacher manual section in the yaml files (if possible)

### ISSUE THREAD

**Issue by MarleenGilsing** [hedyorg/hedy#4701]
![image](https://github.com/hedyorg/hedy/assets/80678586/8390cd78-c438-491e-8f64-6b6fa891249e)

Maybe a weird request, but the teacher manual is currently called 'sections', which is a very vague name. If this doesn't cause too much trouble, could it be changed to 'teacher_manual' or something like that? If not, you can just close this issue, because not a lot of people will be bothered by it.

**Comment by Felienne** [comment]
This should be possible, but:

* weblate needs to be closed
* it also needs to be changed in code, so it is a little bit involved
