### ISSUE TITLE
[CHORE] Add tracking pixel

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#4705]
We need to add a tracking pixel from Hour of Code (https://code.org/api/hour/begin_hedy_text.png) somewhere on the link we will create for them, info:

**Tracking Pixel**
In order to help us more accurately track participation in the Hour of Code, please include a 1-pixel tracking image on the first page of your Hour of Code activity. Place the pixel-image on the start page (if you have a landing page before the real start of your activity, place the pixel-image on the start page instead of the landing page). Please do not place the pixel on any other page. 

If an activity is only offered as an app download, or a lesson plan download (or link to a PDF or Google Doc), there is no need to include the tracking pixel and you can ignore this 

I am still double checking the link, will update later, but we can start to think about how/where to add it.

**Comment by hasan-sh** [comment]
Integrated in #4714

**Comment by Felienne** [comment]
Hi @hasan-sh, we usually only close issues when merged into main, so I am reopening this one, so we don't forget. I added it to the description of #4714 so it will automatically be closed.
