### ISSUE TITLE
Level 6, french code execution failure when using french keywords

### ISSUE THREAD

**Issue by etienneCharignon** [hedyorg/hedy#4713]
**Describe the bug**
At level 6, when you try to execute the following code and answer 'spaghettis' to the question, 
- the line 9 is ignored. 'Vous avez commandé…' is not printed. 
- the variable 'prix' stray at 0

**Hedy code & level**
At level 6 :
```
affiche "Bienvenue au restaurant Chez Hedy"
affiche "Voici notre menu :"
affiche "Nos plats principaux sont : pizza, lasagnes ou spaghettis"
plat_principal = demande "Quel plat principal souhaitez-vous ?"
prix = 0
si plat_principal est pizza prix = 10
si plat_principal est lasagnes prix = 12
si plat_principal est spaghettis prix = 8
affiche "Vous avez commandé " plat_principal
affiche "Ce sera " prix " euros, s'il vous plaît"
affiche "Merci, bon appétit !"
```

- If you answer 'lasagnes', it is working
- line 8 : if I replace the 'est'  by 'is' or replace the '=' by 'est', then it is working
- if I remove the 3 first lines, then it is working!
- if I switch to keywords in English it is working.
- if I switch line 7 and 8, then the problem happens with the course 'lasagnes'. With 'spaghettis' the price is set to 8 by the line 9 is still not displayed.

**Screenshot**
<img width="1484" alt="Capture d’écran 2023-11-04 à 21 40 52" src="https://github.com/hedyorg/hedy/assets/298214/2433cc0d-4f4f-4921-a5c1-7cfb1979418b">

**Machine and browser**
I'm on a mac. I'm using Firefox. The problem is also present with Chrome

**Comment by etienneCharignon** [comment]
I forgot to notice that I was testing on the alpha environment. This morning the problem is not present anymore and it is not present on https://www.hedycode.com

**Comment by etienneCharignon** [comment]
Hum… I do have it in production, but not for every execution /o\.
Here is a screenshot where I entered 'pizza', the line 9 did not print its output :
<img width="1496" alt="Capture d’écran 2023-11-05 à 13 47 24" src="https://github.com/hedyorg/hedy/assets/298214/d1e4c0e7-3352-4f61-95e5-580495287dc9">

**Comment by Felienne** [comment]
Thanks for the issue, I will look into it (I guess that the issue is flaky, happening only sometimes, explaining why you don't see it always)
