### ISSUE TITLE
[UI idea] Dropdown arrows

### ISSUE THREAD

**Issue by hasan-sh** [hedyorg/hedy#4718]
**Idea incl level**
Switch the arrows when a dropdown is opened.
![image](https://github.com/hedyorg/hedy/assets/20051470/30e3bf1a-7a6d-4e28-9fff-8fc8a6e8b649)

**Additional context**
- downwards arrow when closed
- upwards arrow when opened
- Please use hyperscript.

**Comment by Felienne** [comment]
I don't think I understand what arrows this issue refers to, but if you know @Annelein, go for it!

**Comment by Annelein** [comment]
> I don't think I understand what arrows this issue refers to, but if you know @Annelein, go for it!

Yes I do, the arrows inside the buttons that open up a dropdown menu (level dropdown, commands dropdown, language dropdown, cheatsheet dropdown), are always pointed downwards. It would be clean to have them pointed upwards if the dropdown button is pressed and the dropdown is opened!
