### ISSUE TITLE
[CONTENT] Odd description of elif in L17

### ISSUE THREAD

**Issue by clementcontet** [hedyorg/hedy#4720]
**Describe the issue**
In level 17, one can read (in two places) in English: **`elif` is short for `else` `if`**.
But in many other languages (not all though) like French, `elif` has been translated literally with `else if`, without contraction.
Then the sentence reads: **`else if` is short for `else` `if`** (in French **`sinon si` est un raccourci pour `sinon` `si`**), which doesn't make much sense :(

**Expected text**
Maybe replace **`elif` is short for `else` `if`** by **`elif` is equivalent to putting the two keywords `else` and `if`** => it would work a bit better in all cases (but it is maybe to verbose).

**Comment by Felienne** [comment]
Thanks for the good catch! Our content developer @MarleenGilsing can pick this up and change the phrasing a bit!
