### ISSUE TITLE
[BUG] /my-profile gives an error

### ISSUE THREAD

**Issue by Annelein** [hedyorg/hedy#4723]
With a teacher account, not sure if it does the same with a student account (Mac, Chrome)

<img width="1440" alt="Screenshot 2023-11-08 at 18 50 08" src="https://github.com/hedyorg/hedy/assets/48122190/faa7c17c-bd0a-4305-86b8-b6014f42d714">

**Comment by jpelay** [comment]
Fixed by #4724
