### ISSUE TITLE
💻 Rewrite first line of error messages

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#4729]
We have a project open for the phrasing of error messages (#3450) but I think there are a few other, smaller, things we can also do. I am interested in picking this up myself now that other stuff is working well.

I will open two issues today for discussion later on.

We need to critically assess the error message layout! Errors now always that with the same message in bold:
<img width="696" alt="image" src="https://github.com/hedyorg/hedy/assets/1003685/621fb246-8777-49c1-8ce3-3298ef5c91bb">

This was really not a clear design decision. I think someone (maybe even me!) early on added this when we had 0 users and we never got back to it because there were so many other things to work on like teacher features.

Now that we have more time to think about this, I really believe we should remove this message, since: 

* it does not add information (is always the same)
* it takes up space 
* it grabs the attention because it is bold

Any thought?

**Comment by jpelay** [comment]
I agree that the error message is not really helpful. I think that maybe we can the name of the error instead.

So in your example it'd be something like this:

![image](https://github.com/hedyorg/hedy/assets/45865185/02be59ce-7ae8-42c1-b3fb-a5c1516e9e33)

**Comment by gisellandrade** [comment]
Here's the new design for the mistakes in the adventures! 
![Image](https://github.com/user-attachments/assets/9e3d74d9-ac1c-4c90-9ab6-c2bc64e1fb8e)

**Comment by jpelay** [comment]
> Here's the new design for the mistakes in the adventures! ![Image](https://private-user-images.githubusercontent.com/154460618/348905805-9e3d74d9-ac1c-4c90-9ab6-c2bc64e1fb8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjExMzEzOTYsIm5iZiI6MTcyMTEzMTA5NiwicGF0aCI6Ii8xNTQ0NjA2MTgvMzQ4OTA1ODA1LTllM2Q3NGQ5LWFjMWMtNGM5MC05YWI2LWMyYmM2NGUxZmI4ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNlQxMTU4MTZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mMmQwODQyODhmNTI4YmYzZDE2Mjk0YmZhMDMyM2I2MTgwZDNjMDhhMjkzOWQ3OTFmNzM3YzRiNTE4MjAxMTQzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dnFtckAlFR142tUaTULUmLj2qi3x3fH4nOgztgTcLno)

I like it! If we want them to be unobtrusive and have a smaller footprint, this design does it. Although I think we could add a little more padding to it, so it's more prominent.

**Comment by AnneliesVlaar** [comment]
> These is the list of all the captions we use in the error messages:
> 
> * Connection_error: We couldn't reach the server. => Happens when there's no connection to the server. Might be fused with the rest of the message: "We couldn't reach the server. Check whether your Internet connection is working."

I agree with fusing the caption with the message. If in the rare case that it is not about the internet connection but a problem with the server, this message shows that it can be problem on either of the two sides (our side or the side of the user).

> * Execute_error: Something went wrong while running the program. => might happen if the program failed, or it took too long, or skip faulty is enabled and we executed but notified the errors. Not sure how to fuse this with the rest of the error unless we do something like this, essentially merge together the messages. Still do it even if it's a python error (that aren't really all that helpful to show to kids, either):
> 
> ![image](https://private-user-images.githubusercontent.com/45865185/384479126-5f3823da-3e5a-4ae1-8a27-73b970ed480f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NjM2NTAsIm5iZiI6MTczMTY2MzM1MCwicGF0aCI6Ii80NTg2NTE4NS8zODQ0NzkxMjYtNWYzODIzZGEtM2U1YS00YWUxLThhMjctNzNiOTcwZWQ0ODBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTE1VDA5MzU1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlYTNhODcxZDRmNGYxODkxMDljNTY5YWIxZWIwYjIzNTkxMTU4YjQ0MjJjMGQxZmViYzViZjdlNTJlZTI3MmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.dnG468CrgRhGS7oZwBGPV1_OPeALMBxh_0pSj92AHt4)
> 

I think this caption can also be removed. You would not get an error if there wasn't something wrong while running the program. The warning symbol and "your program takes too long to run" is enough information.

> * Other_error: Oops! Maybe we made a little mistake. => This is the one where we ask people to send us they're program

I like this caption because it shows that the blame is not always on the user.

> * Transpile_error: We can't run your program. => Possibly the one that offers the least ammount of info. Remove?

agree

> * Transpile_warning: Warning! Also, remove?

Is this about unused variables? "Warning!" can indeed be removed. In issue "add warnings about unused variables in list of variabels #5806 " I argue that we might want to show warnings not the same as errors. 
> 
> @Felienne @AnneliesVlaar What do you guys think?
