### ISSUE TITLE
[BUG] When editing the code while ask prompt is open, the editor loses focus

### ISSUE THREAD

**Issue by jpelay** [hedyorg/hedy#4742]
**Describe the bug**

Consider this video:

When an ask prompt is open, and user decides to edit the code, by clicking on the editor, the ask prompt correctly closes and the editor gets focus. But annoyingly, after a single keystroke the editor loses focus again, and the user has to click it.

https://github.com/hedyorg/hedy/assets/45865185/ef97d32f-344c-488b-8a47-59e946b379fb

This happens both with CodeMirror and Ace, so it's likely not a problem with the editor itself.

**Comment by Felienne** [comment]
This might involve a bit of detective work @Annelein, could be a small fix or a complicated solution, I don't know!

**Comment by Annelein** [comment]
@Felienne I've already spend a few hours looking into this but it is quite unclear to me, I also haven't worked with the editor a lot yet. It probably has something to do with asynchronous behavior
