### ISSUE TITLE
[UI idea] Map reserved keywords back to original in variable view

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#4749]
**Idea incl level**
We map reserved keywords to unused words by prepending an underscore, which should be an internal thing but now leaks out in the watches screen:

![image](https://github.com/hedyorg/hedy/assets/1003685/9c441cc0-9d77-4174-9bb8-17b27ba7ce35)

Steps to fix this include:

* Creating a dictionary with original value (continue in this case) and remapped value (_continue) in Python
* Fetching the original value from that dictionary in the watches view (not sure if that will be done at the front-end or backend?)

**Comment by jpelay** [comment]
> * Fetching the original value from that dictionary in the watches view (not sure if that will be done at the front-end or backend?)

The variable view is updates in the front-end, and we get the variable names from Skulpt, so this is a front-end task and the relevant function is `load_variable` in `debugging.ts`
