### ISSUE TITLE
[CONTENT] At command exception not being formatted correctly

### ISSUE THREAD

**Issue by jpelay** [hedyorg/hedy#4773]
Level 16
![image](https://github.com/hedyorg/hedy/assets/45865185/5d07e458-d6e5-4861-82f3-392cbbdb17b5)

**Comment by boryanagoncharenko** [comment]
This issue has already been resolved by #5275
<img width="530" alt="Screenshot 2024-03-27 at 12 11 25" src="https://github.com/hedyorg/hedy/assets/3010723/7e4def69-9788-48f7-b2b2-6ff2366f93f5">
