### ISSUE TITLE
[BUG] Debugger issue using turtle and `sleep` commands

### ISSUE THREAD

**Issue by juliabolt** [hedyorg/hedy#4775]
**Describe the bug**
When you have a turtle program including `sleep` commands and you use the debugger to run the program step-by-step and you keep clicking the `>>` button for next step during a `sleep` command, things go wrong and you don't get the right drawing.

**Paste the Hedy code & level**
For example in level 2:

```
print I will draw a plus
forward 20
sleep 1
turn -90
color blue
forward 20
sleep 1
turn 90
color red
forward 20
sleep 1
turn -90
color black
forward 20
sleep 1
turn -90
color blue
forward 20
sleep 1
turn 90
color red
forward 20
sleep 1
turn -90
color black
forward 20
sleep 1
turn -90
color blue
forward 20
sleep 1
turn 90
color red
forward 20
sleep 1
turn -90
color black
forward 20
sleep 1
turn -90
color blue
forward 20
sleep 1
turn 90
color red
forward 20
```

**Add a screenshot (optional)**
Make a picture or screenshot to show the issue. Tip! You can make a screenshot and simply paste the image into GitHub with ctrl-v.

**What machine and browser you were using (optional)**
If the issue concerns things in the website, let us know:
- What computer you are using (Windows, Mac, Linux?) Windows
- What browser you were using (Chrome, Edge, Safari) Chrome

**Comment by Felienne** [comment]
Hola @jpelay! Has this been fixed with the new debugger?

**Comment by jpelay** [comment]
> Hola @jpelay! Has this been fixed with the new debugger?

It still messes up badly I'm afraid, if you keep clicking and clicking

**Comment by Felienne** [comment]
> > Hola @jpelay! Has this been fixed with the new debugger?
> 
> It still messes up badly I'm afraid, if you keep clicking and clicking

ok, thanks! We will leave this open then and work on it when we have fixed allll other things :)
