### ISSUE TITLE
[UI idea] dropdown should go over warning, not under

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#4778]
This is really a tiny issue, but it does not look nice:

<img width="741" alt="image" src="https://github.com/hedyorg/hedy/assets/1003685/270e7b1a-2642-4654-9cd7-436a301b67cf">

**Comment by jpelay** [comment]
Haha we found the same thing #4771

**Comment by Felienne** [comment]
Oops, duplicate of #4771
