### ISSUE TITLE
[BUG] Code isn't visible in program view 

### ISSUE THREAD

**Issue by hasan-sh** [hedyorg/hedy#4796]
**Describe the bug**
- go to programs (`/explore` view),
- try to view any program,
- the code isn't appended to the editor and thus you cannot run it

**screenshot**
![image](https://github.com/hedyorg/hedy/assets/20051470/e89f78c0-ed48-48e1-9339-2640fab1ec88)

**machine and browser**
- on  Linux
- using chrome, firefox

**Comment by Felienne** [comment]
Ah good catch @hasan-sh!
