### ISSUE TITLE
[BUG] A user cannot be invited as student/second teacher to more than one class at a time

### ISSUE THREAD

**Issue by rix0rrr** [hedyorg/hedy#4804]
**Describe the bug**

If a teacher is invited to one class, they cannot be invited to any other class anymore as long as the invite is pending.

Reproduce as follows:

* Create a class, invite `teacher2`
* Create another class, invite `teacher2` to that as well

You get an error saying that `teacher2` is already invited to the class (but it isn't, that's another class!)

This behavior may not occur a lot in practice, but makes it harder to write reliable tests because tests cannot be made independent, and state left behind from a past test in the database can interfere with future tests.

EDIT: Jesus noted that this may actually happen in practice: one teacher may be creating a bunch of classes at once, and then inviting a second teacher to all of them in one go. With the current behavior, the second teacher would need to be present to accept each invite before the next invite can be sent.

**Comment by Felienne** [comment]
> EDIT: Jesus noted that this may actually happen in practice: one teacher may be creating a bunch of classes at once, and then inviting a second teacher to all of them in one go. With the current behavior, the second teacher would need to be present to accept each invite before the next invite can be sent.

Yes I agree this can be common, for example if you have an intern from a few classes, you will invite them to all in one go!

**Comment by hasan-sh** [comment]
This same wrong behavior occurs for student invitations actually. Will fix both of them!
