### ISSUE TITLE
[BUG] New exception system creates issues in skip faulty

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#4863]
Hi @ToniSkulj!

In #4838 I have made a change to how we process invalid code, but it breaks two of your tests (see: https://github.com/hedyorg/hedy/pull/4838/commits/cf1b87fca76889ccc3a20d492f433c58db983557) I dod not know how to fix those, could you maybe take a look?

I suspect that now we throw an exception when we find the first error (rather than processing the remainder of the tree also) might require a bit of a change to your handling of code with multiple errors? Hope you manage to make it back in order, thanks!

**Comment by ToniSkulj** [comment]
Hi @Felienne! 

> could you maybe take a look?

Sure thing, I will keep you updated.

**Comment by ToniSkulj** [comment]
Hi @Felienne!

https://github.com/hedyorg/hedy/pull/4882 fixes the failing tests.
