### ISSUE TITLE
[BUG] Run code button on the slides is hidden by input field

### ISSUE THREAD

**Issue by MarleenGilsing** [hedyorg/hedy#4866]
**Describe the bug**
The run code button and debugger are hidden by the input field in the slides. If you click the side of the bebugger button that is reachable, the debugger starts and you can afterwards use all the other buttons as well. 

**Paste the Hedy code & level**
Tried it in level 1, but probably the case in all levels.

**Add a screenshot (optional)**
![image](https://github.com/hedyorg/hedy/assets/80678586/b122616c-16a7-47c6-b603-7c1b13eae73c)

**Comment by Felienne** [comment]
Good catch @MarleenGilsing! I think this is due to the new editor. Maybe @jpelay can take a look (and also add a fest tests for the slides? I made them and I did not add any tests, so they break a lot 😓

**Comment by jpelay** [comment]
The previous tab button is also not working.
![Screenshot from 2023-12-07 13-54-35](https://github.com/hedyorg/hedy/assets/45865185/dd0575ed-2180-4aeb-8f4a-fe3e409cce5f)
