### ISSUE TITLE
[BUG] InvalidSpaceWarning not being shown in the editor

### ISSUE THREAD

**Issue by jpelay** [hedyorg/hedy#4869]
**Describe the bug**

The editor is not showing the warning for `InvalidSpace` and maybe for other warnings that come from the server?:

![image](https://github.com/hedyorg/hedy/assets/45865185/f9706010-8dc8-4842-8d1e-8dcd9a3740a3)

**Comment by jpelay** [comment]
> It is no longer needed because the editor strips leading spaces (So I think we can close this issue)

I  don't think that's the case! See how the code that we send to the server actually has the leading spaces. Do you want me to work on this?
![image](https://github.com/hedyorg/hedy/assets/45865185/03abac97-4a57-45ac-a26e-d75c1dd67feb)

**Comment by Felienne** [comment]
Weird! Then how can the code still run! I will dive in since I was working on a branch about it anyway.
