### ISSUE TITLE
[BUG] Unmatched quotes are highlighted

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#4874]
Got this email from a teacher pointing out it is confusing that this string is highlighted in purple but then does not parse (which is a great point)

![image](https://github.com/hedyorg/hedy/assets/1003685/87728ead-8e6c-4d23-8928-d61c9369ca61)

**Comment by jpelay** [comment]
This one is actually a bit hard, but will try to solve it!

**Comment by Felienne** [comment]
Ah sorry did not mean to give you a tough one!
