### ISSUE TITLE
📜 Teacher manual does not use {} around all keywords

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#4899]
This issue is part of the root cause of [#4134](https://github.com/hedyorg/hedy/issues/4134). The manual cannot use localized keywords because a lot of the content does not use curlies around keyword. 

So @MarleenGilsing (who opened #4134 haha) if you want to move this forward, we need to clean up the yamls. For example:

Here you see an example of a few codes where some do and some don't use curlies:

<img width="653" alt="image" src="https://github.com/hedyorg/hedy/assets/1003685/9aec3d21-118e-40d1-b39a-f317d4769642"> (https://github.com/hedyorg/hedy/blob/f10527506b6468131e03e1db89a2f48d6bbee940/content/pages/en.yaml#L465)

So step one is to add them, and ideally also in other languages (I know that wil be a lot of work and not fun...)

And, it will not always be possible to do localize, for example, broken keywords like `printt` cannot be translated:

<img width="610" alt="image" src="https://github.com/hedyorg/hedy/assets/1003685/7675695e-ea1e-4412-b7f7-5ce1f93c2a9d">

But I guess a teacher will understand.

**Comment by Felienne** [comment]
Maybe this would also be a good task for @SabinaChita? I will let the two of you sync on that!

**Comment by jpelay** [comment]
This was fixed by #5167
