### ISSUE TITLE
[BUG] Unused variable warning when using functions

### ISSUE THREAD

**Issue by jpelay** [hedyorg/hedy#4911]
**Describe the bug**

When defining a function, even if later is being called, the transpiler returns the Unused variable warning.

**Paste the Hedy code & level**
I tried this in the level 16

```
define sum with n1, n2
    return n1 + n2

print call sum with 1, 2
```
**Add a screenshot (optional)**
![Screenshot_20231216-072540](https://github.com/hedyorg/hedy/assets/45865185/9536baf5-d644-46c9-b8a1-5c6d45f6e51c)

**Comment by Felienne** [comment]
Ah sorry @jpelay! I will pick that up when I can.
