### ISSUE TITLE
[HIGHLIGHTER] add not highlighted in level 16

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#4916]
Code in level 16 that works but is not highlighted:

```
colors1 is ['green', 'red', 'blue']
x is 'pink'
add x to colors1
print colors1[4]
```

<img width="1015" alt="image" src="https://github.com/hedyorg/hedy/assets/1003685/52485734-501a-4d91-9c1f-9901f76067ad">

**Comment by jpelay** [comment]
Hello, @Felienne!  I can't reproduce this issue on main, can you tell me what language did you have set up?

![image](https://github.com/hedyorg/hedy/assets/45865185/72cf85d2-6b0f-4fbf-814d-744aecaa3088)

**Comment by jpelay** [comment]
I reproduced it on hedy.org! Which means that this issue have already been solved!

![image](https://github.com/hedyorg/hedy/assets/45865185/1f97a79b-10da-42da-aecb-233a9bfc9505)

**Comment by jpelay** [comment]
Oh I know what it happened, level 11 introduced the keyword `to` for the `for`, and it collided with the `to` from the `add` command, #4898 fixes that problem.
