### ISSUE TITLE
[HIGHLIGHTER] Don't highlight French space

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#4918]
The French content files use a "non-breaking space" which we highlight weirdly:

<img width="1462" alt="image" src="https://github.com/hedyorg/hedy/assets/1003685/bc9b811c-99c4-4c94-bebe-73d9694c7fe9">

We should just not do anything with it as a regular space?

**Comment by jpelay** [comment]
This actually happens in the Ace editors, I think it's about time that I replace them with CodeMirror!

**Comment by jpelay** [comment]
This actually happens in the Ace editors, and the CodeMirror editor shows them fine

![image](https://github.com/hedyorg/hedy/assets/45865185/59d56cd8-8510-4f29-9258-07dfe66131b8)

 I think it's about time that I replace them with CodeMirror!

**Comment by Felienne** [comment]
Ah of course I did not think of this still being Ace. I think we can close this issue since it will solve itself soon(ish)
