### ISSUE TITLE
[BUG] Leading spaces work in English but not French, Spanish, Portuguese, presumably others.

### ISSUE THREAD

**Issue by nevdelap** [hedyorg/hedy#4925]
**Describe the bug**

Go to https://www.hedycode.com/hedy#ask_command, and this works...

```
  print Hello!
ask What is your name?
echo hello
```

It still works if you change to French after having made that change, because the program is still in English.

But switching to French before starting the lesson, and adding the spaces, gets this result...

![image](https://github.com/hedyorg/hedy/assets/583807/14719000-b88a-4481-9cd5-88f71641ce53)

**NOTE:** I had to go back to the home page and Clear Site Data and go back to the lesson in between after being in English to reproduce the issue reliably.

I checked Spanish and Portuguese, they have the same issue.

**Paste the Hedy code & level**

https://www.hedycode.com/hedy#ask_command

```
  affiche Salut !
demande Quel est ton nom ?
réponds salut
```

**What machine and browser you were using (optional)**
If the issue concerns things in the website, let us know:
- Linux
- Chrome Version 120.0.6099.71

(I'm watching Felienne's GOTO 2022 video and she mentions kid's being able to make that specific mistake. Hedy looks great!)

**Comment by Felienne** [comment]
Thanks for the detailed issue description and the kind words about Hedy @nevdelap! I was on a small winter break, but I look into this issue today!
