### ISSUE TITLE
[BUG] Improve sizing of embedded editor

### ISSUE THREAD

**Issue by jpelay** [hedyorg/hedy#4933]
**Describe the bug**
The embedded editor has some issues:

1. The editor can grow unlimited horizontally, so it takes up the space of the output window:

https://github.com/hedyorg/hedy/assets/45865185/658e188b-77ca-4fa4-867b-9b56fb02533d

2. The scrollbar appears bellow the first line, because the editor doesn't take the entire space available to it:

![image](https://github.com/hedyorg/hedy/assets/45865185/bca4b712-ea59-4d35-b496-b3d5acf5b3a9)

**Comment by Felienne** [comment]
Probably an issue issue to pick up in between?

**Comment by Felienne** [comment]
If Hasan is doing other things, @Annelein could also do this one?

**Comment by jpelay** [comment]
> If Hasan is doing other things, @Annelein could also do this one?

This issue has actually been solved already!
