### ISSUE TITLE
[CONTENT] Some examples in the Common Mistakes section have curly braces

### ISSUE THREAD

**Issue by jpelay** [hedyorg/hedy#4934]
**Describe the issue**
Some examples in this [page](https://hedy-alpha.herokuapp.com/for-teachers/manual/common_mistakes) incorrctly replace the curly braces around keywords.
![image](https://github.com/hedyorg/hedy/assets/45865185/28c65286-f588-478a-a825-8e54c9721f2d)

**Comment by Felienne** [comment]
I think we already have an issue open for this! Let me check.

**Comment by Felienne** [comment]
Ah yes, this one: https://github.com/hedyorg/hedy/issues/4899
