### ISSUE TITLE
[BUG] changing keyword language not working

### ISSUE THREAD

**Issue by hasan-sh** [hedyorg/hedy#4943]
**Describe the bug**
If we change the keyword language from source to target language, an error is returned. See the following:

![image](https://github.com/hedyorg/hedy/assets/20051470/ffd27c72-3c13-43b0-ab58-47df024bdfe4)

**Comment by Felienne** [comment]
Hi @hasan-sh!

I think this only happens when the editor is empty, can you verify that? If that is indeed the case, it is on my radar!

The problem did not really matter before because we always had start code, but now that we have removed that, it is suddenly a visible problem.

**Comment by hasan-sh** [comment]
> can you verify that?

Yes, that's entirely correct.
