### ISSUE TITLE
📜 Add information about Public adventures

### ISSUE THREAD

**Issue by hasan-sh** [hedyorg/hedy#4955]
**Describe the issue**
We need to add text explaining the new public adventures feature both in `for-teacher` and teacher's manual. Check the issue by Felienne in #4909 for more info. Also contact me if any further explination is needed.

**Comment by Felienne** [comment]
Hi @MarleenGilsing and @SabinaChita!

We have recently added a new feature called "public adventures" That means that people can start to re-use adventures from other teachers! It would be great to add this to the teacher guide and to the newsletter.

You can try the feature via: https://hedy-alpha.herokuapp.com/public-adventures

**Comment by MarleenGilsing** [comment]
@Felienne Do we have a login for a teachers account on alpha?

**Comment by Felienne** [comment]
Hi @Annelein!

I think yo will address this with the new tile in the teachers page!

**Comment by Annelein** [comment]
Hi @Felienne, what do you mean? I should write the new information about public adventures?

**Comment by Felienne** [comment]
> @Felienne Do we have a login for a teachers account on alpha?

Yes! DM you on Discord

**Comment by Felienne** [comment]
> Hi @Felienne, what do you mean? I should write the new information about public adventures?

No I mean that @MarleenGilsing will write it, and you can add it to the new teacher page (in the new 4th tile)

**Comment by Annelein** [comment]
@MarleenGilsing the new view is already merged, so you can add the new information to `public_content_info`
