### ISSUE TITLE
🧪 Not use Cypress for Lezer tests

### ISSUE THREAD

**Issue by jpelay** [hedyorg/hedy#4956]
We are experiencing problems with the Lezer tests in #4799  due to them calling application code directly. This causes problems with the imports, due to diverging conventions used by TypeScript and CodeMirror. Thus the easiest fix is to just use a different test framework for Lezer, something like Jest, although I think that in the Lezer's language packs they use something else.

**Comment by rix0rrr** [comment]
You know what -- if we use `esbuild` to bundle the TypeScript files and set module resolution back to `node10`, then it all probably works again. So you might not need to do this.
