### ISSUE TITLE
💻 Add language switcher to slides

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#4960]
**Idea**

Slides don't have a language switcher at the moment, they just take the settings from the site:
<img width="1183" alt="image" src="https://github.com/hedyorg/hedy/assets/1003685/fcff953e-e47a-475e-bbc6-1f3bed40564e">

But as a teacher you might want to show the code in multiple languages, switching while presenting.

**Comment by Felienne** [comment]
Maybe fun for @Mark-Giesen when he is done with his current front-end wrestling :D

**Comment by Mark-Giesen** [comment]
> Maybe fun for @Mark-Giesen when he is done with his current front-end wrestling :D

If I finish up on top, this would be a walk in the park.
