### ISSUE TITLE
Error screen for students when their previously used level is now locked 

### ISSUE THREAD

**Issue by LegoPink** [hedyorg/hedy#4968]
When students end a session in level 1, and the next session that level is no longer available to them (teacher closed it), the student gets an error screen. 

(Kids are using Chromebooks, chrome browser (not relevant, I guess)

**Comment by hasan-sh** [comment]
Hi @LegoPink , thanks for reporting this issue. I guess we talked about it on discord? If so, I changed the behavior to match what a teacher would expect #4970. That is, students will see all levels of a class if you disable the quiz. Some visual aids are added too. 

Thanks again!

**Comment by LegoPink** [comment]
We did indeed discuss this on discord. Last week I still saw the screens, but I don't think I saw any yesterday. 
But I've re-enabled the quiz, so not sure if it is really solved yet.
(It's pretty hard to keep track of things when 25 enthousiastic 9 year olds want to show you their work...)

**Comment by hasan-sh** [comment]
> We did indeed discuss this on discord. Last week I still saw the screens, but I don't think I saw any yesterday. But I've re-enabled the quiz, so not sure if it is really solved yet. (It's pretty hard to keep track of things when 25 enthousiastic 9 year olds want to show you their work...)

Totally understandable! Please let me know if there's any issue still so that we look into it again!

**Comment by LegoPink** [comment]
Kids still end up in the error screen, I think when they somehow try to acces a level not available to them.
Today I noticed some, it is possible that the last program they worked on was on Level 1 and I closed that level (after checking they all passed the level 1 quiz)

The button on the error screen brings them to the home screen, but that doesn't help, since they end up om the error screen again as soon as they click on Hedy again

**Comment by LegoPink** [comment]
I reproduced this by adding a student to a test class, locking the first level and login in as this student.

**Comment by Felienne** [comment]
Hi @hasan-sh!

Will this also be solved by #5061?
