### ISSUE TITLE
📜 Check for missing NL translations and translate it

### ISSUE THREAD

**Issue by MarleenGilsing** [hedyorg/hedy#4984]
@SabinaChita or I should go over the content and see if we miss any Dutch translations.

There has been some new content to the slides, quizzes, adventures and teacher manual that probably isn't translated yet.

**Comment by Felienne** [comment]
Hi @MarleenGilsing! I just chatted with @SabinaChita and she can pick this one up.

@SabinaChita, all content is located in [/content](https://github.com/hedyorg/hedy/tree/main/content). So it is a matter of going to each folder (for example, quizzes) and then opening the nl.yaml file:

https://github.com/hedyorg/hedy/blob/main/content/quizzes/nl.yaml

Simply browse the file and see if there is any English content present, and if so, translate it :) Marleen might give you some pointers to new things that are not translated yet, like the new music adventures.
