### ISSUE TITLE
🪲 Local host doesn't show example code 2 and 3

### ISSUE THREAD

**Issue by MarleenGilsing** [hedyorg/hedy#4986]
**Describe the bug**
I'm working on a new music adventure and I've made multiple examples in level 2. Only they don't show up in my local host for some reason. @jpelay, do you know what's going on?

![image](https://github.com/hedyorg/hedy/assets/80678586/8d6f1bf4-36ec-4ab2-976e-639123ba584d)
Multiple examples :)

![image](https://github.com/hedyorg/hedy/assets/80678586/7ec57dc9-2e2d-42b5-be35-34647f0b33c9)
Only one example :(

**Comment by jpelay** [comment]
Could it be that each example_code needs its own story_text?

**Comment by jpelay** [comment]
I think this might be a bug: https://hedy-alpha.herokuapp.com/hedy/6#dice in this example there should be text bellow the editor saying: "Did you manage to calculate the score for 8 dice? That required a lot of copy and pasting, right? We are going to make that easier in level 7!"

**Comment by MarleenGilsing** [comment]
Yes I think it's a bug too, because I tried adding story_text, but it didn't help.

**Comment by Felienne** [comment]
The "bug" is that example_codes will only be shown if there is an accompanying text! We can add a test to warn for this but it feels a bit overkill.
