### ISSUE TITLE
🪲🎶 Notes should only go between 1 and 70

### ISSUE THREAD

**Issue by MarleenGilsing** [hedyorg/hedy#4987]
Only play 1 to play 70 should work, teh rest should get an error message
Right now play 71 also works, but it restarts, so 71 is the same note as 1. 
And you can also play -1 but then it crashes and keeps playing that note until you close the browser. (You've taken a pic of the errormessage)

**Comment by Felienne** [comment]
Yes this is the error, very ugly:

<img width="774" alt="image" src="https://github.com/hedyorg/hedy/assets/1003685/9e582364-1b6a-4adc-8752-b55acbc757ab">
