### ISSUE TITLE
🪲🎶 You can't play a variable +1 after a repeat

### ISSUE THREAD

**Issue by MarleenGilsing** [hedyorg/hedy#4988]
I found something else on my mission to break the musical notes ;)

![image](https://github.com/hedyorg/hedy/assets/80678586/556410dc-cd21-4af2-a0ce-578db3000476)

In level 7
Allowed:
repeat 3 times play 20 + 1

Also allowed:
note = 20
repeat 3 times play note 

Not allowed:
note = 20
repeat 3 times play note - 1

In level 8
Allowed:
repeat 3 times
    play 20 + 1

Also allowed: 
note = 20
repeat 3 times
    note = note -1
    play note

Not allowed:
note = 20
repeat 3 times
    play note - 1

**Comment by Felienne** [comment]
And tis one @boryanagoncharenko?

**Comment by boryanagoncharenko** [comment]
All of the 6 snippets in the description work with the main branch (but they fail on PRO).
Level 7:
<img width="742" alt="Screenshot 2024-02-28 at 15 31 17" src="https://github.com/hedyorg/hedy/assets/3010723/980de68a-ad8a-4b4c-8c5e-8265ab26fe5f">

Level 8:
<img width="745" alt="Screenshot 2024-02-28 at 15 30 56" src="https://github.com/hedyorg/hedy/assets/3010723/1bb8046d-6fe2-4e93-9b7e-47f75a4fc4b6">

Probably, the issues were fixed as a side effect of #5044. Should I close the issue or ask @MarleenGilsing to re-test the scenarios once the changes are deployed to PRO?

**Comment by Felienne** [comment]
@MarleenGilsing can retest this on main locally and check if it is fixed!

**Comment by MarleenGilsing** [comment]
Works perfectly!
