### ISSUE TITLE
💻Make a error messages for when [ ] are forgotten around lists

### ISSUE THREAD

**Issue by MarleenGilsing** [hedyorg/hedy#5013]
In level 16 (and up) the square brackets are introduced to use around lists. If you don't use them you'll get this error message:
![image](https://github.com/hedyorg/hedy/assets/80678586/220b1bf8-1d5c-415a-8bc1-68c29e432a92)

Can we make an error message that tells you that you forgot the brackets instead of telling you not to use a comma?

**Comment by brielle5810** [comment]
Hi! Could I give this a try?

**Comment by MarleenGilsing** [comment]
@brielle5810 Sure!

**Comment by akseron** [comment]
> @akseron will probably not pick this up, maybe one for @boryanagoncharenko?

Oh pardon, I thought the other commenter was already trying out the issue 😅 I will take a look at it in the weekend if @boryanagoncharenko does not mind.

**Comment by boryanagoncharenko** [comment]
@akseron of course! I am assigning the issue to you. Feel free to assign it back to me in case you want to get rid of it in the future :)
