### ISSUE TITLE
📜 Adventures misses a title

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#5020]
**Describe the issue**

Similar to #5019, the adventures title is also missing: 
<img width="186" alt="image" src="https://github.com/hedyorg/hedy/assets/1003685/028da7cd-1f4c-4f86-8985-d5bf8996dcc1">

(https://hedy-alpha.herokuapp.com/public-adventures)

Maybe a good idea to check all related strings? And maybe to slab a test on the po files that English should never have "" as value?

**Comment by hasan-sh** [comment]
> Similar to #5019, the adventures title is also missing:

I'll add and remove translation keys related to the public adventures in https://github.com/hedyorg/hedy/pull/4990
