### ISSUE TITLE
💻My programs adventures sort alphabetically

### ISSUE THREAD

**Issue by AnneliesVlaar** [hedyorg/hedy#5027]
When I go to the 'my programs' page. There is a drop down menu to search for programs from a specific adventure. The adventures however are not sorted alphabetically. It would be really helpful if it was sorted, to easier find the right adventure. 

![afbeelding](https://github.com/hedyorg/hedy/assets/66774020/3c23ef50-2b47-4d7a-be34-15eecd4ecb96)

**Comment by Annelein** [comment]
I will pick this up!
