### ISSUE TITLE
💻 Add "copy code" to my programs page

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#5037]
If you want to reuse code, you have to go to myprograms and then select a program, open it and copy the code. We could add a "copy code" button to the programs list (this idea comes from @AnneliesVlaar, maybe she wants to expand?)

**Comment by Felienne** [comment]
Hi @Annelein!

Maybe you can pick this one up? Should not be all too hard! (Let me know if the plan is clear enough!)

**Comment by Annelein** [comment]
@Felienne Yes I got it, will pick it up!
