### ISSUE TITLE
🪲Introduction exercise is missing sample code

### ISSUE THREAD

**Issue by marc-bouvier** [hedyorg/hedy#5042]
In [the very first exercise](https://www.hedycode.com/hedy#default) there is no code to try anymore. Which I find a bit puzzling. I guess it was an infortunate side effect of the global replacement of placeholder code.

I feel some code needs to be there.

![image](https://github.com/hedyorg/hedy/assets/15436007/af7cdd79-4a9c-4b6e-80b2-5bd2f4416d3e)

**Comment by Felienne** [comment]
Great point! @MarleenGilsing can add a small sample back in to try!
