### ISSUE TITLE
🧹 Remove live statistics

### ISSUE THREAD

**Issue by LegoPink** [hedyorg/hedy#5047]
**Describe the bug**
When in the screen of a class (logged in as teacher), when I press the 'Live Statistieken ' button, I get an error

**Comment by Felienne** [comment]
Yeah sadly the live statistics suffer from some performance issues, we hope to be able to pick them up in the hackathon next week! (Are you also coming @LegoPink??)

**Comment by LegoPink** [comment]
I might com on Thursday, not sure yet,  but I have other plans for Friday

**Comment by Felienne** [comment]
We can close this once we have removed the code
