### ISSUE TITLE
🪲 translating keywords

### ISSUE THREAD

**Issue by juliabolt** [hedyorg/hedy#5063]
**Describe the bug**

Changing the language of Hedy into any other language, lets say Welsh, including the keywords, and then changing the interface back to English, the keywords stay in Welsh. The button for changing the language of the keywords is gone, but the keywords didn't automatically go back to English. This way, users need to change the keywords back into English, before they change the interface back to English. 

**Paste the Hedy code & level**
It is super helpful if we can copy-paste the Hedy code to test, so please paste the code here, and don't forget to tell us what level you were in.

**Add a screenshot (optional)**
Make a picture or screenshot to show the issue. Tip! You can make a screenshot and simply paste the image into GitHub with ctrl-v.

![image](https://github.com/hedyorg/hedy/assets/32330467/b1fe7259-db7e-4a5f-8bc4-bd842123b305)

**What machine and browser you were using (optional)**
If the issue concerns things in the website, let us know:
- What computer you are using (Windows, Mac, Linux?) Windows
- What browser you were using (Chrome, Edge, Safari) Chrome

**Comment by hasan-sh** [comment]
> and then changing the interface back to English, the keywords stay in Welsh.

Hello @juliabolt, thanks for reporting:) I tried to reproduce this bug and it only happens when you specifically switch the keyword after switching the language. I'll pick it up!
