### ISSUE TITLE
📜 Level 2 Quiz question 4

### ISSUE THREAD

**Issue by juliabolt** [hedyorg/hedy#5068]
**Describe the issue**
What level, language and adventure does this concern?

Level 2, English, Quiz, question 4 has an exclamation point in the question which needs to be removed. With the '!', actually none of the answers are correct and it will be printed as name! and not as Hedy, which is the whole point of this question. 

**Add a screenshot (optional)**
Make a picture or screenshot to show the issue. Tip! You can make a screenshot and simply paste the image into GitHub with ctrl-v.
![image](https://github.com/hedyorg/hedy/assets/32330467/b259343a-2840-4cea-8ac3-acab90a7653c)

**Expected text**
What should we write instead?

the '!' should be removed (or, the '!' needs to get a space in front of it and it should be added to the answer options)

**Comment by Felienne** [comment]
> I found a yaml file where I could adjust this myself, but I don't know for sure if that's all, where it should be adjusted?

Yes that is all! So if you want to fix it, go for it!
