### ISSUE TITLE
🪲 'Introduction' program not found in Programs

### ISSUE THREAD

**Issue by Annelein** [hedyorg/hedy#5072]
_(Make sure you have an 'Introduction' program in My Programs)_
If you go to `/programs` and select the program 'Introduction' in the Adventure box, it says: 'There are no programs'.

<img width="1440" alt="Screenshot 2024-02-06 at 17 38 08" src="https://github.com/hedyorg/hedy/assets/48122190/27bb1e69-2c19-4012-bef6-4d83c098ecd2">

<img width="1440" alt="Screenshot 2024-02-06 at 17 38 20" src="https://github.com/hedyorg/hedy/assets/48122190/4a992352-319b-45d1-9ec3-f6b1ec8adc5d">

This has to do with these if statements, because Introduction programs have the adventure_name 'default':
https://github.com/hedyorg/hedy/blob/04ccac1d6959088f0f147dffb028528407096a06/website/database.py#L233C13-L237C29

**Comment by Felienne** [comment]
@jpelay I am not sure now if this is still the case, can you double check?

**Comment by jpelay** [comment]
> [@jpelay](https://github.com/jpelay) I am not sure now if this is still the case, can you double check?

Yes, it is still the case, I made a PR to solve this: #6019
