### ISSUE TITLE
💻 Allow teachers to add model examples to their custom adventures

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#5086]
Ask @AnneliesVlaar for details

**Comment by AnneliesVlaar** [comment]
With adding examples to custom adventures there was a question on how this would fit in the interface. 
I have painted an idea by using the tab structure. 

There could be a tab for general settings:
![Hedy-custom-adventure-settings](https://github.com/hedyorg/hedy/assets/66774020/07581886-5a4f-43b7-8e2c-d09b63e72863)

A tab for writing the adventure:
![Hedy-custom-adventure-adventure](https://github.com/hedyorg/hedy/assets/66774020/6f0287f7-b932-42bc-8089-cd248e917175)

Then in the next tab one could see a preview of the adventure, similar to how it would look like for the students:
![Hedy-custom-adventure-preview](https://github.com/hedyorg/hedy/assets/66774020/1925a6d0-84f4-4191-9407-eadc13543114)

In the last tab one could store the answers:
![Hedy-custom-adventure-example-model](https://github.com/hedyorg/hedy/assets/66774020/d474b49c-2050-4acf-b5c7-2b171d8b2377)

**Comment by hasan-sh** [comment]
I really like the idea @AnneliesVlaar !

**Comment by Felienne** [comment]
We also have to think about how to visualize this for browsing public adventures maybe with an extra option "show model answer" to copy the answer to the input field
