### ISSUE TITLE
🪲 preview class not (always) possible for teachers 

### ISSUE THREAD

**Issue by hasan-sh** [hedyorg/hedy#5088]
**Describe the bug**
In https://github.com/hedyorg/hedy/blob/main/app.py#L1481 we redirect the user to a level according to their progress (e.g. if they finished quiz 1, they're redirected to level 2). But we don't need that logic for teachers. This logic should be there only for non-teachers.

**Comment by LegoPink** [comment]
When I am logged in as a teacher, and I try to preview a class in which the first level is closed, I end up on an error page: 
![image](https://github.com/hedyorg/hedy/assets/132092424/d3dab0d1-0868-4c32-90df-c23216477f28)

**Comment by Felienne** [comment]
Hi @Annelein! I am not 100% sure what the issue (and the proposed solution) is but I am sure Hasan will know!

**Comment by Annelein** [comment]
@hasan-sh I don't really understand the issue, if you could explain it to me would be great!

**Comment by hasan-sh** [comment]
This was most likely solved by one of the PRs but never closed!
