### ISSUE TITLE
🪲Variable is not highlighted if followed by an exclamation mark

### ISSUE THREAD

**Issue by jpelay** [hedyorg/hedy#5089]
**Describe the bug**
On level 2 if a variable if followed by an exclamation mark it is still valid, and the syntax highlighter it should reflect this:

![image](https://github.com/hedyorg/hedy/assets/45865185/aaef37df-bac7-49b6-b0a9-c28173d71005)

**Comment by juliabolt** [comment]
shouldn't the output be `Hedy is name!` since `name! ` is another string than `name ` ? or do we definitely want variables to be replaced with their values? If so, I agree the syntax highlighter should reflect this.

**Comment by Felienne** [comment]
> shouldn't the output be `Hedy is name!` since `name! ` is another string than `name ` ? or do we definitely want variables to be replaced with their values? If so, I agree the syntax highlighter should reflect this.

That is a great point but that shows you think like a programmer haha! We thought that for a kid this behaviour makes sense (and thus it should be highlighted)
