### ISSUE TITLE
💻 Adding students to a class (ignore empty lines)

### ISSUE THREAD

**Issue by LegoPink** [hedyorg/hedy#5091]
When adding students, and adding less then the number of lines in the interface, it tells you to fill the empty fields. 
I'd rather have it would ignore the empty line

![image](https://github.com/hedyorg/hedy/assets/132092424/ca72aaf5-df55-49a1-aad8-058033a3810b)

**Comment by TiBiBa** [comment]
I was just looking at this but it is a bit more complex than I thought. You can also remove the line users the red cross at the end. Do you think this is sufficient? Otherwise I will look into automatically removing empty lines.

**Comment by TiBiBa** [comment]
Whoops update: Just found a fix, will push this.
