### ISSUE TITLE
💻 Improving Teacher Dashboard

### ISSUE THREAD

**Issue by juliabolt** [hedyorg/hedy#5097]
CLASS INSIGHTS PAGE (these things could also be on the main class page, but hidden/collapsed)
- common errors, but including example programs where these errors occurred (does not need to be completely live)
- last login per student (remove from main class page)
- number of programs per student (remove from main class page)

MAIN CLASS PAGE
- remove last login
- move highest level reached to the customize class page
- remove number of programs
- make one username list, clickable
- keep change password button
- keep remove  student button
- put add student button below the students table
- put add teacher below the teachers table

CUSTOMIZE CLASS PAGE
- make clearer which options are global and which options for a specific level
- make it possible to close the quiz per level, so that the quiz can be open for one level but closed for other levels
- more user friendly if the page doesn't always open in level 1, but goes to the level that the teacher used most recently for example (now teacher makes a change to level 1 by accident when they actually want to change it in another level)
- the scrolling through adventures is awkward. maybe we can put the adventures they some way that scrolling is not needed
- add possibility to close the Explore page (for during a test for example, prevent kids from copy pasting someone else's solution) 
- highest level reached per student (remove from main class page)

NOT SURE WHERE TO PUT THIS YET
- The overview of where students are LIVE, the compact circle view, add that you can also click it and see what they are doing or the most recent program a student was running
- Overview with eyes and crosses and tickmarks, adjust that the eyes do not appear when a student is just copy pasting the example code into the hedy editor using the yellow arrow buttons
- Have a bookmark option for a show-and-tell that can be done at the end of a lesson. For example, aside from Hedy's choices also have a Teacher's choices, or something similar. 

UNRELATED TO TEACHER DASHBOARD ITSELF BUT REQUESTED BY TEACHERS
- more hints for kids
- better error messages, for example sometimes an intentation error is shown when the actual problem is something else
- in the create account page, swap box for student and for teacher (now kids make teacher accounts by accident because that's where the mouse is. could also help to make the student box bigger than the teacher box or something like that)

**Comment by juliabolt** [comment]
@jpelay

**Comment by juliabolt** [comment]
ABOUT THE LIVE STATISTICS PAGE
- remove the class overview
- keep compact circle view, not sure where to put it
- keep common errors, move to class insights page, make it faster, and add examples

**Comment by juliabolt** [comment]
IDEA TO REPLACE LIVE STUDENT VIEW WITH CIRCLES
have a bar (similar to a timeline) where you can see in which level/adventure every student is LIVE

![WhatsApp Image 2024-02-08 at 17 18 37_5eee9097](https://github.com/hedyorg/hedy/assets/32330467/caeacb19-6bf8-4953-8ddc-bca5e43d4d7a)

**Comment by jpelay** [comment]
![Uploading PXL_20240209_125535953.jpg…]()

**Comment by jpelay** [comment]
![PXL_20240209_125535953](https://github.com/hedyorg/hedy/assets/45865185/9b85fcff-6c68-420d-ba11-0d3afc57a38c)
