### ISSUE TITLE
🪲 teachers should see programs even if broken 

### ISSUE THREAD

**Issue by hasan-sh** [hedyorg/hedy#5098]
**Describe the bug**
a teacher is not able to see student's handed in program because it has an error in the code.

**Comment by Felienne** [comment]
Ah I see in the notes you were not able to reproduce this? Could you sync with Renee, because if I remember it correctly, she has an example where that happened? But maybe it was legacy and it works now for new programs?

I would feel better if she can confirm it is solved :)

**Comment by Felienne** [comment]
Teacher that reported this says it has been fixed!
