### ISSUE TITLE
💻 Colors of the tabs change

### ISSUE THREAD

**Issue by MarleenGilsing** [hedyorg/hedy#5119]
Can we make the debugger tab blue, since it's not a new command, so it shouldn't be pink?

And can we come up with a new color tab for music and turtle, and draw it? These do use new commands, but these commands are adventure specific so they shouldn't be pink.

**Comment by Annelein** [comment]
@Felienne @MarleenGilsing this can be closed due to the new design? https://github.com/hedyorg/hedy/pull/5648
