### ISSUE TITLE
🪲 Favourite program undefined error at public profile

### ISSUE THREAD

**Issue by Annelein** [hedyorg/hedy#5131]
https://github.com/hedyorg/hedy/blob/48c28f9a9190809a17d303341d31122ba8861521/templates/public-page.html#L135

incorrect spelling: adventure=favorite_program

should be: adventure=favourite_program

<img width="1440" alt="Screenshot 2024-02-12 at 10 22 36" src="https://github.com/hedyorg/hedy/assets/48122190/1010f7f8-9c7c-4785-9409-88c8681e982d">

**Comment by Felienne** [comment]
Hi @Annelein!

I am not entirely sure how to reach the error page that you show here? I have tried clicking the star as admin but that does not fail.

**Comment by Annelein** [comment]
Sorry didn't make it clear enough, if you go to My Public Profile @Felienne
