### ISSUE TITLE
💻 Cannot unfavourite a program

### ISSUE THREAD

**Issue by Annelein** [hedyorg/hedy#5132]
After favouriting a program, there is no way to unfavourite it. It will just ask you the same question.

<img width="1433" alt="Screenshot 2024-02-12 at 10 25 51" src="https://github.com/hedyorg/hedy/assets/48122190/72ef2225-72e0-4759-954f-93d46b96fd65">

**Comment by Felienne** [comment]
Ahhhh good catch! Do you know why this happens? If so feel free to pick it up!

**Comment by Annelein** [comment]
@TiBiBa Hi! I think you have worked on this, could you maybe look into unfavouriting a program?

**Comment by TiBiBa** [comment]
Yes no problem, will look into this today!
