### ISSUE TITLE
🪲 Non-used variable warning not translated

### ISSUE THREAD

**Issue by TiBiBa** [hedyorg/hedy#5149]
**Describe the bug**
The warning string is still in English while Hedy is set to Dutch. Level 2, but I think this is an issue in general.

**Paste the Hedy code & level**
```
print Welkom bij restaurant Hedy
eten is hamburger
naam is ask wat is je naam?
Dus is jij wilt graag hamburger
Wat is wil je drinken?
Dus is jij wilt graag
```

**Add a screenshot (optional)**
<img width="1505" alt="Scherm­afbeelding 2024-02-14 om 09 58 13" src="https://github.com/hedyorg/hedy/assets/38155424/8da8f63d-2d86-40e0-82ba-eb503f930496">

**Comment by Felienne** [comment]
Hi @TiBiBa!

I think this is a content issue, the string has not yet been translated, see:

https://hosted.weblate.org/translate/hedy/web-texts/nl/?checksum=4f17ab4d8ddbbe9a&q=%22you+did+not+use+it%22&sort_by=-priority%2Cposition

(feel free to add a Dutch translation! 🙏 )
