### ISSUE TITLE
💻 Go back buttons

### ISSUE THREAD

**Issue by Annelein** [hedyorg/hedy#5155]
The "Go back" buttons are positioned all over the place and I feel like this button could look way more professional and consistent.
@gisellandrade could you look into this?
 
Naturally I would think of an arrow top left, because I think most "Go back" buttons are designed like that on other websites.
Or do we prefer one with text? @Felienne

'Go back to class' bottom right:
<img width="1440" alt="Screenshot 2024-02-15 at 13 44 06" src="https://github.com/hedyorg/hedy/assets/48122190/c30a335b-7b04-4fe7-b210-a460804bfa2b">
'Go back to teacher page' bottom left:
<img width="1440" alt="Screenshot 2024-02-15 at 13 44 26" src="https://github.com/hedyorg/hedy/assets/48122190/d6b62973-bae2-49c7-ab8e-4e41aaa12552">
'Go back to class' top right:
<img width="1440" alt="Screenshot 2024-02-15 at 13 44 41" src="https://github.com/hedyorg/hedy/assets/48122190/7aa7b3ac-340d-4b7a-ac2c-e1928fb81ef2">

**Comment by gisellandrade** [comment]
Hey, I've done this proposal. To put the go back button above the title always, having as a reference github and it's near to the back button of the browser header, so it won't be so difficult to recongnize the action, and just say on the button "go back" or maybe "back to (previous page)" in this case it would be teacher's page 

![image](https://github.com/hedyorg/hedy/assets/154460618/a6002014-5b70-4466-875f-b39c1a2e6e15)
![image](https://github.com/hedyorg/hedy/assets/154460618/a4785627-bde2-4295-a746-8d491b06bdb1)
