### ISSUE TITLE
Action buttons order and styles need to be standardized

### ISSUE THREAD

**Issue by gisellandrade** [hedyorg/hedy#5168]
Looking at this pages, the order of the action buttons below are different. It should have just one order and also a color and if its necessary an icon that represents the action that is going to get done to provide a better UX. 

![image](https://github.com/hedyorg/hedy/assets/154460618/ba74ff2f-c989-437e-9ea5-618c2dfa1b66)
![image](https://github.com/hedyorg/hedy/assets/154460618/969296f3-8e8d-41dd-9fbb-ea9183fe9eec)

**Comment by jpelay** [comment]
Hi Giselle! Do you want me to assign this issue to you and add it to your project board?

**Comment by gisellandrade** [comment]
Yes, assign it to me please!

**Comment by gisellandrade** [comment]
This is another proposal for these button 
![image](https://github.com/hedyorg/hedy/assets/154460618/3f1508c1-3979-4414-ade7-fbf1700783f5)
