### ISSUE TITLE
Unsupported operand type(s) for +📜

### ISSUE THREAD

**Issue by Jsgn3** [hedyorg/hedy#5170]
In level 18 I run below program and it reacts with:

![afbeelding](https://github.com/hedyorg/hedy/assets/160884004/1afdd0d5-6034-4e70-8782-00a55537d697)

Why is this? It concerns the line: midden= laag+hoog

As far as I know laag and hoog are numbers.

---

def round(x):

  y= 0

  while x> 0:
    x= x-1
    y= y+1

  return y

laag= 1
hoog= 10

print('Neem een getal van 1...', hoog, ' in gedachten...')

while laag!= hoog:
  midden= laag+hoog
  midden= midden/2

  midden= round(midden)

  print('Is je getal lager (0) of hoger of gelijk aan (1) dan ', midden, '?')
  a= input('0/1: ')

  if a!= 0 en a!= 1:
    print('Ongeldige keuze!')
  else:
    if a= 0:
      hoog= midden

    if a= 1:
      laag= midden

print('Ik denk dat je getal ', hoog, ' is')

**Comment by boryanagoncharenko** [comment]
I am unable to replicate the error you pasted. Since your snippet is missing formatting, could you please confirm that this is the code you run:
```
def round(x):
    y = 0
    while x > 0:
        x = x-1
        y = y+1
    return y

laag = 1
hoog = 10

print('Neem een getal van 1...', hoog, ' in gedachten...')

while laag != hoog:
    midden = laag+hoog
    midden = midden/2

midden = round(midden)

print('Is je getal lager (0) of hoger of gelijk aan (1) dan ', midden, '?')
a = input('0/1: ')

if a != 0 and a!= 1:
    print('Ongeldige keuze!')
else:
    if a = 0:
        hoog = midden

if a = 1:
    laag = midden

print('Ik denk dat je getal ', hoog, ' is')
```

**Comment by Jsgn3** [comment]
I am sorry for the missing formatting. This is the link to the program: 
   
  
      
   
   https://hedy.org/hedy/731760d10edc4798af03f7695263b1a0/view 
   
  
      
   
  
    The error I now get is: 
   
  
      
   
   
    
   
  
      
   
  
    Regards, 
   
  
    Jos 
   
  
      
   
  
      
   
   
   
     Op 27-03-2024 10:22 CET schreef boryanagoncharenko ***@***.***>: 
    
   
       
    
   
       
    
     
   I am unable to replicate the error you pasted. Since your snippet is missing formatting, could you please confirm that this is the code you run: 
   def round(x):
    y = 0
    while x > 0:
        x = x-1
        y = y+1
    return y

laag = 1
hoog = 10

print('Neem een getal van 1...', hoog, ' in gedachten...')

while laag != hoog:
    midden = laag+hoog
    midden = midden/2

midden = round(midden)

print('Is je getal lager (0) of hoger of gelijk aan (1) dan ', midden, '?')
a = input('0/1: ')

if a != 0 and a!= 1:
    print('Ongeldige keuze!')
else:
    if a = 0:
        hoog = midden

if a = 1:
    laag = midden

print('Ik denk dat je getal ', hoog, ' is')
