### ISSUE TITLE
🪲 Variables in Hedy can't start or end in underscore

### ISSUE THREAD

**Issue by jpelay** [hedyorg/hedy#5184]
If a variable starts with an underscore or ends in an underscore, then we will pick it as being an incomplete program. For example, this is level 2:

![image](https://github.com/hedyorg/hedy/assets/45865185/7cbbff32-fb01-47eb-8056-da49389e3fad)

![image](https://github.com/hedyorg/hedy/assets/45865185/8691fdc7-0355-47eb-a05d-d0a836b27cc3)

I think perhaps this should be allowed?

**Comment by boryanagoncharenko** [comment]
Based on the discussion in the closed PR, this is not functionality that we want atm.
