### ISSUE TITLE
💻 My programs page should also show program count

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#5192]
I went to a school yesterday, and the kids had some ideas!

Here is one:

Public profile shows the number of programs on the top:

<img width="770" alt="image" src="https://github.com/hedyorg/hedy/assets/1003685/7c87f8d5-fde4-4143-a892-0e678a8193f2">

Could we add it to my programs also?

**Comment by Annelein** [comment]
@Felienne if I understand correctly, just somewhere on the 'my-programs' page that indicates the amount of programs saved, right?
@gisellandrade could you maybe suggest a design for this? Then I can implement it!

**Comment by gisellandrade** [comment]
Yeeesss!! I'll be working on that, and leave it here once I get it done 😎

**Comment by Felienne** [comment]
> @Felienne if I understand correctly, just somewhere on the 'my-programs' page that indicates the amount of programs saved, right?

Yes!

**Comment by Annelein** [comment]
@gisellandrade have you worked on this yet?

**Comment by gisellandrade** [comment]
Not yet! I'll be working on that today

**Comment by gisellandrade** [comment]
Did you mean something like this? Do you want to add something? Did I get this right? 

![image](https://github.com/hedyorg/hedy/assets/154460618/0630af7b-5407-42c0-96e7-7cd94f8baede)

**Comment by Annelein** [comment]
> Did you mean something like this? Do you want to add something? Did I get this right? 
> 
> 
> 
> ![image](https://github.com/hedyorg/hedy/assets/154460618/0630af7b-5407-42c0-96e7-7cd94f8baede)
> 
> 

Hi @gisellandrade ! Thank you for working on it and reaching out. Something like that yes but now it looks kind of like a button right? But it should not be a button.

**Comment by gisellandrade** [comment]
What about this? This one looks a lot better, don't you think so? 

![Image](https://github.com/hedyorg/hedy/assets/154460618/b718449a-326a-4e1c-8e5a-2e53c67c80ae)

![Image](https://github.com/hedyorg/hedy/assets/154460618/0bc921ea-c6ba-4960-a684-f0024a54144e)

**Comment by Annelein** [comment]
This would be fine for this page, but we want it to be coherent to:

![Uploading Screenshot 2024-04-08 at 12.07.51.png…]()

Right @Felienne ? So @gisellandrade could you make a suggestion which makes this also looks nice on the my profile page?

**Comment by Felienne** [comment]
> This would be fine for this page, but we want it to be coherent to:
> 
> <img alt="Screenshot 2024-04-08 at 12 07 51" width="1440" src="https://private-user-images.githubusercontent.com/48122190/320441365-2775b85b-5dba-4c0b-9814-976a833830ba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI1NzM5NDgsIm5iZiI6MTcxMjU3MzY0OCwicGF0aCI6Ii80ODEyMjE5MC8zMjA0NDEzNjUtMjc3NWI4NWItNWRiYS00YzBiLTk4MTQtOTc2YTgzMzgzMGJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA4VDEwNTQwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUxZDQ2YjhkZjIxYjY1YjU1YjUxODRhNDBkMWIwZjJlZTNhYjdlOTAxZTNkZTBlYjE2N2YxNTllNjliZTM0NDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.0tHGdbRT_M_nSEcyVvkhXO85MiokIgkm0D_nrhzAVhw">
> Right @Felienne ? So @gisellandrade could you make a suggestion which makes this also looks nice on the my profile page?

Yes, we'd like those to be similar (maybe even sharing a partial template?) The only thin that would be different is the text part (the haaaaaaai here) and the avatar because if you have not set a profile, we do not have that text/picture.

**Comment by Annelein** [comment]
@gisellandrade [this](https://github.com/hedyorg/hedy/issues/5386) is the new issue, hopefully it explains it a bit better

**Comment by gisellandrade** [comment]
Oooh, I get it. I'll be working on that, so it can match both sides.

**Comment by Annelein** [comment]
> Oooh, I get it. I'll be working on that, so it can match both sides.

Amazing!! Thank you! You can post it in there, as this will probably be closed by then.
