### ISSUE TITLE
💻 change calculation and phrasing of number of programs in profile page

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#5193]
Here is another remark from yesterday's school, in your public profile, why is there "programs created" and "programs saved", what is the difference?

<img width="779" alt="image" src="https://github.com/hedyorg/hedy/assets/1003685/b38323af-0593-4297-872f-0663b3bdf807">

I suspect this is legacy from when we really had a save button! IN the current state of things, where a run is a save, what does this mean?

And even more general (this is my note, not from the kids...) what does programs created mean? Should we use the new system here that @jpelay made in #5162 so we count the actual changed adventure codes (and change the label into something like "number of adventures completed" or "number of adventures tried" ?

**Comment by jpelay** [comment]
>  And even more general (this is my note, not from the kids...) what does programs created mean? Should we use the new system here that @jpelay made in #5162 so we count the actual changed adventure codes (and change the label into something like "number of adventures completed" or "number of adventures tried" ?

I like this idea! Gives more of a sense of completion I think! It'll be a little weird for kids that just use the editor to program their own thing as opposed to competing the adventures, but for students in a class I think it makes a lot of sense!

**Comment by Annelein** [comment]
@Felienne now 'programs saved' correspondents with the total of 'My programs', would this also mean that it's needed to implement that only a program becomes 'My program' once the adventure code is actually changed?

**Comment by Felienne** [comment]
Yes that sounds like a sensible idea! Because we used to have explicit save
the way we did it made sense before but not anymore

**Comment by Annelein** [comment]
> @Felienne now 'programs saved' correspondents with the total of 'My programs', would this also mean that it's needed to implement that only a program becomes 'My program' once the adventure code is actually changed?

@jpelay is this possible with #5162 ? https://github.com/hedyorg/hedy/blob/8a2c0679c363afa3338db31fd45932993e9c6a5a/website/statistics.py#L215

Because for that function you need a program but depending on that function, you want it to be saved as a program or not.

**Comment by jpelay** [comment]
> > @Felienne now 'programs saved' correspondents with the total of 'My programs', would this also mean that it's needed to implement that only a program becomes 'My program' once the adventure code is actually changed?
> 
> @jpelay is this possible with #5162 ?
> 
> https://github.com/hedyorg/hedy/blob/8a2c0679c363afa3338db31fd45932993e9c6a5a/website/statistics.py#L215
> 
> Because for that function you need a program but depending on that function, you want it to be saved as a program or not.

I think so! It should be possible, but you'd need to pass all of the adventures and the teacher adventures that the student might have completed.

**Comment by jpelay** [comment]
> @jpelay and how would it work with having to pass a program, but depending on that function, you want it to be saved as a program or not. So the 'program' does not exist yet?

I think in this case the program does exist. We would automatically save the program just as we do right now, but we'd filter the programs we show on the basis of whether they're modified or not; or even show them, but as Felienne says, instead of saying: "X programs created", display: "X adventures completed/tried", and this would be the result of iterating through the programs and then adding the ones for which `is_program_modified` returns true.
