### ISSUE TITLE
🪲 Discrepancy in program count

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#5199]
One more from the same school.

It seems teachers see a really different number of programs than students. Here is an example where that happens for user Sofie1bs:

![IMG_7851](https://github.com/hedyorg/hedy/assets/1003685/4c987026-4d57-4a36-a513-4582fa8515d9)

Other kids in the class also had counts over a hundred. But the teacher sees this:

<img width="1001" alt="image" src="https://github.com/hedyorg/hedy/assets/1003685/4009e281-fae9-4c26-bd6e-1b7b2eba6518">

**Comment by Felienne** [comment]
Maybe another small one for you @hasan-sh? No rush though, more of a palet cleanser between cypress tests and the translation pipeline?

**Comment by hasan-sh** [comment]
@Felienne could you explain what the problem here is?

**Comment by Felienne** [comment]
As explained in the images, the user shown has 147 programs in their own
public page, but only 4 when seen from the teacher's view (I blacked out
the names of the other students on the second picture, maybe that is
confusing?)

**Comment by hasan-sh** [comment]
> 147 programs in their own public page, but only 4 when seen from the teacher's view

Correct! The problem was that in their public page, the `created programs` count is actually the account of how many times they run a program; `run_programs` property from the achievements table. I've changed that to work as the labels suggests; i.e., the number of created programs.
