### ISSUE TITLE
💻 Highlighted line of code in debugger, running step by step, should be the former line?

### ISSUE THREAD

**Issue by juliabolt** [hedyorg/hedy#5203]
Right now, when we run a program step by step in Hedy, the line that is highlighted, is the line that will be executed next, not the line that has just been executed. Is that logical? Do we want this? I would think we want to highlight the line that has just been executed, or maybe even both, but in a way that we make clear which line has already been executed and which line is the next one to be executed.

**Comment by Felienne** [comment]
Yes this is a bit different from VS code or other tools, but this is what Skulpt does, so it would be hard to change
