### ISSUE TITLE
🪲 Switching to another tab with an ask prompt open, causes the program to mix up

### ISSUE THREAD

**Issue by jpelay** [hedyorg/hedy#5211]
**Describe the bug**
To reproduce this bug do the following:

1. Student beging to runs program
2. Then student switches to another adventure, while previous program still has an ask propmpt open
3. When the student runs the new program, somehow skulpt still is processing the old ask prompt (handled internally as a promise), and then everything gets mixed up

**Comment by AnneliesVlaar** [comment]
I noticed the same problem when I used ``` if key is pressed ```.

**Comment by jpelay** [comment]
> I noticed the same problem when I used `if key is pressed`.

Yes, that happens because the ask command and the ifpressed command use the same internal mechanism!
