### ISSUE TITLE
🪲 Exceptions that come from Skulpt don't format commands correctly

### ISSUE THREAD

**Issue by jpelay** [hedyorg/hedy#5252]
For example, consider this screenshot:
![image](https://github.com/hedyorg/hedy/assets/45865185/d21db8b1-7300-461f-ae62-21509b498531)

Here, ask should be shown like forward, but for some reason that doesn't work. Gotta investigate why this happen and how to solve this.

**Comment by boryanagoncharenko** [comment]
Resolved by #5275
