### ISSUE TITLE
🪲 Previewing a large adventure messes up the modal

### ISSUE THREAD

**Issue by jpelay** [hedyorg/hedy#5261]
**Describe the bug**
If you have an adventure that is too long, if I try to preview it, the modal can't show me the close button because it overflows the available space in the screen.

![image](https://github.com/hedyorg/hedy/assets/45865185/6b71cd1b-7e60-4e6f-9a80-fa416035753c)

.

**Paste the Hedy code & level**
It is super helpful if we can copy-paste the Hedy code to test, so please paste the code here, and don't forget to tell us what level you were in.

**Add a screenshot (optional)**
Make a picture or screenshot to show the issue. Tip! You can make a screenshot and simply paste the image into GitHub with ctrl-v.

**What machine and browser you were using (optional)**
If the issue concerns things in the website, let us know:
- What computer you are using (Windows, Mac, Linux?)
- What browser you were using (Chrome, Edge, Safari)

**Comment by Annelein** [comment]
isn't this the same as #5152 ?
