### ISSUE TITLE
📜What to do with Tic-Tac-Toe 

### ISSUE THREAD

**Issue by MarleenGilsing** [hedyorg/hedy#5268]
We have a Tic-Tac-Toe adventure starting from level 13. It is cool that we have it, but it's never explained how the example code works. 

It uses the line
```
print field at 1 field at 2 field at 3
```

But this line is never explained. Is `at` a new command? Do we want it to be? 
@Felienne Maybe we can discuss this next week, when we meet.

**Comment by Felienne** [comment]
Hi @MarleenGilsing!

Good point. The `at` is not really new, it is like the `at random` but then with a number, like we do for the friends code in level 16. It should indeed be explained somewhere (maybe just here?)

**Comment by MarleenGilsing** [comment]
WIth the new Tic Tac Toe, Hangman and Simon Says adventures done, I'm closing this issue.
