### ISSUE TITLE
🪲 adding an adventure to classes

### ISSUE THREAD

**Issue by hasan-sh** [hedyorg/hedy#5289]
**Describe the bug**
When i create/clone an adventure and add it to an existing class, an error occurs!
![image](https://github.com/hedyorg/hedy/assets/20051470/ef881300-3f62-4b0d-8dd0-b72031ce422d)

@Annelein I thought i mentioned we should use `.get(..)` in case we're accessing new properties that may or may not exist?! I see you changed it in one place and likely forgot other places, but we need to do convert them all!

**Comment by Annelein** [comment]
> **Describe the bug** When i create/clone an adventure and add it to an existing class, an error occurs! ![image]
Can you add a screenshot video of when this happens? It's not really clear. 

> @Annelein I thought i mentioned we should use `.get(..)` in case we're accessing new properties that may or may not exist?! I see you changed it in one place and likely forgot other places, but we need to do convert them all!

> Check if the adv does exist before removing it!
This is all you told me, which I solved, so no you didn't mention that. I've never had the issue you just described. But if you share a screenshot video I will look into it straight away.

**Comment by Annelein** [comment]
Already found the bug solving it now
