### ISSUE TITLE
🪲 Variables can't start with a number

### ISSUE THREAD

**Issue by AnneliesVlaar** [hedyorg/hedy#5299]
**Describe the bug**
If a variable starts with a number it's not recognised as a variable.

**Paste the Hedy code & level**
This is in level 2
![afbeelding](https://github.com/hedyorg/hedy/assets/66774020/35e38adf-c2c5-4985-aaf9-6fd2e7fe21b3)

**Comment by Felienne** [comment]
Yeah that's Pythons var convention so that is ok I think
