### ISSUE TITLE
🪲 adding an adventure to multiple classes gives multiple levels warning

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#5305]
**Describe the bug**

<img width="715" alt="image" src="https://github.com/hedyorg/hedy/assets/1003685/b8c749d0-68aa-4a47-a462-c781e3bdc9dd">

**Comment by hasan-sh** [comment]
Duplicate of https://github.com/hedyorg/hedy/issues/5290

**Comment by Felienne** [comment]
Sorry!
