### ISSUE TITLE
🪲 Forward command failing

### ISSUE THREAD

**Issue by boryanagoncharenko** [hedyorg/hedy#5322]
**Describe the bug**
In levels 2 and 3, the forward command cannot transpile correctly variables that are also reserved keywords, e.g. `all`, `time` etc.

**Paste the Hedy code & level**
Level 2
```
time is 10
forward time
```

**Add a screenshot (optional)**
<img width="521" alt="Screenshot 2024-03-27 at 12 07 20" src="https://github.com/hedyorg/hedy/assets/3010723/1d4b4522-9e23-43bc-8f63-34d71c94a1c8">

**Comment by karimsellami2024** [comment]
i Have encountered the same problem , the bug is still present . i notice that there is another opened issue that dates back to november . is someone working on it or would it be possible for me to look for and suggest a solution ?

**Comment by boryanagoncharenko** [comment]
I did not realize there is another issue opened for this bug, so I created this one.
I am assigning the issue to you. Feel free to have a look and if you need any help, I'd be happy to assist.

**Comment by boryanagoncharenko** [comment]
Addressed in #5676
