### ISSUE TITLE
🪲 Translating keywords in teacher adventures causes the program to be translated in the database

### ISSUE THREAD

**Issue by jpelay** [hedyorg/hedy#5328]
If I log in as a student and change the language of the keywords, aftewards the adventure is always shown in the translated language in the UI

**Comment by jpelay** [comment]
Further investigation suggests that the problem was not caused by #5253, since it was also present on previous versions of Hedy.

**Comment by Felienne** [comment]
Closed by [#5350](https://github.com/hedyorg/hedy/pull/5350)
