### ISSUE TITLE
🪲Added as teacher: unable to see 'live statistics' and 'overview programs per adventure'

### ISSUE THREAD

**Issue by moluccagit** [hedyorg/hedy#5330]
I was added as a teacher to a class by another teacher. However, when I am in the page of this class, I am not able to view the 'live statistics' or 'overview programs per adventure'. I get the following:

![hedybug](https://github.com/hedyorg/hedy/assets/78602819/c4368759-996e-4832-a5c1-a1a087e35fb1)

 using Mac, Firefox

Also, another bug seems to appear when the main teacher **is** able to see the content of these pages: an adventure that was created and added to this class (it was in Level 6, student's were able to do the adventure) is not visible in the 'overview programs per adventure' 

@hasan-sh I guess I should tag you! 
Hope this is clear enough, let me know if you need additional info.

**Comment by El-Houssein-bedoui** [comment]
Hey , this bug has already been declared and **already assigned** to someone
🧹 Remove live statistics #5047:
https://github.com/hedyorg/hedy/issues/5047

**Comment by El-Houssein-bedoui** [comment]
Hey , this bug has already been declared and **already assigned** to someone
🧹 Remove live statistics #5047 .
