### ISSUE TITLE
🪲 Yellow-btn does not appear when using the French language

### ISSUE THREAD

**Issue by karimsellami2024** [hedyorg/hedy#5342]
**Describe the bug**
When i changed the language from english to french there is no  yellow-btn as a name in the code . 

**Paste the Hedy code & level**
the code part is present in the screenshot i provided down below . If there is any other way i can share the code please enlighten me .

i was in the level 1 / rock paper scissors . 

this is the french version : 
![image](https://github.com/hedyorg/hedy/assets/165578103/fcd79c8f-fa97-4378-be3e-d6a4b2b96afb)
this is the english version : 
![image](https://github.com/hedyorg/hedy/assets/165578103/3529bac6-a7d1-4ca3-91da-54f947944811)

i am using the chrome browser on windows 11 .

**Comment by Felienne** [comment]
Thanks for letting us know @karimsellami2024! This is not so much an issue with the button as an error in typescript, somehow. I cannot reproduce the problem though on my machine. Is there a list of steps you can share where the issue always occurs? That would help in debugging!

(pinging @hasan-sh who might be able to also take a look)

**Comment by hasan-sh** [comment]
Same here @karimsellami2024!

**Comment by karimsellami2024** [comment]
Hello , i remember changing the language and the country before finding out that the yellow btn was missing , at first i didn t think that it would impact the creation of the bug , but since it doesn t appear right away i will try to reproduce the steps i did and i will keep you informed guys . thanks .

**Comment by Felienne** [comment]
By best guess is that this was a timing issue, sometimes it takes a while for the front-end code to load and then you get in this exact situation. Let me know if it happens again!
