### ISSUE TITLE
> The info text that appears by clicking the (i) button should be replaced.

### ISSUE THREAD

**Issue by hasan-sh** [hedyorg/hedy#5356]
> The (i) text appears in a weird place:

The one I pasted above shows all the way at the bottom:

<img width="1251" alt="image" src="https://github.com/hedyorg/hedy/assets/1003685/520a537a-abce-4c9f-8395-2cb9dd69491a">

Should be above with the (i) I guess?

_Originally posted by @Felienne in https://github.com/hedyorg/hedy/issues/5311#issuecomment-2029849480_

**Comment by Annelein** [comment]
@gisellandrade can you take a look at this one too?

**Comment by gisellandrade** [comment]
What do you think about this?  
@Felienne @hasan-sh @Annelein 
![Image](https://github.com/hedyorg/hedy/assets/154460618/e2fd41c0-45a7-4676-843d-e8ba9e271c61)

**Comment by Annelein** [comment]
> What do you think about this? @Felienne @hasan-sh @Annelein ![Image](https://private-user-images.githubusercontent.com/154460618/320628731-e2fd41c0-45a7-4676-843d-e8ba9e271c61.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI2NzM5MDcsIm5iZiI6MTcxMjY3MzYwNywicGF0aCI6Ii8xNTQ0NjA2MTgvMzIwNjI4NzMxLWUyZmQ0MWMwLTQ1YTctNDY3Ni04NDNkLWU4YmE5ZTI3MWM2MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwOVQxNDQwMDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xNzJiZGMwYmVlNTNiODEyZGE4NWMxMTc3MmZmM2UxYmJjMGRiOTZlMTVkMDMyMDU0MDI4NTA4YWJkNjc5NzNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.oqX50hnXtqKlan4QupBVJga3KWJ7ceWq1M4maEH3mFo)

So it pops open if you click it and closes the second time you click? I could live with it, it would look more like our other designs then what it looks like now.

**Comment by gisellandrade** [comment]
Yep, just like that. That's how tooltips usually works

**Comment by Annelein** [comment]
@Felienne @hasan-sh what do you think? Then I can start implementing it

**Comment by Felienne** [comment]
Yes that looks like the right place! I am not sure we want the editor to go down, is that the suggestion? That type of moving stuff around in the UI I find a bit confusing.

Could we do modal that looks like this (not the colorfull kid-modal we have now), so this in a modal:

<img width="252" alt="image" src="https://github.com/hedyorg/hedy/assets/1003685/a145209f-4b2a-4ad6-8f1b-28e7ecd882ca">

Somewhere close to the (i) icon? 

I think we wanted to make a "adult facing" modal anyway, maybe we can start here?

**Comment by Annelein** [comment]
I'm not sure if I really like a modal. Because I can image it would be nice to have the info text visible while you're editing the adventure. Instead of having to open it every time you want to read it or don't understand something? Let me know if you understand what I mean? 

What about an "information" slide that opens up on the right side of the screen, which doesn't overlap anything on the page, but just makes the page smaller? Kind of like the inspect, maybe a strange example haha, but I think visualizing something can be helpful:

https://github.com/hedyorg/hedy/assets/48122190/ac653106-03de-4041-86d0-aae27d85f48c

**Comment by Felienne** [comment]
> I'm not sure if I really like a modal. Because I can image it would be nice to have the info text visible while you're editing the adventure. Instead of having to open it every time you want to read it or don't understand something? Let me know if you understand what I mean?
> 
> What about an "information" slide that opens up on the right side of the screen, which doesn't overlap anything on the page, but just makes the page smaller? Kind of like the inspect, maybe a strange example haha, but I think visualizing something can be helpful:
> 
>  Screen.Recording.2024-04-10.at.16.10.27.mov

I love that idea!! I guess we can use it in other places too!

**Comment by Annelein** [comment]
@gisellandrade what do you think of this idea? And @hasan-sh curious what you think as well?

**Comment by gisellandrade** [comment]
I really like that idea, that you don't really need to open it, but the info is just there. Let me see how it would look like, and I'll put it over here.

**Comment by Annelein** [comment]
@gisellandrade I did mean that you would have to click something to open it, so that if you don't want to see it, you can also close it. Or did you get that part?

**Comment by gisellandrade** [comment]
@Annelein Yes, I got that part. But, the thing is that there's not like a lot of text, and half of the screen would be empty. I'm not sure if that would look good 😕

**Comment by Annelein** [comment]
@gisellandrade ah yes I get that! Great if you could look into it!

**Comment by hasan-sh** [comment]
I like it and I think we should implement this drawer in a generic way such that it expects some html. It'd work similar to opening an issue in the board meeting of Github:

[Screencast from 11-04-24 15:46:42.webm](https://github.com/hedyorg/hedy/assets/20051470/3522d45e-63f7-4e4d-96c6-95b874d59cf4)


The size we control so it doesn't need to be this wide. Also, we can gradually enhance it according to our needs.

**Comment by gisellandrade** [comment]
This is the best I could find, let me know what you think! 
![image](https://github.com/hedyorg/hedy/assets/154460618/e30d8eec-99a5-476e-b5c0-b24ae9836cdd)

**Comment by hasan-sh** [comment]
> This is the best I could find, let me know what you think! ![image](https://private-user-images.githubusercontent.com/154460618/322679602-e30d8eec-99a5-476e-b5c0-b24ae9836cdd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNjY0NjAsIm5iZiI6MTcxMzI2NjE2MCwicGF0aCI6Ii8xNTQ0NjA2MTgvMzIyNjc5NjAyLWUzMGQ4ZWVjLTk5YTUtNDc2ZS1iNWMwLWIyNGFlOTgzNmNkZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNlQxMTE2MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNDhiZmIyZmRhMWVhMTM0YjcyMzM1MDkxMTM0YzAwN2IzZmIxMDlkZjY4ZWY5ZTgwNzU4MjUwZGZjM2JlMDVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZC1XI-UzgzK5ZEHeoNHEo9GGD4u160dY7rG-ZrZB4bY)

I think it should rather be a menu that doesn't change the view width! What do you think about what i commented up? I think we could implement a generic drawer! We could also simply show a modal!!

**Comment by Annelein** [comment]
Lets discuss this in the meeting?

**Comment by gisellandrade** [comment]
> > This is the best I could find, let me know what you think! ![image](https://private-user-images.githubusercontent.com/154460618/322679602-e30d8eec-99a5-476e-b5c0-b24ae9836cdd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMyNjY0NjAsIm5iZiI6MTcxMzI2NjE2MCwicGF0aCI6Ii8xNTQ0NjA2MTgvMzIyNjc5NjAyLWUzMGQ4ZWVjLTk5YTUtNDc2ZS1iNWMwLWIyNGFlOTgzNmNkZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNlQxMTE2MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yNDhiZmIyZmRhMWVhMTM0YjcyMzM1MDkxMTM0YzAwN2IzZmIxMDlkZjY4ZWY5ZTgwNzU4MjUwZGZjM2JlMDVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZC1XI-UzgzK5ZEHeoNHEo9GGD4u160dY7rG-ZrZB4bY)
> 
> I think it should rather be a menu that doesn't change the view width! What do you think about what i commented up? We could also simply show this info in a modal!!

What do you think about this? Just for smalls screen, or maybe like using it always? so we don't have that problem with differents screens? @Annelein @hasan-sh 

![image](https://github.com/hedyorg/hedy/assets/154460618/e4ece4d6-c16e-4e54-b553-7cd5a9859cea)

**Comment by Annelein** [comment]
@Felienne @gisellandrade @hasan-sh what do you think? (the top of the border is not visible in the screenvideo somehow)



https://github.com/hedyorg/hedy/assets/48122190/64ae40b4-5c38-4eaf-b1b8-87892bf1a041

**Comment by gisellandrade** [comment]
I think this way looks awesome! I really like it :)
