### ISSUE TITLE
The run Code functionality doesn't  work in the explore page

### ISSUE THREAD

**Issue by El-Houssein-bedoui** [hedyorg/hedy#5357]
When opening a public adventure and try to run the code an error is displayed 
here is the actual error , this happens in every single code : 
![image](https://github.com/hedyorg/hedy/assets/141435410/3fb5ef25-255f-4444-a943-49821c6f6ea2)
![image](https://github.com/hedyorg/hedy/assets/141435410/9b1577e7-a0e4-4c36-86db-ae331d8b8776)

Current environment: Opera , windows 11 .

**Comment by El-Houssein-bedoui** [comment]
> **Describe the issue** In the explore Page , when clicking on the Dropdown bar to display the categories , the Puzzle option is missing. **Add a screenshot (optional)** The first image is the Puzzle category present in the levels : ![image](https://private-user-images.githubusercontent.com/141435410/318990134-b871e3fb-3f91-48ff-8f15-5ba288133ec0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxMDk1MDQsIm5iZiI6MTcxMjEwOTIwNCwicGF0aCI6Ii8xNDE0MzU0MTAvMzE4OTkwMTM0LWI4NzFlM2ZiLTNmOTEtNDhmZi04ZjE1LTViYTI4ODEzM2VjMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwM1QwMTUzMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iY2YwYjYyMTRmNWM0NjQzYzVjMmUzNDQxZjgwY2JlMTRiM2I3NGY0ZjgxZTU5Mjc5ZmY2ZmEwMzg5OTVlMWQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.F-B6dWbPWI3NGzvt1um3TLZO0XNy1N3hlDjGUHsr_lc) The second image is the current Dropdown bar missing the Puzzle option: ![image](https://private-user-images.githubusercontent.com/141435410/318990426-b7f9e85c-d404-4c86-8878-07ce784d7eff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIxMDk1MDQsIm5iZiI6MTcxMjEwOTIwNCwicGF0aCI6Ii8xNDE0MzU0MTAvMzE4OTkwNDI2LWI3ZjllODVjLWQ0MDQtNGM4Ni04ODc4LTA3Y2U3ODRkN2VmZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQwM1QwMTUzMjRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jN2U4MzZiOTNjMGM0MDQ4NTVlMDc3YWM1ODU2OTRiYmViZDA4ZDFmMTE0ZmY4Yzk3NGIzYWU4ODc5M2M3ZWEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Umuo0z1u3WH8AajTRJ6dpjuTduM6nM4MgGuW3pvRvjs)
> 
> Current Browser: Opera , Windows 11

**Comment by Felienne** [comment]
Thanks for letting us know! @hasan-sh will take a look when he can!

**Comment by TiBiBa** [comment]
I think #5361 solves this issue, but not sure!

**Comment by Felienne** [comment]
> I think #5361 solves this issue, but not sure!

Yes, indeed, thanks a lot!!
