### ISSUE TITLE
🪲 Public adventures 'no adventures available'

### ISSUE THREAD

**Issue by MarleenGilsing** [hedyorg/hedy#5367]
**Describe the bug**
I sometimes get the message that there are no public adventures available on this level, while there are. When I get that message, I can't select another level and I'm stuck on this page. 

![image](https://github.com/hedyorg/hedy/assets/80678586/28efbcd6-fa78-438c-b9e3-95a6fb9f0c4a)

If you reload the page, everything is fine, but I had this happen a couple of times now. 

**What machine and browser you were using (optional)**
Windows, chrome

**Comment by hasan-sh** [comment]
Obviously this doesn't happen on testing nor alpha. It could be due to the amount of adventures there are on beta. Will look into it more!
