### ISSUE TITLE
🪲 duplicate adventures

### ISSUE THREAD

**Issue by hasan-sh** [hedyorg/hedy#5375]
**Describe the bug**
Something is off when you want to create an adventure. Currently we append an X to the adventure's name to avoid duplicates. This doesn't seem to work. 

How to reproduce? Create an adventure, you'd see it has the same name as other adventures. If not, create another adventure and you'd get a duplicate error if you try to save. 

This is very problemetic since the content of adventures would dissapear from the code page due to duplicate adventures.

[Screencast from 08-04-24 10:52:17.webm](https://github.com/hedyorg/hedy/assets/20051470/5dbbbcbb-43b7-4d0a-bc70-a505e8fd5026)

**Comment by hasan-sh** [comment]
I'm working on this right away since it's quite urgent.

**Comment by Annelein** [comment]
> I'm working on this right away since it's quite urgent.
Could you check in with me next time, I was already working on it.

**Comment by hasan-sh** [comment]
Did you start before today? Cuz this morning Felienne asked me to do so! Therefore, i removed your assignement and put a comment. Anyway, it's not a big deal because I didn't find a solution, did you?!

**Comment by hasan-sh** [comment]
> I started this morning. I cannot reproduce the issue... How did you manage to get AdventureXX twice?

Just updated the issue description with a video. This is on alpha. Beta has the same issue.
