### ISSUE TITLE
🪲 Stepping while debugging with turtle removes canvas.

### ISSUE THREAD

**Issue by antoineveldhoven** [hedyorg/hedy#5405]
While debugging a turtle program the canvas element disappears from the DOM after second step / line.

Level 1 > Tekenen (2nd example 5-line code)

<img width="1716" alt="First line" src="https://github.com/hedyorg/hedy/assets/14979232/6d7d6324-ea00-4450-a39e-111178375270">
First step / line while debugging (notice the canvas element)

<img width="1722" alt="Scherm­afbeelding 2024-04-11 om 17 40 08" src="https://github.com/hedyorg/hedy/assets/14979232/7d60ee6c-bfb0-4cac-a792-ebc0f107a281">
Second step / line while debugging (notice the canvas element)

<img width="1727" alt="Scherm­afbeelding 2024-04-11 om 17 40 15" src="https://github.com/hedyorg/hedy/assets/14979232/9cb3bbae-0a99-4617-beeb-c9f8798e73ef">
Third step / line while debugging (notice the canvas element is missing)

Could reproduce on Chromebook and on Mac FF

**Comment by jpelay** [comment]
This was fixed by #5673
