### ISSUE TITLE
💻 variable list appearing automatically

### ISSUE THREAD

**Issue by juliabolt** [hedyorg/hedy#5408]
Now, the variable list is shown automatically after every run, because we wanted to give it more attention. Maybe this is now becoming too much, so we should either:
1) make the list appear when debugging (running step by step with the ladybug), but not when running normally.
2) make the list appear only a short amount of time, like 1 second, and then it hides again. users can view the list again by clicking the label icon.

**Comment by Felienne** [comment]
Our proposed solution for now is:

* Open when the debugger is used
* Closed when you run normally, like we have it!

**Comment by Felienne** [comment]
In the meantime we will think of a nicer way!

**Comment by AnneliesVlaar** [comment]
I have painted some idea's on how to display the variables.

This is how the variables are displayed now on top of the output field:
![Hedy-current-variabele-display](https://github.com/hedyorg/hedy/assets/66774020/25ee640a-2f16-43dd-92d5-2df35a0fa3a0)

My first suggestion was to copy the display of errors i.e. a pop-up at the bottom of output field:
(and than make the output field smaller such that the pop-up isn't on top of the output field.)
![Hedy-bottom-pop-up](https://github.com/hedyorg/hedy/assets/66774020/33bbd124-958a-4b6d-a31c-086844f69fed)
There can be a cross to close this pop-up, but then there should also be a button to get it back. I would suggest a button that is close to the pop-up. Here it is in between the green buttons under the output field. 

I think all solutions will get worse if the content of variables become larger. This is how it appears now if a variable contains a large string. 
![Hedy-current-variabele-display-long-var](https://github.com/hedyorg/hedy/assets/66774020/64f8df8e-5b16-4d04-b5db-fb98e15dd5dd)

This can be prevented when long variables are cut off and displayed with dots at the end. Combined with a pop-up at the bottom, you maybe can preview 8 variables :
![Hedy-bottom-pop-up-long-var](https://github.com/hedyorg/hedy/assets/66774020/7a8ecb2e-d7e7-407d-bb95-5ddb468598b9)

Then you still somehow want to see all the content of the variables at once. This could be achieved by expanding the pop-up:
![Hedy-bottom-pop-up-extended-long-var](https://github.com/hedyorg/hedy/assets/66774020/86c1c552-c737-4063-9261-3522c27ecf81)

This hides the output field, which is not handy when debugging. Another suggestion was to put it to the side of the output field. 
The input field and output field would have to squeeze in a bit:
![Hedy-right-window-extended](https://github.com/hedyorg/hedy/assets/66774020/f50f7d98-ae9e-499c-9e44-19e92ec1e38b)

I don't know how you can give the impression that something is there (what students want/should check out). But in this solution I think you can't always show (a preview of) the variables.
![Hedy-right-window-no-show](https://github.com/hedyorg/hedy/assets/66774020/0e7ee254-c68a-4f3d-a6bc-bbfe3eaf9f2b)

**Comment by juliabolt** [comment]
very nice ideas Annelies! I think those options would definitely be an improvement compared to how it works now!
