### ISSUE TITLE
💻 Add a new language button

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#5426]
**Idea incl level**
In the menu of languages, we can add a button "add your language" to go to Weblate directly:

<img width="624" alt="image" src="https://github.com/hedyorg/hedy/assets/1003685/3841741d-84c2-4785-9272-6f86c80a1218">

Stolen from Wordplay:
<img width="709" alt="image" src="https://github.com/hedyorg/hedy/assets/1003685/cec641b0-ff6a-46fe-8bc4-da269685e9dd">

**Comment by Annelein** [comment]
@Felienne what is the link for adding a language in Weblate?

**Comment by Annelein** [comment]
![Image](https://github.com/hedyorg/hedy/assets/48122190/3c659162-1b92-45f3-bf7a-003f9c0bb459)

@Felienne would it make sense to also add the button somewhere here? Because if you already have an account, you won't see the other button anymore and this would be the place where you would look for a language?

**Comment by Felienne** [comment]
> ![Image](https://private-user-images.githubusercontent.com/48122190/323237381-3c659162-1b92-45f3-bf7a-003f9c0bb459.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMzNjE1ODksIm5iZiI6MTcxMzM2MTI4OSwicGF0aCI6Ii80ODEyMjE5MC8zMjMyMzczODEtM2M2NTkxNjItMWI5Mi00NWYzLWJmN2EtMDAzZjljMGJiNDU5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE3VDEzNDEyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE3Njg0ZWFjYTVhMGVhNTQ2MGY4MDc0MWUwZjJjMjc4ZjYxMzI5ZDRmODRiYTVmYzg5OGNkMzU5ZjRkYzZhYzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rnVy-WvHoJQlJLUtXEhI6yqkQ-NVeh0ccnszmn5zPOY)
> 
> @Felienne would it make sense to also add the button somewhere here? Because if you already have an account, you won't see the other button anymore and this would be the place where you would look for a language?

Ow this is a great idea, yes!

**Comment by Felienne** [comment]
> @Felienne what is the link for adding a language in Weblate?

https://hosted.weblate.org/new-lang/hedy/adventures/
