### ISSUE TITLE
💻 Two new fields in the sign up page for teachers

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#5428]
In https://github.com/hedyorg/hedy/issues/5212 we added a tickmark for pairing, we need one more, for student/company support that we are going to roll out soon(ish):

[ ] I would like to be connected with a guest teacher who can give a few lessons (tickmark)

If this is ticked, we want the teacher's phone number too

**Comment by Annelein** [comment]
@Felienne do you just want me to do the backend or also the frontend?

**Comment by Felienne** [comment]
> @Felienne do you just want me to do the frontend or also the backend?

Backend too, we can just add two columns on the teacher field, I will look at them for now (in the future, SuperTeachers could maybe also arrange this)
