### ISSUE TITLE
📜The translation is missing in the " Pour les enseignants " window. 

### ISSUE THREAD

**Issue by karimsellami2024** [hedyorg/hedy#5441]
**Describe the issue**
What level, language and adventure does this concern?

This is present in the option " Pour les enseignants " , i have been using Hedy in french and just noticed that this part was not translated . I figured that i could translate it for the project as it is quite simple   yet important for teachers using Hedy to understand the way it works . 

**Add a screenshot (optional)**

![image](https://github.com/hedyorg/hedy/assets/165578103/9de18462-bee6-47e2-96b1-53fb28bf085e)

**Comment by Felienne** [comment]
See Discord
