### ISSUE TITLE
💻 Slides layout

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#5457]
reported by @LegoPink:

On my Chromebook, and on the TV in my classroom, the teacher slides look like this. Request: smaller left and right margins / padding, resulting in wider code and output.

![image](https://github.com/hedyorg/hedy/assets/1003685/c924f65d-69c9-49ed-b7ad-8a495f6a4482)

**Comment by LegoPink** [comment]
Also, when presenting on the tv, the "Voer de code uit" button is not visible. The code window is too tall. During the lesson yesterday, I opened Developer Tools, which scaled the page, and the button became visible again.

**Comment by Felienne** [comment]
> Also, when presenting on the tv, the "Voer de code uit" button is not visible. The code window is too tall. During the lesson yesterday, I opened Developer Tools, which scaled the page, and the button became visible again.

Thanks! Do you happen to know the resolution of the tv, so we can test it on that?

**Comment by Annelein** [comment]
@hasan-sh I've been trying to change the size of "slides" which is set at 960px. But I think it is set bij "reveal" from iFrame, could you maybe take a look?
