### ISSUE TITLE
📜 Improve phrasing in level 2 example

### ISSUE THREAD

**Issue by hrj** [hedyorg/hedy#5461]
In Level 2, English, I see two potential confusions:

### First confusion

 ```
                    name {is} Hedy
                    age {is} 15
                    {print} name is age years old
```

The word `is` in the print statement was confusing to my kid, because it looks the same as the `is` in the previous two statements which have a completely different meaning in the language.

I don't know how to tackle this without being too verbose. For example, you could modify the print statement as
```
  {print} name happens to be age years old
```

### Second confusion

This one is simpler:

```
                    favorite_animals {is} _
                    {print} I like favorite_animals
```

Instead of plural `favourite_animals`, using singular would be better: `favourite_animal {is} ...`

The plural makes it appear as if a list of animals is expected.

**Comment by Felienne** [comment]
Great catch on the second one, that indeed should be singular to avoid confusion (I will make an issue for our content developer)

As for the first one I think the difference is clear because of the syntax highlighting colors, so I'd propose to leave that as it.

**Comment by Felienne** [comment]
If you want to pick it up yourself btw, you can also do that in Weblate!
