### ISSUE TITLE
📜 Quiz mistakes

### ISSUE THREAD

**Issue by pepa65** [hedyorg/hedy#5478]
**Quiz level 16 question 10**:

In the Code, line 3 is displayed as `{books} = ['Narnia', 'The Hobbit', 'Oliver Twist', 'Harry Potter', 'Green eggs and ham']` (including the curly brackets). Fix: remove the curly brackets around `books`.

The variable `list_of_raffle_numbers` is used in the code (lines 5 and 7), but `list_of_numbers` in the Options. Fix: use `list_of_numbers` in the Code.

**Quiz level 17 question 6**:

Line 3 of the displayed code is not indented, which is clearly wrong (line 2 ends with a colon). Option 4 should be: `There is an indentation mistake in the third line.` (instead of the last line).

**Comment by Felienne** [comment]
Thanks for this PR and welcome to Hedy @pepa65!

This issue will probably also exist in other yamls (which are a copy of the en file) Are you able to also make these changes in other languages where needed 🙏?

**Comment by pepa65** [comment]
Option 4 stays as `There is an indentation mistake in the third line.` and line 3 gets properly indented is the smallest change to fix the problem.
