### ISSUE TITLE
📜 Level 13 Tic Tac Toe is a non sequitur

### ISSUE THREAD

**Issue by t1u1** [hedyorg/hedy#5516]
This [exercise in level 13](https://hedy.org/hedy/13#tic) asks students to debug some code which has concepts that haven't been introduced earlier:

* The idea of indexing into a list. The syntax of `list at random` has been introduced, but `list at number` hasn't
* The idea of mutating values inside a list

While observing students trying to solve this, I found them very confused.

PS. Thanks for creating this excellent project :pray:

**Comment by Felienne** [comment]
Hi @t1u1!

Thanks for the kind words! We were aware too and this adventure is now moved to level 16 with more explanation:

https://hedy.org/hedy/16#tic

**Comment by t1u1** [comment]
That's great! I see that this adventure is now broken down into smaller parts and with detailed explanations too! :+1: 

Thanks again!


PS: Is there a changelog or announcement of what has been deployed to the website? It would help me decide whether students need to redo some levels.
