### ISSUE TITLE
Add saved programs in test DB

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#5522]
> Also fixes that only modified programs are shown in 'My public profile'
> 
> **How to test** Is it correct that we don't have saved programs in the test database? Then it's a bit difficult to test:

Good point! I will make a new issue to discuss that!

> 1. Go to programs.py and comment out line 101, 104 and 106
> 2. Save a few programs, check if they are shown in `/my-programs`
> 3. Make a few public and see if they are shown in 'My public profile'

I will be lazy and test on alpha :)

_Originally posted by @Felienne in https://github.com/hedyorg/hedy/issues/5521#issuecomment-2108242386_

**Comment by Annelein** [comment]
Maybe it would also be nice to make teacher1 a public profile? Because now to test it, you have to add the public profile every time.

**Comment by Felienne** [comment]
> Maybe it would also be nice to make teacher1 a public profile? Because now to test it, you have to add the public profile every time.

Absolutely! Will you pick this issue up yourself?
