### ISSUE TITLE
🪲 Numbers are not translated to Arabic when printed

### ISSUE THREAD

**Issue by boryanagoncharenko** [hedyorg/hedy#5549]
**Describe the bug**
When the selected language is Arabic, numbers are output in Arabic and not in Latin. However, when we print literal values, they appear in Latin.

In level 6 and currently language Arabic
```
print 1 + 1
# outputs ٢
```
<img width="1055" alt="Screenshot 2024-05-21 at 17 10 07" src="https://github.com/hedyorg/hedy/assets/3010723/f128fef3-c2ae-49fb-920e-e833b6dc888f">

But if we print the literal value 1, the output is a Latin number:
```
print 1
# outputs 1
```
<img width="1059" alt="Screenshot 2024-05-21 at 17 10 21" src="https://github.com/hedyorg/hedy/assets/3010723/d17bd3c8-0a1a-434e-9530-4479da3dccb1">

**Comment by Felienne** [comment]
Ah yes, great catch! I suspect the translation only happens in a calculation, not in a literal!

**Comment by boryanagoncharenko** [comment]
Oh no, I mistyped the number of this issue in the PR that resolves it, so it did not get closed automatically. Here is the PR: https://github.com/hedyorg/hedy/pull/5567
