### ISSUE TITLE
🪲 Console errors related to user activity

### ISSUE THREAD

**Issue by jpelay** [hedyorg/hedy#5550]
This is happening on `alpha` right now, we are getting console errors related to some JSON. I checked the response that is being turned to json and it seemed fine, does anyone else have any clue?

![image](https://github.com/hedyorg/hedy/assets/45865185/087e0b06-9b73-4f4a-b934-39c02d31f4b3)

**Comment by jpelay** [comment]
Tagging @hasan-sh!

**Comment by hasan-sh** [comment]
Resolved by #5527

**Comment by jpelay** [comment]
> Fixed by #5527

I don't think it is! As I see it, the error is not the same? Now it says "Unexpected end of JSON input".

**Comment by Annelein** [comment]
@hasan-sh it would be nice to have it fixed because it's quite an annoying bug when debugging!
