### ISSUE TITLE
🪲 Issue with saving adventures

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#5571]
As reported on Discord by @LegoPink:

`when making a new adventure, and you forget to check the checkbox for to allow sharing, the adventure will not save correctly. Hmm. Maybe it is a bug...`

**Comment by jpelay** [comment]
After talking with Pink we found out that this wasn't a bug, but a missconception from her part. On the hand while testing this I did found a bug related to checking off the checkbox to make the adventure public, so Im repurposing this issue to handle that!

**Comment by jpelay** [comment]
Fixed by #5580
