### ISSUE TITLE
🪲 turtle graphics auto-run steal focus

### ISSUE THREAD

**Issue by zellyn** [hedyorg/hedy#5596]
**Describe the bug**
It's difficult to type a multi-line turtle graphics program, because each time you hit "enter", the program re-runs (which is great!) and **when it finishes, it steals the focus**.  Depending on how fast you type, it varies how much you can type before it stops working.

(You can get back to the coding area by clicking, or with shift-TAB.)

**What machine and browser you were using (optional)**
- OS: Mac
- Browser: Firefox

**Comment by Felienne** [comment]
Interesting.... I don't think programs should run if you hit enter (only option-enter) so this might be a wird bug. I can't reproduce on my mac with Chrome, maybe @Annelein can see if she can reproduce this with Firefox?

**Comment by zellyn** [comment]
I'll try to record my screen… brb

**Comment by zellyn** [comment]
Nope. I cannot get it to happen now. If it happens again, I'll try to find a path to reproducing it.
