### ISSUE TITLE
🪲 Language selection non-responsive on "narrow" viewport

### ISSUE THREAD

**Issue by Remi-Gau** [hedyorg/hedy#5622]
Complete drive-by issue I ran into while browsing the website of this awesome project.

**Describe the bug**

Some languages become unselectable when on a narrower view port

**Paste the Hedy code & level**

This is UI / front-end related

**Add a screenshot (optional)**

Firefox
![image](https://github.com/hedyorg/hedy/assets/6961185/87d8a9d2-477f-4878-aa56-6a2493bf6588)

Google chrome
![image](https://github.com/hedyorg/hedy/assets/6961185/b931da22-182e-4bfe-a665-1b2ed62689f3)

**What machine and browser you were using (optional)**

If the issue concerns things in the website, let us know:
- What computer you are using (Windows, Mac, Linux?) Ubuntu 22.04
- What browser you were using (Chrome, Edge, Safari) Tested on Chrome and Firefox

**Comment by Felienne** [comment]
Hi @Annelein!

This of course is a result of the whole site not really being responsive (which we should work on, one day) but this specific bug is really annoying, can you maybe pick up only this one for now? 

Thanks!!

**Comment by Annelein** [comment]
@Felienne I will look into it!

**Comment by Felienne** [comment]
Thanks for letting us know @Remi-Gau!! We fixed the issue and it should be available on the site when we deploy next (you can follow along here when that happens: https://github.com/hedyorg/hedy/releases)
