### ISSUE TITLE
🪲 badges not removed when profile deleted

### ISSUE THREAD

**Issue by AnneliesVlaar** [hedyorg/hedy#5638]
**Describe the bug**
When checking the achievement badges for new users, I created a new profile, made some programs, earned badges. Then (to start again from scratch) I deleted the profile and made a new one with the same profile name. In the profile the programs were gone, as expected, but the badges were still there. 

**Add a screenshot (optional)**
The profile with the badges
![Annelies_test2_badges](https://github.com/hedyorg/hedy/assets/66774020/0a04456e-d7da-4765-a100-c7b768e55972)
Then I deleted this profile
![Annelies_test2_delete_profiel](https://github.com/hedyorg/hedy/assets/66774020/dcae6cef-f995-4d3f-957d-e32e2422b378)
I created a new profile with the same username
![Annelies_test2_create_profile again](https://github.com/hedyorg/hedy/assets/66774020/5212f4dc-9709-4a00-9ef5-9d8fc4c980ac)
There were no programs in the new profile, as expected
![Annelies_test2_zero_programs](https://github.com/hedyorg/hedy/assets/66774020/a9fbfb49-2c6e-448f-a304-0f0e71100ef1)
But all the badges were still there, not expected
![Annelies_test2_still_badges](https://github.com/hedyorg/hedy/assets/66774020/ffe258c8-9b9b-49f2-9ef8-60de78d5db2d)

**What machine and browser you were using (optional)**
If the issue concerns things in the website, let us know:
- What computer you are using Windows
- What browser you were using Firefox

**Comment by jpelay** [comment]
Since we removed achievements, we can close this issue.
