### ISSUE TITLE
🪲/💻  No dropdown in single adventure mode

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#5641]
**Describe the bug**
In single adventure mode (using /adventure/<name>, such as /adventure/music) the level selector does not show:

<img width="1470" alt="image" src="https://github.com/hedyorg/hedy/assets/1003685/cd254ae2-87b9-4911-b3e6-d6c704b47f1c">

This is a result of some changes, we used to have button below which did work. This is a bit annoying for workshops, can you take a look @Annelein?

**Comment by Felienne** [comment]
And probably we should also have a Cypres test for this (because we should have known before the changes broke this!)

**Comment by Annelein** [comment]
I will look at it!

**Comment by Annelein** [comment]
@Felienne How would a user get to /adventure ? There is indeed no Cypress test for this.

**Comment by Felienne** [comment]
> @Felienne How would a user get to /adventure ? There is indeed no Cypress test for this.

Type it manually :) (we commonly use this in one day workshops)

**Comment by Annelein** [comment]
@Felienne Allright, good to know :)! Is it fine if I add tests for that page (because I don't think /adventure is covered at all) in one of the Cypress refactor PR once the Hedy page is redesigned? I will add it to this list: https://github.com/hedyorg/hedy/issues/4027#issue-1579937487

**Comment by Felienne** [comment]
Yes, we can totally add the tests later (if we fix the issue now)

**Comment by Annelein** [comment]
> Yes, we can totally add the tests later (if we fix the issue now)

Great! It's ready to be reviewed
