### ISSUE TITLE
remove /landing-page

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#5661]
The /landing page was was made to go to after email confirmation (https://github.com/hedyorg/hedy/pull/1368) which we no longer have. So we can just remove it. Turning this into an issue.

**Comment by jpelay** [comment]
Hi, Felienne, could you clarify something for me? We are still sending verification emails after registration.

https://github.com/hedyorg/hedy/blob/5ac78a9c2d9a6d05b2f6d24455d2c6fd6a2c38d4/website/auth_pages.py#L433-L438

Is this what you meant by email confirmation? Do you want me to remove this as well, or instead redirect directly to the home or first level page.

**Comment by Felienne** [comment]
> Hi, Felienne, could you clarify something for me? We are still sending verification emails after registration.
> 
> https://github.com/hedyorg/hedy/blob/5ac78a9c2d9a6d05b2f6d24455d2c6fd6a2c38d4/website/auth_pages.py#L433-L438
> 
> Is this what you meant by email confirmation? Do you want me to remove this as well, or instead redirect directly to the home or first level page.

No I think the email is really nice, let's keep it! Just redirect to the home page
