### ISSUE TITLE
Stop approving teachers accounts 

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#5724]
As discussed in the meeting yesterday, we will simply auto-approve all teachers' accounts. 

We can, for now, leave the interface as we have it now, so that we can *revoke* access though the admin panel if needed.  In the future we might want to have a better search option, because now it is paginated and annoying!

**Comment by jpelay** [comment]
Hi! I've already implemented the change were creating a teacher account directly makes you a teacher. What about requesting a teacher account though? 

![image](https://github.com/user-attachments/assets/cc258bac-17f5-43bb-913f-468b1c74d80c)

Do you want me to remove this option or turn it into a: "Turn you into a teacher" kind of option.

**Comment by Felienne** [comment]
> Do you want me to remove this option or turn it into a: "Turn you into a teacher" kind of option.

Yes, we can leave the button and change the text a bit indeed.

And have we thought about the email workflow too (maybe the "your account is ready" email should be rephrased too?
