### ISSUE TITLE
💻 Add tickmark in student exercise

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#5752]
I can already add tickmarks fro the overview page, but could we add a tickmark box inside the assignment of the student, then I don't have to go back, that saves me a lot of clicks, so here:

<img width="1270" alt="image" src="https://github.com/user-attachments/assets/29e08dab-d7d8-4517-84c8-91d0c8aac2bc">

And, can we show that to the students too, if I have ticked it off, they get a tickmark icon next to the tab?

That would be amazing!!

**Comment by jpelay** [comment]
Hi! You mean something like this?

![image](https://github.com/user-attachments/assets/5156db66-860a-4698-a133-0145e1c1ebcc)

And when you click the table or the program you check and they are in sync?

**Comment by Felienne** [comment]
Hi @jpelay 

It does not have to connect to the submitted programs (that has a very specific meaning where indeed it can't be altered), just showing a tickmark in the tab (when the student looks at all tabs) is enough, and it is fine if it requires a reload.

So, again in short:

* as a teacher, I can view a program with the eye icon, and than on the program page, there is a tickmark box that I can tick (with the exact same meaning as we have it now in the overview, so it is just copying over the tickmark to save me a click)

* as a student, in the top of all tabs, next to the name, there will be a tickmark icon (not a box) shown when the teacher has ticked off the program.

* it is totally fine if the student can then still change the program and view it in the tab view.

Hope that helps.
