### ISSUE TITLE
🪲Assigning a random list item to another list item leads to a cryptic error

### ISSUE THREAD

**Issue by AnneliesVlaar** [hedyorg/hedy#5758]
**Describe the bug**
When I use the random function from a list and I want to assign the result to a item of another list, I get the error message 'We detected that a new line is being used on line 12 which is not allowed. Can you try looking for a missing or an extra character on your code?'. It does work when I assign the random choice to a variable and assign the variable to the item of the list. 

**Paste the Hedy code & level**
level 17
```
kassa_munten = [1,1,1,1,1,1]
random_aantal_muntjes = [1,2,3,4,5]
kassa_munten[1] = random_aantal_muntjes[random]
```

**Add a screenshot (optional)**
![afbeelding](https://github.com/user-attachments/assets/0303d04e-09f2-4b10-8d77-b0b7d5adfef0)

**What machine and browser you were using (optional)**
If the issue concerns things in the website, let us know:
- What computer you are using (**Windows**, Mac, Linux?)
- What browser you were using Mozzila

**Comment by MarleenGilsing** [comment]
I found that the same error message is shown when you use the add command without specifying which list you want to add the new item to. This should be fixed too.
