### ISSUE TITLE
🪲 Programmer's mode pops up after viewing a program

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#5771]
Reproduce this issue as follows:

* Log in as a teacher
* View a student's program from the program's page
* Switch to a new tab

**Comment by Felienne** [comment]
Ow there is an even easier way! Go to explore, and go back to Hedy!

Video: 

https://github.com/user-attachments/assets/9c38e8b3-5465-454a-b659-d0b05c0bf044

**Comment by jpelay** [comment]
> Ow there is an even easier way! Go to explore, and go back to Hedy!
> 
> Video:
> 
>  IMG_0854.mov

Thanks for the detailed video!
