### ISSUE TITLE
💻 "Add next student" in the teachers view of code submission

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#5772]
When I look at the students's submission, I now open them all one my one, but it would be amazing if the first row, this one:

<img width="1398" alt="image" src="https://github.com/user-attachments/assets/a0e483b1-03b4-4084-bf73-c330a11da510">

Would also have an eye button, which would open all tried programs (the ones with an eye) and open them all in new tabs.

**Comment by Felienne** [comment]
I suspect that this might be even a better UX than the modal, but let's discuss!

**Comment by Felienne** [comment]
As discussed in the meeting, let's add a "next student" button at the top!

And we also add a "go back" button that goes back.

Plus, refresh should stay on the same level.

**Comment by jpelay** [comment]
> As discussed in the meeting, let's add a "next student" button at the top!
> 
> And we also add a "go back" button that goes back.
> 
> Plus, refresh should stay on the same level.

Thanks for updating the issue, was just on my way to do this!
