### ISSUE TITLE
Teacher trainer ZOOM plannen

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#5804]
Two actions:

* Find a few options in the next few weeks for a teacher hangout
* Fix a new date ("first\last X of the month") for a structural meeting

**Comment by MarleenGilsing** [comment]
I've adjusted the email according to your feedback, I like the term 'spreekuur' so let's see if it draws some teachers to the meeting. Can you take a look at it and send it tomorrow or friday?

**Comment by MarleenGilsing** [comment]
changed the date to friday. The e-mail is ready to go!

**Comment by Felienne** [comment]
Scheduled for tomorrow!
