### ISSUE TITLE
🪲Graph looking weird

### ISSUE THREAD

**Issue by jpelay** [hedyorg/hedy#5817]
Felienne reported this on Discord:

> One my my students is destroying your visualization Jesus:
> ![image](https://github.com/user-attachments/assets/77ffa60b-b778-4fec-9558-267c6714f4f9)
> And I would not even say the numbers are crazy:
> ![image](https://github.com/user-attachments/assets/942fd066-48bc-4d1f-988e-6c9266246182)

**Comment by Felienne** [comment]
Haha I just wanted to open an issue on this but you already did, thanks!!

**Comment by Felienne** [comment]
@jpelay I added you as teacher to my class in school so you can see with your own eyes what it looks like if you have real useage.

**Comment by jpelay** [comment]
> [@jpelay](https://github.com/jpelay) I added you as teacher to my class in school so you can see with your own eyes what it looks like if you have real useage.

I saw! Thanks a lot. Boryana and I discussed today about this, we have several ideas about this, but I would like to confirm with you.

**Comment by Felienne** [comment]
> > [@jpelay](https://github.com/jpelay) I added you as teacher to my class in school so you can see with your own eyes what it looks like if you have real useage.
> 
> I saw! Thanks a lot. Boryana and I discussed today about this, we have several ideas about this, but I would like to confirm with you.

Hi Jesus! Thanks! Don't make it overly complex, just a normalization so that the larger ones are somehow capped would also already be better. "First we make it work, then we make it better" :) 

And @MarleenGilsing/@AnneliesVlaar will be the people to confirm with as POs, but we can have a brief chat about it today in the meeting.

**Comment by Felienne** [comment]
If we are fixing the graph, can we also think about initialization?

I am helping a new teacher get started today and they were a bit confused what they were looking at:

<img width="578" alt="image" src="https://github.com/user-attachments/assets/05108133-821b-4285-9109-1c259015336b">

The hover over does not really help in this case:

<img width="1453" alt="image" src="https://github.com/user-attachments/assets/8a998e42-3530-415f-aeb1-40e48c1930f9">

A quick fix would be to make the graph empty if there is no data, and make the hover over say: "when students start working, data will appear here" (with a link to the teachers manual where it is explained)?

**Comment by Felienne** [comment]
This looks so much better now!!!

<img width="957" alt="image" src="https://github.com/user-attachments/assets/cd274755-22a9-447d-b6b4-4088852b905e" />
