### ISSUE TITLE
🪲Explore tab of navbar is not visible in responsive view.

### ISSUE THREAD

**Issue by meetarora10** [hedyorg/hedy#5849]
**Describe the bug**
Explore tab of navbar is not visible in responsive view.
**Paste the Hedy code & level**
I can make changes in the CSS to fix this issue .

**Add a screenshot (optional)**
![Screenshot (1131)](https://github.com/user-attachments/assets/2a8b6bf0-ceaf-4a39-8e34-9eee007f85f7)

**What machine and browser you were using (optional)**
Firefox
If the issue concerns things in the website, let us know:
- What computer you are using (Windows, Mac, Linux?) Windows
- What browser you were using (Chrome, Edge, Safari)Firefox

**Comment by jpelay** [comment]
Hi! Yeah, thanks for pointing this out. I actually have a design ready, but we want to couple it with a complete redesign of the adventure page 😄 So soon will have a proper responsive navbar

**Comment by Felienne** [comment]
You can see our new design (and test the new navbar) via: https://hedy.org/tryit#default

Let us know if that solves it, in that case in due time, it will be fixes!
