### ISSUE TITLE
🪲 Make changes to the create student accounts in bulk

### ISSUE THREAD

**Issue by boryanagoncharenko** [hedyorg/hedy#5886]
As discussed in #5864, add the following changes to the create student accounts:
- [ ] When a username contains `@` or `:` the error message should display the rows containing the incorrect values.
- [ ] Change the font of the passwords, so that lowercase L and uppercase i do not look the same. This should be changed in the table that displays the accounts and the table for printing
- [ ] Add Hedyness to the printed table. Add the URL of Hedy to the table, so that it is handed out to the students. Add the logo of Hedy along with a nice title to the page.

**Comment by boryanagoncharenko** [comment]
@AnneliesVlaar could you please check whether you like the current styling? I recorded a short video which illustrates it:


https://github.com/user-attachments/assets/3d84a7f1-a774-400e-b733-e24e1467eec8

**Comment by AnneliesVlaar** [comment]
@boryanagoncharenko I like the monospace font too, good choice. The Hedy logo really gives it some personalization, I like it.
I am not sure about the title I suggested. Maybe we should have a title: 'Hedy.org' and a subtitle 'student accounts'? 
Not sure how teachers will use this, but if they print it out and cut it in pieces to hand out to the students it might be helpful if the height of the cells are a bit larger. Is that something we can control?

**Comment by boryanagoncharenko** [comment]
> @boryanagoncharenko I like the monospace font too, good choice. The Hedy logo really gives it some personalization, I like it. I am not sure about the title I suggested. Maybe we should have a title: 'Hedy.org' and a subtitle 'student accounts'? Not sure how teachers will use this, but if they print it out and cut it in pieces to hand out to the students it might be helpful if the height of the cells are a bit larger. Is that something we can control?

I am hesitant to make the title 'Hedy.org' because this string that appears so many times on the page already, so I don't think it brings value. Perhaps we could just leave the title as 'Student accounts' or 'Student accounts created for Hedy'?

We could increase the height of the table cells. However, if I teacher creates 30 accounts, adjusting the height could make it nicer to handout but could also lead to too many pages. So there is a trade off to take into account. This is how 30 accounts look with the current height:

https://github.com/user-attachments/assets/b4a46f7f-4482-4179-9d2d-4c4aa4d00273

And this is how the same accounts look with increased height:

https://github.com/user-attachments/assets/070eabf0-a389-493f-ad46-1e3a6dd05482

Let me know what is better.
