### ISSUE TITLE
📜Music instructions not consistent with implementation of notes

### ISSUE THREAD

**Issue by AnneliesVlaar** [hedyorg/hedy#5945]
The instructions for music says that the notes are available from C1 up until C10.
But the error message states that the notes are available from C0 up until B9. 

<img width="741" alt="Scherm­afbeelding 2024-11-16 om 11 45 04" src="https://github.com/user-attachments/assets/c87c9464-ebe4-45a5-b034-63d84d426f10">

@MarleenGilsing do we want to change the instructions?
Going from 0 to 9 is logical in a (Python) programmers brain, going from 1 to 10 is probably logical in all other brains. 
Or do we want to implement different to match the instructions @Felienne ?

**Comment by MarleenGilsing** [comment]
I'll change the instructions, seems like a lot less work ;)
