### ISSUE TITLE
📜 Update the Privacy Terms section on the website

### ISSUE THREAD

**Issue by boryanagoncharenko** [hedyorg/hedy#5957]
Currently, the Privacy Terms section says that `Vrije Universiteit Amsterdam is the entity responsible for the processing of your Personal Information` which should be updated to Hedy Stichting.

Additionally, perhaps it is a good idea to double-check the part about "Account Information". It does say that the email of a parent should be used if the user is under 16. But this means the user can choose share their year of birth, country and gender if they are under 16 without parental approval.

**Comment by Felienne** [comment]
> Additionally, perhaps it is a good idea to double-check the part about "Account Information". It does say that the email of a parent should be used if the user is under 16. But this means the user can choose share their year of birth, country and gender if they are under 16 without parental approval.

Yes, it would be great if someone (I hope you?) can dive into 1) what we should write and 2) if we can implement a technical solution too (f.e. if a student chooses a year that currently means they'd be younger, to give a warning)

**Comment by Felienne** [comment]
Ready for now, Eelko is working on the legal side
