### ISSUE TITLE
💻 Can't rename a class

### ISSUE THREAD

**Issue by Felienne** [hedyorg/hedy#5965]
I am not sure we had this option before (but I think so?) but I would like to rename a class, so I can call last year's classes something like "2023 - classname", but I don't see an option to do so now:

<img width="1459" alt="image" src="https://github.com/user-attachments/assets/b852d96a-0f08-459d-be4e-8294a0474b9b">

**Comment by Sidd-T** [comment]
Hey there, I'm looking to get into open source contribution and stumbled on this repo. I'm interested in this project, could I give this a shot?

**Comment by Felienne** [comment]
> Hey there, I'm looking to get into open source contribution and stumbled on this repo. I'm interested in this project, could I give this a shot?

The steps would, roughly, be:

* Change the text box into an editable element
* On changes in the box, do an update call to the database (table class)

Absolutely! Let us know if you need any help!
