### ISSUE TITLE
🪲 Missing adventures in level 13

### ISSUE THREAD

**Issue by boryanagoncharenko** [hedyorg/hedy#6008]
**Describe the bug**
In level 13 we have content for the hotel and songs adventures, but they do not appear on Hedy. The issue is that the order of the tabs is not defined [here](https://github.com/hedyorg/hedy/blob/main/hedy_content.py#L45).

I checked if we have other pieces of hidden content and these 2 adventures for this level are the only issues.

**Comment by AnneliesVlaar** [comment]
I think we could place hotel before calculator, then it is at the same place as in level 14 and it is after the introduction of functions arguments which are needed.

**Comment by boryanagoncharenko** [comment]
How about the songs adventure, should it go before the music one?

**Comment by AnneliesVlaar** [comment]
> How about the songs adventure, should it go before the music one?

The song Adventure would work better right after the music Adventure.
