### ISSUE TITLE
Save program pop-up occurs when it shouldn't

### ISSUE THREAD

**Issue by TiBiBa** [hedyorg/hedy#955]
Currently when not saving a created program and switching to the 'end' tab the warning pop-up occurs if you are sure that you don't want to save the program. However, when directly afterwards switching to another tab the same pop-up will still occur. Might be due to the 'end' tab not having an editor and therefore not resetting the value.

Possible solution: reset editor() value anyway when switching to 'end' tab.

**Comment by Felienne** [comment]
A small fix is fine if it is easy but let's also think about how to make the whole thing smoother.
