### ISSUE TITLE
Move cursor to mistake/error

### ISSUE THREAD

**Issue by remva** [hedyorg/hedy#984]
Whenever an error occurs in someones code, the cursor could jump to the error. This will only/mainly work when there's only one mistake in the code. 

With this, it will immediately become clear where the mistake is.

**Comment by Felienne** [comment]
I was thinking about this issue in connection to the very cool modals we have now and I was thinking... could we first show the wrong code in the modal (aka the code that the kids submitted) and then have it "morph" into the right code?

With a string differ that should not be all too hard (and with a string differ it also does not necessarily depend on #845)

**Comment by Felienne** [comment]
Think we can safely close this!
